#!/usr/bin/env python3
import json, requests, time
API = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGS = ['ko', 'ja', 'zh', 'es', 'fr', 'de']
WORDS = [
    ("abode", "noun", "home", "Humble abode.", "Band 8.0+"),
    ("abolishment", "noun", "ending", "Slavery abolishment.", "Band 8.0+"),
    ("abrasion", "noun", "scrape", "Skin abrasion.", "Band 8.0+"),
    ("abstinence", "noun", "restraint", "Total abstinence.", "Band 8.0+"),
    ("abstraction", "noun", "concept", "Pure abstraction.", "Band 8.0+"),
    ("absurdity", "noun", "nonsense", "Total absurdity.", "Band 8.0+"),
    ("accompaniment", "noun", "addition", "Musical accompaniment.", "Band 8.0+"),
    ("accomplice", "noun", "partner in crime", "Willing accomplice.", "Band 8.0+"),
    ("accumulator", "noun", "collector", "Energy accumulator.", "Band 8.0+"),
    ("acidification", "noun", "becoming acidic", "Ocean acidification.", "Band 8.0+"),
    ("acquiescence", "noun", "acceptance", "Silent acquiescence.", "Band 8.0+"),
    ("actualization", "noun", "realization", "Self-actualization.", "Band 8.0+"),
    ("addendum", "noun", "addition", "Contract addendum.", "Band 8.0+"),
    ("adherent", "noun", "follower", "Strict adherent.", "Band 8.0+"),
    ("adjournment", "noun", "postponement", "Court adjournment.", "Band 8.0+"),
    ("adjudication", "noun", "judgment", "Legal adjudication.", "Band 8.0+"),
    ("administratrix", "noun", "female admin", "Estate administratrix.", "Band 8.0+"),
    ("admiralty", "noun", "naval authority", "British admiralty.", "Band 8.0+"),
    ("adornment", "noun", "decoration", "Simple adornment.", "Band 8.0+"),
    ("adulation", "noun", "excessive praise", "Public adulation.", "Band 8.0+"),
    ("adversary", "noun", "opponent", "Political adversary.", "Band 8.0+"),
    ("advocacy", "noun", "support", "Patient advocacy.", "Band 7.0-7.5"),
    ("aerodynamics", "noun", "air physics", "Car aerodynamics.", "Band 8.0+"),
    ("affidavit", "noun", "sworn statement", "Sign affidavit.", "Band 8.0+"),
    ("affiliation", "noun", "connection", "Party affiliation.", "Band 7.0-7.5"),
    ("affirmation", "noun", "confirmation", "Positive affirmation.", "Band 7.0-7.5"),
    ("affliction", "noun", "suffering", "Physical affliction.", "Band 8.0+"),
    ("affluence", "noun", "wealth", "Growing affluence.", "Band 8.0+"),
    ("aftermath", "noun", "consequence", "War aftermath.", "Band 7.0-7.5"),
    ("agility", "noun", "nimbleness", "Mental agility.", "Band 7.0-7.5"),
    ("agitation", "noun", "anxiety", "Political agitation.", "Band 8.0+"),
    ("agrarian", "adjective", "farming", "Agrarian society.", "Band 8.0+"),
    ("ailment", "noun", "illness", "Minor ailment.", "Band 7.0-7.5"),
    ("airfare", "noun", "flight cost", "Cheap airfare.", "Band 6.0-6.5"),
    ("airstrip", "noun", "runway", "Small airstrip.", "Band 7.0-7.5"),
    ("alcove", "noun", "recess", "Reading alcove.", "Band 8.0+"),
    ("alertness", "noun", "vigilance", "Mental alertness.", "Band 7.0-7.5"),
    ("alienation", "noun", "isolation", "Social alienation.", "Band 8.0+"),
    ("alignment", "noun", "arrangement", "Wheel alignment.", "Band 7.0-7.5"),
    ("allegation", "noun", "claim", "Serious allegation.", "Band 7.0-7.5"),
    ("allegiance", "noun", "loyalty", "National allegiance.", "Band 8.0+"),
    ("allergy", "noun", "sensitivity", "Food allergy.", "Band 6.0-6.5"),
    ("alleviation", "noun", "relief", "Pain alleviation.", "Band 8.0+"),
    ("alliance", "noun", "partnership", "Military alliance.", "Band 7.0-7.5"),
    ("allocation", "noun", "distribution", "Budget allocation.", "Band 7.0-7.5"),
    ("allotment", "noun", "portion", "Garden allotment.", "Band 8.0+"),
    ("alteration", "noun", "change", "Minor alteration.", "Band 7.0-7.5"),
    ("altercation", "noun", "argument", "Verbal altercation.", "Band 8.0+"),
    ("alternation", "noun", "switching", "Regular alternation.", "Band 8.0+"),
    ("altruism", "noun", "selflessness", "True altruism.", "Band 8.0+"),
    ("amalgamation", "noun", "merger", "Company amalgamation.", "Band 8.0+"),
    ("ambiguity", "noun", "uncertainty", "Avoid ambiguity.", "Band 7.0-7.5"),
    ("ambivalence", "noun", "mixed feelings", "Emotional ambivalence.", "Band 8.0+"),
    ("amenity", "noun", "facility", "Hotel amenity.", "Band 7.0-7.5"),
    ("amiability", "noun", "friendliness", "Natural amiability.", "Band 8.0+"),
    ("amnesty", "noun", "pardon", "Political amnesty.", "Band 8.0+"),
    ("amplification", "noun", "increase", "Sound amplification.", "Band 8.0+"),
    ("amplifier", "noun", "sound device", "Guitar amplifier.", "Band 7.0-7.5"),
    ("amplitude", "noun", "extent", "Wave amplitude.", "Band 8.0+"),
    ("amusement", "noun", "entertainment", "Amusement park.", "Band 6.0-6.5"),
    ("analogue", "noun", "equivalent", "Digital analogue.", "Band 8.0+"),
    ("anarchist", "noun", "rebel", "Political anarchist.", "Band 8.0+"),
    ("anarchy", "noun", "disorder", "Social anarchy.", "Band 8.0+"),
    ("anatomy", "noun", "body structure", "Human anatomy.", "Band 7.0-7.5"),
    ("ancestor", "noun", "forefather", "Common ancestor.", "Band 6.0-6.5"),
    ("ancestry", "noun", "lineage", "Royal ancestry.", "Band 7.0-7.5"),
    ("anchorage", "noun", "harbor", "Safe anchorage.", "Band 8.0+"),
    ("anecdote", "noun", "short story", "Funny anecdote.", "Band 7.0-7.5"),
    ("anesthesia", "noun", "numbness", "General anesthesia.", "Band 7.0-7.5"),
    ("anguish", "noun", "suffering", "Mental anguish.", "Band 8.0+"),
    ("animation", "noun", "cartoon", "Computer animation.", "Band 6.0-6.5"),
    ("animosity", "noun", "hatred", "Personal animosity.", "Band 8.0+"),
    ("annexation", "noun", "taking over", "Territory annexation.", "Band 8.0+"),
    ("announcement", "noun", "declaration", "Public announcement.", "Band 6.0-6.5"),
    ("annoyance", "noun", "irritation", "Minor annoyance.", "Band 6.0-6.5"),
    ("anomaly", "noun", "irregularity", "Statistical anomaly.", "Band 8.0+"),
    ("anonymity", "noun", "namelessness", "Online anonymity.", "Band 8.0+"),
    ("antagonism", "noun", "hostility", "Deep antagonism.", "Band 8.0+"),
    ("anthology", "noun", "collection", "Poetry anthology.", "Band 8.0+"),
    ("anthropology", "noun", "human study", "Cultural anthropology.", "Band 7.0-7.5"),
    ("anticipation", "noun", "expectation", "Great anticipation.", "Band 6.0-6.5"),
    ("antidote", "noun", "remedy", "Snake antidote.", "Band 8.0+"),
    ("antique", "noun", "old item", "Valuable antique.", "Band 6.0-6.5"),
    ("antiquity", "noun", "ancient times", "Classical antiquity.", "Band 8.0+"),
    ("antiseptic", "noun", "disinfectant", "Antiseptic cream.", "Band 7.0-7.5"),
    ("anvil", "noun", "metal block", "Blacksmith anvil.", "Band 8.0+"),
    ("apartheid", "noun", "segregation", "End apartheid.", "Band 8.0+"),
    ("apathy", "noun", "indifference", "Voter apathy.", "Band 8.0+"),
    ("aperture", "noun", "opening", "Camera aperture.", "Band 8.0+"),
    ("apex", "noun", "peak", "Career apex.", "Band 8.0+"),
    ("aplomb", "noun", "composure", "Handle with aplomb.", "Band 8.0+"),
    ("apology", "noun", "sorry", "Sincere apology.", "Band 6.0-6.5"),
    ("apparatus", "noun", "equipment", "Scientific apparatus.", "Band 7.0-7.5"),
    ("apparel", "noun", "clothing", "Sports apparel.", "Band 7.0-7.5"),
    ("apparition", "noun", "ghost", "Strange apparition.", "Band 8.0+"),
    ("appendix", "noun", "supplement", "Book appendix.", "Band 7.0-7.5"),
    ("appetite", "noun", "hunger", "Good appetite.", "Band 6.0-6.5"),
    ("applause", "noun", "clapping", "Loud applause.", "Band 6.0-6.5"),
    ("applicant", "noun", "candidate", "Job applicant.", "Band 6.0-6.5"),
    ("appraisal", "noun", "evaluation", "Performance appraisal.", "Band 7.0-7.5"),
    ("appreciation", "noun", "gratitude", "Show appreciation.", "Band 6.0-6.5"),
    ("apprehension", "noun", "worry", "Growing apprehension.", "Band 8.0+"),
    ("apprentice", "noun", "trainee", "Young apprentice.", "Band 7.0-7.5"),
    ("appropriation", "noun", "taking", "Budget appropriation.", "Band 8.0+"),
    ("approximation", "noun", "estimate", "Rough approximation.", "Band 7.0-7.5"),
    ("aptitude", "noun", "ability", "Natural aptitude.", "Band 7.0-7.5"),
    ("aquarium", "noun", "fish tank", "Visit aquarium.", "Band 6.0-6.5"),
    ("arbitration", "noun", "mediation", "Binding arbitration.", "Band 8.0+"),
    ("arcade", "noun", "covered passage", "Shopping arcade.", "Band 7.0-7.5"),
    ("archaeologist", "noun", "scientist", "Famous archaeologist.", "Band 7.0-7.5"),
    ("archaeology", "noun", "ancient study", "Marine archaeology.", "Band 7.0-7.5"),
    ("archetype", "noun", "original model", "Classic archetype.", "Band 8.0+"),
    ("archipelago", "noun", "island group", "Indonesian archipelago.", "Band 8.0+"),
    ("archive", "noun", "records", "National archive.", "Band 7.0-7.5"),
    ("arena", "noun", "stadium", "Sports arena.", "Band 6.0-6.5"),
    ("aristocracy", "noun", "nobility", "British aristocracy.", "Band 8.0+"),
    ("aristocrat", "noun", "noble", "European aristocrat.", "Band 8.0+"),
    ("arithmetic", "noun", "math", "Basic arithmetic.", "Band 7.0-7.5"),
    ("armament", "noun", "weapons", "Nuclear armament.", "Band 8.0+"),
    ("armchair", "noun", "seat", "Leather armchair.", "Band 6.0-6.5"),
    ("armor", "noun", "protection", "Body armor.", "Band 7.0-7.5"),
    ("armory", "noun", "weapons storage", "Castle armory.", "Band 8.0+"),
    ("aroma", "noun", "smell", "Coffee aroma.", "Band 6.0-6.5"),
    ("arraignment", "noun", "court hearing", "Criminal arraignment.", "Band 8.0+"),
    ("arrangement", "noun", "organization", "Seating arrangement.", "Band 6.0-6.5"),
    ("array", "noun", "collection", "Vast array.", "Band 7.0-7.5"),
    ("arrears", "noun", "debt", "Rent arrears.", "Band 8.0+"),
    ("arrogance", "noun", "pride", "Sheer arrogance.", "Band 7.0-7.5"),
    ("arson", "noun", "fire crime", "Commit arson.", "Band 8.0+"),
    ("artery", "noun", "blood vessel", "Main artery.", "Band 7.0-7.5"),
    ("arthritis", "noun", "joint disease", "Rheumatoid arthritis.", "Band 7.0-7.5"),
    ("artifact", "noun", "historical object", "Ancient artifact.", "Band 7.0-7.5"),
    ("artillery", "noun", "heavy weapons", "Field artillery.", "Band 8.0+"),
    ("artisan", "noun", "craftsman", "Local artisan.", "Band 7.0-7.5"),
    ("artwork", "noun", "art piece", "Original artwork.", "Band 6.0-6.5"),
    ("ascendancy", "noun", "dominance", "Political ascendancy.", "Band 8.0+"),
    ("ascent", "noun", "climb", "Mountain ascent.", "Band 7.0-7.5"),
    ("asceticism", "noun", "self-denial", "Religious asceticism.", "Band 8.0+"),
    ("aspiration", "noun", "ambition", "Career aspiration.", "Band 7.0-7.5"),
    ("assassin", "noun", "killer", "Political assassin.", "Band 8.0+"),
    ("assassination", "noun", "murder", "Political assassination.", "Band 8.0+"),
    ("assault", "noun", "attack", "Physical assault.", "Band 7.0-7.5"),
    ("assemblage", "noun", "collection", "Art assemblage.", "Band 8.0+"),
    ("assertion", "noun", "claim", "Bold assertion.", "Band 7.0-7.5"),
    ("assertiveness", "noun", "confidence", "Personal assertiveness.", "Band 8.0+"),
    ("assessor", "noun", "evaluator", "Tax assessor.", "Band 8.0+"),
    ("asset", "noun", "resource", "Valuable asset.", "Band 6.0-6.5"),
    ("assignment", "noun", "task", "School assignment.", "Band 6.0-6.5"),
    ("assimilation", "noun", "absorption", "Cultural assimilation.", "Band 8.0+"),
    ("assistance", "noun", "help", "Financial assistance.", "Band 6.0-6.5"),
    ("association", "noun", "organization", "Trade association.", "Band 6.0-6.5"),
    ("assortment", "noun", "variety", "Wide assortment.", "Band 7.0-7.5"),
    ("assumption", "noun", "belief", "Basic assumption.", "Band 6.0-6.5"),
    ("assurance", "noun", "guarantee", "Quality assurance.", "Band 7.0-7.5"),
    ("asterisk", "noun", "symbol", "Add asterisk.", "Band 8.0+"),
    ("asteroid", "noun", "space rock", "Asteroid belt.", "Band 7.0-7.5"),
    ("asthma", "noun", "breathing condition", "Childhood asthma.", "Band 6.0-6.5"),
    ("astonishment", "noun", "amazement", "Total astonishment.", "Band 7.0-7.5"),
    ("astrology", "noun", "star study", "Believe in astrology.", "Band 7.0-7.5"),
    ("astronaut", "noun", "space traveler", "Famous astronaut.", "Band 6.0-6.5"),
    ("astronomer", "noun", "scientist", "Famous astronomer.", "Band 7.0-7.5"),
    ("astronomy", "noun", "star science", "Study astronomy.", "Band 7.0-7.5"),
    ("asylum", "noun", "refuge", "Political asylum.", "Band 7.0-7.5"),
    ("atheism", "noun", "non-belief", "Modern atheism.", "Band 8.0+"),
    ("athlete", "noun", "sportsperson", "Professional athlete.", "Band 6.0-6.5"),
    ("athletics", "noun", "sports", "Track athletics.", "Band 6.0-6.5"),
    ("atlas", "noun", "map book", "World atlas.", "Band 7.0-7.5"),
    ("atmosphere", "noun", "air", "Earth's atmosphere.", "Band 6.0-6.5"),
    ("atom", "noun", "particle", "Hydrogen atom.", "Band 7.0-7.5"),
    ("attachment", "noun", "connection", "Email attachment.", "Band 6.0-6.5"),
    ("attainment", "noun", "achievement", "Educational attainment.", "Band 7.0-7.5"),
    ("attendant", "noun", "helper", "Flight attendant.", "Band 6.0-6.5"),
    ("attentiveness", "noun", "alertness", "Careful attentiveness.", "Band 8.0+"),
    ("attic", "noun", "loft", "Dusty attic.", "Band 6.0-6.5"),
    ("attire", "noun", "clothing", "Formal attire.", "Band 7.0-7.5"),
    ("attorney", "noun", "lawyer", "Defense attorney.", "Band 6.0-6.5"),
    ("attraction", "noun", "appeal", "Tourist attraction.", "Band 6.0-6.5"),
    ("attribute", "noun", "quality", "Key attribute.", "Band 7.0-7.5"),
    ("attrition", "noun", "gradual loss", "Staff attrition.", "Band 8.0+"),
    ("auction", "noun", "sale", "Art auction.", "Band 6.0-6.5"),
    ("audacity", "noun", "boldness", "Sheer audacity.", "Band 8.0+"),
    ("auditor", "noun", "examiner", "Internal auditor.", "Band 7.0-7.5"),
    ("auditorium", "noun", "hall", "School auditorium.", "Band 6.0-6.5"),
    ("aura", "noun", "atmosphere", "Mysterious aura.", "Band 8.0+"),
    ("aurora", "noun", "light display", "Aurora borealis.", "Band 8.0+"),
    ("austerity", "noun", "strictness", "Economic austerity.", "Band 8.0+"),
    ("authenticity", "noun", "genuineness", "Prove authenticity.", "Band 7.0-7.5"),
    ("authorization", "noun", "permission", "Written authorization.", "Band 7.0-7.5"),
    ("autocracy", "noun", "dictatorship", "Political autocracy.", "Band 8.0+"),
    ("autobiography", "noun", "life story", "Write autobiography.", "Band 7.0-7.5"),
    ("automaton", "noun", "robot", "Mechanical automaton.", "Band 8.0+"),
    ("autonomy", "noun", "independence", "Personal autonomy.", "Band 7.0-7.5"),
    ("autopsy", "noun", "examination", "Perform autopsy.", "Band 8.0+"),
    ("availability", "noun", "access", "Product availability.", "Band 6.0-6.5"),
    ("avalanche", "noun", "snow slide", "Deadly avalanche.", "Band 7.0-7.5"),
    ("avarice", "noun", "greed", "Pure avarice.", "Band 8.0+"),
    ("avenue", "noun", "street", "Fifth Avenue.", "Band 6.0-6.5"),
    ("aversion", "noun", "dislike", "Strong aversion.", "Band 8.0+"),
    ("aviation", "noun", "flying", "Civil aviation.", "Band 7.0-7.5"),
    ("avocado", "noun", "fruit", "Fresh avocado.", "Band 6.0-6.5"),
    ("avoidance", "noun", "evasion", "Tax avoidance.", "Band 7.0-7.5"),
    ("awakening", "noun", "realization", "Spiritual awakening.", "Band 7.0-7.5"),
    ("awe", "noun", "wonder", "Stand in awe.", "Band 7.0-7.5"),
    ("axis", "noun", "center line", "Earth's axis.", "Band 7.0-7.5"),
    ("axle", "noun", "shaft", "Car axle.", "Band 8.0+"),
    ("babysitter", "noun", "child carer", "Hire babysitter.", "Band 6.0-6.5"),
    ("backlash", "noun", "negative reaction", "Public backlash.", "Band 7.0-7.5"),
    ("backlog", "noun", "buildup", "Work backlog.", "Band 7.0-7.5"),
    ("backpack", "noun", "bag", "School backpack.", "Band 6.0-6.5"),
    ("backup", "noun", "reserve", "Data backup.", "Band 6.0-6.5"),
    ("bacterium", "noun", "microorganism", "Harmful bacterium.", "Band 7.0-7.5"),
    ("badge", "noun", "emblem", "Name badge.", "Band 6.0-6.5"),
    ("badminton", "noun", "sport", "Play badminton.", "Band 6.0-6.5"),
    ("baggage", "noun", "luggage", "Carry baggage.", "Band 6.0-6.5"),
    ("bail", "noun", "release money", "Post bail.", "Band 7.0-7.5"),
    ("bailout", "noun", "rescue", "Government bailout.", "Band 7.0-7.5"),
    ("bakery", "noun", "bread shop", "Local bakery.", "Band 6.0-6.5"),
    ("ballad", "noun", "song", "Love ballad.", "Band 7.0-7.5"),
    ("ballet", "noun", "dance", "Classical ballet.", "Band 6.0-6.5"),
    ("ballot", "noun", "vote", "Secret ballot.", "Band 7.0-7.5"),
    ("bamboo", "noun", "plant", "Bamboo forest.", "Band 6.0-6.5"),
    ("bandwidth", "noun", "data capacity", "Network bandwidth.", "Band 7.0-7.5"),
    ("banner", "noun", "flag", "Campaign banner.", "Band 6.0-6.5"),
    ("banquet", "noun", "feast", "Wedding banquet.", "Band 7.0-7.5"),
    ("barber", "noun", "hair cutter", "Local barber.", "Band 6.0-6.5"),
    ("bargain", "noun", "deal", "Great bargain.", "Band 6.0-6.5"),
    ("barge", "noun", "boat", "River barge.", "Band 7.0-7.5"),
    ("baritone", "noun", "voice type", "Deep baritone.", "Band 8.0+"),
    ("barometer", "noun", "weather instrument", "Economic barometer.", "Band 8.0+"),
    ("baron", "noun", "noble", "Oil baron.", "Band 8.0+"),
    ("barracks", "noun", "military housing", "Army barracks.", "Band 8.0+"),
]

def translate_batch(texts, lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={API}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            r = requests.post(url, json={"q": batch, "source": "en", "target": lang}, timeout=30)
            if r.status_code == 200:
                result.extend([t['translatedText'] for t in r.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    words = json.load(f)
existing = {w['word'].lower() for w in words}
start_id = max(w['id'] for w in words) + 1
cats = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
new_words = []
for word, pos, defn, ex, level in WORDS:
    if word.lower() not in existing:
        new_words.append({"id": start_id + len(new_words), "word": word, "level": level, "partOfSpeech": pos, "definition": defn, "example": ex, "category": cats[(start_id + len(new_words)) % 10]})
        existing.add(word.lower())
print(f"새 단어: {len(new_words)}개")
if new_words:
    defs = [w['definition'] for w in new_words]
    exs = [w['example'] for w in new_words]
    for lang in LANGS:
        print(f"{lang}...")
        td = translate_batch(defs, lang)
        te = translate_batch(exs, lang)
        for i, w in enumerate(new_words):
            if 'translations' not in w: w['translations'] = {}
            w['translations'][lang] = {'definition': td[i], 'example': te[i]}
    words.extend(new_words)
    with open('assets/data/words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
print(f"총: {len(words)}개")
