#!/usr/bin/env python3
"""IELTS 단어 대량 추가 - Part 2"""
import json
import requests
import time

GOOGLE_API_KEY = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGUAGES = ['ko', 'ja', 'zh', 'es', 'fr', 'de']

WORDS_PART2 = [
    # 더 많은 IELTS 필수 단어
    ("exceed", "verb", "to go beyond a limit", "Don't exceed the speed limit.", "Band 6.0-6.5"),
    ("exclude", "verb", "to leave out", "Exclude irrelevant data.", "Band 6.0-6.5"),
    ("exhibit", "verb", "to display", "Exhibit your work.", "Band 6.0-6.5"),
    ("expand", "verb", "to make larger", "Expand your vocabulary.", "Band 4.5-5.5"),
    ("expert", "noun", "a specialist", "Consult an expert.", "Band 4.5-5.5"),
    ("explicit", "adjective", "clearly stated", "Give explicit instructions.", "Band 7.0-7.5"),
    ("exploit", "verb", "to use selfishly", "Exploit resources.", "Band 7.0-7.5"),
    ("expose", "verb", "to reveal", "Expose the truth.", "Band 6.0-6.5"),
    ("external", "adjective", "outside", "External factors.", "Band 6.0-6.5"),
    ("extract", "verb", "to remove", "Extract information.", "Band 6.0-6.5"),
    ("facilitate", "verb", "to make easier", "Facilitate learning.", "Band 7.0-7.5"),
    ("federal", "adjective", "relating to central government", "Federal laws.", "Band 6.0-6.5"),
    ("fee", "noun", "a payment", "Pay the fee.", "Band 4.5-5.5"),
    ("file", "noun", "a collection of data", "Open the file.", "Band 4.5-5.5"),
    ("final", "adjective", "last", "Final decision.", "Band 4.5-5.5"),
    ("finite", "adjective", "limited", "Finite resources.", "Band 8.0+"),
    ("flexible", "adjective", "adaptable", "Be flexible.", "Band 6.0-6.5"),
    ("fluctuate", "verb", "to vary irregularly", "Prices fluctuate.", "Band 7.0-7.5"),
    ("focus", "verb", "to concentrate", "Focus on goals.", "Band 4.5-5.5"),
    ("format", "noun", "arrangement", "Choose a format.", "Band 6.0-6.5"),
    ("foundation", "noun", "basis", "Build a foundation.", "Band 6.0-6.5"),
    ("framework", "noun", "basic structure", "Establish a framework.", "Band 7.0-7.5"),
    ("fund", "noun", "money for a purpose", "Raise funds.", "Band 6.0-6.5"),
    ("fundamental", "adjective", "basic", "Fundamental principles.", "Band 7.0-7.5"),
    ("furthermore", "adverb", "in addition", "Furthermore, we agree.", "Band 7.0-7.5"),
    ("gender", "noun", "male or female", "Gender equality.", "Band 6.0-6.5"),
    ("generate", "verb", "to produce", "Generate ideas.", "Band 6.0-6.5"),
    ("generation", "noun", "people born at similar time", "The younger generation.", "Band 6.0-6.5"),
    ("globe", "noun", "the earth", "Around the globe.", "Band 6.0-6.5"),
    ("goal", "noun", "an aim", "Achieve your goals.", "Band 4.5-5.5"),
    ("grade", "noun", "a level", "High grade.", "Band 4.5-5.5"),
    ("grant", "verb", "to give", "Grant permission.", "Band 6.0-6.5"),
    ("guarantee", "verb", "to promise", "Guarantee quality.", "Band 6.0-6.5"),
    ("guideline", "noun", "a rule", "Follow guidelines.", "Band 6.0-6.5"),
    ("hence", "adverb", "therefore", "Hence the delay.", "Band 7.0-7.5"),
    ("hierarchy", "noun", "ranked system", "Corporate hierarchy.", "Band 8.0+"),
    ("highlight", "verb", "to emphasize", "Highlight key points.", "Band 6.0-6.5"),
    ("hypothesis", "noun", "a theory", "Test the hypothesis.", "Band 7.0-7.5"),
    ("identical", "adjective", "exactly the same", "Identical twins.", "Band 6.0-6.5"),
    ("ideology", "noun", "a set of beliefs", "Political ideology.", "Band 8.0+"),
    ("ignorance", "noun", "lack of knowledge", "Ignorance is not an excuse.", "Band 7.0-7.5"),
    ("illustrate", "verb", "to explain with examples", "Illustrate the point.", "Band 6.0-6.5"),
    ("image", "noun", "a picture", "Public image.", "Band 4.5-5.5"),
    ("immigrate", "verb", "to move to another country", "Immigrate for work.", "Band 6.0-6.5"),
    ("impact", "noun", "effect", "Positive impact.", "Band 6.0-6.5"),
    ("implement", "verb", "to put into action", "Implement the plan.", "Band 7.0-7.5"),
    ("implicate", "verb", "to show involvement", "Evidence implicates him.", "Band 8.0+"),
    ("implicit", "adjective", "implied", "Implicit meaning.", "Band 8.0+"),
    ("imply", "verb", "to suggest", "What do you imply?", "Band 6.0-6.5"),
    ("impose", "verb", "to force upon", "Impose restrictions.", "Band 7.0-7.5"),
    ("incentive", "noun", "motivation", "Financial incentive.", "Band 7.0-7.5"),
    ("incidence", "noun", "rate of occurrence", "High incidence of disease.", "Band 8.0+"),
    ("incline", "verb", "to tend toward", "I'm inclined to agree.", "Band 7.0-7.5"),
    ("incorporate", "verb", "to include", "Incorporate feedback.", "Band 7.0-7.5"),
    ("index", "noun", "an indicator", "Price index.", "Band 6.0-6.5"),
    ("indicate", "verb", "to show", "Results indicate progress.", "Band 6.0-6.5"),
    ("induce", "verb", "to cause", "Induce change.", "Band 8.0+"),
    ("inevitable", "adjective", "unavoidable", "Change is inevitable.", "Band 7.0-7.5"),
    ("infer", "verb", "to conclude", "Infer meaning from context.", "Band 7.0-7.5"),
    ("infrastructure", "noun", "basic facilities", "Improve infrastructure.", "Band 7.0-7.5"),
    ("inherent", "adjective", "existing naturally", "Inherent risks.", "Band 8.0+"),
    ("inhibit", "verb", "to prevent", "Inhibit growth.", "Band 8.0+"),
    ("initial", "adjective", "first", "Initial stage.", "Band 6.0-6.5"),
    ("initiate", "verb", "to begin", "Initiate the process.", "Band 7.0-7.5"),
    ("innovate", "verb", "to introduce new ideas", "Innovate constantly.", "Band 7.0-7.5"),
    ("input", "noun", "contribution", "Valuable input.", "Band 6.0-6.5"),
    ("insert", "verb", "to put in", "Insert the key.", "Band 6.0-6.5"),
    ("insight", "noun", "understanding", "Gain insight.", "Band 7.0-7.5"),
    ("inspect", "verb", "to examine", "Inspect the goods.", "Band 6.0-6.5"),
    ("instance", "noun", "an example", "For instance.", "Band 6.0-6.5"),
    ("institute", "noun", "an organization", "Research institute.", "Band 6.0-6.5"),
    ("instruct", "verb", "to teach", "Instruct students.", "Band 6.0-6.5"),
    ("integral", "adjective", "essential", "Integral part.", "Band 8.0+"),
    ("integrate", "verb", "to combine", "Integrate systems.", "Band 7.0-7.5"),
    ("integrity", "noun", "honesty", "Act with integrity.", "Band 8.0+"),
    ("intelligent", "adjective", "smart", "Intelligent design.", "Band 6.0-6.5"),
    ("intense", "adjective", "very strong", "Intense heat.", "Band 6.0-6.5"),
    ("interact", "verb", "to communicate", "Interact with others.", "Band 6.0-6.5"),
    ("intermediate", "adjective", "in the middle", "Intermediate level.", "Band 6.0-6.5"),
    ("internal", "adjective", "inside", "Internal affairs.", "Band 6.0-6.5"),
    ("interval", "noun", "a gap", "Regular intervals.", "Band 7.0-7.5"),
    ("intervene", "verb", "to interfere", "Police intervened.", "Band 7.0-7.5"),
    ("intrinsic", "adjective", "inherent", "Intrinsic value.", "Band 8.0+"),
    ("invest", "verb", "to put money into", "Invest wisely.", "Band 6.0-6.5"),
    ("investigate", "verb", "to examine", "Investigate the case.", "Band 6.0-6.5"),
    ("invoke", "verb", "to call upon", "Invoke the law.", "Band 8.0+"),
    ("isolate", "verb", "to separate", "Isolate the problem.", "Band 7.0-7.5"),
    ("item", "noun", "a thing", "Each item.", "Band 4.5-5.5"),
    ("job", "noun", "work", "Find a job.", "Band 4.5-5.5"),
    ("journal", "noun", "a publication", "Academic journal.", "Band 6.0-6.5"),
    ("justify", "verb", "to give reasons", "Justify your answer.", "Band 7.0-7.5"),
    ("label", "noun", "a tag", "Read the label.", "Band 4.5-5.5"),
    ("layer", "noun", "a level", "Multiple layers.", "Band 6.0-6.5"),
    ("lecture", "noun", "a talk", "Attend a lecture.", "Band 6.0-6.5"),
    ("legal", "adjective", "lawful", "Legal advice.", "Band 6.0-6.5"),
    ("legislate", "verb", "to make laws", "Legislate change.", "Band 7.0-7.5"),
    ("levy", "verb", "to impose", "Levy taxes.", "Band 8.0+"),
    ("liberal", "adjective", "open to change", "Liberal views.", "Band 7.0-7.5"),
    ("license", "noun", "permission", "Driver's license.", "Band 6.0-6.5"),
    ("likewise", "adverb", "similarly", "Likewise, we agree.", "Band 7.0-7.5"),
    ("link", "verb", "to connect", "Link the ideas.", "Band 4.5-5.5"),
    ("locate", "verb", "to find", "Locate the source.", "Band 6.0-6.5"),
    ("logic", "noun", "reasoning", "Sound logic.", "Band 6.0-6.5"),
    ("maintain", "verb", "to keep", "Maintain standards.", "Band 6.0-6.5"),
    ("manual", "adjective", "done by hand", "Manual labor.", "Band 6.0-6.5"),
    ("margin", "noun", "edge", "Profit margin.", "Band 7.0-7.5"),
    ("mature", "adjective", "fully developed", "Mature approach.", "Band 6.0-6.5"),
    ("maximize", "verb", "to increase to maximum", "Maximize profit.", "Band 7.0-7.5"),
    ("mechanism", "noun", "a system", "Defense mechanism.", "Band 7.0-7.5"),
    ("media", "noun", "communication channels", "Social media.", "Band 6.0-6.5"),
    ("mediate", "verb", "to negotiate", "Mediate a dispute.", "Band 8.0+"),
    ("medical", "adjective", "relating to medicine", "Medical care.", "Band 6.0-6.5"),
    ("medium", "noun", "a means", "Through this medium.", "Band 6.0-6.5"),
    ("mental", "adjective", "relating to the mind", "Mental health.", "Band 6.0-6.5"),
    ("migrate", "verb", "to move", "Birds migrate south.", "Band 6.0-6.5"),
    ("military", "adjective", "relating to armed forces", "Military service.", "Band 6.0-6.5"),
    ("minimize", "verb", "to reduce to minimum", "Minimize risk.", "Band 7.0-7.5"),
    ("minimum", "noun", "the least amount", "Minimum wage.", "Band 6.0-6.5"),
    ("ministry", "noun", "government department", "Ministry of Education.", "Band 7.0-7.5"),
    ("minor", "adjective", "small", "Minor changes.", "Band 6.0-6.5"),
    ("mode", "noun", "a way", "Mode of transport.", "Band 6.0-6.5"),
    ("modify", "verb", "to change", "Modify the design.", "Band 6.0-6.5"),
    ("monitor", "verb", "to observe", "Monitor progress.", "Band 6.0-6.5"),
    ("motive", "noun", "a reason", "What's the motive?", "Band 7.0-7.5"),
    ("mutual", "adjective", "shared", "Mutual respect.", "Band 7.0-7.5"),
    ("negate", "verb", "to deny", "Negate the effect.", "Band 8.0+"),
    ("network", "noun", "a system of connections", "Social network.", "Band 6.0-6.5"),
    ("neutral", "adjective", "impartial", "Stay neutral.", "Band 7.0-7.5"),
    ("nevertheless", "adverb", "however", "Nevertheless, we tried.", "Band 7.0-7.5"),
    ("nonetheless", "adverb", "in spite of that", "Nonetheless, it worked.", "Band 8.0+"),
    ("norm", "noun", "a standard", "Social norms.", "Band 7.0-7.5"),
    ("normal", "adjective", "usual", "Normal behavior.", "Band 4.5-5.5"),
    ("notion", "noun", "an idea", "The notion of freedom.", "Band 7.0-7.5"),
    ("notwithstanding", "preposition", "despite", "Notwithstanding the risks.", "Band 8.0+"),
    ("nuclear", "adjective", "relating to atoms", "Nuclear energy.", "Band 6.0-6.5"),
    ("objective", "noun", "a goal", "Main objective.", "Band 6.0-6.5"),
    ("obtain", "verb", "to get", "Obtain permission.", "Band 6.0-6.5"),
    ("obvious", "adjective", "clear", "It's obvious.", "Band 6.0-6.5"),
    ("occupy", "verb", "to fill", "Occupy the space.", "Band 6.0-6.5"),
    ("odd", "adjective", "strange", "Odd behavior.", "Band 6.0-6.5"),
    ("offset", "verb", "to balance", "Offset the cost.", "Band 8.0+"),
    ("ongoing", "adjective", "continuing", "Ongoing project.", "Band 7.0-7.5"),
    ("option", "noun", "a choice", "Best option.", "Band 6.0-6.5"),
    ("orient", "verb", "to direct", "Orient yourself.", "Band 7.0-7.5"),
    ("outcome", "noun", "a result", "Positive outcome.", "Band 6.0-6.5"),
    ("output", "noun", "production", "Increase output.", "Band 6.0-6.5"),
    ("overall", "adjective", "total", "Overall performance.", "Band 6.0-6.5"),
    ("overlap", "verb", "to cover partly", "Ideas overlap.", "Band 7.0-7.5"),
    ("overseas", "adverb", "abroad", "Work overseas.", "Band 6.0-6.5"),
    ("panel", "noun", "a group", "Expert panel.", "Band 6.0-6.5"),
    ("paradigm", "noun", "a model", "Paradigm shift.", "Band 8.0+"),
    ("paragraph", "noun", "a section of text", "First paragraph.", "Band 4.5-5.5"),
    ("parallel", "adjective", "side by side", "Parallel lines.", "Band 7.0-7.5"),
    ("parameter", "noun", "a limit", "Set parameters.", "Band 8.0+"),
    ("participate", "verb", "to take part", "Participate actively.", "Band 6.0-6.5"),
    ("partner", "noun", "an associate", "Business partner.", "Band 4.5-5.5"),
    ("passive", "adjective", "not active", "Passive role.", "Band 7.0-7.5"),
    ("perceive", "verb", "to notice", "Perceive the difference.", "Band 7.0-7.5"),
    ("persist", "verb", "to continue", "Problems persist.", "Band 7.0-7.5"),
    ("perspective", "noun", "a viewpoint", "Different perspective.", "Band 7.0-7.5"),
    ("phase", "noun", "a stage", "First phase.", "Band 6.0-6.5"),
    ("phenomenon", "noun", "an event", "Natural phenomenon.", "Band 7.0-7.5"),
    ("philosophy", "noun", "a belief system", "My philosophy.", "Band 7.0-7.5"),
    ("physical", "adjective", "relating to the body", "Physical exercise.", "Band 6.0-6.5"),
    ("plus", "conjunction", "in addition", "Plus, it's cheap.", "Band 4.5-5.5"),
    ("portion", "noun", "a part", "Large portion.", "Band 6.0-6.5"),
    ("pose", "verb", "to present", "Pose a question.", "Band 7.0-7.5"),
    ("positive", "adjective", "favorable", "Positive attitude.", "Band 4.5-5.5"),
    ("potential", "adjective", "possible", "Potential risk.", "Band 6.0-6.5"),
    ("practitioner", "noun", "a professional", "Medical practitioner.", "Band 8.0+"),
    ("precede", "verb", "to come before", "This precedes that.", "Band 7.0-7.5"),
    ("precise", "adjective", "exact", "Be precise.", "Band 7.0-7.5"),
    ("predict", "verb", "to forecast", "Predict the outcome.", "Band 6.0-6.5"),
    ("predominant", "adjective", "most common", "Predominant view.", "Band 8.0+"),
    ("preliminary", "adjective", "initial", "Preliminary results.", "Band 8.0+"),
    ("presume", "verb", "to assume", "I presume so.", "Band 8.0+"),
    ("previous", "adjective", "earlier", "Previous experience.", "Band 6.0-6.5"),
    ("primary", "adjective", "main", "Primary goal.", "Band 6.0-6.5"),
    ("prime", "adjective", "main", "Prime example.", "Band 7.0-7.5"),
    ("principal", "adjective", "most important", "Principal reason.", "Band 7.0-7.5"),
    ("prior", "adjective", "earlier", "Prior knowledge.", "Band 7.0-7.5"),
    ("priority", "noun", "importance", "Top priority.", "Band 6.0-6.5"),
    ("procedure", "noun", "a method", "Follow procedure.", "Band 6.0-6.5"),
    ("professional", "adjective", "relating to a profession", "Professional advice.", "Band 6.0-6.5"),
    ("prohibit", "verb", "to forbid", "Smoking prohibited.", "Band 7.0-7.5"),
    ("project", "noun", "a planned work", "New project.", "Band 4.5-5.5"),
    ("promote", "verb", "to encourage", "Promote health.", "Band 6.0-6.5"),
    ("proportion", "noun", "a part", "Large proportion.", "Band 7.0-7.5"),
    ("prospect", "noun", "possibility", "Future prospects.", "Band 7.0-7.5"),
    ("protocol", "noun", "a procedure", "Follow protocol.", "Band 8.0+"),
    ("psychology", "noun", "study of mind", "Study psychology.", "Band 7.0-7.5"),
    ("publication", "noun", "a published work", "Recent publication.", "Band 7.0-7.5"),
    ("publish", "verb", "to issue", "Publish research.", "Band 6.0-6.5"),
    ("purchase", "verb", "to buy", "Purchase online.", "Band 6.0-6.5"),
    ("pursue", "verb", "to follow", "Pursue your dreams.", "Band 7.0-7.5"),
    ("qualitative", "adjective", "relating to quality", "Qualitative analysis.", "Band 8.0+"),
    ("quote", "verb", "to cite", "Quote the source.", "Band 6.0-6.5"),
    ("radical", "adjective", "extreme", "Radical change.", "Band 7.0-7.5"),
    ("random", "adjective", "without pattern", "Random selection.", "Band 6.0-6.5"),
    ("range", "noun", "a variety", "Wide range.", "Band 6.0-6.5"),
    ("ratio", "noun", "proportion", "Calculate the ratio.", "Band 7.0-7.5"),
    ("rational", "adjective", "logical", "Rational thinking.", "Band 7.0-7.5"),
    ("react", "verb", "to respond", "React quickly.", "Band 6.0-6.5"),
    ("recover", "verb", "to get back", "Recover from illness.", "Band 6.0-6.5"),
    ("refine", "verb", "to improve", "Refine the process.", "Band 7.0-7.5"),
    ("regime", "noun", "a system", "New regime.", "Band 8.0+"),
    ("region", "noun", "an area", "This region.", "Band 6.0-6.5"),
    ("register", "verb", "to record", "Register online.", "Band 6.0-6.5"),
    ("regulate", "verb", "to control", "Regulate the market.", "Band 7.0-7.5"),
    ("reinforce", "verb", "to strengthen", "Reinforce learning.", "Band 7.0-7.5"),
    ("reject", "verb", "to refuse", "Reject the offer.", "Band 6.0-6.5"),
    ("relax", "verb", "to rest", "Relax and breathe.", "Band 4.5-5.5"),
    ("release", "verb", "to let go", "Release the report.", "Band 6.0-6.5"),
    ("relevant", "adjective", "connected", "Relevant information.", "Band 6.0-6.5"),
    ("reluctance", "noun", "unwillingness", "Show reluctance.", "Band 8.0+"),
    ("rely", "verb", "to depend", "Rely on data.", "Band 6.0-6.5"),
    ("remove", "verb", "to take away", "Remove obstacles.", "Band 4.5-5.5"),
    ("replicate", "verb", "to copy", "Replicate results.", "Band 8.0+"),
    ("represent", "verb", "to stand for", "Represent the company.", "Band 6.0-6.5"),
    ("require", "verb", "to need", "This requires effort.", "Band 6.0-6.5"),
    ("reside", "verb", "to live", "Reside in the city.", "Band 7.0-7.5"),
    ("resolve", "verb", "to solve", "Resolve conflicts.", "Band 7.0-7.5"),
    ("resource", "noun", "a supply", "Natural resources.", "Band 6.0-6.5"),
    ("restore", "verb", "to bring back", "Restore order.", "Band 7.0-7.5"),
    ("restrain", "verb", "to hold back", "Restrain yourself.", "Band 8.0+"),
    ("restrict", "verb", "to limit", "Restrict access.", "Band 7.0-7.5"),
    ("retain", "verb", "to keep", "Retain information.", "Band 7.0-7.5"),
    ("reveal", "verb", "to show", "Reveal the truth.", "Band 6.0-6.5"),
    ("revenue", "noun", "income", "Increase revenue.", "Band 7.0-7.5"),
    ("reverse", "verb", "to change to opposite", "Reverse the decision.", "Band 7.0-7.5"),
    ("revise", "verb", "to change", "Revise the plan.", "Band 6.0-6.5"),
    ("revolution", "noun", "a major change", "Industrial revolution.", "Band 7.0-7.5"),
    ("rigid", "adjective", "inflexible", "Rigid rules.", "Band 8.0+"),
    ("route", "noun", "a way", "Best route.", "Band 6.0-6.5"),
    ("scenario", "noun", "a situation", "Worst-case scenario.", "Band 7.0-7.5"),
    ("schedule", "noun", "a plan", "Tight schedule.", "Band 6.0-6.5"),
    ("scheme", "noun", "a plan", "New scheme.", "Band 7.0-7.5"),
    ("scope", "noun", "extent", "Within scope.", "Band 7.0-7.5"),
    ("seek", "verb", "to look for", "Seek advice.", "Band 6.0-6.5"),
    ("select", "verb", "to choose", "Select carefully.", "Band 6.0-6.5"),
    ("sequence", "noun", "an order", "In sequence.", "Band 7.0-7.5"),
    ("series", "noun", "a set", "A series of events.", "Band 6.0-6.5"),
    ("shift", "verb", "to move", "Shift focus.", "Band 6.0-6.5"),
    ("simulate", "verb", "to imitate", "Simulate conditions.", "Band 8.0+"),
    ("site", "noun", "a location", "Construction site.", "Band 6.0-6.5"),
    ("so-called", "adjective", "commonly named", "So-called experts.", "Band 7.0-7.5"),
    ("sole", "adjective", "only", "Sole purpose.", "Band 7.0-7.5"),
    ("somewhat", "adverb", "to some degree", "Somewhat different.", "Band 6.0-6.5"),
    ("sophisticated", "adjective", "complex", "Sophisticated system.", "Band 7.0-7.5"),
    ("sphere", "noun", "an area", "Public sphere.", "Band 8.0+"),
    ("stable", "adjective", "steady", "Stable condition.", "Band 6.0-6.5"),
    ("statistic", "noun", "numerical data", "Key statistics.", "Band 6.0-6.5"),
    ("status", "noun", "position", "Current status.", "Band 6.0-6.5"),
    ("straightforward", "adjective", "simple", "Straightforward answer.", "Band 7.0-7.5"),
    ("strategy", "noun", "a plan", "Marketing strategy.", "Band 6.0-6.5"),
    ("stress", "noun", "pressure", "Under stress.", "Band 6.0-6.5"),
    ("structure", "noun", "arrangement", "Organizational structure.", "Band 6.0-6.5"),
    ("style", "noun", "manner", "Writing style.", "Band 4.5-5.5"),
    ("submit", "verb", "to present", "Submit your work.", "Band 6.0-6.5"),
    ("subordinate", "adjective", "lower in rank", "Subordinate role.", "Band 8.0+"),
    ("subsequent", "adjective", "following", "Subsequent events.", "Band 7.0-7.5"),
    ("subsidy", "noun", "financial aid", "Government subsidy.", "Band 8.0+"),
    ("substitute", "verb", "to replace", "Substitute ingredients.", "Band 7.0-7.5"),
    ("successor", "noun", "one who follows", "Choose a successor.", "Band 8.0+"),
    ("sufficient", "adjective", "enough", "Sufficient evidence.", "Band 6.0-6.5"),
    ("sum", "noun", "total", "Large sum.", "Band 6.0-6.5"),
    ("summarize", "verb", "to give a summary", "Summarize the points.", "Band 6.0-6.5"),
    ("supplement", "verb", "to add to", "Supplement your income.", "Band 7.0-7.5"),
    ("survey", "noun", "a study", "Conduct a survey.", "Band 6.0-6.5"),
    ("survive", "verb", "to stay alive", "Survive the crisis.", "Band 6.0-6.5"),
    ("suspend", "verb", "to stop temporarily", "Suspend operations.", "Band 7.0-7.5"),
    ("sustain", "verb", "to maintain", "Sustain growth.", "Band 7.0-7.5"),
    ("symbol", "noun", "a sign", "National symbol.", "Band 6.0-6.5"),
    ("tape", "noun", "a strip", "Tape recording.", "Band 4.5-5.5"),
    ("target", "noun", "a goal", "Meet the target.", "Band 6.0-6.5"),
    ("task", "noun", "a job", "Complete the task.", "Band 4.5-5.5"),
    ("team", "noun", "a group", "Team work.", "Band 4.5-5.5"),
    ("technical", "adjective", "relating to technology", "Technical skills.", "Band 6.0-6.5"),
    ("technique", "noun", "a method", "New technique.", "Band 6.0-6.5"),
    ("technology", "noun", "applied science", "Modern technology.", "Band 6.0-6.5"),
    ("temporary", "adjective", "not permanent", "Temporary solution.", "Band 6.0-6.5"),
    ("tense", "adjective", "nervous", "Tense atmosphere.", "Band 6.0-6.5"),
    ("terminate", "verb", "to end", "Terminate the contract.", "Band 8.0+"),
    ("text", "noun", "written material", "Read the text.", "Band 4.5-5.5"),
    ("theme", "noun", "a subject", "Main theme.", "Band 6.0-6.5"),
    ("thereby", "adverb", "by that means", "Thereby improving.", "Band 8.0+"),
    ("thesis", "noun", "a theory", "Thesis statement.", "Band 8.0+"),
    ("topic", "noun", "a subject", "Main topic.", "Band 4.5-5.5"),
    ("trace", "verb", "to find", "Trace the origin.", "Band 7.0-7.5"),
    ("tradition", "noun", "a custom", "Cultural tradition.", "Band 6.0-6.5"),
    ("transfer", "verb", "to move", "Transfer funds.", "Band 6.0-6.5"),
    ("transform", "verb", "to change completely", "Transform the industry.", "Band 7.0-7.5"),
    ("transit", "noun", "passage", "In transit.", "Band 7.0-7.5"),
    ("transmit", "verb", "to send", "Transmit data.", "Band 7.0-7.5"),
    ("transport", "verb", "to carry", "Transport goods.", "Band 6.0-6.5"),
    ("trend", "noun", "a tendency", "Current trend.", "Band 6.0-6.5"),
    ("trigger", "verb", "to cause", "Trigger a response.", "Band 7.0-7.5"),
    ("ultimate", "adjective", "final", "Ultimate goal.", "Band 7.0-7.5"),
    ("undergo", "verb", "to experience", "Undergo change.", "Band 7.0-7.5"),
    ("underlie", "verb", "to be the basis", "Principles underlie success.", "Band 8.0+"),
    ("undertake", "verb", "to begin", "Undertake a task.", "Band 7.0-7.5"),
    ("uniform", "adjective", "consistent", "Uniform standards.", "Band 7.0-7.5"),
    ("unify", "verb", "to unite", "Unify the team.", "Band 8.0+"),
    ("unique", "adjective", "one of a kind", "Unique opportunity.", "Band 6.0-6.5"),
    ("utilize", "verb", "to use", "Utilize resources.", "Band 7.0-7.5"),
    ("valid", "adjective", "acceptable", "Valid argument.", "Band 6.0-6.5"),
    ("vehicle", "noun", "a means of transport", "Electric vehicle.", "Band 6.0-6.5"),
    ("version", "noun", "a form", "Latest version.", "Band 6.0-6.5"),
    ("via", "preposition", "by way of", "Via email.", "Band 6.0-6.5"),
    ("violate", "verb", "to break", "Violate rules.", "Band 7.0-7.5"),
    ("virtual", "adjective", "simulated", "Virtual reality.", "Band 7.0-7.5"),
    ("visible", "adjective", "able to be seen", "Visible change.", "Band 6.0-6.5"),
    ("vision", "noun", "sight", "Clear vision.", "Band 6.0-6.5"),
    ("visual", "adjective", "relating to sight", "Visual aids.", "Band 6.0-6.5"),
    ("volume", "noun", "amount", "High volume.", "Band 6.0-6.5"),
    ("voluntary", "adjective", "done by choice", "Voluntary work.", "Band 7.0-7.5"),
    ("welfare", "noun", "well-being", "Social welfare.", "Band 7.0-7.5"),
    ("whereas", "conjunction", "while", "Whereas others disagree.", "Band 7.0-7.5"),
    ("whereby", "adverb", "by which", "A system whereby.", "Band 8.0+"),
    ("widespread", "adjective", "common", "Widespread use.", "Band 7.0-7.5"),
]

def translate_batch(texts, target_lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={GOOGLE_API_KEY}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            resp = requests.post(url, json={"q": batch, "source": "en", "target": target_lang}, timeout=30)
            if resp.status_code == 200:
                result.extend([t['translatedText'] for t in resp.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

def main():
    with open('assets/data/words.json', 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    existing = {w['word'].lower() for w in words}
    start_id = max(w['id'] for w in words) + 1
    categories = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
    
    new_words = []
    for word, pos, definition, example, level in WORDS_PART2:
        if word.lower() not in existing:
            new_words.append({
                "id": start_id + len(new_words),
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": categories[(start_id + len(new_words)) % len(categories)]
            })
            existing.add(word.lower())
    
    print(f"새 단어: {len(new_words)}개")
    
    if new_words:
        defs = [w['definition'] for w in new_words]
        exs = [w['example'] for w in new_words]
        
        for lang in LANGUAGES:
            print(f"{lang} 번역중...")
            trans_defs = translate_batch(defs, lang)
            trans_exs = translate_batch(exs, lang)
            for i, w in enumerate(new_words):
                if 'translations' not in w:
                    w['translations'] = {}
                w['translations'][lang] = {
                    'definition': trans_defs[i],
                    'example': trans_exs[i]
                }
        
        words.extend(new_words)
        with open('assets/data/words.json', 'w', encoding='utf-8') as f:
            json.dump(words, f, ensure_ascii=False, indent=2)
    
    print(f"총: {len(words)}개")

if __name__ == "__main__":
    main()
