#!/usr/bin/env python3
import json, requests, time
API = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGS = ['ko', 'ja', 'zh', 'es', 'fr', 'de']
WORDS = [
    ("table", "noun", "furniture", "Dining table.", "Band 4.5-5.5"),
    ("tablet", "noun", "device", "Digital tablet.", "Band 6.0-6.5"),
    ("taboo", "noun", "prohibition", "Social taboo.", "Band 8.0+"),
    ("tactic", "noun", "strategy", "Negotiation tactic.", "Band 7.0-7.5"),
    ("tag", "noun", "label", "Price tag.", "Band 6.0-6.5"),
    ("tail", "noun", "animal part", "Dog tail.", "Band 4.5-5.5"),
    ("tailor", "noun", "clothes maker", "Local tailor.", "Band 6.0-6.5"),
    ("takeaway", "noun", "food to go", "Chinese takeaway.", "Band 6.0-6.5"),
    ("takeover", "noun", "acquisition", "Hostile takeover.", "Band 7.0-7.5"),
    ("tale", "noun", "story", "Fairy tale.", "Band 6.0-6.5"),
    ("talent", "noun", "ability", "Natural talent.", "Band 6.0-6.5"),
    ("tank", "noun", "container", "Water tank.", "Band 6.0-6.5"),
    ("tap", "noun", "faucet", "Water tap.", "Band 6.0-6.5"),
    ("tape", "noun", "strip", "Adhesive tape.", "Band 4.5-5.5"),
    ("target", "noun", "goal", "Sales target.", "Band 6.0-6.5"),
    ("tariff", "noun", "tax", "Import tariff.", "Band 8.0+"),
    ("task", "noun", "job", "Simple task.", "Band 4.5-5.5"),
    ("taste", "noun", "flavor", "Good taste.", "Band 4.5-5.5"),
    ("taxation", "noun", "taxing", "Heavy taxation.", "Band 7.0-7.5"),
    ("taxi", "noun", "cab", "Take a taxi.", "Band 4.5-5.5"),
    ("taxpayer", "noun", "tax payer", "Average taxpayer.", "Band 7.0-7.5"),
    ("tea", "noun", "drink", "Green tea.", "Band 4.5-5.5"),
    ("teacher", "noun", "educator", "English teacher.", "Band 4.5-5.5"),
    ("teaching", "noun", "instruction", "Teaching method.", "Band 4.5-5.5"),
    ("team", "noun", "group", "Football team.", "Band 4.5-5.5"),
    ("teammate", "noun", "team member", "Former teammate.", "Band 6.0-6.5"),
    ("teamwork", "noun", "cooperation", "Good teamwork.", "Band 6.0-6.5"),
    ("tear", "noun", "drop", "Shed tears.", "Band 6.0-6.5"),
    ("technique", "noun", "method", "New technique.", "Band 6.0-6.5"),
    ("technology", "noun", "tech", "Modern technology.", "Band 4.5-5.5"),
    ("teenager", "noun", "youth", "Average teenager.", "Band 4.5-5.5"),
    ("telecommunication", "noun", "communication", "Telecommunication industry.", "Band 7.0-7.5"),
    ("telegraph", "noun", "communication device", "Old telegraph.", "Band 8.0+"),
    ("telephone", "noun", "phone", "Use telephone.", "Band 4.5-5.5"),
    ("telescope", "noun", "viewing device", "Space telescope.", "Band 6.0-6.5"),
    ("television", "noun", "TV", "Watch television.", "Band 4.5-5.5"),
    ("temper", "noun", "mood", "Bad temper.", "Band 6.0-6.5"),
    ("temperament", "noun", "disposition", "Artistic temperament.", "Band 8.0+"),
    ("temperature", "noun", "heat level", "Body temperature.", "Band 4.5-5.5"),
    ("temple", "noun", "sacred place", "Ancient temple.", "Band 6.0-6.5"),
    ("tempo", "noun", "speed", "Fast tempo.", "Band 7.0-7.5"),
    ("temptation", "noun", "desire", "Resist temptation.", "Band 7.0-7.5"),
    ("tenant", "noun", "renter", "Current tenant.", "Band 6.0-6.5"),
    ("tendency", "noun", "inclination", "Natural tendency.", "Band 6.0-6.5"),
    ("tennis", "noun", "sport", "Play tennis.", "Band 4.5-5.5"),
    ("tension", "noun", "stress", "Political tension.", "Band 6.0-6.5"),
    ("tent", "noun", "shelter", "Camping tent.", "Band 6.0-6.5"),
    ("tenure", "noun", "holding period", "Academic tenure.", "Band 8.0+"),
    ("term", "noun", "period", "School term.", "Band 4.5-5.5"),
    ("terminal", "noun", "station", "Airport terminal.", "Band 6.0-6.5"),
    ("termination", "noun", "ending", "Contract termination.", "Band 7.0-7.5"),
    ("terminology", "noun", "terms", "Medical terminology.", "Band 7.0-7.5"),
    ("terrace", "noun", "patio", "Garden terrace.", "Band 6.0-6.5"),
    ("terrain", "noun", "ground", "Rough terrain.", "Band 7.0-7.5"),
    ("territory", "noun", "area", "Enemy territory.", "Band 6.0-6.5"),
    ("terror", "noun", "fear", "Reign of terror.", "Band 7.0-7.5"),
    ("terrorism", "noun", "violence", "Fight terrorism.", "Band 7.0-7.5"),
    ("terrorist", "noun", "violent person", "Known terrorist.", "Band 7.0-7.5"),
    ("testament", "noun", "proof", "Living testament.", "Band 8.0+"),
    ("testimony", "noun", "evidence", "Expert testimony.", "Band 8.0+"),
    ("text", "noun", "written material", "Read the text.", "Band 4.5-5.5"),
    ("textbook", "noun", "school book", "Science textbook.", "Band 6.0-6.5"),
    ("textile", "noun", "fabric", "Textile industry.", "Band 7.0-7.5"),
    ("texture", "noun", "surface feel", "Smooth texture.", "Band 6.0-6.5"),
    ("thanksgiving", "noun", "gratitude", "Thanksgiving dinner.", "Band 6.0-6.5"),
    ("theatre", "noun", "theater", "Live theatre.", "Band 4.5-5.5"),
    ("theft", "noun", "stealing", "Identity theft.", "Band 6.0-6.5"),
    ("theme", "noun", "topic", "Main theme.", "Band 6.0-6.5"),
    ("theology", "noun", "religious study", "Christian theology.", "Band 8.0+"),
    ("theorem", "noun", "principle", "Math theorem.", "Band 8.0+"),
    ("therapist", "noun", "counselor", "Physical therapist.", "Band 6.0-6.5"),
    ("therapy", "noun", "treatment", "Speech therapy.", "Band 6.0-6.5"),
    ("thesis", "noun", "dissertation", "PhD thesis.", "Band 7.0-7.5"),
    ("thief", "noun", "robber", "Catch the thief.", "Band 6.0-6.5"),
    ("thigh", "noun", "body part", "Thigh muscle.", "Band 7.0-7.5"),
    ("thinker", "noun", "philosopher", "Great thinker.", "Band 7.0-7.5"),
    ("thinking", "noun", "thought process", "Critical thinking.", "Band 6.0-6.5"),
    ("thirst", "noun", "need for water", "Quench thirst.", "Band 6.0-6.5"),
    ("thorn", "noun", "spike", "Rose thorn.", "Band 6.0-6.5"),
    ("thought", "noun", "idea", "Deep thought.", "Band 4.5-5.5"),
    ("thread", "noun", "string", "Sewing thread.", "Band 6.0-6.5"),
    ("threat", "noun", "danger", "Security threat.", "Band 6.0-6.5"),
    ("threshold", "noun", "limit", "Pain threshold.", "Band 7.0-7.5"),
    ("thrill", "noun", "excitement", "Great thrill.", "Band 6.0-6.5"),
    ("thriller", "noun", "exciting story", "Crime thriller.", "Band 6.0-6.5"),
    ("throat", "noun", "body part", "Sore throat.", "Band 4.5-5.5"),
    ("throne", "noun", "royal seat", "Royal throne.", "Band 7.0-7.5"),
    ("thumb", "noun", "finger", "Thumb up.", "Band 4.5-5.5"),
    ("thunder", "noun", "loud sound", "Thunder and lightning.", "Band 6.0-6.5"),
    ("tick", "noun", "mark", "Check tick.", "Band 6.0-6.5"),
    ("ticket", "noun", "pass", "Train ticket.", "Band 4.5-5.5"),
    ("tide", "noun", "water movement", "High tide.", "Band 6.0-6.5"),
    ("tie", "noun", "necktie", "Silk tie.", "Band 4.5-5.5"),
    ("tiger", "noun", "animal", "Bengal tiger.", "Band 4.5-5.5"),
    ("tile", "noun", "flat piece", "Floor tile.", "Band 6.0-6.5"),
    ("timber", "noun", "wood", "Construction timber.", "Band 7.0-7.5"),
    ("timeframe", "noun", "period", "Project timeframe.", "Band 7.0-7.5"),
    ("timeline", "noun", "schedule", "Project timeline.", "Band 7.0-7.5"),
    ("timer", "noun", "clock", "Kitchen timer.", "Band 6.0-6.5"),
    ("tin", "noun", "metal container", "Tin can.", "Band 6.0-6.5"),
    ("tip", "noun", "advice", "Helpful tip.", "Band 4.5-5.5"),
    ("tissue", "noun", "thin paper", "Facial tissue.", "Band 6.0-6.5"),
    ("title", "noun", "name", "Book title.", "Band 4.5-5.5"),
    ("toast", "noun", "bread", "Buttered toast.", "Band 4.5-5.5"),
    ("tobacco", "noun", "plant", "Tobacco product.", "Band 6.0-6.5"),
    ("toe", "noun", "body part", "Big toe.", "Band 4.5-5.5"),
    ("tolerance", "noun", "acceptance", "Religious tolerance.", "Band 7.0-7.5"),
    ("toll", "noun", "fee", "Road toll.", "Band 7.0-7.5"),
    ("tomato", "noun", "vegetable", "Fresh tomato.", "Band 4.5-5.5"),
    ("tomb", "noun", "burial place", "Ancient tomb.", "Band 7.0-7.5"),
    ("tomorrow", "noun", "next day", "See you tomorrow.", "Band 4.5-5.5"),
    ("ton", "noun", "weight unit", "Metric ton.", "Band 6.0-6.5"),
    ("tone", "noun", "sound quality", "Soft tone.", "Band 6.0-6.5"),
    ("tongue", "noun", "body part", "Native tongue.", "Band 6.0-6.5"),
    ("toolkit", "noun", "tool set", "Software toolkit.", "Band 7.0-7.5"),
    ("tooth", "noun", "body part", "Wisdom tooth.", "Band 4.5-5.5"),
    ("top", "noun", "highest point", "Mountain top.", "Band 4.5-5.5"),
    ("topic", "noun", "subject", "Hot topic.", "Band 4.5-5.5"),
    ("torch", "noun", "light", "Olympic torch.", "Band 6.0-6.5"),
    ("tornado", "noun", "storm", "Powerful tornado.", "Band 6.0-6.5"),
    ("torture", "noun", "cruelty", "Mental torture.", "Band 8.0+"),
    ("touch", "noun", "contact", "Light touch.", "Band 4.5-5.5"),
    ("tour", "noun", "trip", "World tour.", "Band 4.5-5.5"),
    ("tourism", "noun", "travel industry", "Mass tourism.", "Band 6.0-6.5"),
    ("tourist", "noun", "traveler", "Foreign tourist.", "Band 4.5-5.5"),
    ("tournament", "noun", "competition", "Tennis tournament.", "Band 6.0-6.5"),
    ("tower", "noun", "tall building", "Eiffel Tower.", "Band 4.5-5.5"),
    ("town", "noun", "small city", "Small town.", "Band 4.5-5.5"),
    ("toxin", "noun", "poison", "Environmental toxin.", "Band 8.0+"),
    ("toy", "noun", "plaything", "Children's toy.", "Band 4.5-5.5"),
    ("trace", "noun", "sign", "Without a trace.", "Band 6.0-6.5"),
    ("track", "noun", "path", "Race track.", "Band 4.5-5.5"),
    ("tract", "noun", "area", "Land tract.", "Band 8.0+"),
    ("trade", "noun", "commerce", "International trade.", "Band 6.0-6.5"),
    ("trademark", "noun", "brand", "Registered trademark.", "Band 7.0-7.5"),
    ("trader", "noun", "merchant", "Stock trader.", "Band 6.0-6.5"),
    ("tradition", "noun", "custom", "Family tradition.", "Band 6.0-6.5"),
    ("traffic", "noun", "vehicles", "Heavy traffic.", "Band 4.5-5.5"),
    ("tragedy", "noun", "disaster", "Personal tragedy.", "Band 6.0-6.5"),
    ("trail", "noun", "path", "Hiking trail.", "Band 6.0-6.5"),
    ("trailer", "noun", "vehicle", "Movie trailer.", "Band 6.0-6.5"),
    ("trainer", "noun", "coach", "Personal trainer.", "Band 6.0-6.5"),
    ("training", "noun", "education", "Job training.", "Band 4.5-5.5"),
    ("trait", "noun", "characteristic", "Personality trait.", "Band 7.0-7.5"),
    ("trajectory", "noun", "path", "Career trajectory.", "Band 8.0+"),
    ("tram", "noun", "streetcar", "City tram.", "Band 6.0-6.5"),
    ("transaction", "noun", "deal", "Financial transaction.", "Band 6.0-6.5"),
    ("transcript", "noun", "written record", "Academic transcript.", "Band 7.0-7.5"),
    ("transfer", "noun", "move", "Bank transfer.", "Band 6.0-6.5"),
    ("transformation", "noun", "change", "Digital transformation.", "Band 6.0-6.5"),
    ("transit", "noun", "transportation", "Public transit.", "Band 7.0-7.5"),
    ("transition", "noun", "change", "Smooth transition.", "Band 6.0-6.5"),
    ("translation", "noun", "conversion", "Accurate translation.", "Band 6.0-6.5"),
    ("transmission", "noun", "sending", "Data transmission.", "Band 7.0-7.5"),
    ("transparency", "noun", "openness", "Financial transparency.", "Band 7.0-7.5"),
    ("transplant", "noun", "organ transfer", "Heart transplant.", "Band 7.0-7.5"),
    ("transportation", "noun", "transport", "Public transportation.", "Band 4.5-5.5"),
    ("trap", "noun", "snare", "Mouse trap.", "Band 6.0-6.5"),
    ("trash", "noun", "garbage", "Take out trash.", "Band 4.5-5.5"),
    ("trauma", "noun", "shock", "Emotional trauma.", "Band 7.0-7.5"),
    ("traveler", "noun", "tourist", "Frequent traveler.", "Band 4.5-5.5"),
    ("tray", "noun", "flat container", "Serving tray.", "Band 6.0-6.5"),
    ("treason", "noun", "betrayal", "Commit treason.", "Band 8.0+"),
    ("treasure", "noun", "valuable thing", "Hidden treasure.", "Band 6.0-6.5"),
    ("treasury", "noun", "finance department", "National treasury.", "Band 8.0+"),
    ("treaty", "noun", "agreement", "Peace treaty.", "Band 7.0-7.5"),
    ("tree", "noun", "plant", "Oak tree.", "Band 4.5-5.5"),
    ("trek", "noun", "journey", "Mountain trek.", "Band 7.0-7.5"),
    ("trench", "noun", "ditch", "Deep trench.", "Band 8.0+"),
    ("trend", "noun", "tendency", "Fashion trend.", "Band 6.0-6.5"),
    ("trial", "noun", "test", "Court trial.", "Band 6.0-6.5"),
    ("triangle", "noun", "shape", "Love triangle.", "Band 6.0-6.5"),
    ("tribe", "noun", "group", "Native tribe.", "Band 6.0-6.5"),
    ("tribute", "noun", "honor", "Pay tribute.", "Band 7.0-7.5"),
    ("trick", "noun", "deception", "Magic trick.", "Band 4.5-5.5"),
    ("trigger", "noun", "cause", "Emotional trigger.", "Band 7.0-7.5"),
    ("trillion", "noun", "number", "One trillion.", "Band 7.0-7.5"),
    ("trio", "noun", "group of three", "Famous trio.", "Band 7.0-7.5"),
    ("trip", "noun", "journey", "Business trip.", "Band 4.5-5.5"),
    ("triumph", "noun", "victory", "Great triumph.", "Band 7.0-7.5"),
    ("trolley", "noun", "cart", "Shopping trolley.", "Band 6.0-6.5"),
    ("troop", "noun", "soldiers", "Military troop.", "Band 6.0-6.5"),
    ("trophy", "noun", "prize", "Gold trophy.", "Band 6.0-6.5"),
    ("tropical", "adjective", "hot and humid", "Tropical climate.", "Band 6.0-6.5"),
    ("trouble", "noun", "problem", "Big trouble.", "Band 4.5-5.5"),
    ("trousers", "noun", "pants", "Black trousers.", "Band 4.5-5.5"),
    ("trout", "noun", "fish", "Fresh trout.", "Band 7.0-7.5"),
    ("truck", "noun", "vehicle", "Delivery truck.", "Band 4.5-5.5"),
    ("trunk", "noun", "tree part", "Tree trunk.", "Band 6.0-6.5"),
    ("trust", "noun", "belief", "Mutual trust.", "Band 6.0-6.5"),
    ("trustee", "noun", "guardian", "Board trustee.", "Band 8.0+"),
    ("truth", "noun", "fact", "Absolute truth.", "Band 4.5-5.5"),
    ("tsunami", "noun", "giant wave", "Devastating tsunami.", "Band 7.0-7.5"),
    ("tube", "noun", "cylinder", "Test tube.", "Band 6.0-6.5"),
    ("tuition", "noun", "fee", "College tuition.", "Band 6.0-6.5"),
    ("tumor", "noun", "growth", "Brain tumor.", "Band 7.0-7.5"),
    ("tune", "noun", "melody", "Catchy tune.", "Band 6.0-6.5"),
    ("tunnel", "noun", "passage", "Underground tunnel.", "Band 6.0-6.5"),
    ("turbulence", "noun", "instability", "Air turbulence.", "Band 7.0-7.5"),
    ("turkey", "noun", "bird", "Roast turkey.", "Band 4.5-5.5"),
    ("turmoil", "noun", "chaos", "Political turmoil.", "Band 8.0+"),
    ("turn", "noun", "rotation", "Take a turn.", "Band 4.5-5.5"),
    ("turnout", "noun", "attendance", "Voter turnout.", "Band 7.0-7.5"),
    ("turnover", "noun", "revenue", "Staff turnover.", "Band 7.0-7.5"),
    ("tutor", "noun", "teacher", "Private tutor.", "Band 6.0-6.5"),
    ("tutorial", "noun", "lesson", "Online tutorial.", "Band 6.0-6.5"),
    ("twilight", "noun", "dusk", "At twilight.", "Band 7.0-7.5"),
    ("twin", "noun", "sibling", "Identical twin.", "Band 4.5-5.5"),
    ("twist", "noun", "turn", "Plot twist.", "Band 6.0-6.5"),
    ("type", "noun", "kind", "Blood type.", "Band 4.5-5.5"),
    ("typhoon", "noun", "storm", "Severe typhoon.", "Band 7.0-7.5"),
    ("tyranny", "noun", "oppression", "Political tyranny.", "Band 8.0+"),
    ("umbrella", "noun", "rain cover", "Open umbrella.", "Band 4.5-5.5"),
    ("uncertainty", "noun", "doubt", "Economic uncertainty.", "Band 6.0-6.5"),
    ("uncle", "noun", "relative", "My uncle.", "Band 4.5-5.5"),
    ("underestimate", "noun", "low estimate", "Big underestimate.", "Band 7.0-7.5"),
    ("undergraduate", "noun", "student", "Undergraduate degree.", "Band 6.0-6.5"),
    ("underline", "noun", "line under", "Add underline.", "Band 6.0-6.5"),
    ("understanding", "noun", "comprehension", "Mutual understanding.", "Band 6.0-6.5"),
    ("undertaking", "noun", "project", "Major undertaking.", "Band 8.0+"),
    ("underwear", "noun", "underclothes", "Cotton underwear.", "Band 6.0-6.5"),
    ("unemployment", "noun", "joblessness", "High unemployment.", "Band 6.0-6.5"),
    ("unification", "noun", "union", "German unification.", "Band 8.0+"),
    ("uniform", "noun", "standard clothes", "School uniform.", "Band 4.5-5.5"),
    ("uniformity", "noun", "sameness", "Strict uniformity.", "Band 8.0+"),
    ("union", "noun", "organization", "Labor union.", "Band 6.0-6.5"),
    ("unit", "noun", "single item", "Metric unit.", "Band 4.5-5.5"),
    ("unity", "noun", "togetherness", "National unity.", "Band 7.0-7.5"),
    ("universe", "noun", "cosmos", "Known universe.", "Band 6.0-6.5"),
    ("university", "noun", "school", "State university.", "Band 4.5-5.5"),
    ("update", "noun", "revision", "System update.", "Band 6.0-6.5"),
    ("upgrade", "noun", "improvement", "Free upgrade.", "Band 6.0-6.5"),
    ("upheaval", "noun", "disruption", "Political upheaval.", "Band 8.0+"),
    ("upload", "noun", "file transfer", "Photo upload.", "Band 6.0-6.5"),
    ("uprising", "noun", "revolt", "Armed uprising.", "Band 8.0+"),
    ("upstairs", "noun", "upper floor", "Go upstairs.", "Band 4.5-5.5"),
    ("uranium", "noun", "element", "Enriched uranium.", "Band 8.0+"),
    ("urgency", "noun", "importance", "Sense of urgency.", "Band 7.0-7.5"),
    ("usage", "noun", "use", "Proper usage.", "Band 6.0-6.5"),
    ("user", "noun", "person who uses", "End user.", "Band 4.5-5.5"),
    ("utility", "noun", "usefulness", "Public utility.", "Band 7.0-7.5"),
    ("utilization", "noun", "use", "Resource utilization.", "Band 8.0+"),
    ("vacancy", "noun", "empty position", "Job vacancy.", "Band 6.0-6.5"),
    ("vacation", "noun", "holiday", "Summer vacation.", "Band 4.5-5.5"),
    ("vaccination", "noun", "immunization", "COVID vaccination.", "Band 6.0-6.5"),
    ("vaccine", "noun", "medicine", "Flu vaccine.", "Band 6.0-6.5"),
    ("vacuum", "noun", "empty space", "Vacuum cleaner.", "Band 6.0-6.5"),
    ("validity", "noun", "legitimacy", "Legal validity.", "Band 8.0+"),
    ("valley", "noun", "low land", "Mountain valley.", "Band 6.0-6.5"),
    ("valuation", "noun", "assessment", "Property valuation.", "Band 8.0+"),
    ("value", "noun", "worth", "Market value.", "Band 4.5-5.5"),
    ("valve", "noun", "control device", "Heart valve.", "Band 7.0-7.5"),
    ("van", "noun", "vehicle", "Moving van.", "Band 6.0-6.5"),
    ("vanilla", "noun", "flavor", "Vanilla ice cream.", "Band 6.0-6.5"),
    ("vanity", "noun", "pride", "Personal vanity.", "Band 8.0+"),
    ("variable", "noun", "changing factor", "Key variable.", "Band 7.0-7.5"),
    ("variance", "noun", "difference", "Price variance.", "Band 8.0+"),
    ("variation", "noun", "change", "Minor variation.", "Band 6.0-6.5"),
    ("variety", "noun", "diversity", "Wide variety.", "Band 6.0-6.5"),
    ("vase", "noun", "container", "Flower vase.", "Band 6.0-6.5"),
    ("vegetable", "noun", "plant food", "Fresh vegetable.", "Band 4.5-5.5"),
    ("vegetation", "noun", "plant life", "Dense vegetation.", "Band 7.0-7.5"),
    ("vehicle", "noun", "transport", "Motor vehicle.", "Band 4.5-5.5"),
    ("vein", "noun", "blood vessel", "Blood vein.", "Band 7.0-7.5"),
    ("velocity", "noun", "speed", "High velocity.", "Band 8.0+"),
    ("vendor", "noun", "seller", "Street vendor.", "Band 6.0-6.5"),
    ("venture", "noun", "project", "Joint venture.", "Band 7.0-7.5"),
    ("venue", "noun", "location", "Concert venue.", "Band 6.0-6.5"),
    ("verb", "noun", "word type", "Action verb.", "Band 6.0-6.5"),
    ("verdict", "noun", "judgment", "Final verdict.", "Band 7.0-7.5"),
    ("verification", "noun", "confirmation", "Identity verification.", "Band 7.0-7.5"),
    ("versatility", "noun", "adaptability", "Show versatility.", "Band 8.0+"),
    ("verse", "noun", "poetry", "Bible verse.", "Band 7.0-7.5"),
    ("version", "noun", "form", "Latest version.", "Band 4.5-5.5"),
    ("vessel", "noun", "container", "Blood vessel.", "Band 7.0-7.5"),
    ("vest", "noun", "sleeveless garment", "Safety vest.", "Band 6.0-6.5"),
    ("veteran", "noun", "experienced person", "War veteran.", "Band 6.0-6.5"),
    ("veto", "noun", "rejection", "Presidential veto.", "Band 8.0+"),
    ("viability", "noun", "feasibility", "Economic viability.", "Band 8.0+"),
    ("vibration", "noun", "shaking", "Strong vibration.", "Band 7.0-7.5"),
    ("vice", "noun", "bad habit", "Vice president.", "Band 7.0-7.5"),
    ("vicinity", "noun", "nearby area", "In the vicinity.", "Band 8.0+"),
    ("victim", "noun", "sufferer", "Crime victim.", "Band 6.0-6.5"),
    ("victory", "noun", "win", "Election victory.", "Band 6.0-6.5"),
    ("video", "noun", "recording", "YouTube video.", "Band 4.5-5.5"),
    ("view", "noun", "sight", "Beautiful view.", "Band 4.5-5.5"),
    ("viewer", "noun", "watcher", "TV viewer.", "Band 6.0-6.5"),
    ("viewpoint", "noun", "perspective", "Different viewpoint.", "Band 7.0-7.5"),
    ("vigor", "noun", "energy", "Full of vigor.", "Band 8.0+"),
    ("villa", "noun", "house", "Holiday villa.", "Band 6.0-6.5"),
    ("village", "noun", "small town", "Fishing village.", "Band 4.5-5.5"),
    ("villager", "noun", "inhabitant", "Local villager.", "Band 6.0-6.5"),
    ("villain", "noun", "bad person", "Movie villain.", "Band 6.0-6.5"),
    ("vine", "noun", "plant", "Grape vine.", "Band 7.0-7.5"),
    ("vinegar", "noun", "liquid", "Apple vinegar.", "Band 6.0-6.5"),
    ("vineyard", "noun", "grape farm", "French vineyard.", "Band 7.0-7.5"),
    ("violation", "noun", "breach", "Human rights violation.", "Band 7.0-7.5"),
    ("violence", "noun", "force", "Domestic violence.", "Band 6.0-6.5"),
    ("violin", "noun", "instrument", "Play violin.", "Band 6.0-6.5"),
    ("virtue", "noun", "good quality", "Patience is a virtue.", "Band 7.0-7.5"),
    ("virus", "noun", "pathogen", "Computer virus.", "Band 6.0-6.5"),
    ("visa", "noun", "permit", "Tourist visa.", "Band 6.0-6.5"),
    ("visibility", "noun", "clearness", "Low visibility.", "Band 7.0-7.5"),
    ("vision", "noun", "sight", "Clear vision.", "Band 6.0-6.5"),
    ("visit", "noun", "trip", "Brief visit.", "Band 4.5-5.5"),
    ("visitor", "noun", "guest", "Museum visitor.", "Band 4.5-5.5"),
    ("vitamin", "noun", "nutrient", "Vitamin C.", "Band 6.0-6.5"),
    ("vocabulary", "noun", "word list", "English vocabulary.", "Band 6.0-6.5"),
    ("vocation", "noun", "profession", "True vocation.", "Band 8.0+"),
    ("voice", "noun", "sound", "Loud voice.", "Band 4.5-5.5"),
    ("volcano", "noun", "mountain", "Active volcano.", "Band 6.0-6.5"),
    ("volleyball", "noun", "sport", "Beach volleyball.", "Band 6.0-6.5"),
    ("voltage", "noun", "electric force", "High voltage.", "Band 7.0-7.5"),
    ("volume", "noun", "amount", "Sales volume.", "Band 6.0-6.5"),
    ("volunteer", "noun", "helper", "Community volunteer.", "Band 6.0-6.5"),
    ("vote", "noun", "ballot", "Cast vote.", "Band 4.5-5.5"),
    ("voter", "noun", "elector", "First-time voter.", "Band 6.0-6.5"),
    ("voucher", "noun", "coupon", "Gift voucher.", "Band 6.0-6.5"),
    ("voyage", "noun", "journey", "Sea voyage.", "Band 7.0-7.5"),
    ("vulnerability", "noun", "weakness", "Show vulnerability.", "Band 8.0+"),
    ("wage", "noun", "pay", "Minimum wage.", "Band 6.0-6.5"),
    ("wagon", "noun", "cart", "Station wagon.", "Band 6.0-6.5"),
    ("waist", "noun", "body part", "Slim waist.", "Band 6.0-6.5"),
    ("waiter", "noun", "server", "Call the waiter.", "Band 4.5-5.5"),
    ("waitress", "noun", "female server", "Our waitress.", "Band 6.0-6.5"),
    ("wake", "noun", "trail", "In the wake of.", "Band 7.0-7.5"),
    ("walk", "noun", "stroll", "Short walk.", "Band 4.5-5.5"),
    ("walker", "noun", "person who walks", "Dog walker.", "Band 6.0-6.5"),
    ("wall", "noun", "barrier", "Brick wall.", "Band 4.5-5.5"),
    ("wallet", "noun", "purse", "Leather wallet.", "Band 4.5-5.5"),
    ("wand", "noun", "stick", "Magic wand.", "Band 7.0-7.5"),
    ("war", "noun", "conflict", "World war.", "Band 4.5-5.5"),
    ("ward", "noun", "section", "Hospital ward.", "Band 7.0-7.5"),
    ("wardrobe", "noun", "closet", "Walk-in wardrobe.", "Band 6.0-6.5"),
    ("warehouse", "noun", "storage", "Large warehouse.", "Band 6.0-6.5"),
    ("warfare", "noun", "war", "Modern warfare.", "Band 7.0-7.5"),
    ("warmth", "noun", "heat", "Body warmth.", "Band 6.0-6.5"),
    ("warning", "noun", "alert", "Health warning.", "Band 4.5-5.5"),
    ("warrant", "noun", "authorization", "Arrest warrant.", "Band 7.0-7.5"),
    ("warranty", "noun", "guarantee", "Product warranty.", "Band 6.0-6.5"),
    ("warrior", "noun", "fighter", "Brave warrior.", "Band 6.0-6.5"),
    ("washing", "noun", "cleaning", "Do the washing.", "Band 4.5-5.5"),
    ("waste", "noun", "garbage", "Reduce waste.", "Band 4.5-5.5"),
    ("watch", "noun", "timepiece", "Wrist watch.", "Band 4.5-5.5"),
    ("water", "noun", "liquid", "Fresh water.", "Band 4.5-5.5"),
    ("waterfall", "noun", "falling water", "Beautiful waterfall.", "Band 6.0-6.5"),
    ("wave", "noun", "water movement", "Ocean wave.", "Band 4.5-5.5"),
    ("wavelength", "noun", "distance", "Same wavelength.", "Band 7.0-7.5"),
    ("wax", "noun", "material", "Candle wax.", "Band 6.0-6.5"),
    ("weakness", "noun", "flaw", "Main weakness.", "Band 6.0-6.5"),
    ("wealth", "noun", "riches", "Personal wealth.", "Band 6.0-6.5"),
    ("weapon", "noun", "arm", "Nuclear weapon.", "Band 6.0-6.5"),
    ("wear", "noun", "clothing", "Casual wear.", "Band 4.5-5.5"),
    ("weather", "noun", "climate", "Bad weather.", "Band 4.5-5.5"),
    ("web", "noun", "network", "Spider web.", "Band 4.5-5.5"),
    ("webcam", "noun", "camera", "Laptop webcam.", "Band 6.0-6.5"),
    ("webinar", "noun", "online seminar", "Free webinar.", "Band 7.0-7.5"),
    ("webpage", "noun", "internet page", "Personal webpage.", "Band 6.0-6.5"),
    ("website", "noun", "internet site", "Company website.", "Band 4.5-5.5"),
    ("wedding", "noun", "marriage ceremony", "Beach wedding.", "Band 4.5-5.5"),
    ("weed", "noun", "unwanted plant", "Garden weed.", "Band 6.0-6.5"),
    ("week", "noun", "time period", "Last week.", "Band 4.5-5.5"),
    ("weekday", "noun", "workday", "Every weekday.", "Band 6.0-6.5"),
    ("weekend", "noun", "Saturday Sunday", "Long weekend.", "Band 4.5-5.5"),
    ("weight", "noun", "heaviness", "Body weight.", "Band 4.5-5.5"),
    ("welfare", "noun", "well-being", "Child welfare.", "Band 6.0-6.5"),
    ("well", "noun", "water source", "Water well.", "Band 4.5-5.5"),
    ("well-being", "noun", "welfare", "Mental well-being.", "Band 7.0-7.5"),
    ("west", "noun", "direction", "Go west.", "Band 4.5-5.5"),
    ("whale", "noun", "sea animal", "Blue whale.", "Band 6.0-6.5"),
    ("wheat", "noun", "grain", "Wheat field.", "Band 6.0-6.5"),
    ("wheel", "noun", "circular part", "Car wheel.", "Band 4.5-5.5"),
    ("wheelchair", "noun", "mobility device", "Electric wheelchair.", "Band 6.0-6.5"),
    ("whisper", "noun", "quiet speech", "Soft whisper.", "Band 6.0-6.5"),
    ("whistle", "noun", "sound maker", "Police whistle.", "Band 6.0-6.5"),
    ("widow", "noun", "bereaved woman", "War widow.", "Band 7.0-7.5"),
    ("width", "noun", "breadth", "Road width.", "Band 6.0-6.5"),
    ("wife", "noun", "spouse", "My wife.", "Band 4.5-5.5"),
    ("wilderness", "noun", "wild area", "Arctic wilderness.", "Band 7.0-7.5"),
    ("wildlife", "noun", "wild animals", "Protect wildlife.", "Band 6.0-6.5"),
    ("will", "noun", "determination", "Strong will.", "Band 6.0-6.5"),
    ("willingness", "noun", "readiness", "Show willingness.", "Band 7.0-7.5"),
    ("win", "noun", "victory", "Big win.", "Band 4.5-5.5"),
    ("wind", "noun", "air movement", "Strong wind.", "Band 4.5-5.5"),
    ("window", "noun", "opening", "Glass window.", "Band 4.5-5.5"),
    ("wine", "noun", "drink", "Red wine.", "Band 4.5-5.5"),
    ("wing", "noun", "body part", "Bird wing.", "Band 4.5-5.5"),
    ("winner", "noun", "victor", "Prize winner.", "Band 4.5-5.5"),
    ("winter", "noun", "season", "Cold winter.", "Band 4.5-5.5"),
    ("wire", "noun", "metal thread", "Electric wire.", "Band 6.0-6.5"),
    ("wisdom", "noun", "knowledge", "Ancient wisdom.", "Band 6.0-6.5"),
    ("wish", "noun", "desire", "Make a wish.", "Band 4.5-5.5"),
    ("wit", "noun", "humor", "Quick wit.", "Band 7.0-7.5"),
    ("witch", "noun", "sorceress", "Wicked witch.", "Band 6.0-6.5"),
    ("withdrawal", "noun", "removal", "Cash withdrawal.", "Band 6.0-6.5"),
    ("witness", "noun", "observer", "Eye witness.", "Band 6.0-6.5"),
    ("wizard", "noun", "magician", "Computer wizard.", "Band 6.0-6.5"),
    ("wolf", "noun", "animal", "Grey wolf.", "Band 6.0-6.5"),
    ("woman", "noun", "female", "Young woman.", "Band 4.5-5.5"),
    ("wonder", "noun", "amazement", "Natural wonder.", "Band 6.0-6.5"),
    ("wood", "noun", "material", "Solid wood.", "Band 4.5-5.5"),
    ("woodland", "noun", "forest", "Ancient woodland.", "Band 7.0-7.5"),
    ("wool", "noun", "fiber", "Sheep wool.", "Band 6.0-6.5"),
    ("word", "noun", "language unit", "New word.", "Band 4.5-5.5"),
    ("wording", "noun", "phrasing", "Careful wording.", "Band 7.0-7.5"),
    ("work", "noun", "job", "Hard work.", "Band 4.5-5.5"),
    ("worker", "noun", "employee", "Factory worker.", "Band 4.5-5.5"),
    ("workforce", "noun", "workers", "Skilled workforce.", "Band 6.0-6.5"),
    ("workload", "noun", "amount of work", "Heavy workload.", "Band 7.0-7.5"),
    ("workplace", "noun", "work location", "Modern workplace.", "Band 6.0-6.5"),
    ("workshop", "noun", "seminar", "Training workshop.", "Band 6.0-6.5"),
    ("world", "noun", "earth", "Modern world.", "Band 4.5-5.5"),
    ("worm", "noun", "animal", "Earth worm.", "Band 6.0-6.5"),
    ("worry", "noun", "concern", "Main worry.", "Band 4.5-5.5"),
    ("worship", "noun", "devotion", "Place of worship.", "Band 7.0-7.5"),
    ("worth", "noun", "value", "Self-worth.", "Band 6.0-6.5"),
    ("wound", "noun", "injury", "Deep wound.", "Band 6.0-6.5"),
    ("wrap", "noun", "covering", "Plastic wrap.", "Band 6.0-6.5"),
    ("wreck", "noun", "destruction", "Car wreck.", "Band 6.0-6.5"),
    ("wrist", "noun", "body part", "Broken wrist.", "Band 4.5-5.5"),
    ("writer", "noun", "author", "Famous writer.", "Band 4.5-5.5"),
    ("writing", "noun", "text", "Creative writing.", "Band 4.5-5.5"),
    ("yacht", "noun", "boat", "Luxury yacht.", "Band 7.0-7.5"),
    ("yard", "noun", "garden", "Back yard.", "Band 4.5-5.5"),
    ("yarn", "noun", "thread", "Knitting yarn.", "Band 7.0-7.5"),
    ("year", "noun", "time period", "Last year.", "Band 4.5-5.5"),
    ("yeast", "noun", "fungus", "Baking yeast.", "Band 7.0-7.5"),
    ("yield", "noun", "output", "Crop yield.", "Band 7.0-7.5"),
    ("yoga", "noun", "exercise", "Practice yoga.", "Band 6.0-6.5"),
    ("yogurt", "noun", "food", "Greek yogurt.", "Band 6.0-6.5"),
    ("youngster", "noun", "young person", "Local youngster.", "Band 7.0-7.5"),
    ("youth", "noun", "young people", "Unemployed youth.", "Band 6.0-6.5"),
    ("zeal", "noun", "enthusiasm", "Religious zeal.", "Band 8.0+"),
    ("zebra", "noun", "animal", "Zebra crossing.", "Band 6.0-6.5"),
    ("zero", "noun", "number", "Below zero.", "Band 4.5-5.5"),
    ("zinc", "noun", "element", "Zinc supplement.", "Band 7.0-7.5"),
    ("zone", "noun", "area", "Time zone.", "Band 6.0-6.5"),
    ("zoo", "noun", "animal park", "Visit the zoo.", "Band 4.5-5.5"),
    ("zoology", "noun", "animal study", "Study zoology.", "Band 8.0+"),
]

def translate_batch(texts, lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={API}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            r = requests.post(url, json={"q": batch, "source": "en", "target": lang}, timeout=30)
            if r.status_code == 200:
                result.extend([t['translatedText'] for t in r.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    words = json.load(f)
existing = {w['word'].lower() for w in words}
start_id = max(w['id'] for w in words) + 1
cats = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
new_words = []
for word, pos, defn, ex, level in WORDS:
    if word.lower() not in existing:
        new_words.append({"id": start_id + len(new_words), "word": word, "level": level, "partOfSpeech": pos, "definition": defn, "example": ex, "category": cats[(start_id + len(new_words)) % 10]})
        existing.add(word.lower())
print(f"새 단어: {len(new_words)}개")
if new_words:
    defs = [w['definition'] for w in new_words]
    exs = [w['example'] for w in new_words]
    for lang in LANGS:
        print(f"{lang}...")
        td = translate_batch(defs, lang)
        te = translate_batch(exs, lang)
        for i, w in enumerate(new_words):
            if 'translations' not in w: w['translations'] = {}
            w['translations'][lang] = {'definition': td[i], 'example': te[i]}
    words.extend(new_words)
    with open('assets/data/words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
print(f"총: {len(words)}개")
