#!/usr/bin/env python3
import json, requests, time
API = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGS = ['ko', 'ja', 'zh', 'es', 'fr', 'de']
WORDS = [
    ("sack", "noun", "bag", "Sack of potatoes.", "Band 6.0-6.5"),
    ("sacrifice", "noun", "offering", "Great sacrifice.", "Band 7.0-7.5"),
    ("sadness", "noun", "sorrow", "Deep sadness.", "Band 6.0-6.5"),
    ("safari", "noun", "wildlife trip", "African safari.", "Band 6.0-6.5"),
    ("safeguard", "noun", "protection", "Safety safeguard.", "Band 7.0-7.5"),
    ("sage", "noun", "wise person", "Village sage.", "Band 8.0+"),
    ("sailor", "noun", "seafarer", "Experienced sailor.", "Band 6.0-6.5"),
    ("saint", "noun", "holy person", "Patron saint.", "Band 7.0-7.5"),
    ("sake", "noun", "purpose", "For the sake of.", "Band 6.0-6.5"),
    ("salad", "noun", "vegetable dish", "Fresh salad.", "Band 4.5-5.5"),
    ("salary", "noun", "wages", "Monthly salary.", "Band 6.0-6.5"),
    ("salmon", "noun", "fish", "Wild salmon.", "Band 6.0-6.5"),
    ("salon", "noun", "beauty shop", "Hair salon.", "Band 6.0-6.5"),
    ("salt", "noun", "seasoning", "Sea salt.", "Band 4.5-5.5"),
    ("salvation", "noun", "rescue", "Seek salvation.", "Band 8.0+"),
    ("sample", "noun", "specimen", "Blood sample.", "Band 6.0-6.5"),
    ("sanction", "noun", "penalty", "Economic sanction.", "Band 8.0+"),
    ("sanctuary", "noun", "refuge", "Wildlife sanctuary.", "Band 7.0-7.5"),
    ("sand", "noun", "beach material", "White sand.", "Band 4.5-5.5"),
    ("sandal", "noun", "footwear", "Leather sandal.", "Band 6.0-6.5"),
    ("sandwich", "noun", "food", "Club sandwich.", "Band 4.5-5.5"),
    ("sanitation", "noun", "hygiene", "Proper sanitation.", "Band 7.0-7.5"),
    ("satellite", "noun", "orbiting object", "Communication satellite.", "Band 6.0-6.5"),
    ("satisfaction", "noun", "contentment", "Customer satisfaction.", "Band 6.0-6.5"),
    ("sauce", "noun", "condiment", "Tomato sauce.", "Band 4.5-5.5"),
    ("sausage", "noun", "meat product", "Grilled sausage.", "Band 6.0-6.5"),
    ("savage", "noun", "wild person", "Noble savage.", "Band 8.0+"),
    ("savings", "noun", "saved money", "Personal savings.", "Band 6.0-6.5"),
    ("saw", "noun", "cutting tool", "Power saw.", "Band 6.0-6.5"),
    ("saying", "noun", "proverb", "Popular saying.", "Band 6.0-6.5"),
    ("scaffold", "noun", "platform", "Construction scaffold.", "Band 7.0-7.5"),
    ("scandal", "noun", "disgrace", "Political scandal.", "Band 7.0-7.5"),
    ("scanner", "noun", "device", "Document scanner.", "Band 6.0-6.5"),
    ("scarcity", "noun", "shortage", "Water scarcity.", "Band 7.0-7.5"),
    ("scare", "noun", "fright", "Health scare.", "Band 6.0-6.5"),
    ("scarf", "noun", "neck covering", "Silk scarf.", "Band 6.0-6.5"),
    ("scenery", "noun", "landscape", "Beautiful scenery.", "Band 6.0-6.5"),
    ("scent", "noun", "smell", "Pleasant scent.", "Band 6.0-6.5"),
    ("scepticism", "noun", "doubt", "Healthy scepticism.", "Band 8.0+"),
    ("scheduler", "noun", "planner", "Meeting scheduler.", "Band 7.0-7.5"),
    ("scheme", "noun", "plan", "Government scheme.", "Band 6.0-6.5"),
    ("scholar", "noun", "academic", "Visiting scholar.", "Band 7.0-7.5"),
    ("scholarship", "noun", "grant", "Full scholarship.", "Band 6.0-6.5"),
    ("scissors", "noun", "cutting tool", "Sharp scissors.", "Band 6.0-6.5"),
    ("scooter", "noun", "vehicle", "Electric scooter.", "Band 6.0-6.5"),
    ("scope", "noun", "range", "Limited scope.", "Band 7.0-7.5"),
    ("score", "noun", "points", "High score.", "Band 4.5-5.5"),
    ("scout", "noun", "explorer", "Boy scout.", "Band 6.0-6.5"),
    ("scrap", "noun", "fragment", "Scrap metal.", "Band 7.0-7.5"),
    ("scratch", "noun", "mark", "Small scratch.", "Band 6.0-6.5"),
    ("screen", "noun", "display", "Computer screen.", "Band 4.5-5.5"),
    ("screenplay", "noun", "film script", "Oscar-winning screenplay.", "Band 7.0-7.5"),
    ("screw", "noun", "fastener", "Loose screw.", "Band 6.0-6.5"),
    ("script", "noun", "written text", "Movie script.", "Band 6.0-6.5"),
    ("scripture", "noun", "sacred text", "Holy scripture.", "Band 8.0+"),
    ("scrutiny", "noun", "examination", "Close scrutiny.", "Band 8.0+"),
    ("sculptor", "noun", "artist", "Famous sculptor.", "Band 7.0-7.5"),
    ("sculpture", "noun", "artwork", "Bronze sculpture.", "Band 7.0-7.5"),
    ("seal", "noun", "marine animal", "Baby seal.", "Band 6.0-6.5"),
    ("seam", "noun", "joint", "Fabric seam.", "Band 7.0-7.5"),
    ("seaport", "noun", "harbor", "Busy seaport.", "Band 7.0-7.5"),
    ("seaside", "noun", "beach area", "Seaside town.", "Band 6.0-6.5"),
    ("seat", "noun", "chair", "Front seat.", "Band 4.5-5.5"),
    ("seaweed", "noun", "marine plant", "Edible seaweed.", "Band 6.0-6.5"),
    ("secretary", "noun", "assistant", "Personal secretary.", "Band 6.0-6.5"),
    ("secretion", "noun", "discharge", "Hormone secretion.", "Band 8.0+"),
    ("sect", "noun", "religious group", "Religious sect.", "Band 8.0+"),
    ("sector", "noun", "area", "Private sector.", "Band 6.0-6.5"),
    ("security", "noun", "safety", "National security.", "Band 6.0-6.5"),
    ("sediment", "noun", "deposit", "River sediment.", "Band 8.0+"),
    ("seed", "noun", "plant part", "Flower seed.", "Band 4.5-5.5"),
    ("segment", "noun", "section", "Market segment.", "Band 7.0-7.5"),
    ("segregation", "noun", "separation", "Racial segregation.", "Band 8.0+"),
    ("seizure", "noun", "taking", "Asset seizure.", "Band 8.0+"),
    ("selection", "noun", "choice", "Wide selection.", "Band 6.0-6.5"),
    ("self", "noun", "oneself", "True self.", "Band 6.0-6.5"),
    ("self-esteem", "noun", "self-worth", "Low self-esteem.", "Band 7.0-7.5"),
    ("seller", "noun", "vendor", "Best seller.", "Band 6.0-6.5"),
    ("seminar", "noun", "workshop", "Research seminar.", "Band 7.0-7.5"),
    ("senate", "noun", "assembly", "US Senate.", "Band 7.0-7.5"),
    ("senator", "noun", "legislator", "State senator.", "Band 7.0-7.5"),
    ("sensation", "noun", "feeling", "Burning sensation.", "Band 7.0-7.5"),
    ("sensitivity", "noun", "responsiveness", "Price sensitivity.", "Band 7.0-7.5"),
    ("sensor", "noun", "detector", "Motion sensor.", "Band 6.0-6.5"),
    ("sentiment", "noun", "feeling", "Public sentiment.", "Band 8.0+"),
    ("separation", "noun", "division", "Temporary separation.", "Band 6.0-6.5"),
    ("sequel", "noun", "continuation", "Movie sequel.", "Band 7.0-7.5"),
    ("sequence", "noun", "order", "Proper sequence.", "Band 6.0-6.5"),
    ("sergeant", "noun", "military rank", "Police sergeant.", "Band 7.0-7.5"),
    ("serial", "noun", "series", "TV serial.", "Band 7.0-7.5"),
    ("sermon", "noun", "religious talk", "Sunday sermon.", "Band 8.0+"),
    ("servant", "noun", "helper", "Civil servant.", "Band 6.0-6.5"),
    ("server", "noun", "computer", "Web server.", "Band 6.0-6.5"),
    ("session", "noun", "meeting", "Training session.", "Band 6.0-6.5"),
    ("setback", "noun", "difficulty", "Major setback.", "Band 7.0-7.5"),
    ("setting", "noun", "environment", "Rural setting.", "Band 6.0-6.5"),
    ("settlement", "noun", "agreement", "Legal settlement.", "Band 6.0-6.5"),
    ("settler", "noun", "colonist", "Early settler.", "Band 7.0-7.5"),
    ("setup", "noun", "arrangement", "Initial setup.", "Band 6.0-6.5"),
    ("severity", "noun", "seriousness", "Injury severity.", "Band 7.0-7.5"),
    ("sewage", "noun", "waste water", "Sewage treatment.", "Band 7.0-7.5"),
    ("shade", "noun", "shadow", "Tree shade.", "Band 6.0-6.5"),
    ("shaft", "noun", "passage", "Elevator shaft.", "Band 7.0-7.5"),
    ("shame", "noun", "disgrace", "Feel shame.", "Band 6.0-6.5"),
    ("shampoo", "noun", "hair wash", "Baby shampoo.", "Band 6.0-6.5"),
    ("shareholder", "noun", "stockholder", "Major shareholder.", "Band 7.0-7.5"),
    ("shark", "noun", "fish", "Great white shark.", "Band 6.0-6.5"),
    ("shave", "noun", "hair removal", "Close shave.", "Band 6.0-6.5"),
    ("shed", "noun", "small building", "Garden shed.", "Band 6.0-6.5"),
    ("sheep", "noun", "animal", "Flock of sheep.", "Band 4.5-5.5"),
    ("sheet", "noun", "flat piece", "Bed sheet.", "Band 4.5-5.5"),
    ("shelf", "noun", "ledge", "Book shelf.", "Band 4.5-5.5"),
    ("shell", "noun", "covering", "Sea shell.", "Band 6.0-6.5"),
    ("shelter", "noun", "refuge", "Emergency shelter.", "Band 6.0-6.5"),
    ("shepherd", "noun", "sheep herder", "Good shepherd.", "Band 7.0-7.5"),
    ("sheriff", "noun", "law officer", "Local sheriff.", "Band 7.0-7.5"),
    ("shield", "noun", "protection", "Protective shield.", "Band 6.0-6.5"),
    ("shift", "noun", "change", "Night shift.", "Band 6.0-6.5"),
    ("shipment", "noun", "delivery", "Large shipment.", "Band 6.0-6.5"),
    ("shipping", "noun", "transport", "Free shipping.", "Band 6.0-6.5"),
    ("shipyard", "noun", "dock", "Naval shipyard.", "Band 8.0+"),
    ("shirt", "noun", "clothing", "White shirt.", "Band 4.5-5.5"),
    ("shock", "noun", "surprise", "Culture shock.", "Band 6.0-6.5"),
    ("shoe", "noun", "footwear", "Running shoe.", "Band 4.5-5.5"),
    ("shooter", "noun", "gunman", "Active shooter.", "Band 7.0-7.5"),
    ("shopkeeper", "noun", "store owner", "Local shopkeeper.", "Band 6.0-6.5"),
    ("shopper", "noun", "buyer", "Online shopper.", "Band 6.0-6.5"),
    ("shortage", "noun", "lack", "Water shortage.", "Band 6.0-6.5"),
    ("shortcoming", "noun", "flaw", "Major shortcoming.", "Band 8.0+"),
    ("shorts", "noun", "clothing", "Denim shorts.", "Band 4.5-5.5"),
    ("shot", "noun", "attempt", "Good shot.", "Band 4.5-5.5"),
    ("shoulder", "noun", "body part", "Shoulder pain.", "Band 4.5-5.5"),
    ("showcase", "noun", "display", "Product showcase.", "Band 7.0-7.5"),
    ("shower", "noun", "bath", "Quick shower.", "Band 4.5-5.5"),
    ("shrine", "noun", "sacred place", "Ancient shrine.", "Band 7.0-7.5"),
    ("shrub", "noun", "bush", "Flowering shrub.", "Band 7.0-7.5"),
    ("shuttle", "noun", "vehicle", "Space shuttle.", "Band 6.0-6.5"),
    ("sibling", "noun", "brother or sister", "Younger sibling.", "Band 6.0-6.5"),
    ("sickness", "noun", "illness", "Motion sickness.", "Band 6.0-6.5"),
    ("sidewalk", "noun", "pavement", "Busy sidewalk.", "Band 6.0-6.5"),
    ("siege", "noun", "blockade", "Under siege.", "Band 8.0+"),
    ("sigh", "noun", "breath", "Heavy sigh.", "Band 6.0-6.5"),
    ("sightseeing", "noun", "touring", "City sightseeing.", "Band 6.0-6.5"),
    ("signal", "noun", "sign", "Traffic signal.", "Band 6.0-6.5"),
    ("signature", "noun", "name written", "Personal signature.", "Band 6.0-6.5"),
    ("significance", "noun", "importance", "Historical significance.", "Band 6.0-6.5"),
    ("silk", "noun", "fabric", "Pure silk.", "Band 6.0-6.5"),
    ("similarity", "noun", "likeness", "Strong similarity.", "Band 6.0-6.5"),
    ("simplicity", "noun", "plainness", "Design simplicity.", "Band 7.0-7.5"),
    ("simulation", "noun", "imitation", "Computer simulation.", "Band 7.0-7.5"),
    ("sin", "noun", "wrongdoing", "Original sin.", "Band 7.0-7.5"),
    ("sincerity", "noun", "honesty", "Show sincerity.", "Band 7.0-7.5"),
    ("singer", "noun", "vocalist", "Famous singer.", "Band 4.5-5.5"),
    ("sink", "noun", "basin", "Kitchen sink.", "Band 4.5-5.5"),
    ("sip", "noun", "small drink", "Take a sip.", "Band 6.0-6.5"),
    ("site", "noun", "location", "Construction site.", "Band 6.0-6.5"),
    ("sitting", "noun", "session", "Photo sitting.", "Band 6.0-6.5"),
    ("skeleton", "noun", "bones", "Human skeleton.", "Band 6.0-6.5"),
    ("sketch", "noun", "drawing", "Quick sketch.", "Band 6.0-6.5"),
    ("ski", "noun", "snow equipment", "Ski resort.", "Band 6.0-6.5"),
    ("skill", "noun", "ability", "Technical skill.", "Band 4.5-5.5"),
    ("skin", "noun", "body covering", "Sensitive skin.", "Band 4.5-5.5"),
    ("skull", "noun", "head bone", "Human skull.", "Band 7.0-7.5"),
    ("skyscraper", "noun", "tall building", "Modern skyscraper.", "Band 6.0-6.5"),
    ("slab", "noun", "flat piece", "Concrete slab.", "Band 7.0-7.5"),
    ("slang", "noun", "informal language", "Street slang.", "Band 7.0-7.5"),
    ("slaughter", "noun", "killing", "Animal slaughter.", "Band 8.0+"),
    ("slavery", "noun", "bondage", "Abolish slavery.", "Band 7.0-7.5"),
    ("sleeve", "noun", "arm covering", "Long sleeve.", "Band 6.0-6.5"),
    ("slice", "noun", "piece", "Pizza slice.", "Band 4.5-5.5"),
    ("slide", "noun", "playground equipment", "Water slide.", "Band 6.0-6.5"),
    ("slogan", "noun", "motto", "Campaign slogan.", "Band 7.0-7.5"),
    ("slope", "noun", "incline", "Steep slope.", "Band 6.0-6.5"),
    ("slot", "noun", "opening", "Time slot.", "Band 6.0-6.5"),
    ("slum", "noun", "poor area", "Urban slum.", "Band 7.0-7.5"),
    ("smartphone", "noun", "mobile device", "Latest smartphone.", "Band 6.0-6.5"),
    ("smell", "noun", "odor", "Bad smell.", "Band 4.5-5.5"),
    ("smile", "noun", "expression", "Big smile.", "Band 4.5-5.5"),
    ("smog", "noun", "pollution", "Heavy smog.", "Band 7.0-7.5"),
    ("smoke", "noun", "gas", "Cigarette smoke.", "Band 4.5-5.5"),
    ("smoker", "noun", "person who smokes", "Heavy smoker.", "Band 6.0-6.5"),
    ("snack", "noun", "light meal", "Healthy snack.", "Band 4.5-5.5"),
    ("snake", "noun", "reptile", "Poisonous snake.", "Band 4.5-5.5"),
    ("snap", "noun", "quick sound", "Loud snap.", "Band 6.0-6.5"),
    ("snapshot", "noun", "photo", "Quick snapshot.", "Band 7.0-7.5"),
    ("sneaker", "noun", "shoe", "Running sneaker.", "Band 6.0-6.5"),
    ("snow", "noun", "precipitation", "Heavy snow.", "Band 4.5-5.5"),
    ("snowfall", "noun", "snow event", "First snowfall.", "Band 6.0-6.5"),
    ("soap", "noun", "cleanser", "Bar of soap.", "Band 4.5-5.5"),
    ("soccer", "noun", "sport", "Play soccer.", "Band 4.5-5.5"),
    ("socialism", "noun", "political theory", "Democratic socialism.", "Band 8.0+"),
    ("socialist", "noun", "political supporter", "Democratic socialist.", "Band 8.0+"),
    ("socket", "noun", "outlet", "Electric socket.", "Band 6.0-6.5"),
    ("sodium", "noun", "element", "Low sodium.", "Band 7.0-7.5"),
    ("sofa", "noun", "couch", "Leather sofa.", "Band 4.5-5.5"),
    ("software", "noun", "program", "New software.", "Band 4.5-5.5"),
    ("soil", "noun", "earth", "Fertile soil.", "Band 6.0-6.5"),
    ("soldier", "noun", "military person", "Brave soldier.", "Band 6.0-6.5"),
    ("sole", "noun", "bottom of foot", "Shoe sole.", "Band 7.0-7.5"),
    ("solidarity", "noun", "unity", "Show solidarity.", "Band 8.0+"),
    ("solitude", "noun", "being alone", "Enjoy solitude.", "Band 8.0+"),
    ("solo", "noun", "alone performance", "Guitar solo.", "Band 6.0-6.5"),
    ("solvent", "noun", "dissolving substance", "Chemical solvent.", "Band 8.0+"),
    ("song", "noun", "music", "Popular song.", "Band 4.5-5.5"),
    ("songwriter", "noun", "music writer", "Famous songwriter.", "Band 6.0-6.5"),
    ("sophistication", "noun", "complexity", "Technical sophistication.", "Band 8.0+"),
    ("sorrow", "noun", "grief", "Deep sorrow.", "Band 7.0-7.5"),
    ("sort", "noun", "type", "Some sort of.", "Band 4.5-5.5"),
    ("soul", "noun", "spirit", "Human soul.", "Band 6.0-6.5"),
    ("soundtrack", "noun", "film music", "Movie soundtrack.", "Band 6.0-6.5"),
    ("soup", "noun", "liquid food", "Vegetable soup.", "Band 4.5-5.5"),
    ("sovereignty", "noun", "supreme power", "National sovereignty.", "Band 8.0+"),
    ("soy", "noun", "bean product", "Soy sauce.", "Band 6.0-6.5"),
    ("spa", "noun", "health resort", "Day spa.", "Band 6.0-6.5"),
    ("spacecraft", "noun", "space vehicle", "Manned spacecraft.", "Band 7.0-7.5"),
    ("span", "noun", "duration", "Life span.", "Band 7.0-7.5"),
    ("spare", "noun", "extra", "Spare part.", "Band 6.0-6.5"),
    ("spark", "noun", "flash", "Creative spark.", "Band 6.0-6.5"),
    ("speaker", "noun", "person who speaks", "Guest speaker.", "Band 4.5-5.5"),
    ("spear", "noun", "weapon", "Hunting spear.", "Band 7.0-7.5"),
    ("specialist", "noun", "expert", "Medical specialist.", "Band 6.0-6.5"),
    ("specialization", "noun", "focus area", "Academic specialization.", "Band 7.0-7.5"),
    ("specialty", "noun", "special thing", "House specialty.", "Band 6.0-6.5"),
    ("species", "noun", "type of animal", "Endangered species.", "Band 6.0-6.5"),
    ("specification", "noun", "detail", "Technical specification.", "Band 7.0-7.5"),
    ("specimen", "noun", "sample", "Lab specimen.", "Band 7.0-7.5"),
    ("spectacle", "noun", "display", "Public spectacle.", "Band 8.0+"),
    ("spectator", "noun", "viewer", "Sports spectator.", "Band 7.0-7.5"),
    ("spectrum", "noun", "range", "Wide spectrum.", "Band 7.0-7.5"),
    ("speculation", "noun", "guessing", "Wild speculation.", "Band 8.0+"),
    ("speech", "noun", "talk", "Public speech.", "Band 4.5-5.5"),
    ("speed", "noun", "velocity", "High speed.", "Band 4.5-5.5"),
    ("spell", "noun", "period", "Cold spell.", "Band 6.0-6.5"),
    ("spelling", "noun", "word formation", "Correct spelling.", "Band 6.0-6.5"),
    ("spending", "noun", "expenditure", "Government spending.", "Band 6.0-6.5"),
    ("sphere", "noun", "ball shape", "Public sphere.", "Band 7.0-7.5"),
    ("spice", "noun", "flavoring", "Add spice.", "Band 6.0-6.5"),
    ("spider", "noun", "insect", "Large spider.", "Band 4.5-5.5"),
    ("spike", "noun", "sharp point", "Price spike.", "Band 7.0-7.5"),
    ("spin", "noun", "rotation", "Spin cycle.", "Band 6.0-6.5"),
    ("spine", "noun", "backbone", "Spinal spine.", "Band 7.0-7.5"),
    ("spiral", "noun", "coil shape", "Downward spiral.", "Band 7.0-7.5"),
    ("spirit", "noun", "soul", "Team spirit.", "Band 6.0-6.5"),
    ("spirituality", "noun", "spiritual quality", "Personal spirituality.", "Band 8.0+"),
    ("spite", "noun", "malice", "Out of spite.", "Band 7.0-7.5"),
    ("splash", "noun", "spray", "Big splash.", "Band 6.0-6.5"),
    ("spokesman", "noun", "representative", "Government spokesman.", "Band 7.0-7.5"),
    ("sponsor", "noun", "supporter", "Main sponsor.", "Band 6.0-6.5"),
    ("sponsorship", "noun", "financial support", "Corporate sponsorship.", "Band 7.0-7.5"),
    ("spoon", "noun", "utensil", "Silver spoon.", "Band 4.5-5.5"),
    ("sport", "noun", "athletic activity", "Team sport.", "Band 4.5-5.5"),
    ("sportsman", "noun", "athlete", "Professional sportsman.", "Band 6.0-6.5"),
    ("spotlight", "noun", "attention", "In the spotlight.", "Band 7.0-7.5"),
    ("spouse", "noun", "marriage partner", "Loving spouse.", "Band 6.0-6.5"),
    ("spray", "noun", "mist", "Hair spray.", "Band 6.0-6.5"),
    ("spread", "noun", "expansion", "Disease spread.", "Band 6.0-6.5"),
    ("spreadsheet", "noun", "document", "Excel spreadsheet.", "Band 6.0-6.5"),
    ("spring", "noun", "season", "Early spring.", "Band 4.5-5.5"),
    ("spy", "noun", "secret agent", "Foreign spy.", "Band 6.0-6.5"),
    ("squad", "noun", "team", "Police squad.", "Band 7.0-7.5"),
    ("square", "noun", "shape", "Town square.", "Band 4.5-5.5"),
    ("squeeze", "noun", "pressure", "Credit squeeze.", "Band 7.0-7.5"),
    ("stability", "noun", "steadiness", "Financial stability.", "Band 6.0-6.5"),
    ("stabilization", "noun", "making stable", "Economic stabilization.", "Band 8.0+"),
    ("stadium", "noun", "sports arena", "Football stadium.", "Band 6.0-6.5"),
    ("staff", "noun", "employees", "Office staff.", "Band 4.5-5.5"),
    ("stage", "noun", "platform", "Theatre stage.", "Band 4.5-5.5"),
    ("stagnation", "noun", "lack of growth", "Economic stagnation.", "Band 8.0+"),
    ("stain", "noun", "spot", "Coffee stain.", "Band 6.0-6.5"),
    ("staircase", "noun", "stairs", "Spiral staircase.", "Band 6.0-6.5"),
    ("stake", "noun", "interest", "High stakes.", "Band 7.0-7.5"),
    ("stakeholder", "noun", "interested party", "Key stakeholder.", "Band 7.0-7.5"),
    ("stall", "noun", "booth", "Market stall.", "Band 6.0-6.5"),
    ("stamp", "noun", "postal mark", "Postage stamp.", "Band 4.5-5.5"),
    ("stance", "noun", "position", "Political stance.", "Band 7.0-7.5"),
    ("stand", "noun", "booth", "Newspaper stand.", "Band 4.5-5.5"),
    ("standard", "noun", "level", "High standard.", "Band 6.0-6.5"),
    ("standardization", "noun", "making uniform", "Industry standardization.", "Band 8.0+"),
    ("standpoint", "noun", "viewpoint", "From this standpoint.", "Band 8.0+"),
    ("staple", "noun", "basic item", "Diet staple.", "Band 7.0-7.5"),
    ("star", "noun", "celestial body", "Bright star.", "Band 4.5-5.5"),
    ("stare", "noun", "fixed look", "Blank stare.", "Band 6.0-6.5"),
    ("start-up", "noun", "new company", "Tech start-up.", "Band 6.0-6.5"),
    ("starvation", "noun", "extreme hunger", "Mass starvation.", "Band 7.0-7.5"),
    ("state", "noun", "condition", "Mental state.", "Band 4.5-5.5"),
    ("statement", "noun", "declaration", "Official statement.", "Band 6.0-6.5"),
    ("statesman", "noun", "political leader", "Elder statesman.", "Band 8.0+"),
    ("static", "noun", "noise", "TV static.", "Band 7.0-7.5"),
    ("station", "noun", "place", "Train station.", "Band 4.5-5.5"),
    ("statistics", "noun", "data", "Crime statistics.", "Band 6.0-6.5"),
    ("statue", "noun", "sculpture", "Bronze statue.", "Band 6.0-6.5"),
    ("stature", "noun", "status", "International stature.", "Band 8.0+"),
    ("status", "noun", "position", "Social status.", "Band 6.0-6.5"),
    ("statute", "noun", "law", "Legal statute.", "Band 8.0+"),
    ("steam", "noun", "vapor", "Hot steam.", "Band 6.0-6.5"),
    ("steel", "noun", "metal", "Stainless steel.", "Band 6.0-6.5"),
    ("stem", "noun", "plant part", "Flower stem.", "Band 6.0-6.5"),
    ("stereotype", "noun", "fixed idea", "Gender stereotype.", "Band 7.0-7.5"),
    ("steward", "noun", "attendant", "Flight steward.", "Band 7.0-7.5"),
    ("stick", "noun", "rod", "Walking stick.", "Band 4.5-5.5"),
    ("sticker", "noun", "label", "Price sticker.", "Band 6.0-6.5"),
    ("stigma", "noun", "shame", "Social stigma.", "Band 8.0+"),
    ("stimulus", "noun", "encouragement", "Economic stimulus.", "Band 8.0+"),
    ("stock", "noun", "supply", "In stock.", "Band 6.0-6.5"),
    ("stockholder", "noun", "share owner", "Major stockholder.", "Band 7.0-7.5"),
    ("stocking", "noun", "hosiery", "Christmas stocking.", "Band 6.0-6.5"),
    ("stomach", "noun", "body organ", "Upset stomach.", "Band 4.5-5.5"),
    ("stone", "noun", "rock", "Stepping stone.", "Band 4.5-5.5"),
    ("stool", "noun", "seat", "Bar stool.", "Band 6.0-6.5"),
    ("stop", "noun", "halt", "Bus stop.", "Band 4.5-5.5"),
    ("storage", "noun", "keeping place", "Data storage.", "Band 6.0-6.5"),
    ("store", "noun", "shop", "Grocery store.", "Band 4.5-5.5"),
    ("storm", "noun", "bad weather", "Violent storm.", "Band 4.5-5.5"),
    ("storyline", "noun", "plot", "Complex storyline.", "Band 7.0-7.5"),
    ("stove", "noun", "cooking appliance", "Gas stove.", "Band 6.0-6.5"),
    ("straightforward", "adjective", "simple", "Straightforward task.", "Band 7.0-7.5"),
    ("strain", "noun", "stress", "Mental strain.", "Band 6.0-6.5"),
    ("strand", "noun", "thread", "Hair strand.", "Band 7.0-7.5"),
    ("stranger", "noun", "unknown person", "Complete stranger.", "Band 4.5-5.5"),
    ("strap", "noun", "band", "Shoulder strap.", "Band 6.0-6.5"),
    ("strategist", "noun", "planner", "Military strategist.", "Band 8.0+"),
    ("strategy", "noun", "plan", "Business strategy.", "Band 6.0-6.5"),
    ("straw", "noun", "drinking tube", "Paper straw.", "Band 6.0-6.5"),
    ("strawberry", "noun", "fruit", "Fresh strawberry.", "Band 4.5-5.5"),
    ("streak", "noun", "line", "Winning streak.", "Band 7.0-7.5"),
    ("stream", "noun", "small river", "Mountain stream.", "Band 6.0-6.5"),
    ("streamline", "verb", "simplify", "Streamline process.", "Band 8.0+"),
    ("street", "noun", "road", "Main street.", "Band 4.5-5.5"),
    ("strength", "noun", "power", "Inner strength.", "Band 4.5-5.5"),
    ("stress", "noun", "pressure", "Work stress.", "Band 4.5-5.5"),
    ("stretch", "noun", "extension", "Final stretch.", "Band 6.0-6.5"),
    ("stride", "noun", "long step", "Giant stride.", "Band 7.0-7.5"),
    ("strike", "noun", "work stoppage", "General strike.", "Band 6.0-6.5"),
    ("striker", "noun", "protester", "Factory striker.", "Band 7.0-7.5"),
    ("string", "noun", "cord", "Guitar string.", "Band 4.5-5.5"),
    ("strip", "noun", "narrow piece", "Comic strip.", "Band 6.0-6.5"),
    ("stripe", "noun", "line", "Zebra stripe.", "Band 6.0-6.5"),
    ("stroke", "noun", "medical condition", "Brain stroke.", "Band 6.0-6.5"),
    ("stronghold", "noun", "fortress", "Political stronghold.", "Band 8.0+"),
    ("structure", "noun", "building", "Basic structure.", "Band 4.5-5.5"),
    ("struggle", "noun", "fight", "Power struggle.", "Band 6.0-6.5"),
    ("studio", "noun", "workroom", "Art studio.", "Band 6.0-6.5"),
    ("stuff", "noun", "things", "Personal stuff.", "Band 4.5-5.5"),
    ("stumble", "noun", "trip", "Slight stumble.", "Band 7.0-7.5"),
    ("stunt", "noun", "trick", "Publicity stunt.", "Band 7.0-7.5"),
    ("style", "noun", "manner", "Fashion style.", "Band 4.5-5.5"),
    ("subdivision", "noun", "section", "Housing subdivision.", "Band 8.0+"),
    ("subject", "noun", "topic", "Main subject.", "Band 4.5-5.5"),
    ("submission", "noun", "surrender", "Article submission.", "Band 7.0-7.5"),
    ("subordinate", "noun", "junior person", "Direct subordinate.", "Band 8.0+"),
    ("subscriber", "noun", "member", "Magazine subscriber.", "Band 7.0-7.5"),
    ("subscription", "noun", "membership", "Monthly subscription.", "Band 6.0-6.5"),
    ("subsidy", "noun", "financial aid", "Government subsidy.", "Band 7.0-7.5"),
    ("substance", "noun", "material", "Chemical substance.", "Band 6.0-6.5"),
    ("substitute", "noun", "replacement", "Find substitute.", "Band 6.0-6.5"),
    ("substitution", "noun", "replacement", "Player substitution.", "Band 7.0-7.5"),
    ("subtitle", "noun", "text", "Movie subtitle.", "Band 6.0-6.5"),
    ("suburb", "noun", "outskirts", "Quiet suburb.", "Band 6.0-6.5"),
    ("subway", "noun", "underground train", "Take the subway.", "Band 6.0-6.5"),
    ("succession", "noun", "series", "In succession.", "Band 7.0-7.5"),
    ("successor", "noun", "replacement", "Legal successor.", "Band 7.0-7.5"),
    ("suffering", "noun", "pain", "Human suffering.", "Band 6.0-6.5"),
    ("sufficiency", "noun", "enough amount", "Self-sufficiency.", "Band 8.0+"),
    ("suffix", "noun", "word ending", "Common suffix.", "Band 7.0-7.5"),
    ("sugar", "noun", "sweetener", "Brown sugar.", "Band 4.5-5.5"),
    ("suggestion", "noun", "proposal", "Helpful suggestion.", "Band 6.0-6.5"),
    ("suicide", "noun", "self-killing", "Prevent suicide.", "Band 7.0-7.5"),
    ("suit", "noun", "formal clothes", "Business suit.", "Band 4.5-5.5"),
    ("suitcase", "noun", "luggage", "Heavy suitcase.", "Band 6.0-6.5"),
    ("suite", "noun", "set of rooms", "Hotel suite.", "Band 6.0-6.5"),
    ("sum", "noun", "total", "Large sum.", "Band 6.0-6.5"),
    ("summary", "noun", "synopsis", "Brief summary.", "Band 6.0-6.5"),
    ("summit", "noun", "peak", "Mountain summit.", "Band 7.0-7.5"),
    ("sun", "noun", "star", "Bright sun.", "Band 4.5-5.5"),
    ("sunlight", "noun", "sun rays", "Natural sunlight.", "Band 6.0-6.5"),
    ("sunrise", "noun", "dawn", "Beautiful sunrise.", "Band 6.0-6.5"),
    ("sunset", "noun", "dusk", "Golden sunset.", "Band 6.0-6.5"),
    ("sunshine", "noun", "sun rays", "Warm sunshine.", "Band 6.0-6.5"),
    ("superintendent", "noun", "supervisor", "School superintendent.", "Band 8.0+"),
    ("superiority", "noun", "higher status", "Air superiority.", "Band 8.0+"),
    ("supermarket", "noun", "grocery store", "Local supermarket.", "Band 4.5-5.5"),
    ("supervision", "noun", "oversight", "Close supervision.", "Band 7.0-7.5"),
    ("supervisor", "noun", "manager", "Site supervisor.", "Band 6.0-6.5"),
    ("supplement", "noun", "addition", "Dietary supplement.", "Band 6.0-6.5"),
    ("supplier", "noun", "provider", "Main supplier.", "Band 6.0-6.5"),
    ("supply", "noun", "stock", "Fresh supply.", "Band 4.5-5.5"),
    ("supporter", "noun", "backer", "Strong supporter.", "Band 6.0-6.5"),
    ("suppression", "noun", "stopping", "Riot suppression.", "Band 8.0+"),
    ("supremacy", "noun", "dominance", "White supremacy.", "Band 8.0+"),
    ("surcharge", "noun", "extra fee", "Fuel surcharge.", "Band 8.0+"),
    ("surface", "noun", "outer part", "Smooth surface.", "Band 4.5-5.5"),
    ("surgeon", "noun", "doctor", "Brain surgeon.", "Band 6.0-6.5"),
    ("surgery", "noun", "operation", "Heart surgery.", "Band 6.0-6.5"),
    ("surplus", "noun", "excess", "Budget surplus.", "Band 7.0-7.5"),
    ("surprise", "noun", "unexpected event", "Big surprise.", "Band 4.5-5.5"),
    ("surrender", "noun", "giving up", "Unconditional surrender.", "Band 7.0-7.5"),
    ("surveillance", "noun", "watching", "Video surveillance.", "Band 7.0-7.5"),
    ("survey", "noun", "study", "Customer survey.", "Band 6.0-6.5"),
    ("survival", "noun", "staying alive", "Human survival.", "Band 6.0-6.5"),
    ("survivor", "noun", "one who survives", "Sole survivor.", "Band 6.0-6.5"),
    ("suspect", "noun", "suspected person", "Prime suspect.", "Band 6.0-6.5"),
    ("suspense", "noun", "uncertainty", "Build suspense.", "Band 7.0-7.5"),
    ("suspension", "noun", "temporary stop", "License suspension.", "Band 7.0-7.5"),
    ("suspicion", "noun", "doubt", "Under suspicion.", "Band 7.0-7.5"),
    ("sustainability", "noun", "maintainability", "Environmental sustainability.", "Band 7.0-7.5"),
    ("swamp", "noun", "wetland", "Dense swamp.", "Band 7.0-7.5"),
    ("swan", "noun", "bird", "White swan.", "Band 6.0-6.5"),
    ("swap", "noun", "exchange", "House swap.", "Band 7.0-7.5"),
    ("sweater", "noun", "clothing", "Wool sweater.", "Band 4.5-5.5"),
    ("sweep", "noun", "clean", "Clean sweep.", "Band 6.0-6.5"),
    ("sweetness", "noun", "sweet taste", "Natural sweetness.", "Band 6.0-6.5"),
    ("swell", "noun", "increase", "Ocean swell.", "Band 7.0-7.5"),
    ("swimmer", "noun", "person who swims", "Olympic swimmer.", "Band 6.0-6.5"),
    ("swimming", "noun", "sport", "Swimming pool.", "Band 4.5-5.5"),
    ("swing", "noun", "movement", "Mood swing.", "Band 6.0-6.5"),
    ("switch", "noun", "control", "Light switch.", "Band 6.0-6.5"),
    ("sword", "noun", "weapon", "Sharp sword.", "Band 6.0-6.5"),
    ("symbol", "noun", "sign", "Peace symbol.", "Band 6.0-6.5"),
    ("symbolism", "noun", "symbolic meaning", "Religious symbolism.", "Band 8.0+"),
    ("symmetry", "noun", "balance", "Perfect symmetry.", "Band 7.0-7.5"),
    ("sympathy", "noun", "compassion", "Deep sympathy.", "Band 6.0-6.5"),
    ("symphony", "noun", "musical work", "Classical symphony.", "Band 7.0-7.5"),
    ("symptom", "noun", "sign", "Common symptom.", "Band 6.0-6.5"),
    ("syndrome", "noun", "condition", "Down syndrome.", "Band 7.0-7.5"),
    ("synonym", "noun", "similar word", "Find synonym.", "Band 7.0-7.5"),
    ("synthesis", "noun", "combination", "Chemical synthesis.", "Band 8.0+"),
    ("system", "noun", "method", "Solar system.", "Band 4.5-5.5"),
]

def translate_batch(texts, lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={API}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            r = requests.post(url, json={"q": batch, "source": "en", "target": lang}, timeout=30)
            if r.status_code == 200:
                result.extend([t['translatedText'] for t in r.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

with open('assets/data/words.json', 'r', encoding='utf-8') as f:
    words = json.load(f)
existing = {w['word'].lower() for w in words}
start_id = max(w['id'] for w in words) + 1
cats = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
new_words = []
for word, pos, defn, ex, level in WORDS:
    if word.lower() not in existing:
        new_words.append({"id": start_id + len(new_words), "word": word, "level": level, "partOfSpeech": pos, "definition": defn, "example": ex, "category": cats[(start_id + len(new_words)) % 10]})
        existing.add(word.lower())
print(f"새 단어: {len(new_words)}개")
if new_words:
    defs = [w['definition'] for w in new_words]
    exs = [w['example'] for w in new_words]
    for lang in LANGS:
        print(f"{lang}...")
        td = translate_batch(defs, lang)
        te = translate_batch(exs, lang)
        for i, w in enumerate(new_words):
            if 'translations' not in w: w['translations'] = {}
            w['translations'][lang] = {'definition': td[i], 'example': te[i]}
    words.extend(new_words)
    with open('assets/data/words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
print(f"총: {len(words)}개")
