#!/usr/bin/env python3
"""IELTS 단어 대량 추가 - Part 6 (M-P)"""
import json
import requests
import time

GOOGLE_API_KEY = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGUAGES = ['ko', 'ja', 'zh', 'es', 'fr', 'de']

WORDS_PART6 = [
    ("machinery", "noun", "machines", "Industrial machinery.", "Band 6.0-6.5"),
    ("madness", "noun", "insanity", "Pure madness.", "Band 6.0-6.5"),
    ("magazine", "noun", "periodical", "Fashion magazine.", "Band 4.5-5.5"),
    ("magic", "noun", "supernatural", "Like magic.", "Band 4.5-5.5"),
    ("magistrate", "noun", "judge", "Local magistrate.", "Band 8.0+"),
    ("magnitude", "noun", "size", "Great magnitude.", "Band 8.0+"),
    ("maid", "noun", "female servant", "Hotel maid.", "Band 6.0-6.5"),
    ("mainland", "noun", "main territory", "Chinese mainland.", "Band 7.0-7.5"),
    ("mainstream", "noun", "main trend", "Enter mainstream.", "Band 7.0-7.5"),
    ("maintenance", "noun", "upkeep", "Regular maintenance.", "Band 6.0-6.5"),
    ("majority", "noun", "greater part", "Vast majority.", "Band 6.0-6.5"),
    ("makeup", "noun", "cosmetics", "Wear makeup.", "Band 6.0-6.5"),
    ("mall", "noun", "shopping center", "Shopping mall.", "Band 6.0-6.5"),
    ("malnutrition", "noun", "poor nutrition", "Suffer malnutrition.", "Band 7.0-7.5"),
    ("mammal", "noun", "warm-blooded animal", "Marine mammal.", "Band 6.0-6.5"),
    ("management", "noun", "administration", "Project management.", "Band 6.0-6.5"),
    ("mandate", "noun", "authority", "Government mandate.", "Band 8.0+"),
    ("maneuver", "noun", "movement", "Political maneuver.", "Band 8.0+"),
    ("manifestation", "noun", "display", "Physical manifestation.", "Band 8.0+"),
    ("manipulation", "noun", "control", "Media manipulation.", "Band 8.0+"),
    ("mankind", "noun", "humanity", "Benefit mankind.", "Band 6.0-6.5"),
    ("manner", "noun", "way", "In this manner.", "Band 6.0-6.5"),
    ("mansion", "noun", "large house", "Historic mansion.", "Band 6.0-6.5"),
    ("manual", "noun", "handbook", "User manual.", "Band 6.0-6.5"),
    ("manufacture", "noun", "production", "Car manufacture.", "Band 6.0-6.5"),
    ("manufacturer", "noun", "producer", "Leading manufacturer.", "Band 6.0-6.5"),
    ("manuscript", "noun", "document", "Ancient manuscript.", "Band 7.0-7.5"),
    ("marble", "noun", "stone", "Marble floor.", "Band 6.0-6.5"),
    ("march", "noun", "walk", "Protest march.", "Band 6.0-6.5"),
    ("margin", "noun", "edge", "Profit margin.", "Band 7.0-7.5"),
    ("marine", "adjective", "sea-related", "Marine life.", "Band 6.0-6.5"),
    ("marker", "noun", "indicator", "Genetic marker.", "Band 7.0-7.5"),
    ("marketplace", "noun", "market", "Global marketplace.", "Band 7.0-7.5"),
    ("marriage", "noun", "union", "Happy marriage.", "Band 4.5-5.5"),
    ("marvel", "noun", "wonder", "Modern marvel.", "Band 7.0-7.5"),
    ("mask", "noun", "face covering", "Wear a mask.", "Band 6.0-6.5"),
    ("mass", "noun", "large amount", "Mass production.", "Band 6.0-6.5"),
    ("massacre", "noun", "mass killing", "Brutal massacre.", "Band 8.0+"),
    ("masterpiece", "noun", "great work", "Artistic masterpiece.", "Band 7.0-7.5"),
    ("mastery", "noun", "skill", "Complete mastery.", "Band 7.0-7.5"),
    ("mate", "noun", "partner", "Class mate.", "Band 6.0-6.5"),
    ("material", "noun", "substance", "Raw material.", "Band 6.0-6.5"),
    ("materialism", "noun", "focus on possessions", "Consumer materialism.", "Band 8.0+"),
    ("mathematics", "noun", "math", "Study mathematics.", "Band 6.0-6.5"),
    ("matrix", "noun", "framework", "Decision matrix.", "Band 8.0+"),
    ("maturity", "noun", "full development", "Emotional maturity.", "Band 7.0-7.5"),
    ("mayor", "noun", "city leader", "City mayor.", "Band 6.0-6.5"),
    ("meadow", "noun", "grassy field", "Green meadow.", "Band 7.0-7.5"),
    ("meal", "noun", "food", "Main meal.", "Band 4.5-5.5"),
    ("meaning", "noun", "sense", "Deep meaning.", "Band 4.5-5.5"),
    ("measurement", "noun", "size determination", "Precise measurement.", "Band 6.0-6.5"),
    ("meat", "noun", "animal flesh", "Red meat.", "Band 4.5-5.5"),
    ("mechanic", "noun", "repair person", "Car mechanic.", "Band 6.0-6.5"),
    ("mechanism", "noun", "system", "Defense mechanism.", "Band 7.0-7.5"),
    ("medal", "noun", "award", "Gold medal.", "Band 6.0-6.5"),
    ("mediation", "noun", "intervention", "Conflict mediation.", "Band 8.0+"),
    ("medication", "noun", "medicine", "Take medication.", "Band 6.0-6.5"),
    ("meditation", "noun", "contemplation", "Daily meditation.", "Band 7.0-7.5"),
    ("medium", "noun", "means", "Communication medium.", "Band 6.0-6.5"),
    ("melody", "noun", "tune", "Beautiful melody.", "Band 6.0-6.5"),
    ("membership", "noun", "belonging", "Club membership.", "Band 6.0-6.5"),
    ("memo", "noun", "note", "Office memo.", "Band 6.0-6.5"),
    ("memoir", "noun", "autobiography", "Personal memoir.", "Band 7.0-7.5"),
    ("memorial", "noun", "monument", "War memorial.", "Band 7.0-7.5"),
    ("memorandum", "noun", "formal note", "Official memorandum.", "Band 8.0+"),
    ("memory", "noun", "recall ability", "Good memory.", "Band 4.5-5.5"),
    ("mentor", "noun", "guide", "Career mentor.", "Band 7.0-7.5"),
    ("merchandise", "noun", "goods", "Licensed merchandise.", "Band 7.0-7.5"),
    ("merchant", "noun", "trader", "Local merchant.", "Band 7.0-7.5"),
    ("mercy", "noun", "compassion", "Show mercy.", "Band 6.0-6.5"),
    ("merger", "noun", "combination", "Company merger.", "Band 7.0-7.5"),
    ("merit", "noun", "worth", "On merit.", "Band 7.0-7.5"),
    ("mess", "noun", "disorder", "What a mess.", "Band 4.5-5.5"),
    ("messenger", "noun", "courier", "Instant messenger.", "Band 6.0-6.5"),
    ("metabolism", "noun", "body process", "Fast metabolism.", "Band 7.0-7.5"),
    ("metal", "noun", "material", "Heavy metal.", "Band 4.5-5.5"),
    ("metaphor", "noun", "figure of speech", "Use a metaphor.", "Band 7.0-7.5"),
    ("meteor", "noun", "space rock", "Meteor shower.", "Band 7.0-7.5"),
    ("methodology", "noun", "approach", "Research methodology.", "Band 8.0+"),
    ("microphone", "noun", "sound device", "Use a microphone.", "Band 6.0-6.5"),
    ("microscope", "noun", "viewing device", "Under the microscope.", "Band 6.0-6.5"),
    ("midnight", "noun", "12 AM", "At midnight.", "Band 4.5-5.5"),
    ("midst", "noun", "middle", "In the midst of.", "Band 7.0-7.5"),
    ("migrant", "noun", "moving person", "Economic migrant.", "Band 7.0-7.5"),
    ("migration", "noun", "movement", "Bird migration.", "Band 7.0-7.5"),
    ("milestone", "noun", "important event", "Major milestone.", "Band 7.0-7.5"),
    ("millennium", "noun", "thousand years", "New millennium.", "Band 7.0-7.5"),
    ("mineral", "noun", "natural substance", "Essential mineral.", "Band 6.0-6.5"),
    ("minimum", "noun", "least amount", "Bare minimum.", "Band 6.0-6.5"),
    ("minister", "noun", "government official", "Prime minister.", "Band 6.0-6.5"),
    ("ministry", "noun", "government department", "Foreign ministry.", "Band 7.0-7.5"),
    ("minority", "noun", "smaller group", "Ethnic minority.", "Band 6.0-6.5"),
    ("miracle", "noun", "wonder", "True miracle.", "Band 6.0-6.5"),
    ("mirror", "noun", "reflecting surface", "Look in the mirror.", "Band 4.5-5.5"),
    ("misbehavior", "noun", "bad conduct", "Punish misbehavior.", "Band 7.0-7.5"),
    ("misconception", "noun", "wrong idea", "Common misconception.", "Band 8.0+"),
    ("misery", "noun", "suffering", "Cause misery.", "Band 7.0-7.5"),
    ("misfortune", "noun", "bad luck", "Financial misfortune.", "Band 7.0-7.5"),
    ("missile", "noun", "weapon", "Cruise missile.", "Band 7.0-7.5"),
    ("mission", "noun", "purpose", "Peace mission.", "Band 6.0-6.5"),
    ("mist", "noun", "fog", "Morning mist.", "Band 6.0-6.5"),
    ("misunderstanding", "noun", "confusion", "Clear up misunderstanding.", "Band 6.0-6.5"),
    ("mixture", "noun", "combination", "Strange mixture.", "Band 6.0-6.5"),
    ("mob", "noun", "crowd", "Angry mob.", "Band 7.0-7.5"),
    ("mobility", "noun", "movement ability", "Social mobility.", "Band 7.0-7.5"),
    ("mode", "noun", "method", "Transport mode.", "Band 6.0-6.5"),
    ("model", "noun", "example", "Role model.", "Band 6.0-6.5"),
    ("modem", "noun", "device", "Internet modem.", "Band 6.0-6.5"),
    ("modification", "noun", "change", "Minor modification.", "Band 7.0-7.5"),
    ("module", "noun", "unit", "Training module.", "Band 7.0-7.5"),
    ("moisture", "noun", "wetness", "Trap moisture.", "Band 7.0-7.5"),
    ("molecule", "noun", "particle", "Water molecule.", "Band 7.0-7.5"),
    ("momentum", "noun", "force", "Gain momentum.", "Band 7.0-7.5"),
    ("monarchy", "noun", "royal rule", "Constitutional monarchy.", "Band 8.0+"),
    ("monastery", "noun", "monks' home", "Buddhist monastery.", "Band 7.0-7.5"),
    ("monitor", "noun", "screen", "Computer monitor.", "Band 6.0-6.5"),
    ("monopoly", "noun", "sole control", "State monopoly.", "Band 8.0+"),
    ("monster", "noun", "creature", "Sea monster.", "Band 4.5-5.5"),
    ("monument", "noun", "memorial", "Historic monument.", "Band 6.0-6.5"),
    ("mood", "noun", "state of mind", "Good mood.", "Band 4.5-5.5"),
    ("morale", "noun", "spirit", "Team morale.", "Band 7.0-7.5"),
    ("morality", "noun", "ethics", "Question morality.", "Band 7.0-7.5"),
    ("mortality", "noun", "death rate", "Infant mortality.", "Band 8.0+"),
    ("mortgage", "noun", "home loan", "Pay mortgage.", "Band 7.0-7.5"),
    ("mosque", "noun", "Muslim temple", "Historic mosque.", "Band 7.0-7.5"),
    ("motion", "noun", "movement", "Slow motion.", "Band 6.0-6.5"),
    ("motivation", "noun", "drive", "Strong motivation.", "Band 6.0-6.5"),
    ("motive", "noun", "reason", "Hidden motive.", "Band 7.0-7.5"),
    ("motor", "noun", "engine", "Electric motor.", "Band 6.0-6.5"),
    ("motorist", "noun", "driver", "Fellow motorist.", "Band 7.0-7.5"),
    ("motto", "noun", "slogan", "Company motto.", "Band 7.0-7.5"),
    ("mound", "noun", "pile", "Burial mound.", "Band 7.0-7.5"),
    ("mountain", "noun", "high land", "Mountain range.", "Band 4.5-5.5"),
    ("mourning", "noun", "grieving", "In mourning.", "Band 7.0-7.5"),
    ("movement", "noun", "motion", "Political movement.", "Band 6.0-6.5"),
    ("mud", "noun", "wet earth", "Deep mud.", "Band 4.5-5.5"),
    ("multitude", "noun", "many", "Multitude of reasons.", "Band 8.0+"),
    ("municipality", "noun", "local government", "Local municipality.", "Band 8.0+"),
    ("murder", "noun", "killing", "Cold-blooded murder.", "Band 6.0-6.5"),
    ("muscle", "noun", "body tissue", "Build muscle.", "Band 6.0-6.5"),
    ("mutation", "noun", "genetic change", "Gene mutation.", "Band 8.0+"),
    ("mystery", "noun", "unknown", "Unsolved mystery.", "Band 6.0-6.5"),
    ("myth", "noun", "legend", "Urban myth.", "Band 6.0-6.5"),
    ("nail", "noun", "metal pin", "Hit the nail.", "Band 4.5-5.5"),
    ("narrative", "noun", "story", "Personal narrative.", "Band 7.0-7.5"),
    ("nation", "noun", "country", "Modern nation.", "Band 6.0-6.5"),
    ("nationality", "noun", "citizenship", "Different nationality.", "Band 6.0-6.5"),
    ("native", "noun", "indigenous person", "Native speaker.", "Band 6.0-6.5"),
    ("navigation", "noun", "directing course", "GPS navigation.", "Band 7.0-7.5"),
    ("navy", "noun", "sea force", "Royal navy.", "Band 6.0-6.5"),
    ("necessity", "noun", "need", "Absolute necessity.", "Band 6.0-6.5"),
    ("neck", "noun", "body part", "Stiff neck.", "Band 4.5-5.5"),
    ("needle", "noun", "sharp instrument", "Sewing needle.", "Band 6.0-6.5"),
    ("neglect", "noun", "disregard", "Child neglect.", "Band 7.0-7.5"),
    ("negligence", "noun", "carelessness", "Criminal negligence.", "Band 8.0+"),
    ("negotiation", "noun", "discussion", "Peace negotiation.", "Band 7.0-7.5"),
    ("neighborhood", "noun", "area", "Quiet neighborhood.", "Band 6.0-6.5"),
    ("nerve", "noun", "body fiber", "Nerve damage.", "Band 6.0-6.5"),
    ("nest", "noun", "bird home", "Bird's nest.", "Band 6.0-6.5"),
    ("networking", "noun", "making connections", "Business networking.", "Band 7.0-7.5"),
    ("neutrality", "noun", "impartiality", "Political neutrality.", "Band 8.0+"),
    ("newcomer", "noun", "new arrival", "Welcome newcomers.", "Band 6.0-6.5"),
    ("newsletter", "noun", "bulletin", "Weekly newsletter.", "Band 6.0-6.5"),
    ("nightmare", "noun", "bad dream", "Living nightmare.", "Band 6.0-6.5"),
    ("nitrogen", "noun", "gas element", "Liquid nitrogen.", "Band 7.0-7.5"),
    ("nobility", "noun", "aristocracy", "British nobility.", "Band 8.0+"),
    ("nobleman", "noun", "aristocrat", "Wealthy nobleman.", "Band 7.0-7.5"),
    ("node", "noun", "junction", "Network node.", "Band 8.0+"),
    ("noise", "noun", "sound", "Background noise.", "Band 4.5-5.5"),
    ("nomination", "noun", "proposal", "Award nomination.", "Band 7.0-7.5"),
    ("nominee", "noun", "candidate", "Presidential nominee.", "Band 8.0+"),
    ("nonsense", "noun", "foolishness", "Complete nonsense.", "Band 6.0-6.5"),
    ("norm", "noun", "standard", "Social norm.", "Band 7.0-7.5"),
    ("nostalgia", "noun", "longing for past", "Feel nostalgia.", "Band 8.0+"),
    ("notation", "noun", "symbol system", "Musical notation.", "Band 8.0+"),
    ("notebook", "noun", "writing pad", "Spiral notebook.", "Band 4.5-5.5"),
    ("notice", "noun", "announcement", "Give notice.", "Band 6.0-6.5"),
    ("notification", "noun", "alert", "Push notification.", "Band 7.0-7.5"),
    ("notion", "noun", "idea", "Vague notion.", "Band 7.0-7.5"),
    ("noun", "noun", "word type", "Common noun.", "Band 6.0-6.5"),
    ("novelist", "noun", "fiction writer", "Famous novelist.", "Band 6.0-6.5"),
    ("novelty", "noun", "newness", "Novelty item.", "Band 7.0-7.5"),
    ("nucleus", "noun", "center", "Cell nucleus.", "Band 7.0-7.5"),
    ("nuisance", "noun", "annoyance", "Public nuisance.", "Band 7.0-7.5"),
    ("number", "noun", "digit", "Large number.", "Band 4.5-5.5"),
    ("nursery", "noun", "plant place", "Day nursery.", "Band 6.0-6.5"),
    ("nursing", "noun", "healthcare", "Nursing home.", "Band 6.0-6.5"),
    ("nutrient", "noun", "food element", "Essential nutrient.", "Band 7.0-7.5"),
    ("nutrition", "noun", "nourishment", "Good nutrition.", "Band 6.0-6.5"),
    ("oak", "noun", "tree type", "Oak tree.", "Band 6.0-6.5"),
    ("oasis", "noun", "desert water", "Desert oasis.", "Band 7.0-7.5"),
    ("oath", "noun", "promise", "Take an oath.", "Band 7.0-7.5"),
    ("obedience", "noun", "compliance", "Blind obedience.", "Band 7.0-7.5"),
    ("obesity", "noun", "overweight", "Combat obesity.", "Band 7.0-7.5"),
    ("objection", "noun", "disagreement", "Raise objection.", "Band 7.0-7.5"),
    ("objective", "noun", "goal", "Main objective.", "Band 6.0-6.5"),
    ("obligation", "noun", "duty", "Legal obligation.", "Band 7.0-7.5"),
    ("observation", "noun", "watching", "Careful observation.", "Band 6.0-6.5"),
    ("observer", "noun", "watcher", "Independent observer.", "Band 7.0-7.5"),
    ("obsession", "noun", "fixation", "Unhealthy obsession.", "Band 7.0-7.5"),
    ("obstacle", "noun", "barrier", "Major obstacle.", "Band 6.0-6.5"),
    ("occupation", "noun", "job", "Main occupation.", "Band 6.0-6.5"),
    ("occurrence", "noun", "event", "Rare occurrence.", "Band 7.0-7.5"),
    ("ocean", "noun", "sea", "Pacific Ocean.", "Band 4.5-5.5"),
    ("odds", "noun", "probability", "Against all odds.", "Band 7.0-7.5"),
    ("odor", "noun", "smell", "Strange odor.", "Band 6.0-6.5"),
    ("offender", "noun", "criminal", "First-time offender.", "Band 7.0-7.5"),
    ("offense", "noun", "crime", "Criminal offense.", "Band 6.0-6.5"),
    ("offering", "noun", "gift", "Peace offering.", "Band 6.0-6.5"),
    ("offspring", "noun", "children", "Animal offspring.", "Band 7.0-7.5"),
    ("oil", "noun", "liquid fuel", "Crude oil.", "Band 4.5-5.5"),
    ("olive", "noun", "fruit", "Olive oil.", "Band 6.0-6.5"),
    ("omission", "noun", "leaving out", "Deliberate omission.", "Band 8.0+"),
    ("onset", "noun", "beginning", "Onset of winter.", "Band 8.0+"),
    ("opening", "noun", "gap", "Job opening.", "Band 6.0-6.5"),
    ("opera", "noun", "musical drama", "Grand opera.", "Band 6.0-6.5"),
    ("operator", "noun", "worker", "Machine operator.", "Band 6.0-6.5"),
    ("opponent", "noun", "rival", "Political opponent.", "Band 6.0-6.5"),
    ("oppression", "noun", "cruel treatment", "Political oppression.", "Band 8.0+"),
    ("optimism", "noun", "hopefulness", "Cautious optimism.", "Band 7.0-7.5"),
    ("option", "noun", "choice", "Best option.", "Band 6.0-6.5"),
    ("oracle", "noun", "prophet", "Ancient oracle.", "Band 8.0+"),
    ("orbit", "noun", "path", "Earth's orbit.", "Band 7.0-7.5"),
    ("orchestra", "noun", "music group", "Symphony orchestra.", "Band 6.0-6.5"),
    ("order", "noun", "arrangement", "In order.", "Band 4.5-5.5"),
    ("organ", "noun", "body part", "Vital organ.", "Band 6.0-6.5"),
    ("organism", "noun", "living thing", "Living organism.", "Band 7.0-7.5"),
    ("organization", "noun", "group", "Non-profit organization.", "Band 6.0-6.5"),
    ("orientation", "noun", "direction", "Sexual orientation.", "Band 7.0-7.5"),
    ("origin", "noun", "source", "Country of origin.", "Band 6.0-6.5"),
    ("originality", "noun", "uniqueness", "Show originality.", "Band 7.0-7.5"),
    ("ornament", "noun", "decoration", "Christmas ornament.", "Band 6.0-6.5"),
    ("orphan", "noun", "parentless child", "War orphan.", "Band 7.0-7.5"),
    ("outbreak", "noun", "sudden occurrence", "Disease outbreak.", "Band 7.0-7.5"),
    ("outcome", "noun", "result", "Successful outcome.", "Band 6.0-6.5"),
    ("outfit", "noun", "set of clothes", "New outfit.", "Band 6.0-6.5"),
    ("outing", "noun", "trip", "Family outing.", "Band 6.0-6.5"),
    ("outlaw", "noun", "criminal", "Notorious outlaw.", "Band 7.0-7.5"),
    ("outlet", "noun", "exit", "Power outlet.", "Band 6.0-6.5"),
    ("outline", "noun", "summary", "Brief outline.", "Band 6.0-6.5"),
    ("outlook", "noun", "view", "Positive outlook.", "Band 6.0-6.5"),
    ("output", "noun", "production", "Total output.", "Band 6.0-6.5"),
    ("outrage", "noun", "anger", "Public outrage.", "Band 7.0-7.5"),
    ("outsider", "noun", "non-member", "Political outsider.", "Band 7.0-7.5"),
    ("outskirts", "noun", "outer areas", "City outskirts.", "Band 7.0-7.5"),
    ("oven", "noun", "cooking device", "Hot oven.", "Band 4.5-5.5"),
    ("overflow", "noun", "excess", "Data overflow.", "Band 7.0-7.5"),
    ("overhead", "noun", "above", "Overhead costs.", "Band 7.0-7.5"),
    ("overlap", "noun", "shared area", "Significant overlap.", "Band 7.0-7.5"),
    ("overpopulation", "noun", "too many people", "Urban overpopulation.", "Band 7.0-7.5"),
    ("oversight", "noun", "supervision", "Government oversight.", "Band 8.0+"),
    ("overview", "noun", "summary", "Brief overview.", "Band 6.0-6.5"),
    ("ownership", "noun", "possession", "Home ownership.", "Band 6.0-6.5"),
    ("oxygen", "noun", "gas", "Oxygen level.", "Band 6.0-6.5"),
    ("pace", "noun", "speed", "Fast pace.", "Band 6.0-6.5"),
    ("pack", "noun", "group", "Wolf pack.", "Band 4.5-5.5"),
    ("package", "noun", "parcel", "Delivery package.", "Band 6.0-6.5"),
    ("pact", "noun", "agreement", "Peace pact.", "Band 7.0-7.5"),
    ("paddle", "noun", "oar", "Kayak paddle.", "Band 6.0-6.5"),
    ("page", "noun", "sheet", "Front page.", "Band 4.5-5.5"),
    ("pain", "noun", "hurt", "Chronic pain.", "Band 4.5-5.5"),
    ("painter", "noun", "artist", "Famous painter.", "Band 6.0-6.5"),
    ("painting", "noun", "artwork", "Oil painting.", "Band 6.0-6.5"),
    ("palace", "noun", "royal residence", "Royal palace.", "Band 6.0-6.5"),
    ("palm", "noun", "hand center", "Palm tree.", "Band 6.0-6.5"),
    ("pamphlet", "noun", "brochure", "Information pamphlet.", "Band 7.0-7.5"),
    ("pan", "noun", "cooking pot", "Frying pan.", "Band 4.5-5.5"),
    ("pandemic", "noun", "global disease", "Global pandemic.", "Band 7.0-7.5"),
    ("panel", "noun", "group of experts", "Expert panel.", "Band 6.0-6.5"),
    ("panic", "noun", "fear", "Cause panic.", "Band 6.0-6.5"),
    ("panorama", "noun", "wide view", "Beautiful panorama.", "Band 7.0-7.5"),
    ("paper", "noun", "material", "Writing paper.", "Band 4.5-5.5"),
    ("parade", "noun", "procession", "Military parade.", "Band 6.0-6.5"),
    ("paradigm", "noun", "model", "New paradigm.", "Band 8.0+"),
    ("paradise", "noun", "heaven", "Tropical paradise.", "Band 6.0-6.5"),
    ("paradox", "noun", "contradiction", "Strange paradox.", "Band 8.0+"),
    ("paragraph", "noun", "text section", "Opening paragraph.", "Band 6.0-6.5"),
    ("parallel", "noun", "similarity", "Draw a parallel.", "Band 7.0-7.5"),
    ("parameter", "noun", "boundary", "Set parameters.", "Band 8.0+"),
    ("parcel", "noun", "package", "Mail parcel.", "Band 6.0-6.5"),
    ("parliament", "noun", "legislature", "British parliament.", "Band 7.0-7.5"),
    ("participation", "noun", "involvement", "Active participation.", "Band 6.0-6.5"),
    ("particle", "noun", "tiny piece", "Dust particle.", "Band 7.0-7.5"),
    ("partner", "noun", "associate", "Business partner.", "Band 6.0-6.5"),
    ("partnership", "noun", "collaboration", "Strategic partnership.", "Band 6.0-6.5"),
    ("passage", "noun", "corridor", "Underground passage.", "Band 6.0-6.5"),
    ("passenger", "noun", "traveler", "Air passenger.", "Band 6.0-6.5"),
    ("passion", "noun", "strong feeling", "Great passion.", "Band 6.0-6.5"),
    ("passport", "noun", "travel document", "Valid passport.", "Band 6.0-6.5"),
    ("password", "noun", "secret code", "Strong password.", "Band 6.0-6.5"),
    ("paste", "noun", "sticky mixture", "Tomato paste.", "Band 6.0-6.5"),
    ("pastime", "noun", "hobby", "Favorite pastime.", "Band 7.0-7.5"),
    ("pastor", "noun", "religious leader", "Church pastor.", "Band 7.0-7.5"),
    ("patch", "noun", "piece", "Eye patch.", "Band 6.0-6.5"),
    ("patent", "noun", "invention right", "File a patent.", "Band 7.0-7.5"),
    ("path", "noun", "way", "Career path.", "Band 4.5-5.5"),
    ("pathway", "noun", "route", "Neural pathway.", "Band 7.0-7.5"),
    ("patience", "noun", "calm waiting", "Have patience.", "Band 6.0-6.5"),
    ("patient", "noun", "sick person", "Hospital patient.", "Band 6.0-6.5"),
    ("patriot", "noun", "country lover", "True patriot.", "Band 7.0-7.5"),
    ("patriotism", "noun", "love of country", "National patriotism.", "Band 8.0+"),
    ("patrol", "noun", "guard duty", "Border patrol.", "Band 6.0-6.5"),
    ("patron", "noun", "supporter", "Art patron.", "Band 7.0-7.5"),
    ("pattern", "noun", "design", "Behavior pattern.", "Band 6.0-6.5"),
    ("pause", "noun", "break", "Brief pause.", "Band 6.0-6.5"),
    ("pavement", "noun", "sidewalk", "Cracked pavement.", "Band 6.0-6.5"),
    ("payment", "noun", "money given", "Monthly payment.", "Band 6.0-6.5"),
    ("peace", "noun", "calm", "World peace.", "Band 4.5-5.5"),
    ("peak", "noun", "top", "Mountain peak.", "Band 6.0-6.5"),
    ("peasant", "noun", "farm worker", "Poor peasant.", "Band 7.0-7.5"),
    ("peculiarity", "noun", "oddity", "Strange peculiarity.", "Band 8.0+"),
    ("pedestrian", "noun", "walker", "Pedestrian crossing.", "Band 6.0-6.5"),
    ("peer", "noun", "equal", "Peer pressure.", "Band 6.0-6.5"),
    ("penalty", "noun", "punishment", "Death penalty.", "Band 6.0-6.5"),
    ("pension", "noun", "retirement pay", "State pension.", "Band 7.0-7.5"),
    ("perception", "noun", "understanding", "Public perception.", "Band 7.0-7.5"),
    ("perfection", "noun", "flawlessness", "Pursue perfection.", "Band 7.0-7.5"),
    ("performer", "noun", "entertainer", "Street performer.", "Band 6.0-6.5"),
    ("peril", "noun", "danger", "Great peril.", "Band 8.0+"),
    ("period", "noun", "time span", "Short period.", "Band 4.5-5.5"),
    ("periodical", "noun", "magazine", "Academic periodical.", "Band 7.0-7.5"),
    ("periphery", "noun", "outer edge", "Social periphery.", "Band 8.0+"),
    ("permission", "noun", "consent", "Get permission.", "Band 6.0-6.5"),
    ("permit", "noun", "license", "Work permit.", "Band 6.0-6.5"),
    ("persecution", "noun", "mistreatment", "Religious persecution.", "Band 8.0+"),
    ("persistence", "noun", "determination", "Show persistence.", "Band 7.0-7.5"),
    ("personality", "noun", "character", "Strong personality.", "Band 6.0-6.5"),
    ("personnel", "noun", "staff", "Military personnel.", "Band 7.0-7.5"),
    ("perspective", "noun", "viewpoint", "New perspective.", "Band 6.0-6.5"),
    ("persuasion", "noun", "convincing", "Gentle persuasion.", "Band 8.0+"),
    ("pessimism", "noun", "negative outlook", "Widespread pessimism.", "Band 8.0+"),
    ("pest", "noun", "harmful insect", "Garden pest.", "Band 6.0-6.5"),
    ("pesticide", "noun", "insect killer", "Chemical pesticide.", "Band 7.0-7.5"),
    ("petition", "noun", "formal request", "Sign a petition.", "Band 7.0-7.5"),
    ("petroleum", "noun", "oil", "Petroleum products.", "Band 7.0-7.5"),
    ("phase", "noun", "stage", "First phase.", "Band 6.0-6.5"),
    ("phenomenon", "noun", "occurrence", "Natural phenomenon.", "Band 7.0-7.5"),
    ("philosopher", "noun", "thinker", "Ancient philosopher.", "Band 7.0-7.5"),
    ("philosophy", "noun", "belief system", "Eastern philosophy.", "Band 7.0-7.5"),
    ("photograph", "noun", "picture", "Old photograph.", "Band 6.0-6.5"),
    ("photographer", "noun", "photo taker", "Professional photographer.", "Band 6.0-6.5"),
    ("photography", "noun", "photo taking", "Digital photography.", "Band 6.0-6.5"),
    ("phrase", "noun", "expression", "Common phrase.", "Band 6.0-6.5"),
    ("physician", "noun", "doctor", "Family physician.", "Band 7.0-7.5"),
    ("physics", "noun", "science", "Quantum physics.", "Band 6.0-6.5"),
    ("physiology", "noun", "body study", "Human physiology.", "Band 8.0+"),
    ("pier", "noun", "dock", "Fishing pier.", "Band 6.0-6.5"),
    ("pile", "noun", "heap", "Large pile.", "Band 6.0-6.5"),
    ("pilgrim", "noun", "religious traveler", "Holy pilgrim.", "Band 7.0-7.5"),
    ("pilgrimage", "noun", "religious journey", "Annual pilgrimage.", "Band 8.0+"),
    ("pillar", "noun", "column", "Stone pillar.", "Band 7.0-7.5"),
    ("pillow", "noun", "head cushion", "Soft pillow.", "Band 4.5-5.5"),
    ("pilot", "noun", "aircraft driver", "Commercial pilot.", "Band 6.0-6.5"),
    ("pine", "noun", "tree type", "Pine tree.", "Band 6.0-6.5"),
    ("pioneer", "noun", "innovator", "Industry pioneer.", "Band 7.0-7.5"),
    ("pipeline", "noun", "pipe system", "Oil pipeline.", "Band 7.0-7.5"),
    ("pirate", "noun", "sea robber", "Modern pirate.", "Band 6.0-6.5"),
    ("pit", "noun", "hole", "Deep pit.", "Band 6.0-6.5"),
    ("pitch", "noun", "level", "Sales pitch.", "Band 6.0-6.5"),
    ("pity", "noun", "sympathy", "Take pity.", "Band 6.0-6.5"),
    ("placement", "noun", "positioning", "Job placement.", "Band 7.0-7.5"),
    ("plague", "noun", "disease", "Bubonic plague.", "Band 7.0-7.5"),
    ("plain", "noun", "flat land", "Grassy plain.", "Band 6.0-6.5"),
    ("plaintiff", "noun", "accuser", "Civil plaintiff.", "Band 8.0+"),
    ("plantation", "noun", "large farm", "Tea plantation.", "Band 7.0-7.5"),
    ("plasma", "noun", "blood component", "Blood plasma.", "Band 8.0+"),
    ("plastic", "noun", "material", "Reduce plastic.", "Band 6.0-6.5"),
    ("plate", "noun", "dish", "Dinner plate.", "Band 4.5-5.5"),
    ("plateau", "noun", "flat highland", "High plateau.", "Band 7.0-7.5"),
    ("platform", "noun", "stage", "Social media platform.", "Band 6.0-6.5"),
    ("playground", "noun", "play area", "School playground.", "Band 6.0-6.5"),
    ("plea", "noun", "appeal", "Emotional plea.", "Band 7.0-7.5"),
    ("pleasure", "noun", "enjoyment", "Great pleasure.", "Band 4.5-5.5"),
    ("pledge", "noun", "promise", "Make a pledge.", "Band 7.0-7.5"),
    ("plot", "noun", "story line", "Complex plot.", "Band 6.0-6.5"),
    ("plug", "noun", "connector", "Electric plug.", "Band 6.0-6.5"),
    ("plumber", "noun", "pipe worker", "Call a plumber.", "Band 6.0-6.5"),
    ("plunge", "noun", "sudden drop", "Take the plunge.", "Band 7.0-7.5"),
    ("plural", "noun", "more than one", "Plural form.", "Band 6.0-6.5"),
    ("pocket", "noun", "clothing pouch", "In my pocket.", "Band 4.5-5.5"),
    ("poem", "noun", "verse", "Beautiful poem.", "Band 6.0-6.5"),
    ("poet", "noun", "verse writer", "Famous poet.", "Band 6.0-6.5"),
    ("poetry", "noun", "verse writing", "Modern poetry.", "Band 6.0-6.5"),
    ("pole", "noun", "long stick", "North Pole.", "Band 6.0-6.5"),
    ("policy", "noun", "plan", "Government policy.", "Band 6.0-6.5"),
    ("polish", "noun", "shine", "Shoe polish.", "Band 6.0-6.5"),
    ("politician", "noun", "political person", "Local politician.", "Band 6.0-6.5"),
    ("poll", "noun", "survey", "Opinion poll.", "Band 7.0-7.5"),
    ("pollutant", "noun", "contaminator", "Air pollutant.", "Band 7.0-7.5"),
    ("pollution", "noun", "contamination", "Air pollution.", "Band 6.0-6.5"),
    ("pond", "noun", "small lake", "Fish pond.", "Band 6.0-6.5"),
    ("pool", "noun", "water body", "Swimming pool.", "Band 4.5-5.5"),
    ("pope", "noun", "Catholic leader", "The Pope.", "Band 7.0-7.5"),
    ("popularity", "noun", "being liked", "Growing popularity.", "Band 6.0-6.5"),
    ("population", "noun", "people count", "World population.", "Band 6.0-6.5"),
    ("port", "noun", "harbor", "Sea port.", "Band 6.0-6.5"),
    ("portable", "adjective", "movable", "Portable device.", "Band 6.0-6.5"),
    ("portfolio", "noun", "collection", "Investment portfolio.", "Band 7.0-7.5"),
    ("portion", "noun", "part", "Small portion.", "Band 6.0-6.5"),
    ("portrait", "noun", "picture", "Family portrait.", "Band 6.0-6.5"),
    ("pose", "noun", "position", "Strike a pose.", "Band 6.0-6.5"),
    ("possession", "noun", "ownership", "Personal possession.", "Band 6.0-6.5"),
    ("possibility", "noun", "chance", "Strong possibility.", "Band 6.0-6.5"),
    ("poster", "noun", "notice", "Movie poster.", "Band 6.0-6.5"),
    ("postponement", "noun", "delay", "Game postponement.", "Band 7.0-7.5"),
    ("posture", "noun", "body position", "Good posture.", "Band 7.0-7.5"),
    ("potential", "noun", "possibility", "Great potential.", "Band 6.0-6.5"),
    ("pottery", "noun", "ceramics", "Ancient pottery.", "Band 6.0-6.5"),
    ("poultry", "noun", "farm birds", "Fresh poultry.", "Band 7.0-7.5"),
    ("poverty", "noun", "being poor", "Extreme poverty.", "Band 6.0-6.5"),
    ("powder", "noun", "fine particles", "Baby powder.", "Band 6.0-6.5"),
    ("power", "noun", "strength", "Political power.", "Band 4.5-5.5"),
    ("practitioner", "noun", "professional", "Medical practitioner.", "Band 7.0-7.5"),
    ("praise", "noun", "approval", "Deserve praise.", "Band 6.0-6.5"),
    ("prayer", "noun", "religious request", "Say a prayer.", "Band 6.0-6.5"),
    ("precedent", "noun", "prior example", "Set a precedent.", "Band 8.0+"),
    ("precision", "noun", "accuracy", "High precision.", "Band 7.0-7.5"),
    ("predator", "noun", "hunter", "Top predator.", "Band 7.0-7.5"),
    ("predecessor", "noun", "former holder", "His predecessor.", "Band 8.0+"),
    ("prediction", "noun", "forecast", "Accurate prediction.", "Band 6.0-6.5"),
    ("predominance", "noun", "superiority", "Economic predominance.", "Band 8.0+"),
    ("preference", "noun", "choice", "Personal preference.", "Band 6.0-6.5"),
    ("pregnancy", "noun", "carrying child", "During pregnancy.", "Band 6.0-6.5"),
    ("prejudice", "noun", "bias", "Racial prejudice.", "Band 7.0-7.5"),
    ("premise", "noun", "assumption", "Basic premise.", "Band 8.0+"),
    ("premium", "noun", "extra cost", "Insurance premium.", "Band 7.0-7.5"),
    ("preparation", "noun", "getting ready", "Careful preparation.", "Band 6.0-6.5"),
    ("prescription", "noun", "medical order", "Doctor's prescription.", "Band 6.0-6.5"),
    ("presence", "noun", "being there", "Strong presence.", "Band 6.0-6.5"),
    ("presentation", "noun", "talk", "Give a presentation.", "Band 6.0-6.5"),
    ("preservation", "noun", "protection", "Wildlife preservation.", "Band 7.0-7.5"),
    ("presidency", "noun", "presidential term", "During his presidency.", "Band 7.0-7.5"),
    ("president", "noun", "leader", "Company president.", "Band 4.5-5.5"),
    ("press", "noun", "media", "Free press.", "Band 6.0-6.5"),
    ("pressure", "noun", "force", "Peer pressure.", "Band 6.0-6.5"),
    ("prestige", "noun", "reputation", "High prestige.", "Band 8.0+"),
    ("prevalence", "noun", "widespread existence", "Disease prevalence.", "Band 8.0+"),
    ("prevention", "noun", "stopping", "Crime prevention.", "Band 6.0-6.5"),
    ("prey", "noun", "hunted animal", "Easy prey.", "Band 7.0-7.5"),
    ("pride", "noun", "self-respect", "Take pride.", "Band 6.0-6.5"),
    ("priest", "noun", "religious leader", "Catholic priest.", "Band 6.0-6.5"),
    ("primary", "adjective", "main", "Primary concern.", "Band 6.0-6.5"),
    ("prime", "adjective", "main", "Prime minister.", "Band 6.0-6.5"),
    ("prince", "noun", "royal son", "Crown prince.", "Band 6.0-6.5"),
    ("princess", "noun", "royal daughter", "Beautiful princess.", "Band 6.0-6.5"),
    ("principal", "noun", "school head", "School principal.", "Band 6.0-6.5"),
    ("principle", "noun", "rule", "Basic principle.", "Band 6.0-6.5"),
    ("print", "noun", "printed matter", "Fine print.", "Band 6.0-6.5"),
    ("printer", "noun", "printing device", "Laser printer.", "Band 6.0-6.5"),
    ("priority", "noun", "importance", "Top priority.", "Band 6.0-6.5"),
    ("prison", "noun", "jail", "Go to prison.", "Band 6.0-6.5"),
    ("prisoner", "noun", "inmate", "Political prisoner.", "Band 6.0-6.5"),
    ("privacy", "noun", "secrecy", "Right to privacy.", "Band 6.0-6.5"),
    ("privilege", "noun", "special right", "Great privilege.", "Band 7.0-7.5"),
    ("probability", "noun", "likelihood", "High probability.", "Band 7.0-7.5"),
    ("probe", "noun", "investigation", "Criminal probe.", "Band 8.0+"),
    ("procedure", "noun", "method", "Standard procedure.", "Band 6.0-6.5"),
    ("proceeds", "noun", "earnings", "Sale proceeds.", "Band 8.0+"),
    ("processor", "noun", "computing unit", "Food processor.", "Band 6.0-6.5"),
    ("proclamation", "noun", "announcement", "Official proclamation.", "Band 8.0+"),
    ("procurement", "noun", "obtaining", "Government procurement.", "Band 8.0+"),
    ("producer", "noun", "maker", "Film producer.", "Band 6.0-6.5"),
    ("productivity", "noun", "output rate", "Increase productivity.", "Band 7.0-7.5"),
    ("profession", "noun", "career", "Medical profession.", "Band 6.0-6.5"),
    ("professional", "noun", "expert", "Healthcare professional.", "Band 6.0-6.5"),
    ("professor", "noun", "university teacher", "University professor.", "Band 6.0-6.5"),
    ("proficiency", "noun", "skill", "Language proficiency.", "Band 7.0-7.5"),
    ("profile", "noun", "outline", "User profile.", "Band 6.0-6.5"),
    ("profit", "noun", "gain", "Make a profit.", "Band 6.0-6.5"),
    ("profitability", "noun", "money-making ability", "Improve profitability.", "Band 8.0+"),
    ("progression", "noun", "advancement", "Career progression.", "Band 7.0-7.5"),
    ("prohibition", "noun", "ban", "Alcohol prohibition.", "Band 8.0+"),
    ("projection", "noun", "forecast", "Sales projection.", "Band 7.0-7.5"),
    ("proliferation", "noun", "rapid spread", "Nuclear proliferation.", "Band 8.0+"),
    ("prominence", "noun", "importance", "Gain prominence.", "Band 8.0+"),
    ("promotion", "noun", "advancement", "Get a promotion.", "Band 6.0-6.5"),
    ("prompt", "noun", "reminder", "Writing prompt.", "Band 7.0-7.5"),
    ("pronunciation", "noun", "way of saying", "Correct pronunciation.", "Band 6.0-6.5"),
    ("propaganda", "noun", "biased information", "Political propaganda.", "Band 8.0+"),
    ("property", "noun", "possession", "Private property.", "Band 6.0-6.5"),
    ("prophecy", "noun", "prediction", "Ancient prophecy.", "Band 8.0+"),
    ("proportion", "noun", "ratio", "In proportion.", "Band 6.0-6.5"),
    ("proposal", "noun", "suggestion", "Marriage proposal.", "Band 6.0-6.5"),
    ("proposition", "noun", "proposal", "Business proposition.", "Band 8.0+"),
    ("prosecution", "noun", "legal action", "Criminal prosecution.", "Band 8.0+"),
    ("prosecutor", "noun", "legal official", "Public prosecutor.", "Band 7.0-7.5"),
    ("prospect", "noun", "possibility", "Job prospects.", "Band 6.0-6.5"),
    ("prosperity", "noun", "wealth", "Economic prosperity.", "Band 7.0-7.5"),
    ("protection", "noun", "safety", "Environmental protection.", "Band 6.0-6.5"),
    ("protein", "noun", "nutrient", "High protein.", "Band 6.0-6.5"),
    ("protest", "noun", "objection", "Public protest.", "Band 6.0-6.5"),
    ("protocol", "noun", "procedure", "Safety protocol.", "Band 7.0-7.5"),
    ("prototype", "noun", "first model", "Product prototype.", "Band 8.0+"),
    ("province", "noun", "region", "Northern province.", "Band 6.0-6.5"),
    ("provision", "noun", "supply", "Make provision.", "Band 7.0-7.5"),
    ("provocation", "noun", "incitement", "Deliberate provocation.", "Band 8.0+"),
    ("proximity", "noun", "nearness", "Close proximity.", "Band 8.0+"),
    ("psychology", "noun", "mind study", "Child psychology.", "Band 7.0-7.5"),
    ("publicity", "noun", "attention", "Media publicity.", "Band 6.0-6.5"),
    ("publisher", "noun", "book producer", "Leading publisher.", "Band 6.0-6.5"),
    ("pulse", "noun", "heartbeat", "Check pulse.", "Band 6.0-6.5"),
    ("pump", "noun", "fluid mover", "Water pump.", "Band 6.0-6.5"),
    ("punch", "noun", "hit", "Deliver a punch.", "Band 6.0-6.5"),
    ("punishment", "noun", "penalty", "Severe punishment.", "Band 6.0-6.5"),
    ("pupil", "noun", "student", "Star pupil.", "Band 6.0-6.5"),
    ("puppet", "noun", "figure", "Political puppet.", "Band 7.0-7.5"),
    ("purchase", "noun", "buying", "Make a purchase.", "Band 6.0-6.5"),
    ("purity", "noun", "cleanness", "Water purity.", "Band 7.0-7.5"),
    ("purple", "noun", "color", "Deep purple.", "Band 4.5-5.5"),
    ("pursuit", "noun", "chase", "In pursuit of.", "Band 7.0-7.5"),
    ("puzzle", "noun", "problem", "Solve the puzzle.", "Band 6.0-6.5"),
    ("pyramid", "noun", "triangle structure", "Egyptian pyramid.", "Band 6.0-6.5"),
]

def translate_batch(texts, target_lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={GOOGLE_API_KEY}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            resp = requests.post(url, json={"q": batch, "source": "en", "target": target_lang}, timeout=30)
            if resp.status_code == 200:
                result.extend([t['translatedText'] for t in resp.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

def main():
    with open('assets/data/words.json', 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    existing = {w['word'].lower() for w in words}
    start_id = max(w['id'] for w in words) + 1
    categories = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
    
    new_words = []
    for word, pos, definition, example, level in WORDS_PART6:
        if word.lower() not in existing:
            new_words.append({
                "id": start_id + len(new_words),
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": categories[(start_id + len(new_words)) % len(categories)]
            })
            existing.add(word.lower())
    
    print(f"새 단어: {len(new_words)}개")
    
    if new_words:
        defs = [w['definition'] for w in new_words]
        exs = [w['example'] for w in new_words]
        
        for lang in LANGUAGES:
            print(f"{lang} 번역중...")
            trans_defs = translate_batch(defs, lang)
            trans_exs = translate_batch(exs, lang)
            for i, w in enumerate(new_words):
                if 'translations' not in w:
                    w['translations'] = {}
                w['translations'][lang] = {
                    'definition': trans_defs[i],
                    'example': trans_exs[i]
                }
        
        words.extend(new_words)
        with open('assets/data/words.json', 'w', encoding='utf-8') as f:
            json.dump(words, f, ensure_ascii=False, indent=2)
    
    print(f"총: {len(words)}개")

if __name__ == "__main__":
    main()
