#!/usr/bin/env python3
"""IELTS 단어 대량 추가 - Part 5 (G-L)"""
import json
import requests
import time

GOOGLE_API_KEY = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGUAGES = ['ko', 'ja', 'zh', 'es', 'fr', 'de']

WORDS_PART5 = [
    ("gadget", "noun", "device", "Electronic gadget.", "Band 6.0-6.5"),
    ("gallery", "noun", "art exhibition place", "Art gallery.", "Band 6.0-6.5"),
    ("gamble", "noun", "bet", "Take a gamble.", "Band 6.0-6.5"),
    ("gang", "noun", "group", "Street gang.", "Band 6.0-6.5"),
    ("gap", "noun", "space", "Generation gap.", "Band 6.0-6.5"),
    ("garage", "noun", "car storage", "Underground garage.", "Band 4.5-5.5"),
    ("garbage", "noun", "waste", "Garbage collection.", "Band 4.5-5.5"),
    ("gardening", "noun", "plant cultivation", "Enjoy gardening.", "Band 6.0-6.5"),
    ("garment", "noun", "clothing item", "Traditional garment.", "Band 7.0-7.5"),
    ("gasoline", "noun", "petrol", "Gasoline prices.", "Band 6.0-6.5"),
    ("gathering", "noun", "assembly", "Family gathering.", "Band 6.0-6.5"),
    ("gauge", "noun", "measuring device", "Pressure gauge.", "Band 7.0-7.5"),
    ("gear", "noun", "equipment", "Camping gear.", "Band 6.0-6.5"),
    ("gem", "noun", "precious stone", "Rare gem.", "Band 6.0-6.5"),
    ("gender", "noun", "sex", "Gender equality.", "Band 6.0-6.5"),
    ("gene", "noun", "hereditary unit", "Genetic gene.", "Band 6.0-6.5"),
    ("generalization", "noun", "broad statement", "Avoid generalization.", "Band 8.0+"),
    ("generator", "noun", "power producer", "Electric generator.", "Band 6.0-6.5"),
    ("generosity", "noun", "kindness", "Show generosity.", "Band 7.0-7.5"),
    ("genius", "noun", "brilliant person", "Creative genius.", "Band 6.0-6.5"),
    ("genocide", "noun", "mass killing", "Prevent genocide.", "Band 8.0+"),
    ("genome", "noun", "genetic material", "Human genome.", "Band 8.0+"),
    ("genre", "noun", "category", "Music genre.", "Band 7.0-7.5"),
    ("gentleman", "noun", "polite man", "True gentleman.", "Band 6.0-6.5"),
    ("geography", "noun", "earth study", "Study geography.", "Band 6.0-6.5"),
    ("geology", "noun", "earth science", "Marine geology.", "Band 7.0-7.5"),
    ("gesture", "noun", "movement", "Kind gesture.", "Band 6.0-6.5"),
    ("giant", "noun", "large being", "Industry giant.", "Band 6.0-6.5"),
    ("gift", "noun", "present", "Birthday gift.", "Band 4.5-5.5"),
    ("glacier", "noun", "ice mass", "Melting glacier.", "Band 7.0-7.5"),
    ("glamour", "noun", "attractiveness", "Hollywood glamour.", "Band 7.0-7.5"),
    ("glance", "noun", "quick look", "At first glance.", "Band 6.0-6.5"),
    ("glimpse", "noun", "brief view", "Catch a glimpse.", "Band 7.0-7.5"),
    ("globalization", "noun", "worldwide integration", "Economic globalization.", "Band 7.0-7.5"),
    ("globe", "noun", "earth", "Around the globe.", "Band 6.0-6.5"),
    ("glory", "noun", "fame", "Past glory.", "Band 6.0-6.5"),
    ("glove", "noun", "hand covering", "Winter gloves.", "Band 4.5-5.5"),
    ("glucose", "noun", "blood sugar", "Blood glucose.", "Band 7.0-7.5"),
    ("goodwill", "noun", "friendly feelings", "Show goodwill.", "Band 7.0-7.5"),
    ("gossip", "noun", "rumor", "Spread gossip.", "Band 6.0-6.5"),
    ("governance", "noun", "management", "Corporate governance.", "Band 8.0+"),
    ("governor", "noun", "state leader", "State governor.", "Band 7.0-7.5"),
    ("grace", "noun", "elegance", "Move with grace.", "Band 6.0-6.5"),
    ("gradient", "noun", "slope", "Steep gradient.", "Band 8.0+"),
    ("graduate", "noun", "degree holder", "Recent graduate.", "Band 6.0-6.5"),
    ("graduation", "noun", "degree completion", "Graduation ceremony.", "Band 6.0-6.5"),
    ("grain", "noun", "cereal", "Whole grain.", "Band 6.0-6.5"),
    ("grammar", "noun", "language rules", "English grammar.", "Band 4.5-5.5"),
    ("grandeur", "noun", "magnificence", "Natural grandeur.", "Band 8.0+"),
    ("grant", "noun", "funding", "Research grant.", "Band 6.0-6.5"),
    ("graph", "noun", "chart", "Bar graph.", "Band 6.0-6.5"),
    ("graphics", "noun", "visual images", "Computer graphics.", "Band 6.0-6.5"),
    ("grasp", "noun", "understanding", "Good grasp.", "Band 6.0-6.5"),
    ("gratitude", "noun", "thankfulness", "Express gratitude.", "Band 7.0-7.5"),
    ("gravity", "noun", "pulling force", "Law of gravity.", "Band 6.0-6.5"),
    ("greenhouse", "noun", "plant building", "Greenhouse effect.", "Band 6.0-6.5"),
    ("grief", "noun", "sorrow", "Deep grief.", "Band 7.0-7.5"),
    ("grievance", "noun", "complaint", "File a grievance.", "Band 8.0+"),
    ("grocery", "noun", "food store", "Grocery shopping.", "Band 6.0-6.5"),
    ("ground", "noun", "surface", "Common ground.", "Band 4.5-5.5"),
    ("groundwork", "noun", "foundation", "Lay the groundwork.", "Band 7.0-7.5"),
    ("grove", "noun", "small forest", "Orange grove.", "Band 7.0-7.5"),
    ("guardian", "noun", "protector", "Legal guardian.", "Band 7.0-7.5"),
    ("guerrilla", "noun", "irregular soldier", "Guerrilla warfare.", "Band 8.0+"),
    ("guidance", "noun", "direction", "Career guidance.", "Band 6.0-6.5"),
    ("guideline", "noun", "recommendation", "Follow guidelines.", "Band 6.0-6.5"),
    ("guilt", "noun", "fault", "Feel guilt.", "Band 6.0-6.5"),
    ("gulf", "noun", "large bay", "Gulf of Mexico.", "Band 7.0-7.5"),
    ("gut", "noun", "intestine", "Gut feeling.", "Band 6.0-6.5"),
    ("gymnasium", "noun", "sports hall", "School gymnasium.", "Band 6.0-6.5"),
    ("habitat", "noun", "natural environment", "Natural habitat.", "Band 6.0-6.5"),
    ("hack", "noun", "shortcut", "Life hack.", "Band 6.0-6.5"),
    ("hallmark", "noun", "distinctive feature", "Quality hallmark.", "Band 8.0+"),
    ("halt", "noun", "stop", "Bring to a halt.", "Band 7.0-7.5"),
    ("hamlet", "noun", "small village", "Remote hamlet.", "Band 7.0-7.5"),
    ("handbook", "noun", "guide", "Employee handbook.", "Band 6.0-6.5"),
    ("handicap", "noun", "disadvantage", "Physical handicap.", "Band 7.0-7.5"),
    ("handling", "noun", "management", "Careful handling.", "Band 6.0-6.5"),
    ("handwriting", "noun", "script", "Neat handwriting.", "Band 6.0-6.5"),
    ("harassment", "noun", "persistent annoyance", "Sexual harassment.", "Band 7.0-7.5"),
    ("harbor", "noun", "port", "Natural harbor.", "Band 6.0-6.5"),
    ("hardship", "noun", "difficulty", "Economic hardship.", "Band 7.0-7.5"),
    ("hardware", "noun", "computer equipment", "Computer hardware.", "Band 6.0-6.5"),
    ("harmony", "noun", "agreement", "Live in harmony.", "Band 6.0-6.5"),
    ("harvest", "noun", "crop gathering", "Autumn harvest.", "Band 6.0-6.5"),
    ("hatred", "noun", "intense dislike", "Racial hatred.", "Band 7.0-7.5"),
    ("haven", "noun", "safe place", "Tax haven.", "Band 7.0-7.5"),
    ("hazard", "noun", "danger", "Health hazard.", "Band 6.0-6.5"),
    ("headline", "noun", "news title", "Front-page headline.", "Band 6.0-6.5"),
    ("headquarters", "noun", "main office", "Company headquarters.", "Band 6.0-6.5"),
    ("healing", "noun", "recovery", "Healing process.", "Band 6.0-6.5"),
    ("healthcare", "noun", "medical services", "Healthcare system.", "Band 6.0-6.5"),
    ("hearing", "noun", "ability to hear", "Good hearing.", "Band 6.0-6.5"),
    ("heartbeat", "noun", "heart rhythm", "Irregular heartbeat.", "Band 6.0-6.5"),
    ("heating", "noun", "warmth system", "Central heating.", "Band 6.0-6.5"),
    ("heaven", "noun", "paradise", "Go to heaven.", "Band 6.0-6.5"),
    ("hedge", "noun", "bush border", "Hedge fund.", "Band 7.0-7.5"),
    ("heel", "noun", "foot back", "High heels.", "Band 6.0-6.5"),
    ("height", "noun", "tallness", "Average height.", "Band 4.5-5.5"),
    ("heir", "noun", "inheritor", "Legal heir.", "Band 7.0-7.5"),
    ("helicopter", "noun", "aircraft", "Rescue helicopter.", "Band 6.0-6.5"),
    ("hemisphere", "noun", "half of sphere", "Northern hemisphere.", "Band 7.0-7.5"),
    ("herb", "noun", "plant for cooking", "Fresh herbs.", "Band 6.0-6.5"),
    ("heritage", "noun", "inheritance", "Cultural heritage.", "Band 7.0-7.5"),
    ("hero", "noun", "brave person", "National hero.", "Band 4.5-5.5"),
    ("heroism", "noun", "bravery", "Acts of heroism.", "Band 7.0-7.5"),
    ("hesitation", "noun", "uncertainty", "Without hesitation.", "Band 7.0-7.5"),
    ("hierarchy", "noun", "ranking system", "Social hierarchy.", "Band 8.0+"),
    ("highlight", "noun", "best part", "Main highlight.", "Band 6.0-6.5"),
    ("highway", "noun", "main road", "National highway.", "Band 6.0-6.5"),
    ("hike", "noun", "long walk", "Mountain hike.", "Band 6.0-6.5"),
    ("hindrance", "noun", "obstacle", "Major hindrance.", "Band 8.0+"),
    ("historian", "noun", "history expert", "Famous historian.", "Band 6.0-6.5"),
    ("homeland", "noun", "native country", "Return to homeland.", "Band 7.0-7.5"),
    ("homelessness", "noun", "being without home", "Combat homelessness.", "Band 7.0-7.5"),
    ("homepage", "noun", "main website page", "Visit our homepage.", "Band 6.0-6.5"),
    ("homework", "noun", "school assignment", "Do homework.", "Band 4.5-5.5"),
    ("honesty", "noun", "truthfulness", "Value honesty.", "Band 6.0-6.5"),
    ("honor", "noun", "respect", "Great honor.", "Band 6.0-6.5"),
    ("hook", "noun", "curved device", "Coat hook.", "Band 6.0-6.5"),
    ("horizon", "noun", "skyline", "On the horizon.", "Band 6.0-6.5"),
    ("hormone", "noun", "body chemical", "Growth hormone.", "Band 7.0-7.5"),
    ("horror", "noun", "fear", "Horror movie.", "Band 6.0-6.5"),
    ("hospitality", "noun", "friendliness", "Show hospitality.", "Band 7.0-7.5"),
    ("hostage", "noun", "captive", "Take hostage.", "Band 7.0-7.5"),
    ("hostility", "noun", "unfriendliness", "Show hostility.", "Band 7.0-7.5"),
    ("household", "noun", "family unit", "Average household.", "Band 6.0-6.5"),
    ("housing", "noun", "accommodation", "Affordable housing.", "Band 6.0-6.5"),
    ("hub", "noun", "center", "Transport hub.", "Band 7.0-7.5"),
    ("humanity", "noun", "human race", "Crimes against humanity.", "Band 7.0-7.5"),
    ("humidity", "noun", "moisture", "High humidity.", "Band 7.0-7.5"),
    ("humiliation", "noun", "embarrassment", "Public humiliation.", "Band 7.0-7.5"),
    ("humility", "noun", "modesty", "Show humility.", "Band 7.0-7.5"),
    ("humor", "noun", "comedy", "Sense of humor.", "Band 6.0-6.5"),
    ("hunger", "noun", "need for food", "World hunger.", "Band 6.0-6.5"),
    ("hunter", "noun", "person who hunts", "Big game hunter.", "Band 6.0-6.5"),
    ("hurdle", "noun", "obstacle", "Major hurdle.", "Band 7.0-7.5"),
    ("hurricane", "noun", "tropical storm", "Devastating hurricane.", "Band 6.0-6.5"),
    ("hybrid", "noun", "mixture", "Hybrid car.", "Band 7.0-7.5"),
    ("hygiene", "noun", "cleanliness", "Personal hygiene.", "Band 6.0-6.5"),
    ("hypothesis", "noun", "theory", "Test the hypothesis.", "Band 7.0-7.5"),
    ("icon", "noun", "symbol", "Cultural icon.", "Band 7.0-7.5"),
    ("idealism", "noun", "pursuit of ideals", "Political idealism.", "Band 8.0+"),
    ("identification", "noun", "recognition", "Photo identification.", "Band 6.0-6.5"),
    ("ideology", "noun", "belief system", "Political ideology.", "Band 8.0+"),
    ("ignorance", "noun", "lack of knowledge", "Out of ignorance.", "Band 7.0-7.5"),
    ("illustration", "noun", "picture", "Book illustration.", "Band 6.0-6.5"),
    ("imagery", "noun", "visual symbols", "Poetic imagery.", "Band 7.0-7.5"),
    ("imagination", "noun", "creative thought", "Use your imagination.", "Band 6.0-6.5"),
    ("imbalance", "noun", "disproportion", "Trade imbalance.", "Band 7.0-7.5"),
    ("imitation", "noun", "copy", "Cheap imitation.", "Band 7.0-7.5"),
    ("immigration", "noun", "entering country", "Illegal immigration.", "Band 7.0-7.5"),
    ("immunity", "noun", "protection", "Build immunity.", "Band 7.0-7.5"),
    ("imperative", "noun", "necessity", "Moral imperative.", "Band 8.0+"),
    ("implication", "noun", "consequence", "Legal implication.", "Band 7.0-7.5"),
    ("import", "noun", "brought goods", "Food import.", "Band 6.0-6.5"),
    ("importance", "noun", "significance", "Great importance.", "Band 6.0-6.5"),
    ("imposition", "noun", "enforcement", "Tax imposition.", "Band 8.0+"),
    ("impression", "noun", "effect", "First impression.", "Band 6.0-6.5"),
    ("imprisonment", "noun", "confinement", "Life imprisonment.", "Band 7.0-7.5"),
    ("improvement", "noun", "betterment", "Make improvements.", "Band 6.0-6.5"),
    ("impulse", "noun", "sudden urge", "Act on impulse.", "Band 7.0-7.5"),
    ("inaccuracy", "noun", "error", "Factual inaccuracy.", "Band 8.0+"),
    ("inadequacy", "noun", "insufficiency", "Feelings of inadequacy.", "Band 8.0+"),
    ("incentive", "noun", "motivation", "Tax incentive.", "Band 7.0-7.5"),
    ("incidence", "noun", "occurrence rate", "High incidence.", "Band 8.0+"),
    ("incident", "noun", "event", "Minor incident.", "Band 6.0-6.5"),
    ("inclination", "noun", "tendency", "Natural inclination.", "Band 8.0+"),
    ("inclusion", "noun", "addition", "Social inclusion.", "Band 7.0-7.5"),
    ("income", "noun", "earnings", "Annual income.", "Band 6.0-6.5"),
    ("inconsistency", "noun", "contradiction", "Logical inconsistency.", "Band 8.0+"),
    ("incorporation", "noun", "inclusion", "Company incorporation.", "Band 8.0+"),
    ("increment", "noun", "increase", "Annual increment.", "Band 8.0+"),
    ("independence", "noun", "freedom", "National independence.", "Band 6.0-6.5"),
    ("index", "noun", "list", "Price index.", "Band 6.0-6.5"),
    ("indication", "noun", "sign", "Clear indication.", "Band 6.0-6.5"),
    ("indicator", "noun", "sign", "Economic indicator.", "Band 7.0-7.5"),
    ("indifference", "noun", "lack of interest", "Show indifference.", "Band 8.0+"),
    ("indigenous", "adjective", "native", "Indigenous people.", "Band 8.0+"),
    ("individual", "noun", "person", "Private individual.", "Band 6.0-6.5"),
    ("individuality", "noun", "uniqueness", "Express individuality.", "Band 8.0+"),
    ("industrialization", "noun", "industrial development", "Rapid industrialization.", "Band 8.0+"),
    ("inequality", "noun", "disparity", "Social inequality.", "Band 7.0-7.5"),
    ("infant", "noun", "baby", "Infant mortality.", "Band 6.0-6.5"),
    ("infection", "noun", "disease spread", "Bacterial infection.", "Band 6.0-6.5"),
    ("inference", "noun", "conclusion", "Draw an inference.", "Band 8.0+"),
    ("inflation", "noun", "price increase", "High inflation.", "Band 7.0-7.5"),
    ("influence", "noun", "effect", "Positive influence.", "Band 6.0-6.5"),
    ("influencer", "noun", "opinion leader", "Social media influencer.", "Band 7.0-7.5"),
    ("infrastructure", "noun", "basic systems", "Transport infrastructure.", "Band 7.0-7.5"),
    ("ingredient", "noun", "component", "Secret ingredient.", "Band 6.0-6.5"),
    ("inhabitant", "noun", "resident", "Local inhabitant.", "Band 7.0-7.5"),
    ("inheritance", "noun", "bequest", "Family inheritance.", "Band 7.0-7.5"),
    ("inhibition", "noun", "restraint", "Without inhibition.", "Band 8.0+"),
    ("initiative", "noun", "new action", "Take initiative.", "Band 6.0-6.5"),
    ("injection", "noun", "shot", "Give injection.", "Band 6.0-6.5"),
    ("injury", "noun", "wound", "Serious injury.", "Band 6.0-6.5"),
    ("injustice", "noun", "unfairness", "Fight injustice.", "Band 7.0-7.5"),
    ("ink", "noun", "writing fluid", "Black ink.", "Band 4.5-5.5"),
    ("innovation", "noun", "new idea", "Technological innovation.", "Band 7.0-7.5"),
    ("input", "noun", "contribution", "User input.", "Band 6.0-6.5"),
    ("inquiry", "noun", "investigation", "Public inquiry.", "Band 7.0-7.5"),
    ("insect", "noun", "bug", "Insect bite.", "Band 4.5-5.5"),
    ("insertion", "noun", "adding in", "Text insertion.", "Band 7.0-7.5"),
    ("insider", "noun", "inside person", "Company insider.", "Band 7.0-7.5"),
    ("insight", "noun", "understanding", "Valuable insight.", "Band 7.0-7.5"),
    ("inspection", "noun", "examination", "Quality inspection.", "Band 6.0-6.5"),
    ("inspector", "noun", "examiner", "Building inspector.", "Band 6.0-6.5"),
    ("inspiration", "noun", "motivation", "Source of inspiration.", "Band 6.0-6.5"),
    ("instability", "noun", "unsteadiness", "Political instability.", "Band 7.0-7.5"),
    ("installation", "noun", "setup", "Software installation.", "Band 6.0-6.5"),
    ("installment", "noun", "payment part", "Monthly installment.", "Band 7.0-7.5"),
    ("instance", "noun", "example", "For instance.", "Band 6.0-6.5"),
    ("instant", "noun", "moment", "In an instant.", "Band 6.0-6.5"),
    ("instinct", "noun", "natural behavior", "Survival instinct.", "Band 6.0-6.5"),
    ("institute", "noun", "organization", "Research institute.", "Band 6.0-6.5"),
    ("institution", "noun", "organization", "Financial institution.", "Band 6.0-6.5"),
    ("instruction", "noun", "direction", "Follow instructions.", "Band 6.0-6.5"),
    ("instructor", "noun", "teacher", "Fitness instructor.", "Band 6.0-6.5"),
    ("instrument", "noun", "tool", "Musical instrument.", "Band 6.0-6.5"),
    ("insulation", "noun", "protection", "Home insulation.", "Band 7.0-7.5"),
    ("insurance", "noun", "protection plan", "Health insurance.", "Band 6.0-6.5"),
    ("intake", "noun", "consumption", "Calorie intake.", "Band 7.0-7.5"),
    ("integration", "noun", "combination", "Social integration.", "Band 7.0-7.5"),
    ("integrity", "noun", "honesty", "Personal integrity.", "Band 7.0-7.5"),
    ("intellect", "noun", "intelligence", "Sharp intellect.", "Band 7.0-7.5"),
    ("intellectual", "noun", "thinker", "Public intellectual.", "Band 7.0-7.5"),
    ("intelligence", "noun", "mental ability", "Artificial intelligence.", "Band 6.0-6.5"),
    ("intensity", "noun", "strength", "High intensity.", "Band 7.0-7.5"),
    ("intention", "noun", "purpose", "Good intentions.", "Band 6.0-6.5"),
    ("interaction", "noun", "communication", "Social interaction.", "Band 6.0-6.5"),
    ("interface", "noun", "connection point", "User interface.", "Band 7.0-7.5"),
    ("interference", "noun", "obstruction", "Government interference.", "Band 7.0-7.5"),
    ("interior", "noun", "inside", "Interior design.", "Band 6.0-6.5"),
    ("intermediate", "adjective", "middle level", "Intermediate level.", "Band 6.0-6.5"),
    ("interpretation", "noun", "explanation", "Open to interpretation.", "Band 7.0-7.5"),
    ("interpreter", "noun", "translator", "Conference interpreter.", "Band 6.0-6.5"),
    ("interruption", "noun", "break", "Without interruption.", "Band 7.0-7.5"),
    ("intersection", "noun", "crossroads", "Busy intersection.", "Band 7.0-7.5"),
    ("interval", "noun", "gap", "Regular intervals.", "Band 7.0-7.5"),
    ("intervention", "noun", "involvement", "Medical intervention.", "Band 7.0-7.5"),
    ("intimacy", "noun", "closeness", "Emotional intimacy.", "Band 8.0+"),
    ("intimidation", "noun", "threatening", "Witness intimidation.", "Band 8.0+"),
    ("introduction", "noun", "beginning", "Brief introduction.", "Band 6.0-6.5"),
    ("intuition", "noun", "instinct", "Trust your intuition.", "Band 7.0-7.5"),
    ("invasion", "noun", "attack", "Foreign invasion.", "Band 7.0-7.5"),
    ("invention", "noun", "creation", "Great invention.", "Band 6.0-6.5"),
    ("inventory", "noun", "stock list", "Check inventory.", "Band 7.0-7.5"),
    ("investigation", "noun", "inquiry", "Police investigation.", "Band 6.0-6.5"),
    ("investigator", "noun", "examiner", "Private investigator.", "Band 7.0-7.5"),
    ("investor", "noun", "financial backer", "Foreign investor.", "Band 6.0-6.5"),
    ("invitation", "noun", "request to attend", "Accept invitation.", "Band 6.0-6.5"),
    ("involvement", "noun", "participation", "Active involvement.", "Band 6.0-6.5"),
    ("irrigation", "noun", "water supply", "Crop irrigation.", "Band 7.0-7.5"),
    ("irritation", "noun", "annoyance", "Skin irritation.", "Band 7.0-7.5"),
    ("isolation", "noun", "separation", "Social isolation.", "Band 7.0-7.5"),
    ("item", "noun", "thing", "List item.", "Band 4.5-5.5"),
    ("itinerary", "noun", "travel plan", "Travel itinerary.", "Band 7.0-7.5"),
    ("jacket", "noun", "coat", "Leather jacket.", "Band 4.5-5.5"),
    ("jail", "noun", "prison", "Go to jail.", "Band 6.0-6.5"),
    ("jam", "noun", "traffic block", "Traffic jam.", "Band 6.0-6.5"),
    ("jaw", "noun", "mouth bone", "Strong jaw.", "Band 6.0-6.5"),
    ("jealousy", "noun", "envy", "Feel jealousy.", "Band 6.0-6.5"),
    ("jeopardy", "noun", "danger", "In jeopardy.", "Band 8.0+"),
    ("jet", "noun", "airplane", "Private jet.", "Band 6.0-6.5"),
    ("jewelry", "noun", "ornaments", "Fine jewelry.", "Band 6.0-6.5"),
    ("joint", "noun", "connection point", "Joint venture.", "Band 6.0-6.5"),
    ("joke", "noun", "funny story", "Practical joke.", "Band 4.5-5.5"),
    ("journal", "noun", "diary", "Scientific journal.", "Band 6.0-6.5"),
    ("journalism", "noun", "news reporting", "Investigative journalism.", "Band 7.0-7.5"),
    ("journalist", "noun", "reporter", "Political journalist.", "Band 6.0-6.5"),
    ("journey", "noun", "trip", "Long journey.", "Band 6.0-6.5"),
    ("joy", "noun", "happiness", "Pure joy.", "Band 4.5-5.5"),
    ("judgment", "noun", "decision", "Good judgment.", "Band 6.0-6.5"),
    ("juice", "noun", "liquid from fruit", "Orange juice.", "Band 4.5-5.5"),
    ("jumble", "noun", "mixture", "Confused jumble.", "Band 7.0-7.5"),
    ("junction", "noun", "meeting point", "Road junction.", "Band 7.0-7.5"),
    ("jungle", "noun", "tropical forest", "Dense jungle.", "Band 6.0-6.5"),
    ("junior", "adjective", "younger", "Junior staff.", "Band 6.0-6.5"),
    ("jurisdiction", "noun", "authority", "Legal jurisdiction.", "Band 8.0+"),
    ("jury", "noun", "trial panel", "Jury verdict.", "Band 7.0-7.5"),
    ("justice", "noun", "fairness", "Social justice.", "Band 6.0-6.5"),
    ("justification", "noun", "reason", "No justification.", "Band 7.0-7.5"),
    ("keeper", "noun", "guardian", "Goal keeper.", "Band 6.0-6.5"),
    ("kernel", "noun", "core", "Kernel of truth.", "Band 8.0+"),
    ("keyboard", "noun", "input device", "Computer keyboard.", "Band 4.5-5.5"),
    ("kidney", "noun", "body organ", "Kidney disease.", "Band 6.0-6.5"),
    ("kilometer", "noun", "distance unit", "Five kilometers.", "Band 4.5-5.5"),
    ("kindergarten", "noun", "preschool", "Start kindergarten.", "Band 6.0-6.5"),
    ("kindness", "noun", "friendliness", "Show kindness.", "Band 4.5-5.5"),
    ("kingdom", "noun", "realm", "Animal kingdom.", "Band 6.0-6.5"),
    ("kit", "noun", "set of tools", "First aid kit.", "Band 6.0-6.5"),
    ("kitchen", "noun", "cooking room", "Modern kitchen.", "Band 4.5-5.5"),
    ("knee", "noun", "leg joint", "Knee injury.", "Band 4.5-5.5"),
    ("knife", "noun", "cutting tool", "Sharp knife.", "Band 4.5-5.5"),
    ("knight", "noun", "medieval warrior", "Noble knight.", "Band 6.0-6.5"),
    ("knot", "noun", "tied rope", "Tight knot.", "Band 6.0-6.5"),
    ("lab", "noun", "laboratory", "Research lab.", "Band 6.0-6.5"),
    ("label", "noun", "tag", "Warning label.", "Band 6.0-6.5"),
    ("labor", "noun", "work", "Manual labor.", "Band 6.0-6.5"),
    ("laboratory", "noun", "research room", "Science laboratory.", "Band 6.0-6.5"),
    ("laborer", "noun", "worker", "Construction laborer.", "Band 7.0-7.5"),
    ("lace", "noun", "fabric", "Lace curtains.", "Band 6.0-6.5"),
    ("ladder", "noun", "climbing device", "Career ladder.", "Band 6.0-6.5"),
    ("lag", "noun", "delay", "Jet lag.", "Band 7.0-7.5"),
    ("lake", "noun", "body of water", "Mountain lake.", "Band 4.5-5.5"),
    ("lamb", "noun", "young sheep", "Roast lamb.", "Band 6.0-6.5"),
    ("lamp", "noun", "light fixture", "Table lamp.", "Band 4.5-5.5"),
    ("landlord", "noun", "property owner", "Strict landlord.", "Band 6.0-6.5"),
    ("landmark", "noun", "notable place", "Historical landmark.", "Band 6.0-6.5"),
    ("landscape", "noun", "scenery", "Beautiful landscape.", "Band 6.0-6.5"),
    ("lane", "noun", "narrow road", "Fast lane.", "Band 6.0-6.5"),
    ("laptop", "noun", "portable computer", "New laptop.", "Band 6.0-6.5"),
    ("laser", "noun", "light beam", "Laser surgery.", "Band 6.0-6.5"),
    ("launch", "noun", "start", "Product launch.", "Band 6.0-6.5"),
    ("laundry", "noun", "clothes washing", "Do laundry.", "Band 6.0-6.5"),
    ("lawsuit", "noun", "legal case", "File a lawsuit.", "Band 7.0-7.5"),
    ("lawyer", "noun", "legal professional", "Defense lawyer.", "Band 6.0-6.5"),
    ("layer", "noun", "level", "Ozone layer.", "Band 6.0-6.5"),
    ("layout", "noun", "arrangement", "Page layout.", "Band 6.0-6.5"),
    ("leadership", "noun", "guidance", "Strong leadership.", "Band 6.0-6.5"),
    ("league", "noun", "association", "Football league.", "Band 6.0-6.5"),
    ("leak", "noun", "escape", "Oil leak.", "Band 6.0-6.5"),
    ("leap", "noun", "jump", "Quantum leap.", "Band 7.0-7.5"),
    ("learner", "noun", "student", "Fast learner.", "Band 6.0-6.5"),
    ("lease", "noun", "rental agreement", "Sign a lease.", "Band 7.0-7.5"),
    ("leather", "noun", "animal skin", "Leather shoes.", "Band 6.0-6.5"),
    ("lecture", "noun", "talk", "University lecture.", "Band 6.0-6.5"),
    ("lecturer", "noun", "teacher", "Senior lecturer.", "Band 6.0-6.5"),
    ("legacy", "noun", "inheritance", "Cultural legacy.", "Band 7.0-7.5"),
    ("legend", "noun", "myth", "Urban legend.", "Band 6.0-6.5"),
    ("legislation", "noun", "laws", "New legislation.", "Band 7.0-7.5"),
    ("legislator", "noun", "lawmaker", "State legislator.", "Band 8.0+"),
    ("legislature", "noun", "law-making body", "State legislature.", "Band 8.0+"),
    ("legitimacy", "noun", "lawfulness", "Question legitimacy.", "Band 8.0+"),
    ("leisure", "noun", "free time", "Leisure activities.", "Band 6.0-6.5"),
    ("lemon", "noun", "citrus fruit", "Fresh lemon.", "Band 4.5-5.5"),
    ("length", "noun", "extent", "Full length.", "Band 4.5-5.5"),
    ("lens", "noun", "optical glass", "Camera lens.", "Band 6.0-6.5"),
    ("leopard", "noun", "big cat", "Snow leopard.", "Band 6.0-6.5"),
    ("lesson", "noun", "class", "Learn a lesson.", "Band 4.5-5.5"),
    ("lever", "noun", "handle", "Pull the lever.", "Band 7.0-7.5"),
    ("leverage", "noun", "advantage", "Financial leverage.", "Band 8.0+"),
    ("liability", "noun", "responsibility", "Legal liability.", "Band 7.0-7.5"),
    ("liberal", "adjective", "open-minded", "Liberal views.", "Band 7.0-7.5"),
    ("liberation", "noun", "freedom", "Women's liberation.", "Band 8.0+"),
    ("liberty", "noun", "freedom", "Civil liberty.", "Band 7.0-7.5"),
    ("librarian", "noun", "library worker", "School librarian.", "Band 6.0-6.5"),
    ("license", "noun", "permit", "Driver's license.", "Band 6.0-6.5"),
    ("lid", "noun", "cover", "Remove the lid.", "Band 6.0-6.5"),
    ("lifespan", "noun", "life duration", "Average lifespan.", "Band 7.0-7.5"),
    ("lifestyle", "noun", "way of living", "Healthy lifestyle.", "Band 6.0-6.5"),
    ("lifetime", "noun", "life duration", "Once in a lifetime.", "Band 6.0-6.5"),
    ("lighting", "noun", "illumination", "Good lighting.", "Band 6.0-6.5"),
    ("likelihood", "noun", "probability", "High likelihood.", "Band 7.0-7.5"),
    ("limb", "noun", "arm or leg", "Lower limb.", "Band 6.0-6.5"),
    ("limitation", "noun", "restriction", "Time limitation.", "Band 6.0-6.5"),
    ("linen", "noun", "fabric", "Bed linen.", "Band 6.0-6.5"),
    ("liner", "noun", "ship", "Ocean liner.", "Band 7.0-7.5"),
    ("lineup", "noun", "arrangement", "Starting lineup.", "Band 6.0-6.5"),
    ("link", "noun", "connection", "Weak link.", "Band 6.0-6.5"),
    ("lion", "noun", "big cat", "African lion.", "Band 4.5-5.5"),
    ("liquid", "noun", "fluid", "Clear liquid.", "Band 6.0-6.5"),
    ("literacy", "noun", "reading ability", "Computer literacy.", "Band 7.0-7.5"),
    ("literature", "noun", "written works", "English literature.", "Band 6.0-6.5"),
    ("litigation", "noun", "legal action", "Civil litigation.", "Band 8.0+"),
    ("liver", "noun", "body organ", "Liver disease.", "Band 6.0-6.5"),
    ("livestock", "noun", "farm animals", "Raise livestock.", "Band 7.0-7.5"),
    ("load", "noun", "cargo", "Heavy load.", "Band 6.0-6.5"),
    ("loan", "noun", "borrowed money", "Bank loan.", "Band 6.0-6.5"),
    ("lobby", "noun", "entrance area", "Hotel lobby.", "Band 6.0-6.5"),
    ("locality", "noun", "area", "In this locality.", "Band 7.0-7.5"),
    ("location", "noun", "place", "Prime location.", "Band 6.0-6.5"),
    ("locomotive", "noun", "train engine", "Steam locomotive.", "Band 7.0-7.5"),
    ("lodge", "noun", "cabin", "Mountain lodge.", "Band 6.0-6.5"),
    ("logic", "noun", "reasoning", "Sound logic.", "Band 6.0-6.5"),
    ("logo", "noun", "symbol", "Company logo.", "Band 6.0-6.5"),
    ("loneliness", "noun", "isolation", "Feel loneliness.", "Band 6.0-6.5"),
    ("longevity", "noun", "long life", "Human longevity.", "Band 8.0+"),
    ("loop", "noun", "circle", "Feedback loop.", "Band 7.0-7.5"),
    ("loophole", "noun", "escape", "Legal loophole.", "Band 8.0+"),
    ("loss", "noun", "losing", "Weight loss.", "Band 4.5-5.5"),
    ("lottery", "noun", "prize draw", "Win the lottery.", "Band 6.0-6.5"),
    ("lounge", "noun", "sitting room", "Airport lounge.", "Band 6.0-6.5"),
    ("loyalty", "noun", "faithfulness", "Brand loyalty.", "Band 6.0-6.5"),
    ("luggage", "noun", "bags", "Carry-on luggage.", "Band 6.0-6.5"),
    ("lumber", "noun", "wood", "Lumber yard.", "Band 7.0-7.5"),
    ("lump", "noun", "mass", "Sugar lump.", "Band 6.0-6.5"),
    ("lunch", "noun", "midday meal", "Lunch break.", "Band 4.5-5.5"),
    ("lung", "noun", "breathing organ", "Lung cancer.", "Band 6.0-6.5"),
    ("lure", "noun", "attraction", "Strong lure.", "Band 7.0-7.5"),
    ("luxury", "noun", "extravagance", "Luxury goods.", "Band 6.0-6.5"),
    ("lyrics", "noun", "song words", "Write lyrics.", "Band 6.0-6.5"),
]

def translate_batch(texts, target_lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={GOOGLE_API_KEY}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            resp = requests.post(url, json={"q": batch, "source": "en", "target": target_lang}, timeout=30)
            if resp.status_code == 200:
                result.extend([t['translatedText'] for t in resp.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

def main():
    with open('assets/data/words.json', 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    existing = {w['word'].lower() for w in words}
    start_id = max(w['id'] for w in words) + 1
    categories = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
    
    new_words = []
    for word, pos, definition, example, level in WORDS_PART5:
        if word.lower() not in existing:
            new_words.append({
                "id": start_id + len(new_words),
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": categories[(start_id + len(new_words)) % len(categories)]
            })
            existing.add(word.lower())
    
    print(f"새 단어: {len(new_words)}개")
    
    if new_words:
        defs = [w['definition'] for w in new_words]
        exs = [w['example'] for w in new_words]
        
        for lang in LANGUAGES:
            print(f"{lang} 번역중...")
            trans_defs = translate_batch(defs, lang)
            trans_exs = translate_batch(exs, lang)
            for i, w in enumerate(new_words):
                if 'translations' not in w:
                    w['translations'] = {}
                w['translations'][lang] = {
                    'definition': trans_defs[i],
                    'example': trans_exs[i]
                }
        
        words.extend(new_words)
        with open('assets/data/words.json', 'w', encoding='utf-8') as f:
            json.dump(words, f, ensure_ascii=False, indent=2)
    
    print(f"총: {len(words)}개")

if __name__ == "__main__":
    main()
