#!/usr/bin/env python3
"""IELTS 단어 대량 추가 - Part 3"""
import json
import requests
import time

GOOGLE_API_KEY = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGUAGES = ['ko', 'ja', 'zh', 'es', 'fr', 'de']

WORDS_PART3 = [
    ("abolish", "verb", "to officially end", "Abolish the law.", "Band 7.0-7.5"),
    ("abortion", "noun", "termination of pregnancy", "Debate on abortion.", "Band 7.0-7.5"),
    ("absence", "noun", "state of being away", "In the absence of evidence.", "Band 6.0-6.5"),
    ("absolute", "adjective", "complete", "Absolute power.", "Band 6.0-6.5"),
    ("absorb", "verb", "to take in", "Absorb information.", "Band 6.0-6.5"),
    ("abundance", "noun", "large quantity", "Abundance of resources.", "Band 7.0-7.5"),
    ("abuse", "noun", "misuse", "Child abuse.", "Band 6.0-6.5"),
    ("accelerate", "verb", "to speed up", "Accelerate growth.", "Band 7.0-7.5"),
    ("acceptance", "noun", "approval", "Gain acceptance.", "Band 6.0-6.5"),
    ("accessible", "adjective", "easy to reach", "Accessible to all.", "Band 6.0-6.5"),
    ("accident", "noun", "unexpected event", "Car accident.", "Band 4.5-5.5"),
    ("accommodation", "noun", "lodging", "Find accommodation.", "Band 6.0-6.5"),
    ("accomplish", "verb", "to achieve", "Accomplish goals.", "Band 6.0-6.5"),
    ("accountability", "noun", "responsibility", "Ensure accountability.", "Band 8.0+"),
    ("accumulation", "noun", "gathering", "Accumulation of wealth.", "Band 8.0+"),
    ("accuracy", "noun", "correctness", "Check for accuracy.", "Band 6.0-6.5"),
    ("accusation", "noun", "charge", "False accusation.", "Band 7.0-7.5"),
    ("achievement", "noun", "accomplishment", "Great achievement.", "Band 6.0-6.5"),
    ("acid", "noun", "sour substance", "Acid rain.", "Band 6.0-6.5"),
    ("acquisition", "noun", "obtaining", "Language acquisition.", "Band 8.0+"),
    ("activation", "noun", "making active", "Account activation.", "Band 7.0-7.5"),
    ("activist", "noun", "campaigner", "Environmental activist.", "Band 7.0-7.5"),
    ("adaptation", "noun", "adjustment", "Climate adaptation.", "Band 7.0-7.5"),
    ("addiction", "noun", "dependence", "Drug addiction.", "Band 7.0-7.5"),
    ("adjustment", "noun", "modification", "Make an adjustment.", "Band 6.0-6.5"),
    ("administration", "noun", "management", "Government administration.", "Band 6.0-6.5"),
    ("admission", "noun", "entry", "University admission.", "Band 6.0-6.5"),
    ("adolescence", "noun", "teenage years", "During adolescence.", "Band 7.0-7.5"),
    ("adoption", "noun", "taking as own", "Child adoption.", "Band 7.0-7.5"),
    ("advancement", "noun", "progress", "Career advancement.", "Band 7.0-7.5"),
    ("adventure", "noun", "exciting experience", "Outdoor adventure.", "Band 4.5-5.5"),
    ("advertisement", "noun", "promotion", "TV advertisement.", "Band 6.0-6.5"),
    ("advisory", "adjective", "giving advice", "Advisory committee.", "Band 7.0-7.5"),
    ("advocacy", "noun", "public support", "Patient advocacy.", "Band 8.0+"),
    ("aesthetic", "adjective", "artistic", "Aesthetic value.", "Band 8.0+"),
    ("affection", "noun", "fondness", "Show affection.", "Band 6.0-6.5"),
    ("affiliation", "noun", "connection", "Political affiliation.", "Band 8.0+"),
    ("aftermath", "noun", "consequences", "In the aftermath.", "Band 7.0-7.5"),
    ("aggression", "noun", "hostile behavior", "Acts of aggression.", "Band 7.0-7.5"),
    ("agreement", "noun", "arrangement", "Reach an agreement.", "Band 6.0-6.5"),
    ("agriculture", "noun", "farming", "Modern agriculture.", "Band 6.0-6.5"),
    ("airline", "noun", "air transport company", "International airline.", "Band 4.5-5.5"),
    ("alarm", "noun", "warning", "Fire alarm.", "Band 4.5-5.5"),
    ("alcohol", "noun", "intoxicating drink", "Avoid alcohol.", "Band 6.0-6.5"),
    ("algorithm", "noun", "set of rules", "Computer algorithm.", "Band 8.0+"),
    ("alien", "adjective", "foreign", "Alien concept.", "Band 7.0-7.5"),
    ("alignment", "noun", "arrangement", "Strategic alignment.", "Band 8.0+"),
    ("allegation", "noun", "claim", "Serious allegation.", "Band 7.0-7.5"),
    ("alliance", "noun", "partnership", "Form an alliance.", "Band 7.0-7.5"),
    ("allocation", "noun", "distribution", "Budget allocation.", "Band 7.0-7.5"),
    ("allowance", "noun", "permitted amount", "Daily allowance.", "Band 6.0-6.5"),
    ("alteration", "noun", "change", "Minor alteration.", "Band 7.0-7.5"),
    ("amateur", "adjective", "non-professional", "Amateur photographer.", "Band 6.0-6.5"),
    ("amazement", "noun", "surprise", "To my amazement.", "Band 6.0-6.5"),
    ("ambassador", "noun", "diplomatic representative", "UN ambassador.", "Band 7.0-7.5"),
    ("ambiguity", "noun", "uncertainty", "Avoid ambiguity.", "Band 8.0+"),
    ("ambition", "noun", "desire to succeed", "Strong ambition.", "Band 6.0-6.5"),
    ("amendment", "noun", "change", "Constitutional amendment.", "Band 7.0-7.5"),
    ("amount", "noun", "quantity", "Large amount.", "Band 4.5-5.5"),
    ("amusement", "noun", "entertainment", "Amusement park.", "Band 6.0-6.5"),
    ("analysis", "noun", "examination", "Data analysis.", "Band 6.0-6.5"),
    ("analyst", "noun", "examiner", "Financial analyst.", "Band 7.0-7.5"),
    ("ancestor", "noun", "forebear", "Our ancestors.", "Band 6.0-6.5"),
    ("ancient", "adjective", "very old", "Ancient history.", "Band 6.0-6.5"),
    ("anger", "noun", "strong displeasure", "Control your anger.", "Band 4.5-5.5"),
    ("angle", "noun", "perspective", "Different angle.", "Band 6.0-6.5"),
    ("animation", "noun", "moving images", "Computer animation.", "Band 6.0-6.5"),
    ("announcement", "noun", "public statement", "Make an announcement.", "Band 6.0-6.5"),
    ("annoyance", "noun", "irritation", "Cause annoyance.", "Band 6.0-6.5"),
    ("anonymity", "noun", "being unnamed", "Maintain anonymity.", "Band 8.0+"),
    ("antibiotics", "noun", "medicine for bacteria", "Take antibiotics.", "Band 6.0-6.5"),
    ("anticipation", "noun", "expectation", "In anticipation.", "Band 7.0-7.5"),
    ("anxiety", "noun", "worry", "Reduce anxiety.", "Band 6.0-6.5"),
    ("apartment", "noun", "flat", "Rent an apartment.", "Band 4.5-5.5"),
    ("apology", "noun", "expression of regret", "Offer an apology.", "Band 6.0-6.5"),
    ("apparatus", "noun", "equipment", "Scientific apparatus.", "Band 8.0+"),
    ("appeal", "noun", "request", "Make an appeal.", "Band 6.0-6.5"),
    ("appearance", "noun", "look", "Physical appearance.", "Band 6.0-6.5"),
    ("appetite", "noun", "desire to eat", "Loss of appetite.", "Band 6.0-6.5"),
    ("applause", "noun", "clapping", "Receive applause.", "Band 6.0-6.5"),
    ("appliance", "noun", "device", "Kitchen appliance.", "Band 6.0-6.5"),
    ("applicant", "noun", "person who applies", "Job applicant.", "Band 6.0-6.5"),
    ("application", "noun", "request", "Submit application.", "Band 6.0-6.5"),
    ("appointment", "noun", "arrangement to meet", "Doctor's appointment.", "Band 6.0-6.5"),
    ("appreciation", "noun", "gratitude", "Show appreciation.", "Band 6.0-6.5"),
    ("apprentice", "noun", "trainee", "Young apprentice.", "Band 7.0-7.5"),
    ("approval", "noun", "acceptance", "Get approval.", "Band 6.0-6.5"),
    ("architect", "noun", "building designer", "Famous architect.", "Band 6.0-6.5"),
    ("architecture", "noun", "building design", "Modern architecture.", "Band 6.0-6.5"),
    ("archive", "noun", "historical records", "National archive.", "Band 7.0-7.5"),
    ("arena", "noun", "stadium", "Sports arena.", "Band 6.0-6.5"),
    ("argument", "noun", "debate", "Strong argument.", "Band 6.0-6.5"),
    ("arithmetic", "noun", "basic math", "Simple arithmetic.", "Band 6.0-6.5"),
    ("arrangement", "noun", "plan", "Make arrangements.", "Band 6.0-6.5"),
    ("arrest", "verb", "to detain", "Arrest the suspect.", "Band 6.0-6.5"),
    ("arrival", "noun", "coming", "Upon arrival.", "Band 6.0-6.5"),
    ("arrogance", "noun", "excessive pride", "Show arrogance.", "Band 7.0-7.5"),
    ("article", "noun", "written piece", "News article.", "Band 4.5-5.5"),
    ("artificial", "adjective", "man-made", "Artificial intelligence.", "Band 6.0-6.5"),
    ("artist", "noun", "creative person", "Famous artist.", "Band 4.5-5.5"),
    ("artwork", "noun", "creative work", "Beautiful artwork.", "Band 6.0-6.5"),
    ("aspiration", "noun", "ambition", "Career aspirations.", "Band 7.0-7.5"),
    ("assassination", "noun", "murder of important person", "Political assassination.", "Band 8.0+"),
    ("assault", "noun", "attack", "Physical assault.", "Band 7.0-7.5"),
    ("assembly", "noun", "gathering", "School assembly.", "Band 6.0-6.5"),
    ("assertion", "noun", "confident statement", "Make an assertion.", "Band 8.0+"),
    ("assessment", "noun", "evaluation", "Risk assessment.", "Band 6.0-6.5"),
    ("assignment", "noun", "task", "Complete the assignment.", "Band 6.0-6.5"),
    ("assistance", "noun", "help", "Provide assistance.", "Band 6.0-6.5"),
    ("assistant", "noun", "helper", "Personal assistant.", "Band 4.5-5.5"),
    ("association", "noun", "organization", "Trade association.", "Band 6.0-6.5"),
    ("assumption", "noun", "belief", "Wrong assumption.", "Band 7.0-7.5"),
    ("assurance", "noun", "guarantee", "Quality assurance.", "Band 7.0-7.5"),
    ("asylum", "noun", "protection", "Seek asylum.", "Band 7.0-7.5"),
    ("athlete", "noun", "sportsperson", "Professional athlete.", "Band 6.0-6.5"),
    ("atmosphere", "noun", "air around earth", "Polluted atmosphere.", "Band 6.0-6.5"),
    ("atom", "noun", "tiny particle", "Split the atom.", "Band 6.0-6.5"),
    ("attachment", "noun", "connection", "Email attachment.", "Band 6.0-6.5"),
    ("attack", "noun", "assault", "Cyber attack.", "Band 4.5-5.5"),
    ("attainment", "noun", "achievement", "Educational attainment.", "Band 8.0+"),
    ("attempt", "noun", "try", "First attempt.", "Band 4.5-5.5"),
    ("attendance", "noun", "presence", "School attendance.", "Band 6.0-6.5"),
    ("attention", "noun", "focus", "Pay attention.", "Band 4.5-5.5"),
    ("attraction", "noun", "appeal", "Tourist attraction.", "Band 6.0-6.5"),
    ("auction", "noun", "public sale", "Art auction.", "Band 7.0-7.5"),
    ("audience", "noun", "spectators", "Large audience.", "Band 6.0-6.5"),
    ("audit", "noun", "official examination", "Financial audit.", "Band 7.0-7.5"),
    ("authenticity", "noun", "genuineness", "Verify authenticity.", "Band 8.0+"),
    ("authorization", "noun", "permission", "Get authorization.", "Band 7.0-7.5"),
    ("automation", "noun", "automatic operation", "Factory automation.", "Band 7.0-7.5"),
    ("autonomy", "noun", "independence", "Regional autonomy.", "Band 8.0+"),
    ("availability", "noun", "being available", "Check availability.", "Band 6.0-6.5"),
    ("avenue", "noun", "road", "Main avenue.", "Band 6.0-6.5"),
    ("average", "noun", "typical amount", "Above average.", "Band 4.5-5.5"),
    ("aviation", "noun", "flying", "Aviation industry.", "Band 7.0-7.5"),
    ("awareness", "noun", "knowledge", "Raise awareness.", "Band 6.0-6.5"),
    ("bachelor", "noun", "unmarried man", "Bachelor's degree.", "Band 6.0-6.5"),
    ("background", "noun", "history", "Educational background.", "Band 6.0-6.5"),
    ("bacteria", "noun", "microorganisms", "Harmful bacteria.", "Band 6.0-6.5"),
    ("badge", "noun", "emblem", "Security badge.", "Band 6.0-6.5"),
    ("balance", "noun", "equilibrium", "Work-life balance.", "Band 6.0-6.5"),
    ("ballot", "noun", "vote", "Secret ballot.", "Band 7.0-7.5"),
    ("ban", "noun", "prohibition", "Smoking ban.", "Band 6.0-6.5"),
    ("bandwidth", "noun", "data capacity", "Limited bandwidth.", "Band 7.0-7.5"),
    ("bankruptcy", "noun", "financial failure", "Declare bankruptcy.", "Band 7.0-7.5"),
    ("banner", "noun", "flag", "Advertising banner.", "Band 6.0-6.5"),
    ("bargain", "noun", "deal", "Good bargain.", "Band 6.0-6.5"),
    ("barrier", "noun", "obstacle", "Language barrier.", "Band 6.0-6.5"),
    ("baseline", "noun", "starting point", "Establish a baseline.", "Band 8.0+"),
    ("basin", "noun", "bowl", "River basin.", "Band 6.0-6.5"),
    ("batch", "noun", "group", "First batch.", "Band 6.0-6.5"),
    ("battlefield", "noun", "combat area", "On the battlefield.", "Band 7.0-7.5"),
    ("beast", "noun", "animal", "Wild beast.", "Band 6.0-6.5"),
    ("behalf", "noun", "interest", "On behalf of.", "Band 6.0-6.5"),
    ("behavioral", "adjective", "relating to behavior", "Behavioral change.", "Band 7.0-7.5"),
    ("believer", "noun", "person who believes", "True believer.", "Band 6.0-6.5"),
    ("belongings", "noun", "possessions", "Personal belongings.", "Band 6.0-6.5"),
    ("benchmark", "noun", "standard", "Industry benchmark.", "Band 8.0+"),
    ("beneficiary", "noun", "recipient", "Main beneficiary.", "Band 8.0+"),
    ("beverage", "noun", "drink", "Hot beverage.", "Band 6.0-6.5"),
    ("bias", "noun", "prejudice", "Media bias.", "Band 7.0-7.5"),
    ("bibliography", "noun", "list of sources", "Include bibliography.", "Band 8.0+"),
    ("billion", "noun", "one thousand million", "Billions of dollars.", "Band 6.0-6.5"),
    ("biography", "noun", "life story", "Read the biography.", "Band 6.0-6.5"),
    ("biology", "noun", "study of life", "Study biology.", "Band 6.0-6.5"),
    ("blade", "noun", "sharp edge", "Knife blade.", "Band 6.0-6.5"),
    ("blame", "noun", "responsibility", "Take the blame.", "Band 6.0-6.5"),
    ("blast", "noun", "explosion", "Bomb blast.", "Band 6.0-6.5"),
    ("blessing", "noun", "approval", "A blessing in disguise.", "Band 6.0-6.5"),
    ("blindness", "noun", "inability to see", "Color blindness.", "Band 6.0-6.5"),
    ("blockage", "noun", "obstruction", "Traffic blockage.", "Band 7.0-7.5"),
    ("blueprint", "noun", "plan", "Project blueprint.", "Band 7.0-7.5"),
    ("board", "noun", "committee", "Board of directors.", "Band 6.0-6.5"),
    ("boom", "noun", "rapid growth", "Economic boom.", "Band 7.0-7.5"),
    ("boost", "noun", "increase", "Confidence boost.", "Band 6.0-6.5"),
    ("border", "noun", "boundary", "National border.", "Band 6.0-6.5"),
    ("boredom", "noun", "tedium", "Fight boredom.", "Band 6.0-6.5"),
    ("boundary", "noun", "limit", "Set boundaries.", "Band 6.0-6.5"),
    ("brand", "noun", "trademark", "Famous brand.", "Band 6.0-6.5"),
    ("breach", "noun", "violation", "Security breach.", "Band 7.0-7.5"),
    ("breakdown", "noun", "failure", "Communication breakdown.", "Band 6.0-6.5"),
    ("breakthrough", "noun", "major advance", "Scientific breakthrough.", "Band 7.0-7.5"),
    ("breeding", "noun", "reproduction", "Animal breeding.", "Band 7.0-7.5"),
    ("bribe", "noun", "corrupt payment", "Accept a bribe.", "Band 7.0-7.5"),
    ("broadcast", "noun", "transmission", "Live broadcast.", "Band 6.0-6.5"),
    ("brochure", "noun", "pamphlet", "Travel brochure.", "Band 6.0-6.5"),
    ("broker", "noun", "agent", "Stock broker.", "Band 7.0-7.5"),
    ("browser", "noun", "web program", "Internet browser.", "Band 6.0-6.5"),
    ("budget", "noun", "financial plan", "Tight budget.", "Band 6.0-6.5"),
    ("buffer", "noun", "cushion", "Buffer zone.", "Band 7.0-7.5"),
    ("bulk", "noun", "large quantity", "In bulk.", "Band 6.0-6.5"),
    ("bulletin", "noun", "news report", "News bulletin.", "Band 7.0-7.5"),
    ("burden", "noun", "load", "Heavy burden.", "Band 6.0-6.5"),
    ("bureaucracy", "noun", "administrative system", "Government bureaucracy.", "Band 8.0+"),
    ("burial", "noun", "interment", "Burial ceremony.", "Band 7.0-7.5"),
    ("cabinet", "noun", "government ministers", "Cabinet meeting.", "Band 7.0-7.5"),
    ("calculation", "noun", "computation", "Quick calculation.", "Band 6.0-6.5"),
    ("calendar", "noun", "date system", "Check the calendar.", "Band 4.5-5.5"),
    ("caliber", "noun", "quality", "High caliber.", "Band 8.0+"),
    ("campaign", "noun", "organized effort", "Election campaign.", "Band 6.0-6.5"),
    ("campus", "noun", "university grounds", "On campus.", "Band 6.0-6.5"),
    ("candidate", "noun", "applicant", "Job candidate.", "Band 6.0-6.5"),
    ("capability", "noun", "ability", "Technical capability.", "Band 7.0-7.5"),
    ("capitalism", "noun", "economic system", "Global capitalism.", "Band 8.0+"),
    ("captain", "noun", "leader", "Team captain.", "Band 4.5-5.5"),
    ("caption", "noun", "title", "Photo caption.", "Band 6.0-6.5"),
    ("capture", "verb", "to catch", "Capture the moment.", "Band 6.0-6.5"),
    ("carbon", "noun", "chemical element", "Carbon emissions.", "Band 6.0-6.5"),
    ("career", "noun", "profession", "Career path.", "Band 6.0-6.5"),
    ("cargo", "noun", "goods", "Ship cargo.", "Band 6.0-6.5"),
    ("carrier", "noun", "transporter", "Mail carrier.", "Band 6.0-6.5"),
    ("carriage", "noun", "vehicle", "Train carriage.", "Band 6.0-6.5"),
    ("casualty", "noun", "victim", "War casualty.", "Band 7.0-7.5"),
    ("catalog", "noun", "list", "Product catalog.", "Band 6.0-6.5"),
    ("catastrophe", "noun", "disaster", "Natural catastrophe.", "Band 7.0-7.5"),
    ("caution", "noun", "care", "Exercise caution.", "Band 6.0-6.5"),
    ("celebrity", "noun", "famous person", "Hollywood celebrity.", "Band 6.0-6.5"),
    ("cell", "noun", "basic unit", "Body cell.", "Band 6.0-6.5"),
    ("cemetery", "noun", "burial ground", "Old cemetery.", "Band 6.0-6.5"),
    ("census", "noun", "population count", "National census.", "Band 7.0-7.5"),
    ("ceremony", "noun", "formal event", "Wedding ceremony.", "Band 6.0-6.5"),
    ("certificate", "noun", "official document", "Birth certificate.", "Band 6.0-6.5"),
    ("chain", "noun", "series", "Supply chain.", "Band 6.0-6.5"),
    ("chair", "noun", "chairperson", "Committee chair.", "Band 6.0-6.5"),
    ("chamber", "noun", "room", "Council chamber.", "Band 7.0-7.5"),
    ("champion", "noun", "winner", "World champion.", "Band 6.0-6.5"),
    ("championship", "noun", "competition", "Win the championship.", "Band 6.0-6.5"),
    ("chaos", "noun", "disorder", "Complete chaos.", "Band 7.0-7.5"),
    ("characteristic", "noun", "feature", "Key characteristic.", "Band 6.0-6.5"),
    ("charity", "noun", "organization for help", "Donate to charity.", "Band 6.0-6.5"),
    ("charter", "noun", "document", "Company charter.", "Band 7.0-7.5"),
    ("chemist", "noun", "scientist", "Research chemist.", "Band 6.0-6.5"),
    ("chemistry", "noun", "science of substances", "Study chemistry.", "Band 6.0-6.5"),
    ("childhood", "noun", "early years", "Happy childhood.", "Band 6.0-6.5"),
    ("chip", "noun", "small piece", "Computer chip.", "Band 6.0-6.5"),
    ("cholesterol", "noun", "fatty substance", "High cholesterol.", "Band 7.0-7.5"),
    ("chunk", "noun", "piece", "Large chunk.", "Band 6.0-6.5"),
    ("circuit", "noun", "path", "Electric circuit.", "Band 6.0-6.5"),
    ("circulation", "noun", "movement", "Blood circulation.", "Band 7.0-7.5"),
    ("citizenship", "noun", "nationality", "Apply for citizenship.", "Band 7.0-7.5"),
    ("civilization", "noun", "advanced society", "Ancient civilization.", "Band 6.0-6.5"),
    ("claim", "noun", "assertion", "Make a claim.", "Band 6.0-6.5"),
    ("clarity", "noun", "clearness", "For clarity.", "Band 7.0-7.5"),
    ("clash", "noun", "conflict", "Culture clash.", "Band 7.0-7.5"),
    ("classification", "noun", "categorization", "Data classification.", "Band 7.0-7.5"),
    ("classroom", "noun", "learning room", "In the classroom.", "Band 4.5-5.5"),
    ("clerk", "noun", "office worker", "Bank clerk.", "Band 6.0-6.5"),
    ("click", "noun", "pressing", "Mouse click.", "Band 4.5-5.5"),
    ("client", "noun", "customer", "New client.", "Band 6.0-6.5"),
    ("cliff", "noun", "steep rock", "High cliff.", "Band 6.0-6.5"),
    ("climate", "noun", "weather pattern", "Climate change.", "Band 6.0-6.5"),
    ("climax", "noun", "peak", "Reach the climax.", "Band 7.0-7.5"),
    ("clinic", "noun", "medical center", "Health clinic.", "Band 6.0-6.5"),
    ("closure", "noun", "closing", "Factory closure.", "Band 7.0-7.5"),
    ("cloth", "noun", "fabric", "Cleaning cloth.", "Band 4.5-5.5"),
    ("clothing", "noun", "garments", "Winter clothing.", "Band 4.5-5.5"),
    ("cluster", "noun", "group", "Star cluster.", "Band 7.0-7.5"),
    ("coalition", "noun", "alliance", "Government coalition.", "Band 8.0+"),
    ("coastal", "adjective", "near the sea", "Coastal area.", "Band 6.0-6.5"),
    ("cocktail", "noun", "mixed drink", "Cocktail party.", "Band 6.0-6.5"),
    ("coefficient", "noun", "numerical factor", "Correlation coefficient.", "Band 8.0+"),
    ("coexistence", "noun", "living together", "Peaceful coexistence.", "Band 8.0+"),
    ("cognition", "noun", "mental process", "Human cognition.", "Band 8.0+"),
    ("cognitive", "adjective", "mental", "Cognitive ability.", "Band 8.0+"),
    ("coincidence", "noun", "chance occurrence", "Strange coincidence.", "Band 7.0-7.5"),
    ("collaboration", "noun", "working together", "Close collaboration.", "Band 7.0-7.5"),
    ("colleague", "noun", "coworker", "Office colleague.", "Band 6.0-6.5"),
    ("collection", "noun", "gathering", "Art collection.", "Band 6.0-6.5"),
    ("collision", "noun", "crash", "Car collision.", "Band 7.0-7.5"),
    ("colony", "noun", "settlement", "British colony.", "Band 7.0-7.5"),
    ("column", "noun", "pillar", "Newspaper column.", "Band 6.0-6.5"),
    ("combat", "noun", "fighting", "Armed combat.", "Band 7.0-7.5"),
    ("combination", "noun", "mixture", "Winning combination.", "Band 6.0-6.5"),
    ("comedy", "noun", "humorous work", "Stand-up comedy.", "Band 6.0-6.5"),
    ("comfort", "noun", "ease", "Physical comfort.", "Band 4.5-5.5"),
    ("commander", "noun", "leader", "Military commander.", "Band 7.0-7.5"),
    ("commentary", "noun", "explanation", "Expert commentary.", "Band 7.0-7.5"),
    ("commerce", "noun", "trade", "E-commerce.", "Band 7.0-7.5"),
    ("commissioner", "noun", "official", "Police commissioner.", "Band 7.0-7.5"),
    ("commitment", "noun", "dedication", "Strong commitment.", "Band 6.0-6.5"),
    ("committee", "noun", "group", "Organizing committee.", "Band 6.0-6.5"),
    ("commonwealth", "noun", "nation group", "Commonwealth countries.", "Band 8.0+"),
    ("communication", "noun", "exchange of information", "Effective communication.", "Band 6.0-6.5"),
    ("communism", "noun", "political system", "Fall of communism.", "Band 8.0+"),
    ("companion", "noun", "friend", "Traveling companion.", "Band 6.0-6.5"),
    ("comparison", "noun", "contrast", "Make a comparison.", "Band 6.0-6.5"),
    ("compassion", "noun", "sympathy", "Show compassion.", "Band 7.0-7.5"),
    ("compensation", "noun", "payment", "Financial compensation.", "Band 7.0-7.5"),
    ("competence", "noun", "ability", "Professional competence.", "Band 7.0-7.5"),
    ("competition", "noun", "contest", "Fierce competition.", "Band 6.0-6.5"),
    ("competitor", "noun", "rival", "Main competitor.", "Band 6.0-6.5"),
    ("complaint", "noun", "criticism", "File a complaint.", "Band 6.0-6.5"),
    ("complexity", "noun", "complication", "Reduce complexity.", "Band 7.0-7.5"),
    ("compliance", "noun", "obedience", "Legal compliance.", "Band 8.0+"),
    ("complication", "noun", "difficulty", "Medical complication.", "Band 7.0-7.5"),
    ("composer", "noun", "music writer", "Famous composer.", "Band 6.0-6.5"),
    ("composition", "noun", "makeup", "Chemical composition.", "Band 7.0-7.5"),
    ("compromise", "noun", "settlement", "Reach a compromise.", "Band 7.0-7.5"),
    ("computer", "noun", "electronic device", "Personal computer.", "Band 4.5-5.5"),
    ("concentration", "noun", "focus", "Lose concentration.", "Band 6.0-6.5"),
    ("conception", "noun", "idea", "Original conception.", "Band 8.0+"),
    ("concern", "noun", "worry", "Growing concern.", "Band 6.0-6.5"),
    ("concert", "noun", "music performance", "Live concert.", "Band 4.5-5.5"),
    ("conclusion", "noun", "end", "In conclusion.", "Band 6.0-6.5"),
    ("concrete", "adjective", "definite", "Concrete evidence.", "Band 7.0-7.5"),
    ("condition", "noun", "state", "Good condition.", "Band 6.0-6.5"),
    ("conductor", "noun", "leader", "Orchestra conductor.", "Band 6.0-6.5"),
    ("conference", "noun", "meeting", "International conference.", "Band 6.0-6.5"),
    ("confession", "noun", "admission", "Make a confession.", "Band 7.0-7.5"),
    ("confidence", "noun", "self-assurance", "Build confidence.", "Band 6.0-6.5"),
    ("configuration", "noun", "arrangement", "System configuration.", "Band 8.0+"),
    ("confinement", "noun", "restriction", "Solitary confinement.", "Band 8.0+"),
    ("confirmation", "noun", "verification", "Booking confirmation.", "Band 6.0-6.5"),
    ("confrontation", "noun", "conflict", "Avoid confrontation.", "Band 7.0-7.5"),
    ("confusion", "noun", "bewilderment", "Cause confusion.", "Band 6.0-6.5"),
    ("congestion", "noun", "overcrowding", "Traffic congestion.", "Band 7.0-7.5"),
    ("conjunction", "noun", "combination", "In conjunction with.", "Band 7.0-7.5"),
    ("connection", "noun", "link", "Internet connection.", "Band 6.0-6.5"),
    ("connotation", "noun", "implied meaning", "Negative connotation.", "Band 8.0+"),
    ("conscience", "noun", "moral sense", "Clear conscience.", "Band 7.0-7.5"),
    ("consciousness", "noun", "awareness", "Lose consciousness.", "Band 7.0-7.5"),
    ("consensus", "noun", "agreement", "Reach consensus.", "Band 7.0-7.5"),
    ("consequence", "noun", "result", "Serious consequence.", "Band 6.0-6.5"),
    ("conservation", "noun", "preservation", "Wildlife conservation.", "Band 7.0-7.5"),
    ("consistency", "noun", "uniformity", "Maintain consistency.", "Band 7.0-7.5"),
    ("consolidation", "noun", "strengthening", "Market consolidation.", "Band 8.0+"),
    ("conspiracy", "noun", "secret plan", "Conspiracy theory.", "Band 8.0+"),
    ("constraint", "noun", "limitation", "Budget constraint.", "Band 7.0-7.5"),
    ("construction", "noun", "building", "Under construction.", "Band 6.0-6.5"),
    ("consultant", "noun", "advisor", "Business consultant.", "Band 6.0-6.5"),
    ("consultation", "noun", "discussion", "Public consultation.", "Band 7.0-7.5"),
    ("consumer", "noun", "buyer", "Consumer rights.", "Band 6.0-6.5"),
    ("consumption", "noun", "using up", "Energy consumption.", "Band 7.0-7.5"),
    ("container", "noun", "holder", "Shipping container.", "Band 6.0-6.5"),
    ("contamination", "noun", "pollution", "Water contamination.", "Band 7.0-7.5"),
    ("contempt", "noun", "scorn", "Show contempt.", "Band 8.0+"),
    ("content", "noun", "substance", "Online content.", "Band 6.0-6.5"),
    ("contestant", "noun", "competitor", "Quiz contestant.", "Band 6.0-6.5"),
    ("continent", "noun", "large landmass", "African continent.", "Band 6.0-6.5"),
    ("contingency", "noun", "possibility", "Contingency plan.", "Band 8.0+"),
    ("continuity", "noun", "unbroken sequence", "Ensure continuity.", "Band 8.0+"),
    ("contractor", "noun", "builder", "Building contractor.", "Band 6.0-6.5"),
    ("contradiction", "noun", "inconsistency", "Direct contradiction.", "Band 7.0-7.5"),
    ("contribution", "noun", "gift", "Valuable contribution.", "Band 6.0-6.5"),
    ("controversy", "noun", "dispute", "Political controversy.", "Band 7.0-7.5"),
    ("convenience", "noun", "ease", "For convenience.", "Band 6.0-6.5"),
    ("convention", "noun", "custom", "Social convention.", "Band 7.0-7.5"),
    ("conversation", "noun", "talk", "Have a conversation.", "Band 4.5-5.5"),
    ("conversion", "noun", "change", "Currency conversion.", "Band 7.0-7.5"),
    ("conviction", "noun", "belief", "Strong conviction.", "Band 7.0-7.5"),
    ("cooperation", "noun", "collaboration", "International cooperation.", "Band 6.0-6.5"),
    ("coordination", "noun", "organization", "Better coordination.", "Band 7.0-7.5"),
    ("copyright", "noun", "legal right", "Copyright law.", "Band 7.0-7.5"),
    ("corporation", "noun", "company", "Large corporation.", "Band 6.0-6.5"),
    ("correlation", "noun", "connection", "Strong correlation.", "Band 8.0+"),
    ("correspondence", "noun", "letters", "Business correspondence.", "Band 7.0-7.5"),
    ("corridor", "noun", "hallway", "Long corridor.", "Band 6.0-6.5"),
    ("corruption", "noun", "dishonesty", "Political corruption.", "Band 7.0-7.5"),
    ("costume", "noun", "outfit", "Halloween costume.", "Band 6.0-6.5"),
    ("cottage", "noun", "small house", "Country cottage.", "Band 6.0-6.5"),
    ("council", "noun", "assembly", "City council.", "Band 6.0-6.5"),
    ("counseling", "noun", "guidance", "Career counseling.", "Band 7.0-7.5"),
    ("counterpart", "noun", "equivalent", "Foreign counterpart.", "Band 8.0+"),
    ("countless", "adjective", "many", "Countless opportunities.", "Band 6.0-6.5"),
    ("countryside", "noun", "rural area", "Beautiful countryside.", "Band 6.0-6.5"),
    ("county", "noun", "region", "Local county.", "Band 6.0-6.5"),
    ("courage", "noun", "bravery", "Show courage.", "Band 6.0-6.5"),
    ("courier", "noun", "messenger", "Courier service.", "Band 6.0-6.5"),
    ("courtesy", "noun", "politeness", "Common courtesy.", "Band 7.0-7.5"),
    ("coverage", "noun", "reporting", "Media coverage.", "Band 6.0-6.5"),
    ("craft", "noun", "skill", "Traditional craft.", "Band 6.0-6.5"),
    ("crash", "noun", "collision", "Market crash.", "Band 6.0-6.5"),
    ("creation", "noun", "making", "Job creation.", "Band 6.0-6.5"),
    ("creativity", "noun", "imagination", "Encourage creativity.", "Band 6.0-6.5"),
    ("creature", "noun", "living thing", "Sea creature.", "Band 6.0-6.5"),
    ("credibility", "noun", "believability", "Damage credibility.", "Band 8.0+"),
    ("creek", "noun", "small stream", "Mountain creek.", "Band 6.0-6.5"),
    ("crew", "noun", "team", "Film crew.", "Band 6.0-6.5"),
    ("crime", "noun", "offense", "Violent crime.", "Band 6.0-6.5"),
    ("criminal", "noun", "offender", "Convicted criminal.", "Band 6.0-6.5"),
    ("crisis", "noun", "emergency", "Financial crisis.", "Band 6.0-6.5"),
    ("criterion", "noun", "standard", "Main criterion.", "Band 7.0-7.5"),
    ("critic", "noun", "reviewer", "Film critic.", "Band 6.0-6.5"),
    ("criticism", "noun", "disapproval", "Constructive criticism.", "Band 6.0-6.5"),
    ("crop", "noun", "harvest", "Cash crop.", "Band 6.0-6.5"),
    ("crowd", "noun", "large group", "Huge crowd.", "Band 4.5-5.5"),
    ("cruise", "noun", "voyage", "Caribbean cruise.", "Band 6.0-6.5"),
    ("crystal", "noun", "clear mineral", "Crystal clear.", "Band 6.0-6.5"),
    ("cuisine", "noun", "cooking style", "French cuisine.", "Band 7.0-7.5"),
    ("cult", "noun", "religious group", "Cult following.", "Band 8.0+"),
    ("cultivation", "noun", "growing", "Land cultivation.", "Band 7.0-7.5"),
    ("curiosity", "noun", "desire to know", "Natural curiosity.", "Band 6.0-6.5"),
    ("curriculum", "noun", "course of study", "School curriculum.", "Band 7.0-7.5"),
    ("custody", "noun", "care", "Child custody.", "Band 7.0-7.5"),
    ("custom", "noun", "tradition", "Local custom.", "Band 6.0-6.5"),
    ("customer", "noun", "buyer", "Loyal customer.", "Band 4.5-5.5"),
    ("cylinder", "noun", "tube shape", "Gas cylinder.", "Band 7.0-7.5"),
]

def translate_batch(texts, target_lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={GOOGLE_API_KEY}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            resp = requests.post(url, json={"q": batch, "source": "en", "target": target_lang}, timeout=30)
            if resp.status_code == 200:
                result.extend([t['translatedText'] for t in resp.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

def main():
    with open('assets/data/words.json', 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    existing = {w['word'].lower() for w in words}
    start_id = max(w['id'] for w in words) + 1
    categories = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
    
    new_words = []
    for word, pos, definition, example, level in WORDS_PART3:
        if word.lower() not in existing:
            new_words.append({
                "id": start_id + len(new_words),
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": categories[(start_id + len(new_words)) % len(categories)]
            })
            existing.add(word.lower())
    
    print(f"새 단어: {len(new_words)}개")
    
    if new_words:
        defs = [w['definition'] for w in new_words]
        exs = [w['example'] for w in new_words]
        
        for lang in LANGUAGES:
            print(f"{lang} 번역중...")
            trans_defs = translate_batch(defs, lang)
            trans_exs = translate_batch(exs, lang)
            for i, w in enumerate(new_words):
                if 'translations' not in w:
                    w['translations'] = {}
                w['translations'][lang] = {
                    'definition': trans_defs[i],
                    'example': trans_exs[i]
                }
        
        words.extend(new_words)
        with open('assets/data/words.json', 'w', encoding='utf-8') as f:
            json.dump(words, f, ensure_ascii=False, indent=2)
    
    print(f"총: {len(words)}개")

if __name__ == "__main__":
    main()
