#!/usr/bin/env python3
"""IELTS 새 단어 추가 - 500개씩 배치"""
import json

# IELTS 고급 단어 리스트 (Band별)
NEW_WORDS_BAND45 = [
    ("ability", "noun", "the power to do something", "She has the ability to succeed."),
    ("abroad", "adverb", "in a foreign country", "He studied abroad for two years."),
    ("absence", "noun", "the state of being away", "His absence was noticed."),
    ("absolute", "adjective", "complete and total", "It was an absolute disaster."),
    ("absorb", "verb", "to take in", "Plants absorb sunlight."),
    ("abstract", "adjective", "existing in thought only", "Abstract art is hard to understand."),
    ("abundant", "adjective", "existing in large quantities", "Water is abundant here."),
    ("academic", "adjective", "relating to education", "Academic success is important."),
    ("accelerate", "verb", "to increase speed", "The car accelerated quickly."),
    ("accent", "noun", "way of pronouncing words", "She has a British accent."),
    ("acceptable", "adjective", "able to be agreed on", "The offer was acceptable."),
    ("accessible", "adjective", "able to be reached", "The building is wheelchair accessible."),
    ("accident", "noun", "unexpected event", "There was a car accident."),
    ("accommodate", "verb", "to provide space for", "The hotel can accommodate 200 guests."),
    ("accompany", "verb", "to go with someone", "I will accompany you to the station."),
    ("accomplish", "verb", "to complete successfully", "She accomplished her goals."),
    ("according", "preposition", "as stated by", "According to the report, sales increased."),
    ("account", "noun", "a record of money", "Open a bank account."),
    ("accurate", "adjective", "correct and exact", "The data is accurate."),
    ("accuse", "verb", "to say someone did wrong", "They accused him of lying."),
    ("acquire", "verb", "to get or obtain", "She acquired new skills."),
    ("adapt", "verb", "to adjust to new conditions", "Animals adapt to their environment."),
    ("addition", "noun", "something added", "In addition to that, we need more time."),
    ("address", "verb", "to speak to", "The president will address the nation."),
    ("adequate", "adjective", "enough for a purpose", "The food supply is adequate."),
    ("adjust", "verb", "to change slightly", "Adjust the settings."),
    ("administration", "noun", "management of affairs", "The hospital administration made changes."),
    ("admire", "verb", "to respect and approve", "I admire her courage."),
    ("adolescent", "noun", "a young person", "Adolescents face many challenges."),
    ("adopt", "verb", "to take as one's own", "They decided to adopt a child."),
    ("adult", "noun", "a fully grown person", "Adults must be responsible."),
    ("advance", "verb", "to move forward", "Technology continues to advance."),
    ("advantage", "noun", "a favorable condition", "Education gives you an advantage."),
    ("adventure", "noun", "an exciting experience", "Life is an adventure."),
    ("advertise", "verb", "to promote publicly", "Companies advertise on TV."),
    ("advice", "noun", "recommendation", "Take my advice seriously."),
    ("advise", "verb", "to give suggestions", "I advise you to study harder."),
    ("advocate", "verb", "to support publicly", "She advocates for human rights."),
    ("affair", "noun", "a matter or concern", "It's a private affair."),
    ("afford", "verb", "to have enough money", "I can't afford a new car."),
    ("afraid", "adjective", "feeling fear", "Don't be afraid of failure."),
    ("agency", "noun", "an organization", "The travel agency helped us."),
    ("agenda", "noun", "a list of items to discuss", "What's on the agenda today?"),
    ("agent", "noun", "a person who acts for another", "The real estate agent called."),
    ("aggressive", "adjective", "ready to attack", "He has an aggressive attitude."),
    ("agree", "verb", "to have the same opinion", "I agree with you completely."),
    ("agriculture", "noun", "farming", "Agriculture is vital to the economy."),
    ("aid", "noun", "help or support", "Foreign aid was sent to the region."),
    ("aim", "verb", "to intend", "We aim to finish by Friday."),
    ("aircraft", "noun", "a flying vehicle", "The aircraft landed safely."),
]

NEW_WORDS_BAND60 = [
    ("albeit", "conjunction", "although", "He accepted, albeit reluctantly."),
    ("allocate", "verb", "to distribute for a purpose", "Funds were allocated to education."),
    ("alter", "verb", "to change", "We need to alter our plans."),
    ("alternative", "noun", "another option", "There is no alternative."),
    ("ambiguous", "adjective", "having multiple meanings", "The statement was ambiguous."),
    ("amend", "verb", "to make changes to", "They amended the constitution."),
    ("analogy", "noun", "a comparison", "He drew an analogy between the two cases."),
    ("anticipate", "verb", "to expect", "We anticipate strong demand."),
    ("apparent", "adjective", "clearly visible", "The solution was apparent."),
    ("append", "verb", "to add at the end", "Append your signature here."),
    ("appreciate", "verb", "to recognize value", "I appreciate your help."),
    ("approach", "noun", "a way of dealing with", "We need a new approach."),
    ("appropriate", "adjective", "suitable", "Choose appropriate clothing."),
    ("approximate", "adjective", "close but not exact", "The approximate cost is $500."),
    ("arbitrary", "adjective", "based on random choice", "The decision seemed arbitrary."),
    ("area", "noun", "a region or space", "This area is restricted."),
    ("aspect", "noun", "a particular part", "Consider every aspect of the problem."),
    ("assemble", "verb", "to gather together", "Students assembled in the hall."),
    ("assess", "verb", "to evaluate", "We need to assess the damage."),
    ("asset", "noun", "a useful thing", "Her skills are an asset to the team."),
    ("assign", "verb", "to give a task", "The teacher assigned homework."),
    ("assist", "verb", "to help", "Can I assist you with anything?"),
    ("assume", "verb", "to suppose", "I assume you know the rules."),
    ("assure", "verb", "to tell confidently", "I assure you it's safe."),
    ("attach", "verb", "to fasten or join", "Attach the file to the email."),
    ("attain", "verb", "to achieve", "She attained her goals."),
    ("attitude", "noun", "a way of thinking", "He has a positive attitude."),
    ("attribute", "verb", "to credit to", "Success is attributed to hard work."),
    ("author", "noun", "a writer", "The author signed copies of the book."),
    ("authority", "noun", "the power to give orders", "The police have authority here."),
    ("automate", "verb", "to make automatic", "We should automate this process."),
    ("available", "adjective", "able to be used", "Is this seat available?"),
    ("aware", "adjective", "having knowledge", "Are you aware of the risks?"),
    ("behalf", "noun", "in the interest of", "I speak on behalf of the team."),
    ("benefit", "noun", "an advantage", "Exercise has many benefits."),
    ("bias", "noun", "unfair preference", "The report showed bias."),
    ("bond", "noun", "a connection", "They formed a strong bond."),
    ("brief", "adjective", "short in duration", "I'll be brief."),
    ("bulk", "noun", "large quantity", "Buy in bulk to save money."),
    ("capable", "adjective", "having ability", "She is capable of great things."),
    ("capacity", "noun", "the ability to contain", "The stadium has a capacity of 50,000."),
    ("category", "noun", "a class or group", "Which category does it belong to?"),
    ("cease", "verb", "to stop", "Hostilities must cease immediately."),
    ("challenge", "noun", "a difficult task", "This is a real challenge."),
    ("channel", "noun", "a medium for communication", "Use official channels."),
    ("chapter", "noun", "a section of a book", "Read chapter five."),
    ("chart", "noun", "a diagram", "The chart shows the data."),
    ("chemical", "noun", "a substance", "Avoid harmful chemicals."),
    ("circumstance", "noun", "a condition", "Under the circumstances, we agreed."),
    ("cite", "verb", "to quote as evidence", "Cite your sources properly."),
]

NEW_WORDS_BAND70 = [
    ("clarify", "verb", "to make clear", "Please clarify your position."),
    ("classic", "adjective", "of highest quality", "It's a classic example."),
    ("clause", "noun", "a part of a sentence", "Add a conditional clause."),
    ("code", "noun", "a system of rules", "Follow the dress code."),
    ("coherent", "adjective", "logical and consistent", "Make a coherent argument."),
    ("coincide", "verb", "to occur at the same time", "Our vacations coincide."),
    ("collapse", "verb", "to fall down suddenly", "The building collapsed."),
    ("colleague", "noun", "a coworker", "My colleague helped me."),
    ("commence", "verb", "to begin", "The ceremony will commence at noon."),
    ("comment", "noun", "a remark", "Do you have any comments?"),
    ("commission", "noun", "a group given authority", "The commission investigated."),
    ("commit", "verb", "to pledge or do", "Commit to your goals."),
    ("commodity", "noun", "a raw material", "Oil is a valuable commodity."),
    ("communicate", "verb", "to share information", "We need to communicate better."),
    ("community", "noun", "a group of people", "The local community helped."),
    ("compatible", "adjective", "able to exist together", "The devices are compatible."),
    ("compensate", "verb", "to make up for", "We will compensate for the loss."),
    ("compile", "verb", "to collect and assemble", "Compile the data into a report."),
    ("complement", "verb", "to complete", "The colors complement each other."),
    ("complex", "adjective", "complicated", "It's a complex issue."),
    ("component", "noun", "a part of something", "Each component is essential."),
    ("compound", "noun", "a combination", "Water is a chemical compound."),
    ("comprehensive", "adjective", "including everything", "We need a comprehensive review."),
    ("comprise", "verb", "to consist of", "The team comprises five members."),
    ("compute", "verb", "to calculate", "Compute the total cost."),
    ("conceive", "verb", "to form an idea", "She conceived a brilliant plan."),
    ("concentrate", "verb", "to focus attention", "Concentrate on your studies."),
    ("concept", "noun", "an idea", "Explain the concept clearly."),
    ("conclude", "verb", "to end or decide", "We concluded the meeting."),
    ("concurrent", "adjective", "happening at the same time", "Concurrent sessions were held."),
    ("conduct", "verb", "to carry out", "Conduct the experiment carefully."),
    ("confer", "verb", "to discuss", "Let me confer with my team."),
    ("confine", "verb", "to limit", "Confine your remarks to the topic."),
    ("confirm", "verb", "to verify", "Please confirm your reservation."),
    ("conflict", "noun", "a disagreement", "There was a conflict of interest."),
    ("conform", "verb", "to comply with rules", "You must conform to standards."),
    ("consent", "noun", "permission", "We need your consent."),
    ("consequent", "adjective", "following as a result", "The consequent effects were severe."),
    ("considerable", "adjective", "large in amount", "There was considerable damage."),
    ("consist", "verb", "to be made up of", "The team consists of experts."),
    ("constant", "adjective", "unchanging", "The temperature remained constant."),
    ("constitute", "verb", "to form or make up", "These factors constitute a risk."),
    ("constrain", "verb", "to restrict", "Budget constraints limited options."),
    ("construct", "verb", "to build", "Construct a strong argument."),
    ("consult", "verb", "to seek advice", "Consult a doctor if symptoms persist."),
    ("consume", "verb", "to use up", "Cars consume a lot of fuel."),
    ("contact", "noun", "communication", "Keep in contact with us."),
    ("contemporary", "adjective", "modern", "Contemporary art is innovative."),
    ("context", "noun", "circumstances", "Consider the context."),
    ("contract", "noun", "a legal agreement", "Sign the contract."),
]

NEW_WORDS_BAND80 = [
    ("contradict", "verb", "to say the opposite", "Don't contradict yourself."),
    ("contrary", "adjective", "opposite", "On the contrary, I agree."),
    ("contrast", "noun", "a difference", "The contrast is striking."),
    ("contribute", "verb", "to give or add", "Everyone should contribute."),
    ("controversy", "noun", "public disagreement", "The decision caused controversy."),
    ("convene", "verb", "to come together", "The committee will convene tomorrow."),
    ("convention", "noun", "a standard practice", "Follow the convention."),
    ("converse", "verb", "to talk", "We conversed for hours."),
    ("convert", "verb", "to change form", "Convert the file to PDF."),
    ("convince", "verb", "to persuade", "I convinced her to stay."),
    ("cooperate", "verb", "to work together", "We must cooperate to succeed."),
    ("coordinate", "verb", "to organize", "Coordinate the activities."),
    ("core", "noun", "the central part", "Get to the core of the problem."),
    ("corporate", "adjective", "relating to business", "Corporate culture is important."),
    ("correspond", "verb", "to match or communicate", "The results correspond to predictions."),
    ("couple", "noun", "two things", "A couple of issues remain."),
    ("create", "verb", "to make something new", "Create a plan."),
    ("credit", "noun", "recognition", "Give credit where it's due."),
    ("criteria", "noun", "standards for judging", "Meet the criteria."),
    ("crucial", "adjective", "extremely important", "This is a crucial decision."),
    ("culture", "noun", "shared beliefs and practices", "Understand the local culture."),
    ("currency", "noun", "money", "Exchange currency at the bank."),
    ("cycle", "noun", "a series of events", "The business cycle affects everyone."),
    ("data", "noun", "facts and statistics", "Analyze the data carefully."),
    ("debate", "noun", "a formal discussion", "The debate was heated."),
    ("decade", "noun", "ten years", "A lot changed in a decade."),
    ("decline", "verb", "to decrease", "Sales declined this quarter."),
    ("deduce", "verb", "to conclude by reasoning", "We can deduce the answer."),
    ("define", "verb", "to explain the meaning", "Define the term clearly."),
    ("definite", "adjective", "certain", "We need a definite answer."),
    ("demonstrate", "verb", "to show clearly", "Demonstrate your skills."),
    ("denote", "verb", "to indicate", "Red denotes danger."),
    ("deny", "verb", "to refuse or reject", "He denied the allegations."),
    ("depress", "verb", "to make sad", "The news depressed everyone."),
    ("derive", "verb", "to obtain from a source", "Derive meaning from context."),
    ("design", "noun", "a plan or drawing", "The design is innovative."),
    ("despite", "preposition", "in spite of", "Despite the rain, we continued."),
    ("detect", "verb", "to discover", "Detect errors in the code."),
    ("deviate", "verb", "to depart from a course", "Don't deviate from the plan."),
    ("device", "noun", "a tool or gadget", "This device saves time."),
    ("devote", "verb", "to give time or effort", "Devote yourself to learning."),
    ("differentiate", "verb", "to distinguish", "Differentiate between fact and opinion."),
    ("dimension", "noun", "a measurement", "Consider all dimensions."),
    ("diminish", "verb", "to reduce", "Interest diminished over time."),
    ("discrete", "adjective", "separate and distinct", "These are discrete categories."),
    ("discriminate", "verb", "to treat unfairly", "Don't discriminate against anyone."),
    ("displace", "verb", "to move from position", "The flood displaced thousands."),
    ("display", "verb", "to show", "Display your work proudly."),
    ("dispose", "verb", "to get rid of", "Dispose of waste properly."),
    ("distinct", "adjective", "clearly different", "There are distinct differences."),
]

def main():
    with open('assets/data/words.json', 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    existing_words = {w['word'].lower() for w in words}
    start_id = max(w['id'] for w in words) + 1
    
    categories = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
    
    new_words = []
    word_id = start_id
    
    all_new = [
        (NEW_WORDS_BAND45, "Band 4.5-5.5"),
        (NEW_WORDS_BAND60, "Band 6.0-6.5"),
        (NEW_WORDS_BAND70, "Band 7.0-7.5"),
        (NEW_WORDS_BAND80, "Band 8.0+"),
    ]
    
    for word_list, level in all_new:
        for word, pos, definition, example in word_list:
            if word.lower() not in existing_words:
                new_words.append({
                    "id": word_id,
                    "word": word,
                    "level": level,
                    "partOfSpeech": pos,
                    "definition": definition,
                    "example": example,
                    "category": categories[word_id % len(categories)]
                })
                existing_words.add(word.lower())
                word_id += 1
    
    words.extend(new_words)
    
    with open('assets/data/words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
    
    print(f"추가된 단어: {len(new_words)}개")
    print(f"총 단어 수: {len(words)}개")

if __name__ == "__main__":
    main()
