#!/usr/bin/env python3
"""IELTS 단어 대량 추가 - Part 4"""
import json
import requests
import time

GOOGLE_API_KEY = "AIzaSyCWW8OXnc7QwIUTs_W0FCEVrZEm3qliDzk"
LANGUAGES = ['ko', 'ja', 'zh', 'es', 'fr', 'de']

WORDS_PART4 = [
    ("dairy", "noun", "milk products", "Dairy products.", "Band 6.0-6.5"),
    ("damage", "noun", "harm", "Flood damage.", "Band 4.5-5.5"),
    ("database", "noun", "data collection", "Customer database.", "Band 6.0-6.5"),
    ("deadline", "noun", "time limit", "Meet the deadline.", "Band 6.0-6.5"),
    ("dealer", "noun", "seller", "Car dealer.", "Band 6.0-6.5"),
    ("dean", "noun", "university head", "Dean of students.", "Band 7.0-7.5"),
    ("debate", "noun", "discussion", "Public debate.", "Band 6.0-6.5"),
    ("debris", "noun", "wreckage", "Building debris.", "Band 7.0-7.5"),
    ("debt", "noun", "money owed", "National debt.", "Band 6.0-6.5"),
    ("decade", "noun", "ten years", "Over the decade.", "Band 6.0-6.5"),
    ("decay", "noun", "decline", "Urban decay.", "Band 7.0-7.5"),
    ("declaration", "noun", "announcement", "Official declaration.", "Band 7.0-7.5"),
    ("decline", "noun", "decrease", "Economic decline.", "Band 6.0-6.5"),
    ("decoration", "noun", "ornament", "Home decoration.", "Band 6.0-6.5"),
    ("dedication", "noun", "commitment", "Show dedication.", "Band 7.0-7.5"),
    ("deduction", "noun", "subtraction", "Tax deduction.", "Band 7.0-7.5"),
    ("deed", "noun", "action", "Good deed.", "Band 6.0-6.5"),
    ("default", "noun", "standard setting", "By default.", "Band 7.0-7.5"),
    ("defeat", "noun", "loss", "Accept defeat.", "Band 6.0-6.5"),
    ("defect", "noun", "flaw", "Manufacturing defect.", "Band 7.0-7.5"),
    ("defender", "noun", "protector", "Public defender.", "Band 6.0-6.5"),
    ("deficiency", "noun", "lack", "Vitamin deficiency.", "Band 7.0-7.5"),
    ("deficit", "noun", "shortfall", "Budget deficit.", "Band 7.0-7.5"),
    ("degradation", "noun", "deterioration", "Environmental degradation.", "Band 8.0+"),
    ("deity", "noun", "god", "Ancient deity.", "Band 8.0+"),
    ("delegation", "noun", "group of representatives", "Trade delegation.", "Band 7.0-7.5"),
    ("deliberation", "noun", "careful thought", "After much deliberation.", "Band 8.0+"),
    ("delight", "noun", "pleasure", "To my delight.", "Band 6.0-6.5"),
    ("delivery", "noun", "distribution", "Free delivery.", "Band 6.0-6.5"),
    ("delusion", "noun", "false belief", "Under the delusion.", "Band 8.0+"),
    ("democracy", "noun", "government by people", "Support democracy.", "Band 7.0-7.5"),
    ("demolition", "noun", "destruction", "Building demolition.", "Band 7.0-7.5"),
    ("demonstration", "noun", "protest", "Peaceful demonstration.", "Band 6.0-6.5"),
    ("denial", "noun", "refusal", "In denial.", "Band 7.0-7.5"),
    ("density", "noun", "thickness", "Population density.", "Band 7.0-7.5"),
    ("departure", "noun", "leaving", "Departure time.", "Band 6.0-6.5"),
    ("dependence", "noun", "reliance", "Drug dependence.", "Band 7.0-7.5"),
    ("deployment", "noun", "use", "Troop deployment.", "Band 8.0+"),
    ("deposit", "noun", "payment", "Security deposit.", "Band 6.0-6.5"),
    ("depression", "noun", "mental illness", "Clinical depression.", "Band 7.0-7.5"),
    ("deprivation", "noun", "lack", "Sleep deprivation.", "Band 8.0+"),
    ("deputy", "noun", "assistant", "Deputy director.", "Band 7.0-7.5"),
    ("derivative", "noun", "derived thing", "Financial derivative.", "Band 8.0+"),
    ("descent", "noun", "going down", "Rapid descent.", "Band 7.0-7.5"),
    ("designation", "noun", "name", "Official designation.", "Band 8.0+"),
    ("designer", "noun", "creator", "Fashion designer.", "Band 6.0-6.5"),
    ("desire", "noun", "want", "Strong desire.", "Band 6.0-6.5"),
    ("desktop", "noun", "computer screen", "Desktop computer.", "Band 6.0-6.5"),
    ("despair", "noun", "hopelessness", "In despair.", "Band 7.0-7.5"),
    ("destination", "noun", "end point", "Popular destination.", "Band 6.0-6.5"),
    ("destruction", "noun", "ruin", "Mass destruction.", "Band 6.0-6.5"),
    ("detective", "noun", "investigator", "Private detective.", "Band 6.0-6.5"),
    ("detention", "noun", "holding", "Police detention.", "Band 7.0-7.5"),
    ("deterioration", "noun", "worsening", "Health deterioration.", "Band 8.0+"),
    ("determination", "noun", "resolve", "Show determination.", "Band 6.0-6.5"),
    ("developer", "noun", "creator", "Software developer.", "Band 6.0-6.5"),
    ("deviation", "noun", "difference", "Standard deviation.", "Band 8.0+"),
    ("device", "noun", "tool", "Electronic device.", "Band 6.0-6.5"),
    ("diagnosis", "noun", "identification", "Medical diagnosis.", "Band 7.0-7.5"),
    ("diagram", "noun", "drawing", "Flow diagram.", "Band 6.0-6.5"),
    ("dialect", "noun", "regional language", "Local dialect.", "Band 7.0-7.5"),
    ("dialogue", "noun", "conversation", "Open dialogue.", "Band 6.0-6.5"),
    ("diameter", "noun", "width", "Large diameter.", "Band 6.0-6.5"),
    ("diary", "noun", "daily record", "Keep a diary.", "Band 6.0-6.5"),
    ("dictator", "noun", "absolute ruler", "Military dictator.", "Band 7.0-7.5"),
    ("dictionary", "noun", "word book", "Use a dictionary.", "Band 4.5-5.5"),
    ("diet", "noun", "food intake", "Healthy diet.", "Band 6.0-6.5"),
    ("dilemma", "noun", "difficult choice", "Ethical dilemma.", "Band 7.0-7.5"),
    ("dimension", "noun", "aspect", "New dimension.", "Band 7.0-7.5"),
    ("diminution", "noun", "decrease", "Diminution of power.", "Band 8.0+"),
    ("diplomacy", "noun", "negotiations", "International diplomacy.", "Band 8.0+"),
    ("diplomat", "noun", "ambassador", "Foreign diplomat.", "Band 7.0-7.5"),
    ("directive", "noun", "instruction", "Government directive.", "Band 8.0+"),
    ("directory", "noun", "list", "Phone directory.", "Band 6.0-6.5"),
    ("disability", "noun", "impairment", "Physical disability.", "Band 6.0-6.5"),
    ("disadvantage", "noun", "drawback", "Major disadvantage.", "Band 6.0-6.5"),
    ("disagreement", "noun", "difference of opinion", "Settle disagreement.", "Band 6.0-6.5"),
    ("disappointment", "noun", "letdown", "Great disappointment.", "Band 6.0-6.5"),
    ("disaster", "noun", "catastrophe", "Natural disaster.", "Band 6.0-6.5"),
    ("discipline", "noun", "training", "Strict discipline.", "Band 6.0-6.5"),
    ("disclaimer", "noun", "denial", "Legal disclaimer.", "Band 8.0+"),
    ("disclosure", "noun", "revelation", "Full disclosure.", "Band 8.0+"),
    ("discomfort", "noun", "unease", "Feel discomfort.", "Band 6.0-6.5"),
    ("discount", "noun", "reduction", "Special discount.", "Band 6.0-6.5"),
    ("discourse", "noun", "discussion", "Public discourse.", "Band 8.0+"),
    ("discovery", "noun", "finding", "Scientific discovery.", "Band 6.0-6.5"),
    ("discretion", "noun", "judgment", "Use discretion.", "Band 8.0+"),
    ("discrimination", "noun", "prejudice", "Racial discrimination.", "Band 7.0-7.5"),
    ("disease", "noun", "illness", "Heart disease.", "Band 6.0-6.5"),
    ("disgrace", "noun", "shame", "Public disgrace.", "Band 7.0-7.5"),
    ("disguise", "noun", "costume", "In disguise.", "Band 6.0-6.5"),
    ("disillusionment", "noun", "disappointment", "Growing disillusionment.", "Band 8.0+"),
    ("dismissal", "noun", "firing", "Unfair dismissal.", "Band 7.0-7.5"),
    ("disorder", "noun", "illness", "Eating disorder.", "Band 6.0-6.5"),
    ("disparity", "noun", "difference", "Income disparity.", "Band 8.0+"),
    ("displacement", "noun", "moving", "Population displacement.", "Band 8.0+"),
    ("disposal", "noun", "throwing away", "Waste disposal.", "Band 7.0-7.5"),
    ("disposition", "noun", "temperament", "Friendly disposition.", "Band 8.0+"),
    ("dispute", "noun", "disagreement", "Labor dispute.", "Band 7.0-7.5"),
    ("disruption", "noun", "disturbance", "Service disruption.", "Band 7.0-7.5"),
    ("dissatisfaction", "noun", "discontent", "Customer dissatisfaction.", "Band 7.0-7.5"),
    ("dissertation", "noun", "thesis", "PhD dissertation.", "Band 8.0+"),
    ("dissolution", "noun", "ending", "Dissolution of partnership.", "Band 8.0+"),
    ("distance", "noun", "space between", "Long distance.", "Band 4.5-5.5"),
    ("distinction", "noun", "difference", "Clear distinction.", "Band 7.0-7.5"),
    ("distortion", "noun", "twisting", "Image distortion.", "Band 8.0+"),
    ("distraction", "noun", "diversion", "Avoid distraction.", "Band 6.0-6.5"),
    ("distribution", "noun", "spreading", "Wealth distribution.", "Band 6.0-6.5"),
    ("district", "noun", "area", "Business district.", "Band 6.0-6.5"),
    ("disturbance", "noun", "disruption", "Public disturbance.", "Band 7.0-7.5"),
    ("diversity", "noun", "variety", "Cultural diversity.", "Band 7.0-7.5"),
    ("dividend", "noun", "share of profit", "Pay dividend.", "Band 8.0+"),
    ("division", "noun", "separation", "Division of labor.", "Band 6.0-6.5"),
    ("divorce", "noun", "marriage end", "File for divorce.", "Band 6.0-6.5"),
    ("doctrine", "noun", "belief system", "Political doctrine.", "Band 8.0+"),
    ("documentary", "noun", "factual film", "Wildlife documentary.", "Band 6.0-6.5"),
    ("documentation", "noun", "records", "Proper documentation.", "Band 7.0-7.5"),
    ("domain", "noun", "area", "Public domain.", "Band 7.0-7.5"),
    ("dominance", "noun", "control", "Market dominance.", "Band 7.0-7.5"),
    ("donation", "noun", "gift", "Blood donation.", "Band 6.0-6.5"),
    ("donor", "noun", "giver", "Organ donor.", "Band 6.0-6.5"),
    ("doom", "noun", "fate", "Sense of doom.", "Band 7.0-7.5"),
    ("doorstep", "noun", "entrance", "On the doorstep.", "Band 6.0-6.5"),
    ("dose", "noun", "amount", "High dose.", "Band 6.0-6.5"),
    ("doubt", "noun", "uncertainty", "No doubt.", "Band 4.5-5.5"),
    ("downtown", "noun", "city center", "Go downtown.", "Band 6.0-6.5"),
    ("draft", "noun", "preliminary version", "First draft.", "Band 6.0-6.5"),
    ("drainage", "noun", "water removal", "Poor drainage.", "Band 7.0-7.5"),
    ("drama", "noun", "play", "TV drama.", "Band 6.0-6.5"),
    ("drawback", "noun", "disadvantage", "Main drawback.", "Band 7.0-7.5"),
    ("drawing", "noun", "picture", "Pencil drawing.", "Band 4.5-5.5"),
    ("dread", "noun", "fear", "Fill with dread.", "Band 7.0-7.5"),
    ("drift", "noun", "movement", "Continental drift.", "Band 7.0-7.5"),
    ("drought", "noun", "dry period", "Severe drought.", "Band 7.0-7.5"),
    ("duality", "noun", "double nature", "Wave-particle duality.", "Band 8.0+"),
    ("dump", "noun", "waste site", "Garbage dump.", "Band 6.0-6.5"),
    ("duration", "noun", "length of time", "For the duration.", "Band 7.0-7.5"),
    ("dust", "noun", "fine particles", "Dust particles.", "Band 4.5-5.5"),
    ("duty", "noun", "responsibility", "Civic duty.", "Band 6.0-6.5"),
    ("dwelling", "noun", "home", "Place of dwelling.", "Band 7.0-7.5"),
    ("dynamic", "noun", "force", "Group dynamic.", "Band 7.0-7.5"),
    ("dynasty", "noun", "ruling family", "Royal dynasty.", "Band 7.0-7.5"),
    ("eagerness", "noun", "enthusiasm", "Show eagerness.", "Band 6.0-6.5"),
    ("earthquake", "noun", "seismic event", "Major earthquake.", "Band 6.0-6.5"),
    ("ecology", "noun", "study of environment", "Marine ecology.", "Band 7.0-7.5"),
    ("economist", "noun", "economy expert", "Leading economist.", "Band 7.0-7.5"),
    ("ecosystem", "noun", "environmental system", "Fragile ecosystem.", "Band 7.0-7.5"),
    ("edition", "noun", "version", "First edition.", "Band 6.0-6.5"),
    ("editor", "noun", "publication head", "Newspaper editor.", "Band 6.0-6.5"),
    ("educator", "noun", "teacher", "Professional educator.", "Band 6.0-6.5"),
    ("effectiveness", "noun", "efficiency", "Measure effectiveness.", "Band 7.0-7.5"),
    ("efficiency", "noun", "productivity", "Fuel efficiency.", "Band 6.0-6.5"),
    ("ego", "noun", "self-esteem", "Big ego.", "Band 7.0-7.5"),
    ("elaboration", "noun", "detail", "Further elaboration.", "Band 8.0+"),
    ("elasticity", "noun", "flexibility", "Price elasticity.", "Band 8.0+"),
    ("elder", "noun", "older person", "Village elder.", "Band 6.0-6.5"),
    ("election", "noun", "vote", "General election.", "Band 6.0-6.5"),
    ("electricity", "noun", "electric power", "Generate electricity.", "Band 6.0-6.5"),
    ("electronics", "noun", "electronic devices", "Consumer electronics.", "Band 6.0-6.5"),
    ("elegance", "noun", "grace", "Simple elegance.", "Band 7.0-7.5"),
    ("element", "noun", "component", "Key element.", "Band 6.0-6.5"),
    ("elevation", "noun", "height", "High elevation.", "Band 7.0-7.5"),
    ("eligibility", "noun", "qualification", "Check eligibility.", "Band 7.0-7.5"),
    ("elite", "noun", "top group", "Social elite.", "Band 7.0-7.5"),
    ("eloquence", "noun", "expressiveness", "Natural eloquence.", "Band 8.0+"),
    ("emancipation", "noun", "freedom", "Women's emancipation.", "Band 8.0+"),
    ("embargo", "noun", "trade ban", "Oil embargo.", "Band 8.0+"),
    ("embarrassment", "noun", "shame", "Public embarrassment.", "Band 6.0-6.5"),
    ("embassy", "noun", "diplomatic office", "Foreign embassy.", "Band 7.0-7.5"),
    ("emergence", "noun", "appearance", "Emergence of new technology.", "Band 7.0-7.5"),
    ("emergency", "noun", "crisis", "State of emergency.", "Band 6.0-6.5"),
    ("emigration", "noun", "leaving country", "Mass emigration.", "Band 7.0-7.5"),
    ("emission", "noun", "release", "Carbon emission.", "Band 7.0-7.5"),
    ("emotion", "noun", "feeling", "Strong emotion.", "Band 6.0-6.5"),
    ("empathy", "noun", "understanding feelings", "Show empathy.", "Band 7.0-7.5"),
    ("emperor", "noun", "ruler", "Roman emperor.", "Band 6.0-6.5"),
    ("emphasis", "noun", "stress", "Put emphasis on.", "Band 6.0-6.5"),
    ("empire", "noun", "large territory", "British Empire.", "Band 6.0-6.5"),
    ("employee", "noun", "worker", "Company employee.", "Band 6.0-6.5"),
    ("employer", "noun", "boss", "Potential employer.", "Band 6.0-6.5"),
    ("employment", "noun", "work", "Full employment.", "Band 6.0-6.5"),
    ("empowerment", "noun", "giving power", "Women's empowerment.", "Band 8.0+"),
    ("encounter", "noun", "meeting", "Brief encounter.", "Band 6.0-6.5"),
    ("encouragement", "noun", "support", "Words of encouragement.", "Band 6.0-6.5"),
    ("encyclopedia", "noun", "reference book", "Online encyclopedia.", "Band 6.0-6.5"),
    ("endeavor", "noun", "effort", "Creative endeavor.", "Band 8.0+"),
    ("ending", "noun", "conclusion", "Happy ending.", "Band 4.5-5.5"),
    ("endorsement", "noun", "approval", "Celebrity endorsement.", "Band 8.0+"),
    ("endurance", "noun", "stamina", "Physical endurance.", "Band 7.0-7.5"),
    ("enemy", "noun", "opponent", "Common enemy.", "Band 4.5-5.5"),
    ("energy", "noun", "power", "Renewable energy.", "Band 6.0-6.5"),
    ("enforcement", "noun", "implementation", "Law enforcement.", "Band 7.0-7.5"),
    ("engagement", "noun", "involvement", "Customer engagement.", "Band 7.0-7.5"),
    ("engineering", "noun", "technical design", "Civil engineering.", "Band 6.0-6.5"),
    ("enhancement", "noun", "improvement", "Quality enhancement.", "Band 7.0-7.5"),
    ("enjoyment", "noun", "pleasure", "Personal enjoyment.", "Band 6.0-6.5"),
    ("enlightenment", "noun", "understanding", "The Enlightenment.", "Band 8.0+"),
    ("enrollment", "noun", "registration", "Student enrollment.", "Band 7.0-7.5"),
    ("enterprise", "noun", "business", "Private enterprise.", "Band 7.0-7.5"),
    ("entertainment", "noun", "amusement", "Live entertainment.", "Band 6.0-6.5"),
    ("enthusiasm", "noun", "excitement", "Great enthusiasm.", "Band 6.0-6.5"),
    ("entity", "noun", "being", "Legal entity.", "Band 8.0+"),
    ("entrance", "noun", "entry point", "Main entrance.", "Band 4.5-5.5"),
    ("entrepreneur", "noun", "business starter", "Young entrepreneur.", "Band 7.0-7.5"),
    ("entry", "noun", "admission", "Entry fee.", "Band 6.0-6.5"),
    ("envelope", "noun", "paper cover", "Sealed envelope.", "Band 4.5-5.5"),
    ("epidemic", "noun", "disease outbreak", "Flu epidemic.", "Band 7.0-7.5"),
    ("episode", "noun", "event", "TV episode.", "Band 6.0-6.5"),
    ("equality", "noun", "fairness", "Gender equality.", "Band 7.0-7.5"),
    ("equation", "noun", "formula", "Mathematical equation.", "Band 7.0-7.5"),
    ("equilibrium", "noun", "balance", "Economic equilibrium.", "Band 8.0+"),
    ("equipment", "noun", "tools", "Sports equipment.", "Band 6.0-6.5"),
    ("equity", "noun", "fairness", "Social equity.", "Band 8.0+"),
    ("equivalence", "noun", "equality", "Functional equivalence.", "Band 8.0+"),
    ("era", "noun", "period", "New era.", "Band 6.0-6.5"),
    ("erosion", "noun", "wearing away", "Soil erosion.", "Band 7.0-7.5"),
    ("error", "noun", "mistake", "Human error.", "Band 6.0-6.5"),
    ("eruption", "noun", "explosion", "Volcanic eruption.", "Band 7.0-7.5"),
    ("escalation", "noun", "increase", "Cost escalation.", "Band 8.0+"),
    ("escape", "noun", "getaway", "Narrow escape.", "Band 6.0-6.5"),
    ("essay", "noun", "written piece", "Write an essay.", "Band 6.0-6.5"),
    ("essence", "noun", "core", "In essence.", "Band 7.0-7.5"),
    ("establishment", "noun", "organization", "The establishment.", "Band 7.0-7.5"),
    ("estate", "noun", "property", "Real estate.", "Band 6.0-6.5"),
    ("estimation", "noun", "calculation", "Rough estimation.", "Band 7.0-7.5"),
    ("ethic", "noun", "moral principle", "Work ethic.", "Band 7.0-7.5"),
    ("ethnicity", "noun", "racial background", "Different ethnicity.", "Band 8.0+"),
    ("etiquette", "noun", "manners", "Business etiquette.", "Band 7.0-7.5"),
    ("evaluation", "noun", "assessment", "Performance evaluation.", "Band 7.0-7.5"),
    ("evacuation", "noun", "removal", "Emergency evacuation.", "Band 7.0-7.5"),
    ("evening", "noun", "late day", "Good evening.", "Band 4.5-5.5"),
    ("evolution", "noun", "development", "Theory of evolution.", "Band 7.0-7.5"),
    ("exaggeration", "noun", "overstatement", "Slight exaggeration.", "Band 7.0-7.5"),
    ("examination", "noun", "test", "Medical examination.", "Band 6.0-6.5"),
    ("examiner", "noun", "tester", "External examiner.", "Band 6.0-6.5"),
    ("excellence", "noun", "high quality", "Academic excellence.", "Band 7.0-7.5"),
    ("exception", "noun", "exclusion", "No exception.", "Band 6.0-6.5"),
    ("excess", "noun", "surplus", "In excess of.", "Band 7.0-7.5"),
    ("exchange", "noun", "trade", "Stock exchange.", "Band 6.0-6.5"),
    ("excitement", "noun", "thrill", "Great excitement.", "Band 4.5-5.5"),
    ("exclusion", "noun", "leaving out", "Social exclusion.", "Band 7.0-7.5"),
    ("execution", "noun", "carrying out", "Plan execution.", "Band 7.0-7.5"),
    ("executive", "noun", "manager", "Chief executive.", "Band 6.0-6.5"),
    ("exemption", "noun", "freedom from", "Tax exemption.", "Band 8.0+"),
    ("exercise", "noun", "physical activity", "Regular exercise.", "Band 4.5-5.5"),
    ("exhaustion", "noun", "tiredness", "Complete exhaustion.", "Band 7.0-7.5"),
    ("exhibition", "noun", "display", "Art exhibition.", "Band 6.0-6.5"),
    ("exile", "noun", "banishment", "Live in exile.", "Band 7.0-7.5"),
    ("existence", "noun", "being", "Human existence.", "Band 6.0-6.5"),
    ("exit", "noun", "way out", "Emergency exit.", "Band 4.5-5.5"),
    ("expansion", "noun", "growth", "Business expansion.", "Band 6.0-6.5"),
    ("expectation", "noun", "anticipation", "High expectations.", "Band 6.0-6.5"),
    ("expedition", "noun", "journey", "Arctic expedition.", "Band 7.0-7.5"),
    ("expenditure", "noun", "spending", "Public expenditure.", "Band 7.0-7.5"),
    ("expense", "noun", "cost", "Travel expense.", "Band 6.0-6.5"),
    ("experiment", "noun", "test", "Scientific experiment.", "Band 6.0-6.5"),
    ("expertise", "noun", "skill", "Technical expertise.", "Band 7.0-7.5"),
    ("expiration", "noun", "ending", "Expiration date.", "Band 7.0-7.5"),
    ("explanation", "noun", "clarification", "Simple explanation.", "Band 6.0-6.5"),
    ("exploitation", "noun", "misuse", "Labor exploitation.", "Band 8.0+"),
    ("exploration", "noun", "investigation", "Space exploration.", "Band 6.0-6.5"),
    ("explosion", "noun", "blast", "Population explosion.", "Band 6.0-6.5"),
    ("export", "noun", "goods sold abroad", "Major export.", "Band 6.0-6.5"),
    ("exposure", "noun", "experience", "Sun exposure.", "Band 6.0-6.5"),
    ("expression", "noun", "phrase", "Facial expression.", "Band 6.0-6.5"),
    ("extension", "noun", "addition", "Contract extension.", "Band 6.0-6.5"),
    ("extent", "noun", "degree", "To some extent.", "Band 6.0-6.5"),
    ("extinction", "noun", "dying out", "Mass extinction.", "Band 7.0-7.5"),
    ("extract", "noun", "excerpt", "Plant extract.", "Band 7.0-7.5"),
    ("extreme", "noun", "end point", "Go to extremes.", "Band 6.0-6.5"),
    ("fabric", "noun", "cloth", "Cotton fabric.", "Band 6.0-6.5"),
    ("fabrication", "noun", "invention", "Complete fabrication.", "Band 8.0+"),
    ("facade", "noun", "front", "Building facade.", "Band 8.0+"),
    ("facility", "noun", "building", "Medical facility.", "Band 6.0-6.5"),
    ("faction", "noun", "group", "Political faction.", "Band 8.0+"),
    ("factory", "noun", "manufacturing plant", "Car factory.", "Band 4.5-5.5"),
    ("faculty", "noun", "department", "University faculty.", "Band 7.0-7.5"),
    ("failure", "noun", "lack of success", "System failure.", "Band 6.0-6.5"),
    ("fairness", "noun", "justice", "Sense of fairness.", "Band 6.0-6.5"),
    ("faith", "noun", "belief", "Strong faith.", "Band 6.0-6.5"),
    ("fallacy", "noun", "false belief", "Logical fallacy.", "Band 8.0+"),
    ("fame", "noun", "renown", "International fame.", "Band 6.0-6.5"),
    ("famine", "noun", "food shortage", "Severe famine.", "Band 7.0-7.5"),
    ("fancy", "noun", "liking", "Take a fancy to.", "Band 6.0-6.5"),
    ("fantasy", "noun", "imagination", "Pure fantasy.", "Band 6.0-6.5"),
    ("fare", "noun", "price", "Bus fare.", "Band 6.0-6.5"),
    ("farewell", "noun", "goodbye", "Say farewell.", "Band 6.0-6.5"),
    ("farming", "noun", "agriculture", "Organic farming.", "Band 6.0-6.5"),
    ("fascination", "noun", "interest", "Deep fascination.", "Band 7.0-7.5"),
    ("fashion", "noun", "style", "Fashion industry.", "Band 6.0-6.5"),
    ("fatigue", "noun", "tiredness", "Mental fatigue.", "Band 7.0-7.5"),
    ("fault", "noun", "defect", "My fault.", "Band 4.5-5.5"),
    ("favor", "noun", "kindness", "Do a favor.", "Band 4.5-5.5"),
    ("feast", "noun", "large meal", "Wedding feast.", "Band 6.0-6.5"),
    ("feat", "noun", "achievement", "Remarkable feat.", "Band 7.0-7.5"),
    ("feather", "noun", "bird covering", "Light as a feather.", "Band 4.5-5.5"),
    ("federation", "noun", "union", "International federation.", "Band 7.0-7.5"),
    ("fee", "noun", "charge", "Entrance fee.", "Band 6.0-6.5"),
    ("feedback", "noun", "response", "Positive feedback.", "Band 6.0-6.5"),
    ("fellow", "noun", "man", "Fellow student.", "Band 6.0-6.5"),
    ("fellowship", "noun", "companionship", "Academic fellowship.", "Band 7.0-7.5"),
    ("feminist", "noun", "equality advocate", "Leading feminist.", "Band 7.0-7.5"),
    ("fence", "noun", "barrier", "Garden fence.", "Band 4.5-5.5"),
    ("ferry", "noun", "boat", "Take the ferry.", "Band 6.0-6.5"),
    ("fertility", "noun", "ability to reproduce", "Soil fertility.", "Band 7.0-7.5"),
    ("festival", "noun", "celebration", "Music festival.", "Band 6.0-6.5"),
    ("fever", "noun", "high temperature", "High fever.", "Band 4.5-5.5"),
    ("fiber", "noun", "thread", "Dietary fiber.", "Band 6.0-6.5"),
    ("fiction", "noun", "made-up story", "Science fiction.", "Band 6.0-6.5"),
    ("field", "noun", "area", "Research field.", "Band 6.0-6.5"),
    ("fighter", "noun", "warrior", "Freedom fighter.", "Band 6.0-6.5"),
    ("figure", "noun", "number", "Public figure.", "Band 6.0-6.5"),
    ("file", "noun", "document", "Computer file.", "Band 4.5-5.5"),
    ("filter", "noun", "strainer", "Water filter.", "Band 6.0-6.5"),
    ("finale", "noun", "ending", "Grand finale.", "Band 7.0-7.5"),
    ("finding", "noun", "discovery", "Research finding.", "Band 6.0-6.5"),
    ("fingerprint", "noun", "finger mark", "Leave fingerprints.", "Band 6.0-6.5"),
    ("firearm", "noun", "gun", "Illegal firearm.", "Band 7.0-7.5"),
    ("firefighter", "noun", "fire rescuer", "Brave firefighter.", "Band 6.0-6.5"),
    ("firework", "noun", "explosive display", "Firework display.", "Band 6.0-6.5"),
    ("firm", "noun", "company", "Law firm.", "Band 6.0-6.5"),
    ("fisherman", "noun", "fishing person", "Local fisherman.", "Band 6.0-6.5"),
    ("fishery", "noun", "fishing area", "Commercial fishery.", "Band 7.0-7.5"),
    ("fitness", "noun", "health", "Physical fitness.", "Band 6.0-6.5"),
    ("fixture", "noun", "permanent fitting", "Light fixture.", "Band 7.0-7.5"),
    ("flag", "noun", "banner", "National flag.", "Band 4.5-5.5"),
    ("flame", "noun", "fire", "Open flame.", "Band 6.0-6.5"),
    ("flaw", "noun", "defect", "Design flaw.", "Band 7.0-7.5"),
    ("fleet", "noun", "group of vehicles", "Car fleet.", "Band 7.0-7.5"),
    ("flexibility", "noun", "adaptability", "Show flexibility.", "Band 7.0-7.5"),
    ("flight", "noun", "air travel", "Book a flight.", "Band 4.5-5.5"),
    ("float", "noun", "parade vehicle", "Carnival float.", "Band 6.0-6.5"),
    ("flood", "noun", "overflow", "Flash flood.", "Band 6.0-6.5"),
    ("flourishing", "noun", "thriving", "Cultural flourishing.", "Band 8.0+"),
    ("flow", "noun", "movement", "Cash flow.", "Band 6.0-6.5"),
    ("fluctuation", "noun", "variation", "Price fluctuation.", "Band 8.0+"),
    ("fluid", "noun", "liquid", "Body fluid.", "Band 6.0-6.5"),
    ("focus", "noun", "center of attention", "Main focus.", "Band 6.0-6.5"),
    ("fog", "noun", "mist", "Dense fog.", "Band 6.0-6.5"),
    ("folklore", "noun", "traditional stories", "Local folklore.", "Band 7.0-7.5"),
    ("follower", "noun", "supporter", "Social media follower.", "Band 6.0-6.5"),
    ("footage", "noun", "film", "Video footage.", "Band 6.0-6.5"),
    ("footprint", "noun", "foot mark", "Carbon footprint.", "Band 7.0-7.5"),
    ("forecast", "noun", "prediction", "Weather forecast.", "Band 6.0-6.5"),
    ("foreigner", "noun", "person from abroad", "Welcome foreigners.", "Band 6.0-6.5"),
    ("forestry", "noun", "forest management", "Sustainable forestry.", "Band 7.0-7.5"),
    ("forgiveness", "noun", "pardon", "Ask for forgiveness.", "Band 6.0-6.5"),
    ("formation", "noun", "creation", "Rock formation.", "Band 6.0-6.5"),
    ("formula", "noun", "method", "Chemical formula.", "Band 6.0-6.5"),
    ("formulation", "noun", "creation", "Policy formulation.", "Band 8.0+"),
    ("fort", "noun", "military building", "Old fort.", "Band 6.0-6.5"),
    ("fortnight", "noun", "two weeks", "In a fortnight.", "Band 6.0-6.5"),
    ("fortune", "noun", "wealth", "Make a fortune.", "Band 6.0-6.5"),
    ("forum", "noun", "discussion place", "Public forum.", "Band 7.0-7.5"),
    ("fossil", "noun", "preserved remains", "Fossil fuel.", "Band 6.0-6.5"),
    ("foundation", "noun", "base", "Charity foundation.", "Band 6.0-6.5"),
    ("founder", "noun", "creator", "Company founder.", "Band 6.0-6.5"),
    ("fountain", "noun", "water feature", "Public fountain.", "Band 6.0-6.5"),
    ("fraction", "noun", "part", "Small fraction.", "Band 6.0-6.5"),
    ("fragility", "noun", "delicacy", "Economic fragility.", "Band 8.0+"),
    ("fragment", "noun", "piece", "Small fragment.", "Band 7.0-7.5"),
    ("framework", "noun", "structure", "Legal framework.", "Band 7.0-7.5"),
    ("franchise", "noun", "business license", "Fast food franchise.", "Band 7.0-7.5"),
    ("fraud", "noun", "deception", "Credit card fraud.", "Band 7.0-7.5"),
    ("freight", "noun", "cargo", "Freight train.", "Band 7.0-7.5"),
    ("frequency", "noun", "rate", "High frequency.", "Band 6.0-6.5"),
    ("friction", "noun", "resistance", "Social friction.", "Band 7.0-7.5"),
    ("friendship", "noun", "companionship", "True friendship.", "Band 4.5-5.5"),
    ("frontier", "noun", "border", "New frontier.", "Band 7.0-7.5"),
    ("frost", "noun", "ice crystals", "Morning frost.", "Band 6.0-6.5"),
    ("frustration", "noun", "disappointment", "Growing frustration.", "Band 6.0-6.5"),
    ("fuel", "noun", "energy source", "Fossil fuel.", "Band 6.0-6.5"),
    ("fulfillment", "noun", "satisfaction", "Personal fulfillment.", "Band 7.0-7.5"),
    ("function", "noun", "purpose", "Important function.", "Band 6.0-6.5"),
    ("functionality", "noun", "capability", "Basic functionality.", "Band 8.0+"),
    ("fund", "noun", "money reserve", "Pension fund.", "Band 6.0-6.5"),
    ("funeral", "noun", "burial ceremony", "Attend a funeral.", "Band 6.0-6.5"),
    ("fur", "noun", "animal hair", "Fur coat.", "Band 6.0-6.5"),
    ("furniture", "noun", "home items", "Office furniture.", "Band 4.5-5.5"),
    ("fury", "noun", "rage", "Blind fury.", "Band 7.0-7.5"),
    ("fusion", "noun", "combination", "Nuclear fusion.", "Band 7.0-7.5"),
    ("future", "noun", "time to come", "Bright future.", "Band 4.5-5.5"),
]

def translate_batch(texts, target_lang):
    url = f"https://translation.googleapis.com/language/translate/v2?key={GOOGLE_API_KEY}"
    result = []
    for i in range(0, len(texts), 100):
        batch = texts[i:i+100]
        try:
            resp = requests.post(url, json={"q": batch, "source": "en", "target": target_lang}, timeout=30)
            if resp.status_code == 200:
                result.extend([t['translatedText'] for t in resp.json()['data']['translations']])
            else:
                result.extend(batch)
        except:
            result.extend(batch)
        time.sleep(0.1)
    return result

def main():
    with open('assets/data/words.json', 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    existing = {w['word'].lower() for w in words}
    start_id = max(w['id'] for w in words) + 1
    categories = ["Academic", "Environment", "Technology", "Health", "Education", "Business", "Science", "Media", "Society", "Culture"]
    
    new_words = []
    for word, pos, definition, example, level in WORDS_PART4:
        if word.lower() not in existing:
            new_words.append({
                "id": start_id + len(new_words),
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": categories[(start_id + len(new_words)) % len(categories)]
            })
            existing.add(word.lower())
    
    print(f"새 단어: {len(new_words)}개")
    
    if new_words:
        defs = [w['definition'] for w in new_words]
        exs = [w['example'] for w in new_words]
        
        for lang in LANGUAGES:
            print(f"{lang} 번역중...")
            trans_defs = translate_batch(defs, lang)
            trans_exs = translate_batch(exs, lang)
            for i, w in enumerate(new_words):
                if 'translations' not in w:
                    w['translations'] = {}
                w['translations'][lang] = {
                    'definition': trans_defs[i],
                    'example': trans_exs[i]
                }
        
        words.extend(new_words)
        with open('assets/data/words.json', 'w', encoding='utf-8') as f:
            json.dump(words, f, ensure_ascii=False, indent=2)
    
    print(f"총: {len(words)}개")

if __name__ == "__main__":
    main()
