workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: IELTS Vocab App
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hooniapps.ieltsvocab
      vars:
        APP_ID: 6756547799
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Generate localizations
        script: |
          flutter gen-l10n
          echo "Checking generated l10n files..."
          ls -la .dart_tool/flutter_gen/gen_l10n/ || echo "l10n directory not found in .dart_tool"
          ls -la lib/l10n/ || echo "l10n directory not found in lib"
      - name: Clean and rebuild
        script: |
          flutter clean
          flutter pub get
          flutter gen-l10n
      - name: Install pods
        script: |
          cd ios && pod install --repo-update && cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.2 \
            --build-number=4 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - hoonijo@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
