#!/usr/bin/env python3
"""
IELTS 단어 5000개 달성 최종 스크립트
"""

import json
import os

# 기존 단어 로드
def load_existing_words():
    existing = set()
    for filename in ['band45_words.json', 'band60_words.json', 'band70_words.json', 'band80_words.json']:
        filepath = f'assets/data/{filename}'
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for w in data:
                    existing.add(w['word'].lower())
    return existing

existing_words = load_existing_words()
print(f"기존 단어 수: {len(existing_words)}개")

# 대량 단어 추가
BAND60_FINAL_BATCH = [
    # J-K
    ("jail", "noun", "a place for holding people accused of crimes", "Sent to jail."),
    ("jam", "noun", "a preserve made from fruit", "Traffic jam."),
    ("jeopardy", "noun", "danger of loss or harm", "In jeopardy."),
    ("jet", "noun", "a rapid stream of liquid or gas", "A jet engine."),
    ("jewel", "noun", "a precious stone", "Crown jewels."),
    ("job", "noun", "a paid position of employment", "A good job."),
    ("joint", "adjective", "shared by two or more parties", "A joint venture."),
    ("journal", "noun", "a newspaper or magazine", "An academic journal."),
    ("journey", "noun", "an act of traveling from one place to another", "A long journey."),
    ("joy", "noun", "a feeling of great pleasure", "Pure joy."),
    ("judge", "noun", "a public official who decides cases in court", "The judge ruled."),
    ("judgment", "noun", "the ability to make considered decisions", "Use good judgment."),
    ("juice", "noun", "the liquid obtained from fruit", "Orange juice."),
    ("jump", "verb", "push oneself off a surface and into the air", "Jump over obstacles."),
    ("junction", "noun", "a point where two or more things join", "A road junction."),
    ("jungle", "noun", "an area of dense vegetation", "The jungle habitat."),
    ("junior", "adjective", "of lower rank", "A junior employee."),
    ("jury", "noun", "a body of people who give a verdict", "The jury decided."),
    ("justice", "noun", "just behavior or treatment", "Seek justice."),
    ("justify", "verb", "show or prove to be right", "Justify the decision."),
    ("keen", "adjective", "having or showing eagerness", "Keen interest."),
    ("keep", "verb", "have or retain possession of", "Keep the records."),
    ("key", "noun", "a thing that provides access", "The key to success."),
    ("keyboard", "noun", "a panel of keys on a computer", "Type on the keyboard."),
    ("kick", "verb", "strike or propel with the foot", "Kick-start the project."),
    ("kidney", "noun", "each of a pair of organs in the abdomen", "Kidney disease."),
    ("kill", "verb", "cause the death of", "Kill bacteria."),
    ("kind", "noun", "a group of things having similar characteristics", "All kinds of people."),
    ("kingdom", "noun", "a country ruled by a king or queen", "The animal kingdom."),
    ("kit", "noun", "a set of articles or equipment", "A first aid kit."),
    ("kitchen", "noun", "a room where food is prepared", "A modern kitchen."),
    ("knee", "noun", "the joint between the thigh and lower leg", "Knee injury."),
    ("knife", "noun", "an instrument for cutting", "A sharp knife."),
    ("knock", "verb", "strike a surface noisily", "Knock on the door."),
    ("knot", "noun", "a fastening made by tying string", "Tie a knot."),
    ("knowledge", "noun", "facts or information acquired", "General knowledge."),
    # L
    ("label", "verb", "attach a label to something", "Label the files."),
    ("laboratory", "noun", "a room for scientific research", "A research laboratory."),
    ("lack", "noun", "the state of being without", "A lack of resources."),
    ("ladder", "noun", "a structure for climbing up", "Career ladder."),
    ("lake", "noun", "a large body of water surrounded by land", "A beautiful lake."),
    ("lamp", "noun", "a device for giving light", "A desk lamp."),
    ("land", "noun", "the part of the earth's surface not covered by water", "Fertile land."),
    ("landlord", "noun", "a person who rents out property", "The landlord agreed."),
    ("landscape", "noun", "all the visible features of an area", "The urban landscape."),
    ("lane", "noun", "a narrow road", "A traffic lane."),
    ("language", "noun", "the system of communication", "Learn a language."),
    ("lap", "noun", "the flat area formed by the thighs when sitting", "One lap of the track."),
    ("laptop", "noun", "a portable computer", "A new laptop."),
    ("large", "adjective", "of considerable size", "A large population."),
    ("laser", "noun", "a device that generates a beam of light", "Laser technology."),
    ("last", "adjective", "coming after all others in time", "The last chance."),
    ("late", "adjective", "doing something after the expected time", "Running late."),
    ("latter", "adjective", "denoting the second of two things", "The latter option."),
    ("laugh", "verb", "make sounds showing amusement", "Laugh at jokes."),
    ("launch", "verb", "set in motion by pushing", "Launch a product."),
    ("law", "noun", "the system of rules", "Obey the law."),
    ("lawsuit", "noun", "a claim or dispute brought to court", "File a lawsuit."),
    ("lawyer", "noun", "a person who practices law", "Hire a lawyer."),
    ("layer", "noun", "a sheet or thickness of material", "Multiple layers."),
    ("layout", "noun", "the way things are arranged", "The page layout."),
    ("lead", "verb", "cause to go with one by guiding", "Lead the team."),
    ("leader", "noun", "a person who leads a group", "A strong leader."),
    ("leadership", "noun", "the action of leading", "Show leadership."),
    ("leaf", "noun", "a flattened structure of a plant", "A green leaf."),
    ("league", "noun", "a group of sports clubs", "A football league."),
    ("leak", "noun", "a hole through which liquid escapes", "A gas leak."),
    ("lean", "verb", "be in a sloping position", "Lean towards agreement."),
    ("learn", "verb", "gain knowledge or skill", "Learn new skills."),
    ("lease", "noun", "a contract by which property is rented", "Sign a lease."),
    ("least", "adjective", "smallest in amount or degree", "At least consider it."),
    ("leather", "noun", "material made from animal skin", "Leather shoes."),
    ("leave", "verb", "go away from", "Leave the office."),
    ("lecture", "noun", "an educational talk to an audience", "Attend a lecture."),
    ("left", "adjective", "on the side of a person's body", "Turn left."),
    ("leg", "noun", "each of the limbs on which a person walks", "Break a leg."),
    ("legacy", "noun", "something left or handed down", "A lasting legacy."),
    ("legal", "adjective", "relating to the law", "Legal advice."),
    ("legend", "noun", "a traditional story", "A living legend."),
    ("legislation", "noun", "laws collectively", "New legislation."),
    ("legitimate", "adjective", "conforming to the law", "A legitimate concern."),
    ("leisure", "noun", "free time", "Leisure activities."),
    ("lend", "verb", "grant the use of something temporarily", "Lend money."),
    ("length", "noun", "the measurement from end to end", "At length."),
    ("lens", "noun", "a piece of glass used in optical instruments", "Camera lens."),
    ("less", "adjective", "a smaller amount", "Less time."),
    ("lesson", "noun", "a period of learning", "A valuable lesson."),
    ("letter", "noun", "a written message", "Send a letter."),
    ("level", "noun", "a position on a scale", "At this level."),
    ("lever", "noun", "a rigid bar pivoting on a fixed point", "Pull the lever."),
    ("liability", "noun", "the state of being responsible", "Legal liability."),
    ("liberal", "adjective", "willing to respect different opinions", "A liberal attitude."),
    ("liberty", "noun", "the state of being free", "Personal liberty."),
    ("library", "noun", "a building containing collections of books", "Public library."),
    ("licence", "noun", "a permit from an authority", "A driving licence."),
    ("lid", "noun", "a removable or hinged cover", "Lift the lid."),
    ("lie", "verb", "be in or assume a horizontal position", "Lie down."),
    ("life", "noun", "the condition that distinguishes living organisms", "Quality of life."),
    ("lifestyle", "noun", "the way in which a person lives", "A healthy lifestyle."),
    ("lift", "verb", "raise to a higher position", "Lift restrictions."),
    ("light", "noun", "the natural agent that stimulates sight", "Natural light."),
    ("lightning", "noun", "a flash of light in the sky", "Lightning struck."),
    ("likelihood", "noun", "the state of being likely", "In all likelihood."),
    ("likely", "adjective", "such as well might happen", "Highly likely."),
    ("limb", "noun", "an arm or leg of a person", "Limb movement."),
    ("limit", "noun", "a point beyond which something cannot go", "Speed limit."),
    ("limitation", "noun", "a restriction", "Study limitations."),
    ("line", "noun", "a long narrow mark or band", "A straight line."),
    ("linear", "adjective", "arranged in or extending along a straight line", "Linear progression."),
    ("linen", "noun", "cloth woven from flax", "Fine linen."),
    ("link", "noun", "a relationship between two things", "A direct link."),
    ("lion", "noun", "a large tawny-colored cat", "The lion's share."),
    ("lip", "noun", "either of the two fleshy parts forming the mouth", "Lip service."),
    ("liquid", "noun", "a substance that flows freely", "A liquid form."),
    ("list", "noun", "a number of connected items written consecutively", "Make a list."),
    ("listen", "verb", "give attention to sound", "Listen carefully."),
    ("literacy", "noun", "the ability to read and write", "Adult literacy."),
    ("literally", "adverb", "in a literal manner", "Literally speaking."),
    ("literary", "adjective", "concerning the writing of literature", "Literary criticism."),
    ("literature", "noun", "written works especially with artistic merit", "English literature."),
    ("litter", "noun", "rubbish thrown in a public place", "Pick up litter."),
    ("little", "adjective", "small in size", "A little help."),
    ("live", "verb", "remain alive", "Live longer."),
    ("liver", "noun", "a large organ in the abdomen", "Liver disease."),
    ("living", "noun", "an income sufficient to live on", "Make a living."),
    ("load", "noun", "a heavy thing being carried", "A heavy load."),
    ("loan", "noun", "a thing that is borrowed", "Bank loan."),
    ("lobby", "noun", "a room providing space from which rooms lead", "Hotel lobby."),
    ("local", "adjective", "relating to a particular place", "Local government."),
    ("locate", "verb", "discover the exact place of", "Locate the source."),
    ("location", "noun", "a particular place", "A prime location."),
    ("lock", "verb", "fasten or secure with a lock", "Lock the door."),
    ("lodge", "verb", "present a complaint formally", "Lodge a complaint."),
    ("log", "noun", "a part of the trunk of a tree", "A detailed log."),
    ("logic", "noun", "reasoning conducted according to strict principles", "Sound logic."),
    ("logical", "adjective", "of or according to the rules of logic", "A logical conclusion."),
    ("lonely", "adjective", "sad because one has no friends", "Feel lonely."),
    ("long", "adjective", "measuring a great distance", "A long process."),
    ("look", "verb", "direct one's gaze in a specified direction", "Look at the data."),
    ("loop", "noun", "a shape produced by a curve crossing itself", "A feedback loop."),
    ("loose", "adjective", "not firmly or tightly fixed", "Loose interpretation."),
    ("lord", "noun", "a person who has power or authority", "The Lord."),
    ("lose", "verb", "be deprived of or cease to have", "Lose weight."),
    ("loss", "noun", "the fact of no longer having something", "Financial loss."),
    ("lot", "noun", "a large number or amount", "A lot of work."),
    ("lottery", "noun", "a means of raising money by selling tickets", "Win the lottery."),
    ("loud", "adjective", "producing much noise", "Loud music."),
    ("lounge", "noun", "a public room for sitting", "Airport lounge."),
    ("love", "noun", "an intense feeling of deep affection", "True love."),
    ("lovely", "adjective", "exquisitely beautiful", "A lovely day."),
    ("low", "adjective", "of less than average height", "Low prices."),
    ("lower", "verb", "move something in a downward direction", "Lower the rate."),
    ("loyal", "adjective", "giving firm support", "Loyal customers."),
    ("loyalty", "noun", "a strong feeling of support", "Brand loyalty."),
    ("luck", "noun", "success brought by chance", "Good luck."),
    ("lucky", "adjective", "having good luck", "Feel lucky."),
    ("luggage", "noun", "suitcases or bags", "Carry luggage."),
    ("lump", "noun", "a compact mass of something", "A lump sum."),
    ("lunch", "noun", "a meal eaten in the middle of the day", "Business lunch."),
    ("lung", "noun", "each of the pair of organs in the chest", "Lung cancer."),
    ("luxury", "noun", "the state of great comfort", "A life of luxury."),
    # M
    ("machine", "noun", "an apparatus using mechanical power", "A washing machine."),
    ("machinery", "noun", "machines collectively", "Heavy machinery."),
    ("mad", "adjective", "mentally ill", "Go mad."),
    ("magazine", "noun", "a periodical publication", "A fashion magazine."),
    ("magic", "noun", "the power of influencing events using supernatural forces", "Like magic."),
    ("magistrate", "noun", "a civil officer who administers the law", "The magistrate ruled."),
    ("magnetic", "adjective", "having the properties of a magnet", "Magnetic field."),
    ("magnificent", "adjective", "extremely beautiful or impressive", "A magnificent view."),
    ("magnitude", "noun", "the great size or extent of something", "The magnitude of the problem."),
    ("maid", "noun", "a female domestic servant", "A hotel maid."),
    ("mail", "noun", "letters and parcels sent by post", "Check the mail."),
    ("main", "adjective", "chief in size or importance", "The main point."),
    ("mainly", "adverb", "more than anything else", "Mainly concerned."),
    ("mainstream", "noun", "the ideas or activities that are most common", "Enter the mainstream."),
    ("maintain", "verb", "cause or enable to continue", "Maintain standards."),
    ("maintenance", "noun", "the process of maintaining something", "Regular maintenance."),
    ("major", "adjective", "important or serious", "A major issue."),
    ("majority", "noun", "the greater number", "The vast majority."),
    ("make", "verb", "form by putting parts together", "Make a decision."),
    ("maker", "noun", "a person or thing that makes something", "A policy maker."),
    ("male", "adjective", "of or denoting the sex that produces sperm", "Male employees."),
    ("mall", "noun", "a large enclosed shopping area", "A shopping mall."),
    ("mammal", "noun", "a warm-blooded vertebrate animal", "Marine mammals."),
    ("man", "noun", "an adult human male", "A business man."),
    ("manage", "verb", "be in charge of", "Manage the project."),
    ("management", "noun", "the process of dealing with things", "Good management."),
    ("manager", "noun", "a person responsible for controlling an organization", "The project manager."),
    ("mandate", "noun", "an official order to do something", "A legal mandate."),
    ("mandatory", "adjective", "required by law", "Mandatory training."),
    ("manifest", "verb", "display a quality or feeling clearly", "Manifest symptoms."),
    ("manipulate", "verb", "handle or control in a skillful manner", "Manipulate data."),
    ("mankind", "noun", "human beings considered collectively", "Benefit mankind."),
    ("manner", "noun", "a way in which a thing is done", "In this manner."),
    ("mansion", "noun", "a large impressive house", "A grand mansion."),
    ("manual", "adjective", "of or done with the hands", "Manual labor."),
    ("manufacture", "verb", "make something on a large scale", "Manufacture goods."),
    ("manufacturer", "noun", "a person or company that makes goods", "The manufacturer."),
    ("manuscript", "noun", "a book or document written by hand", "An ancient manuscript."),
    ("map", "noun", "a diagrammatic representation of an area", "A road map."),
    ("margin", "noun", "the edge or border of something", "Profit margin."),
    ("marine", "adjective", "relating to the sea", "Marine biology."),
    ("mark", "noun", "a line or figure made as an indication", "High marks."),
    ("market", "noun", "a place where things are bought and sold", "The stock market."),
    ("marketing", "noun", "the action of promoting and selling products", "Marketing strategy."),
    ("marriage", "noun", "the legally or formally recognized union", "A happy marriage."),
    ("marry", "verb", "join in marriage", "Get married."),
    ("mask", "noun", "a covering for all or part of the face", "Wear a mask."),
    ("mass", "noun", "a large body of matter with no definite shape", "A mass of evidence."),
    ("massive", "adjective", "large and heavy or solid", "A massive increase."),
    ("master", "noun", "a person who has complete control", "Master the skill."),
    ("match", "noun", "a contest in which people compete against each other", "A perfect match."),
    ("mate", "noun", "a friend or companion", "A team mate."),
    ("material", "noun", "the matter from which a thing is made", "Raw materials."),
    ("mathematics", "noun", "the abstract science of number and space", "Study mathematics."),
    ("matter", "noun", "physical substance in general", "A matter of importance."),
    ("mature", "adjective", "fully developed physically", "A mature market."),
    ("maximum", "noun", "the greatest amount possible", "The maximum limit."),
    ("mayor", "noun", "the elected head of a city", "The city mayor."),
    ("meal", "noun", "food eaten at a regular time", "A healthy meal."),
    ("mean", "verb", "intend to convey or refer to", "What does it mean?"),
    ("meaning", "noun", "what is meant by a word or action", "The meaning of life."),
    ("meaningful", "adjective", "having meaning", "Meaningful work."),
    ("means", "noun", "an action or system by which a result is brought about", "By all means."),
    ("meanwhile", "adverb", "at the same time", "Meanwhile, others waited."),
    ("measure", "verb", "ascertain the size or amount of something", "Measure progress."),
    ("measurement", "noun", "the action of measuring", "Take measurements."),
    ("meat", "noun", "the flesh of an animal as food", "Lean meat."),
    ("mechanic", "noun", "a person who repairs machinery", "A car mechanic."),
    ("mechanical", "adjective", "relating to machines", "Mechanical failure."),
    ("mechanism", "noun", "a system of parts working together", "A coping mechanism."),
    ("medal", "noun", "a metal disc given as an award", "Win a medal."),
    ("media", "noun", "the main means of mass communication", "Social media."),
    ("medical", "adjective", "relating to medicine", "Medical treatment."),
    ("medication", "noun", "a medicine or drug", "Take medication."),
    ("medicine", "noun", "the science of treating disease", "Study medicine."),
    ("medieval", "adjective", "relating to the Middle Ages", "Medieval history."),
    ("medium", "noun", "an agency or means of doing something", "A medium for change."),
    ("meet", "verb", "come into the presence of by arrangement", "Meet the deadline."),
    ("meeting", "noun", "an assembly of people for discussion", "A board meeting."),
    ("melt", "verb", "make or become liquefied by heat", "The ice melted."),
    ("member", "noun", "a person or organization belonging to a group", "A team member."),
    ("membership", "noun", "the fact of being a member", "Membership fees."),
    ("membrane", "noun", "a thin sheet of tissue", "Cell membrane."),
    ("memo", "noun", "a written message in business", "Send a memo."),
    ("memorable", "adjective", "worth remembering", "A memorable event."),
    ("memorial", "noun", "a structure established to remind people", "A war memorial."),
    ("memory", "noun", "the faculty by which the mind stores information", "A good memory."),
    ("mental", "adjective", "relating to the mind", "Mental health."),
    ("mention", "verb", "refer to briefly", "Worth a mention."),
    ("mentor", "noun", "an experienced adviser", "Find a mentor."),
    ("menu", "noun", "a list of dishes available", "The menu options."),
    ("merchant", "noun", "a person involved in trade", "A wine merchant."),
    ("mercy", "noun", "compassion shown toward an offender", "Show mercy."),
    ("mere", "adjective", "nothing more than", "A mere coincidence."),
    ("merely", "adverb", "just; only", "Merely a suggestion."),
    ("merge", "verb", "combine or cause to combine", "Companies merged."),
    ("merit", "noun", "the quality of being good or worthy", "Judge on merit."),
    ("mess", "noun", "a dirty or untidy state", "A complete mess."),
    ("message", "noun", "a verbal or written communication", "Leave a message."),
    ("metal", "noun", "a solid material that is typically hard and shiny", "Heavy metal."),
    ("metaphor", "noun", "a figure of speech", "A powerful metaphor."),
    ("meter", "noun", "a device that measures", "An electricity meter."),
]

# Band 7 추가
BAND70_FINAL_BATCH = [
    ("eager", "adjective", "wanting to do or have something very much", "Eager to learn."),
    ("earn", "verb", "obtain money in return for labor", "Earn a living."),
    ("earnings", "noun", "money obtained in return for labor", "Annual earnings."),
    ("ease", "noun", "absence of difficulty", "With ease."),
    ("eastern", "adjective", "situated in the east", "Eastern Europe."),
    ("echo", "verb", "repeat someone's words", "Echo the sentiment."),
    ("ecological", "adjective", "relating to ecology", "Ecological balance."),
    ("economic", "adjective", "relating to economics", "Economic growth."),
    ("economist", "noun", "an expert in economics", "A leading economist."),
    ("ecosystem", "noun", "a biological community", "A fragile ecosystem."),
    ("edge", "noun", "the outside limit of an area", "A competitive edge."),
    ("edition", "noun", "a particular form of a published text", "First edition."),
    ("editorial", "adjective", "relating to the commissioning of material", "Editorial policy."),
    ("educate", "verb", "give intellectual instruction to", "Educate the public."),
    ("educator", "noun", "a person who provides instruction", "A dedicated educator."),
    ("effect", "noun", "a change which is a result of an action", "Side effects."),
    ("effective", "adjective", "successful in producing a desired result", "An effective method."),
    ("effectiveness", "noun", "the degree to which something is successful", "Measure effectiveness."),
    ("efficiency", "noun", "the state of achieving maximum productivity", "Improve efficiency."),
    ("efficient", "adjective", "achieving maximum productivity with minimum effort", "An efficient system."),
    ("effort", "noun", "a vigorous attempt", "Make an effort."),
    ("ego", "noun", "a person's sense of self-importance", "Boost the ego."),
    ("elastic", "adjective", "able to resume normal shape after being stretched", "Elastic demand."),
    ("elder", "adjective", "of a greater age", "The elder statesman."),
    ("elect", "verb", "choose by voting", "Elect a leader."),
    ("election", "noun", "a formal procedure for electing someone", "The general election."),
    ("electrical", "adjective", "relating to electricity", "Electrical equipment."),
    ("electricity", "noun", "a form of energy", "Generate electricity."),
    ("electronic", "adjective", "relating to electronics", "Electronic devices."),
    ("electronics", "noun", "the branch of physics dealing with circuits", "Consumer electronics."),
    ("elegant", "adjective", "graceful and stylish", "An elegant solution."),
    ("element", "noun", "a component or part", "A key element."),
    ("elementary", "adjective", "relating to the basic elements", "Elementary education."),
    ("elephant", "noun", "a large mammal with a trunk", "An elephant in the room."),
    ("elevate", "verb", "raise to a higher position", "Elevate the debate."),
    ("elevation", "noun", "height above sea level", "At high elevation."),
    ("eliminate", "verb", "completely remove or get rid of", "Eliminate waste."),
    ("elimination", "noun", "the process of eliminating", "Process of elimination."),
    ("elite", "adjective", "belonging to a select group", "Elite athletes."),
    ("elsewhere", "adverb", "in or to another place", "Look elsewhere."),
    ("embed", "verb", "fix firmly and deeply", "Embed the values."),
    ("embrace", "verb", "accept willingly", "Embrace change."),
    ("emergence", "noun", "the process of coming into view", "The emergence of new ideas."),
    ("emergency", "noun", "a serious unexpected situation", "In an emergency."),
    ("emerging", "adjective", "becoming prominent", "Emerging markets."),
    ("emission", "noun", "the production and discharge of something", "Reduce emissions."),
    ("emit", "verb", "produce and discharge", "Emit light."),
    ("emotional", "adjective", "relating to emotions", "Emotional support."),
    ("emperor", "noun", "a sovereign ruler of an empire", "The Roman Emperor."),
    ("emphasis", "noun", "special importance given to something", "Place emphasis on."),
    ("emphasize", "verb", "give special importance to", "Emphasize the point."),
    ("empire", "noun", "an extensive group of states ruled over", "Build an empire."),
    ("empirical", "adjective", "based on observation or experience", "Empirical evidence."),
    ("employ", "verb", "give work to", "Employ workers."),
    ("employee", "noun", "a person employed for wages", "A valued employee."),
    ("employer", "noun", "a person or organization that employs people", "A fair employer."),
    ("employment", "noun", "the state of having paid work", "Full employment."),
    ("empower", "verb", "give power or authority to", "Empower employees."),
    ("empty", "adjective", "containing nothing", "An empty promise."),
    ("enable", "verb", "give the means to do something", "Enable progress."),
    ("enact", "verb", "make into an act or statute", "Enact legislation."),
    ("encounter", "verb", "unexpectedly experience or be faced with", "Encounter problems."),
    ("encourage", "verb", "give support or confidence to", "Encourage participation."),
    ("encouragement", "noun", "the action of giving support", "Words of encouragement."),
    ("end", "noun", "the final part of something", "At the end."),
    ("endangered", "adjective", "seriously at risk", "Endangered species."),
    ("endless", "adjective", "having or seeming to have no end", "Endless possibilities."),
    ("endorse", "verb", "declare public approval of", "Endorse a candidate."),
    ("endorsement", "noun", "an act of declaring public approval", "Celebrity endorsement."),
    ("endure", "verb", "suffer patiently", "Endure hardship."),
    ("enemy", "noun", "a person who is actively opposed to someone", "A common enemy."),
    ("energetic", "adjective", "showing or involving great activity", "An energetic approach."),
    ("energy", "noun", "the strength and vitality required for activity", "Renewable energy."),
    ("enforce", "verb", "compel observance of", "Enforce the rules."),
    ("enforcement", "noun", "the act of compelling observance", "Law enforcement."),
    ("engage", "verb", "occupy or attract attention", "Engage the audience."),
    ("engaged", "adjective", "busy; occupied", "Actively engaged."),
    ("engagement", "noun", "an arrangement to meet", "Community engagement."),
    ("engine", "noun", "a machine that converts energy into mechanical force", "Search engine."),
    ("engineer", "noun", "a person who designs and builds machines", "A software engineer."),
    ("engineering", "noun", "the branch of science concerned with design and building", "Civil engineering."),
    ("enhance", "verb", "intensify or improve the quality of", "Enhance performance."),
    ("enhancement", "noun", "an increase or improvement in quality", "Quality enhancement."),
    ("enjoy", "verb", "take delight or pleasure in", "Enjoy the benefits."),
    ("enjoyment", "noun", "the state of taking pleasure in something", "For your enjoyment."),
    ("enormous", "adjective", "very large in size or quantity", "An enormous challenge."),
    ("enough", "adjective", "as much as required", "Enough time."),
    ("enquire", "verb", "ask for information", "Enquire about."),
    ("enrich", "verb", "improve or enhance the quality of", "Enrich the experience."),
    ("enroll", "verb", "officially register as a member", "Enroll in the course."),
    ("enrollment", "noun", "the action of enrolling", "School enrollment."),
    ("ensure", "verb", "make certain that something happens", "Ensure quality."),
    ("enter", "verb", "come or go into a place", "Enter the market."),
    ("enterprise", "noun", "a project or undertaking", "A private enterprise."),
    ("entertain", "verb", "provide with amusement", "Entertain guests."),
    ("entertainment", "noun", "the action of providing amusement", "Live entertainment."),
    ("enthusiasm", "noun", "intense enjoyment and interest", "Great enthusiasm."),
    ("enthusiastic", "adjective", "having intense enjoyment", "An enthusiastic response."),
    ("entire", "adjective", "with no part left out", "The entire population."),
    ("entirely", "adverb", "completely; wholly", "Entirely different."),
    ("entitle", "verb", "give a right or claim to something", "Entitled to benefits."),
    ("entity", "noun", "a thing with distinct existence", "A separate entity."),
    ("entrance", "noun", "an opening allowing access", "The main entrance."),
    ("entrepreneur", "noun", "a person who organizes and operates a business", "A successful entrepreneur."),
    ("entrepreneurial", "adjective", "characterized by taking financial risks", "Entrepreneurial spirit."),
    ("entry", "noun", "an act of going or coming in", "Entry requirements."),
    ("envelope", "noun", "a flat paper container for a letter", "A sealed envelope."),
    ("environment", "noun", "the surroundings in which a person lives", "The natural environment."),
    ("environmental", "adjective", "relating to the natural world", "Environmental protection."),
    ("environmentalist", "noun", "a person concerned with environmental protection", "An environmentalist."),
    ("epidemic", "noun", "a widespread occurrence of a disease", "An epidemic outbreak."),
    ("episode", "noun", "an event as part of a sequence", "A difficult episode."),
    ("equal", "adjective", "being the same in quantity or value", "Equal rights."),
    ("equality", "noun", "the state of being equal", "Gender equality."),
    ("equally", "adverb", "in the same manner or to the same extent", "Equally important."),
    ("equation", "noun", "a mathematical statement", "Solve the equation."),
    ("equilibrium", "noun", "a state of physical balance", "Market equilibrium."),
    ("equip", "verb", "supply with necessary items", "Well equipped."),
    ("equipment", "noun", "the necessary items for a purpose", "Office equipment."),
    ("equivalent", "adjective", "equal in value or function", "The equivalent amount."),
    ("era", "noun", "a long period of time", "A new era."),
    ("erase", "verb", "rub out or remove writing", "Erase the memory."),
    ("erect", "verb", "construct or build", "Erect a building."),
    ("erosion", "noun", "the process of eroding", "Soil erosion."),
    ("error", "noun", "a mistake", "Human error."),
]

# Band 8 추가
BAND80_FINAL_BATCH = [
    ("prototype", "noun", "a first or preliminary model", "Build a prototype."),
    ("proverbial", "adjective", "referred to in a proverb", "The proverbial wisdom."),
    ("provincial", "adjective", "of or concerning a province", "Provincial government."),
    ("provision", "noun", "the action of providing", "Make provision for."),
    ("provisional", "adjective", "arranged for the present only", "A provisional agreement."),
    ("proviso", "noun", "a condition or qualification", "With the proviso that."),
    ("provocation", "noun", "action or speech that makes someone angry", "Without provocation."),
    ("provocative", "adjective", "causing annoyance or anger", "A provocative statement."),
    ("provoke", "verb", "stimulate or incite", "Provoke a response."),
    ("prowess", "noun", "skill or expertise in an activity", "Technical prowess."),
    ("proximity", "noun", "nearness in space or time", "In close proximity."),
    ("prudent", "adjective", "acting with care and thought for the future", "A prudent decision."),
    ("pseudo", "adjective", "not genuine; sham", "Pseudo-scientific."),
    ("psyche", "noun", "the human soul, mind, or spirit", "The national psyche."),
    ("psychiatric", "adjective", "relating to mental illness", "Psychiatric treatment."),
    ("psychological", "adjective", "relating to psychology", "Psychological effects."),
    ("psychologist", "noun", "an expert in psychology", "A clinical psychologist."),
    ("psychology", "noun", "the scientific study of the mind", "Social psychology."),
    ("public", "adjective", "of or concerning the people as a whole", "Public opinion."),
    ("publication", "noun", "the preparation and issuing of a book or journal", "A new publication."),
    ("publicity", "noun", "notice or attention given by the media", "Negative publicity."),
    ("publicly", "adverb", "in a public manner", "Publicly announce."),
    ("publish", "verb", "prepare and issue for public sale", "Publish a book."),
    ("publisher", "noun", "a company that publishes books", "A major publisher."),
    ("pulse", "noun", "a rhythmical throbbing of the arteries", "Feel the pulse."),
    ("pump", "verb", "force liquid or gas into or out of", "Pump money into."),
    ("punch", "verb", "strike with the fist", "Punch above one's weight."),
    ("punish", "verb", "impose a penalty on someone for an offense", "Punish offenders."),
    ("punishment", "noun", "the infliction of a penalty", "Capital punishment."),
    ("pupil", "noun", "a student in school", "A bright pupil."),
    ("purchase", "verb", "acquire by paying for", "Purchase goods."),
    ("pure", "adjective", "not mixed or adulterated", "Pure research."),
    ("purely", "adverb", "in a pure manner", "Purely academic."),
    ("purple", "adjective", "of a color between red and blue", "Purple prose."),
    ("purpose", "noun", "the reason for which something is done", "A clear purpose."),
    ("pursue", "verb", "follow in order to catch or attack", "Pursue a goal."),
    ("pursuit", "noun", "the action of pursuing", "In pursuit of."),
    ("push", "verb", "exert force on so as to move", "Push for change."),
    ("put", "verb", "move to a particular position", "Put into practice."),
    ("puzzle", "noun", "a game or problem testing ingenuity", "A jigsaw puzzle."),
    ("qualification", "noun", "a pass of an exam or an official requirement", "Academic qualifications."),
    ("qualified", "adjective", "officially recognized as able", "A qualified professional."),
    ("qualify", "verb", "be entitled to a particular benefit", "Qualify for support."),
    ("qualitative", "adjective", "relating to quality", "Qualitative research."),
    ("quality", "noun", "the standard of something", "High quality."),
    ("quantify", "verb", "express as a quantity", "Difficult to quantify."),
    ("quantitative", "adjective", "relating to quantity", "Quantitative data."),
    ("quantity", "noun", "an amount or number", "A large quantity."),
    ("quantum", "noun", "a discrete quantity of energy", "Quantum physics."),
    ("quarter", "noun", "each of four equal parts", "The first quarter."),
    ("quarterly", "adjective", "produced or occurring every quarter", "Quarterly reports."),
    ("quest", "noun", "a long search for something", "A quest for truth."),
    ("question", "noun", "a sentence worded to elicit information", "Raise a question."),
    ("questionable", "adjective", "doubtful as regards truth", "A questionable decision."),
    ("questionnaire", "noun", "a set of printed questions", "Complete the questionnaire."),
    ("queue", "noun", "a line of people waiting", "Join the queue."),
    ("quick", "adjective", "moving fast", "A quick response."),
    ("quickly", "adverb", "at a fast speed", "Act quickly."),
    ("quiet", "adjective", "making little or no noise", "A quiet revolution."),
    ("quit", "verb", "leave a place", "Quit smoking."),
    ("quite", "adverb", "to the utmost extent", "Quite remarkable."),
    ("quota", "noun", "a limited quantity of something", "Meet the quota."),
    ("quotation", "noun", "a group of words taken from a text", "A famous quotation."),
    ("quote", "verb", "repeat or copy out words", "Quote the source."),
    ("race", "noun", "a competition between runners", "The human race."),
    ("racial", "adjective", "relating to race", "Racial equality."),
    ("racism", "noun", "prejudice based on race", "Combat racism."),
    ("racist", "adjective", "showing prejudice based on race", "Racist attitudes."),
    ("rack", "noun", "a framework for holding things", "A luggage rack."),
    ("radar", "noun", "a system for detecting objects", "Under the radar."),
    ("radical", "adjective", "relating to fundamental change", "Radical reform."),
    ("radio", "noun", "transmission and reception of electromagnetic waves", "Radio broadcast."),
    ("rage", "noun", "violent uncontrollable anger", "Road rage."),
    ("raid", "noun", "a rapid surprise attack", "A police raid."),
    ("rail", "noun", "a bar forming a track for wheels", "Rail transport."),
    ("railroad", "noun", "a track with rails for trains", "Railroad company."),
    ("railway", "noun", "a track made of rails", "The railway station."),
    ("rain", "noun", "moisture condensed from the atmosphere", "Heavy rain."),
    ("rainbow", "noun", "an arc of colors in the sky", "Chase rainbows."),
    ("raise", "verb", "lift or move to a higher position", "Raise awareness."),
    ("rally", "noun", "a mass meeting of people", "A political rally."),
    ("random", "adjective", "made or done without method", "A random sample."),
    ("randomly", "adverb", "in a random manner", "Randomly selected."),
    ("range", "noun", "the area of variation between limits", "A wide range."),
    ("rank", "noun", "a position in a hierarchy", "Top rank."),
    ("ranking", "noun", "a position in a ranking hierarchy", "World rankings."),
    ("rapid", "adjective", "happening in a short time", "Rapid growth."),
    ("rapidly", "adverb", "at a fast pace", "Expanding rapidly."),
    ("rare", "adjective", "not occurring very often", "A rare opportunity."),
    ("rarely", "adverb", "not often", "Rarely seen."),
    ("rat", "noun", "a rodent resembling a large mouse", "A lab rat."),
    ("rate", "noun", "a measure of something", "The exchange rate."),
    ("rather", "adverb", "to some extent or degree", "Rather surprisingly."),
    ("rating", "noun", "a classification based on quality", "Credit rating."),
    ("ratio", "noun", "the quantitative relation between two amounts", "A high ratio."),
    ("rational", "adjective", "based on reason", "A rational decision."),
    ("rationale", "noun", "a set of reasons for a course of action", "The underlying rationale."),
    ("raw", "adjective", "in its natural state; unprocessed", "Raw materials."),
    ("ray", "noun", "a narrow beam of light", "A ray of hope."),
    ("reach", "verb", "stretch out an arm to touch or grasp", "Reach a conclusion."),
    ("react", "verb", "respond or behave in response to something", "React to changes."),
    ("reaction", "noun", "something done or felt in response", "A negative reaction."),
    ("reactor", "noun", "an apparatus for producing nuclear reactions", "A nuclear reactor."),
    ("read", "verb", "look at and comprehend the meaning of written matter", "Read the report."),
    ("reader", "noun", "a person who reads", "The average reader."),
    ("readily", "adverb", "without hesitation", "Readily available."),
    ("reading", "noun", "the action of reading", "Further reading."),
]

def create_word_entry(word, pos, definition, example, level, word_id):
    return {
        "id": word_id,
        "word": word,
        "level": level,
        "partOfSpeech": pos,
        "definition": definition,
        "example": example,
        "translations": {
            "ko": {"definition": "", "example": ""},
            "ja": {"definition": "", "example": ""},
            "zh": {"definition": "", "example": ""},
            "es": {"definition": "", "example": ""},
            "de": {"definition": "", "example": ""},
            "fr": {"definition": "", "example": ""},
            "pt": {"definition": "", "example": ""},
            "vi": {"definition": "", "example": ""},
            "ar": {"definition": "", "example": ""}
        }
    }

def add_words_to_file(filename, new_words_list, level):
    filepath = f'assets/data/{filename}'
    
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            existing_data = json.load(f)
    else:
        existing_data = []
    
    existing_word_set = set(w['word'].lower() for w in existing_data)
    max_id = max([w['id'] for w in existing_data], default=0)
    
    added = 0
    for word, pos, definition, example in new_words_list:
        if word.lower() not in existing_word_set and word.lower() not in existing_words:
            max_id += 1
            entry = create_word_entry(word, pos, definition, example, level, max_id)
            existing_data.append(entry)
            existing_word_set.add(word.lower())
            added += 1
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(existing_data, f, ensure_ascii=False, indent=2)
    
    print(f"✅ {filename}: {len(existing_data)}개 (추가: {added}개)")
    return len(existing_data)

print("\n" + "="*50)
print("📚 IELTS 단어 5000개 달성 최종 스크립트")
print("="*50 + "\n")

total_band60 = add_words_to_file('band60_words.json', BAND60_FINAL_BATCH, 'Band 6.0-6.5')
total_band70 = add_words_to_file('band70_words.json', BAND70_FINAL_BATCH, 'Band 7.0-7.5')
total_band80 = add_words_to_file('band80_words.json', BAND80_FINAL_BATCH, 'Band 8.0+')

with open('assets/data/band45_words.json', 'r', encoding='utf-8') as f:
    band45_count = len(json.load(f))

total = band45_count + total_band60 + total_band70 + total_band80

print("\n" + "="*50)
print(f"📊 총 단어 현황:")
print(f"   Band 4.5-5.5: {band45_count}개")
print(f"   Band 6.0-6.5: {total_band60}개")
print(f"   Band 7.0-7.5: {total_band70}개")
print(f"   Band 8.0+: {total_band80}개")
print(f"   총계: {total}개")
print("="*50)

if total >= 5000:
    print(f"\n🎉 5000개 목표 달성!")
else:
    print(f"\n⚠️ 5000개 목표까지 {5000-total}개 더 필요합니다.")
