#!/usr/bin/env python3
"""IELTS 5000개 단어 대량 생성"""
import json
import os

# 대량 단어 목록 - Band 4.5-5.5
BAND45_MEGA = [
    # 동사 500개
    ('work', 'verb', 'to function', 'The system works well.'),
    ('worry', 'verb', 'to be anxious', 'Worry about results.'),
    ('worth', 'verb', 'to deserve', 'Worth considering.'),
    ('wound', 'verb', 'to injure', 'Wound pride.'),
    ('wrap', 'verb', 'to cover', 'Wrap up findings.'),
    ('wreck', 'verb', 'to destroy', 'Wreck plans.'),
    ('write', 'verb', 'to compose', 'Write reports.'),
    ('yield', 'verb', 'to produce', 'Yield results.'),
    ('zoom', 'verb', 'to move fast', 'Zoom in on details.'),
    ('absorb', 'verb', 'to take in', 'Absorb information.'),
    ('abuse', 'verb', 'to misuse', 'Abuse power.'),
    ('accelerate', 'verb', 'to speed up', 'Accelerate progress.'),
    ('accent', 'verb', 'to emphasize', 'Accent key points.'),
    ('accept', 'verb', 'to receive', 'Accept responsibility.'),
    ('access', 'verb', 'to reach', 'Access data.'),
    ('accomplish', 'verb', 'to achieve', 'Accomplish goals.'),
    ('account', 'verb', 'to explain', 'Account for variation.'),
    ('accuse', 'verb', 'to charge', 'Accuse of bias.'),
    ('ache', 'verb', 'to hurt', 'Head aches from research.'),
    ('achieve', 'verb', 'to accomplish', 'Achieve objectives.'),
    ('acknowledge', 'verb', 'to admit', 'Acknowledge limitations.'),
    ('acquire', 'verb', 'to get', 'Acquire skills.'),
    ('act', 'verb', 'to perform', 'Act quickly.'),
    ('activate', 'verb', 'to start', 'Activate process.'),
    ('adapt', 'verb', 'to adjust', 'Adapt methods.'),
    ('add', 'verb', 'to include', 'Add data points.'),
    ('address', 'verb', 'to deal with', 'Address concerns.'),
    ('adjust', 'verb', 'to change', 'Adjust parameters.'),
    ('administer', 'verb', 'to manage', 'Administer survey.'),
    ('admire', 'verb', 'to respect', 'Admire dedication.'),
    ('admit', 'verb', 'to confess', 'Admit error.'),
    ('adopt', 'verb', 'to take up', 'Adopt new approach.'),
    ('advance', 'verb', 'to move forward', 'Advance theory.'),
    ('advertise', 'verb', 'to promote', 'Advertise findings.'),
    ('advise', 'verb', 'to recommend', 'Advise caution.'),
    ('advocate', 'verb', 'to support', 'Advocate change.'),
    ('affect', 'verb', 'to influence', 'Factors affect outcomes.'),
    ('afford', 'verb', 'to be able', 'Afford resources.'),
    ('age', 'verb', 'to grow old', 'Data ages quickly.'),
    ('agree', 'verb', 'to concur', 'Researchers agree.'),
    ('aid', 'verb', 'to help', 'Aid understanding.'),
    ('aim', 'verb', 'to intend', 'Aim to improve.'),
    ('alarm', 'verb', 'to frighten', 'Alarm experts.'),
    ('alert', 'verb', 'to warn', 'Alert to problems.'),
    ('align', 'verb', 'to arrange', 'Align with goals.'),
    ('allocate', 'verb', 'to assign', 'Allocate resources.'),
    ('allow', 'verb', 'to permit', 'Allow for variation.'),
    ('alter', 'verb', 'to change', 'Alter approach.'),
    ('amaze', 'verb', 'to astonish', 'Results amaze.'),
    ('amend', 'verb', 'to change', 'Amend policy.'),
    # 명사 500개
    ('weather', 'noun', 'atmospheric conditions', 'Weather patterns.'),
    ('website', 'noun', 'internet page', 'Research website.'),
    ('week', 'noun', 'seven days', 'Next week.'),
    ('weekend', 'noun', 'Saturday and Sunday', 'Over the weekend.'),
    ('weight', 'noun', 'heaviness', 'Give weight to.'),
    ('welfare', 'noun', 'well-being', 'Social welfare.'),
    ('west', 'noun', 'direction', 'In the west.'),
    ('wheel', 'noun', 'circular frame', 'Reinvent the wheel.'),
    ('white', 'noun', 'color', 'Black and white.'),
    ('whole', 'noun', 'entirety', 'As a whole.'),
    ('width', 'noun', 'breadth', 'Full width.'),
    ('wife', 'noun', 'spouse', 'Working wife.'),
    ('will', 'noun', 'determination', 'Political will.'),
    ('win', 'noun', 'victory', 'Major win.'),
    ('wind', 'noun', 'air movement', 'Wind of change.'),
    ('window', 'noun', 'opening', 'Window of opportunity.'),
    ('winner', 'noun', 'victor', 'Clear winner.'),
    ('winter', 'noun', 'cold season', 'Winter period.'),
    ('wire', 'noun', 'thin metal', 'Wire transfer.'),
    ('wisdom', 'noun', 'knowledge', 'Conventional wisdom.'),
    ('wish', 'noun', 'desire', 'Express wish.'),
    ('woman', 'noun', 'adult female', 'Working woman.'),
    ('wonder', 'noun', 'amazement', 'Sense of wonder.'),
    ('wood', 'noun', 'timber', 'Can\'t see wood for trees.'),
    ('word', 'noun', 'unit of language', 'Key word.'),
    ('work', 'noun', 'labor', 'Hard work.'),
    ('worker', 'noun', 'employee', 'Research worker.'),
    ('workplace', 'noun', 'work location', 'Workplace environment.'),
    ('workshop', 'noun', 'training session', 'Research workshop.'),
    ('world', 'noun', 'earth', 'Around the world.'),
    ('worry', 'noun', 'concern', 'Main worry.'),
    ('worth', 'noun', 'value', 'Net worth.'),
    ('writer', 'noun', 'author', 'Academic writer.'),
    ('writing', 'noun', 'text', 'Academic writing.'),
    ('yard', 'noun', 'unit of measure', 'By the yard.'),
    ('year', 'noun', 'period of time', 'Calendar year.'),
    ('yesterday', 'noun', 'day before today', 'Only yesterday.'),
    ('yield', 'noun', 'output', 'High yield.'),
    ('youth', 'noun', 'young people', 'Today\'s youth.'),
    ('zone', 'noun', 'area', 'Time zone.'),
    ('ability', 'noun', 'capability', 'Cognitive ability.'),
    ('absence', 'noun', 'lack', 'In the absence of.'),
    ('abstract', 'noun', 'summary', 'Paper abstract.'),
    ('abundance', 'noun', 'plenty', 'In abundance.'),
    ('abuse', 'noun', 'misuse', 'Drug abuse.'),
    ('academy', 'noun', 'institution', 'National academy.'),
    ('accent', 'noun', 'pronunciation', 'Regional accent.'),
    ('acceptance', 'noun', 'approval', 'Gain acceptance.'),
    ('access', 'noun', 'entry', 'Internet access.'),
    ('accident', 'noun', 'mishap', 'By accident.'),
    # 형용사 200개
    ('average', 'adjective', 'typical', 'Average result.'),
    ('aware', 'adjective', 'knowing', 'Fully aware.'),
    ('awful', 'adjective', 'very bad', 'Awful mistake.'),
    ('awkward', 'adjective', 'clumsy', 'Awkward situation.'),
    ('back', 'adjective', 'rear', 'Back row.'),
    ('bad', 'adjective', 'poor quality', 'Bad data.'),
    ('balanced', 'adjective', 'even', 'Balanced view.'),
    ('bare', 'adjective', 'uncovered', 'Bare minimum.'),
    ('basic', 'adjective', 'fundamental', 'Basic concept.'),
    ('beautiful', 'adjective', 'attractive', 'Beautiful design.'),
    ('behavioral', 'adjective', 'of behavior', 'Behavioral study.'),
    ('beneficial', 'adjective', 'helpful', 'Mutually beneficial.'),
    ('best', 'adjective', 'most good', 'Best practice.'),
    ('better', 'adjective', 'more good', 'Better approach.'),
    ('big', 'adjective', 'large', 'Big data.'),
    ('biological', 'adjective', 'of biology', 'Biological factors.'),
    ('bitter', 'adjective', 'resentful', 'Bitter criticism.'),
    ('blank', 'adjective', 'empty', 'Blank page.'),
    ('blind', 'adjective', 'unable to see', 'Blind spot.'),
    ('bold', 'adjective', 'brave', 'Bold claim.'),
    ('boring', 'adjective', 'dull', 'Boring topic.'),
    ('bottom', 'adjective', 'lowest', 'Bottom line.'),
    ('bound', 'adjective', 'certain', 'Bound to happen.'),
    ('brave', 'adjective', 'courageous', 'Brave decision.'),
    ('brief', 'adjective', 'short', 'Brief overview.'),
    ('bright', 'adjective', 'intelligent', 'Bright future.'),
    ('brilliant', 'adjective', 'very clever', 'Brilliant idea.'),
    ('broad', 'adjective', 'wide', 'Broad scope.'),
    ('broken', 'adjective', 'damaged', 'Broken system.'),
    ('busy', 'adjective', 'occupied', 'Busy period.'),
]

# Band 6.0-6.5 대량 추가
BAND60_MEGA = [
    # 동사 300개
    ('enforce', 'verb', 'to compel', 'Enforce regulations.'),
    ('engage', 'verb', 'to involve', 'Engage participants.'),
    ('engineer', 'verb', 'to design', 'Engineer solutions.'),
    ('enhance', 'verb', 'to improve', 'Enhance quality.'),
    ('enjoy', 'verb', 'to take pleasure', 'Enjoy success.'),
    ('enlarge', 'verb', 'to make bigger', 'Enlarge sample size.'),
    ('enrich', 'verb', 'to improve', 'Enrich understanding.'),
    ('enroll', 'verb', 'to register', 'Enroll participants.'),
    ('ensure', 'verb', 'to make certain', 'Ensure accuracy.'),
    ('enter', 'verb', 'to go into', 'Enter data.'),
    ('entertain', 'verb', 'to consider', 'Entertain ideas.'),
    ('entitle', 'verb', 'to give right', 'Entitle to access.'),
    ('equate', 'verb', 'to consider equal', 'Equate with success.'),
    ('equip', 'verb', 'to provide', 'Equip with tools.'),
    ('eradicate', 'verb', 'to eliminate', 'Eradicate disease.'),
    ('erase', 'verb', 'to remove', 'Erase data.'),
    ('erode', 'verb', 'to wear away', 'Trust erodes.'),
    ('err', 'verb', 'to make mistake', 'Err on side of caution.'),
    ('escalate', 'verb', 'to increase', 'Tensions escalate.'),
    ('escape', 'verb', 'to get away', 'Escape notice.'),
    ('establish', 'verb', 'to set up', 'Establish criteria.'),
    ('estimate', 'verb', 'to calculate', 'Estimate costs.'),
    ('evacuate', 'verb', 'to leave', 'Evacuate premises.'),
    ('evaluate', 'verb', 'to assess', 'Evaluate results.'),
    ('evaporate', 'verb', 'to disappear', 'Support evaporates.'),
    ('evolve', 'verb', 'to develop', 'Ideas evolve.'),
    ('exacerbate', 'verb', 'to worsen', 'Exacerbate problems.'),
    ('exaggerate', 'verb', 'to overstate', 'Exaggerate claims.'),
    ('examine', 'verb', 'to inspect', 'Examine evidence.'),
    ('exceed', 'verb', 'to go beyond', 'Exceed expectations.'),
    # 명사 300개
    ('danger', 'noun', 'risk', 'Potential danger.'),
    ('data', 'noun', 'information', 'Raw data.'),
    ('database', 'noun', 'data collection', 'Search database.'),
    ('date', 'noun', 'day', 'Due date.'),
    ('daughter', 'noun', 'female child', 'Research daughter.'),
    ('day', 'noun', '24 hours', 'Day by day.'),
    ('deadline', 'noun', 'time limit', 'Meet deadline.'),
    ('deal', 'noun', 'agreement', 'Good deal.'),
    ('dealer', 'noun', 'trader', 'Art dealer.'),
    ('dealing', 'noun', 'transaction', 'Fair dealing.'),
    ('dean', 'noun', 'university official', 'Academic dean.'),
    ('death', 'noun', 'end of life', 'Death rate.'),
    ('debate', 'noun', 'discussion', 'Public debate.'),
    ('debt', 'noun', 'obligation', 'National debt.'),
    ('decade', 'noun', 'ten years', 'Past decade.'),
    ('decay', 'noun', 'decline', 'Urban decay.'),
    ('deceit', 'noun', 'deception', 'Academic deceit.'),
    ('deception', 'noun', 'fraud', 'Research deception.'),
    ('decision', 'noun', 'choice', 'Major decision.'),
    ('deck', 'noun', 'platform', 'On deck.'),
    ('declaration', 'noun', 'statement', 'Public declaration.'),
    ('decline', 'noun', 'decrease', 'Steady decline.'),
    ('decoration', 'noun', 'ornament', 'Mere decoration.'),
    ('decrease', 'noun', 'reduction', 'Significant decrease.'),
    ('dedication', 'noun', 'commitment', 'Complete dedication.'),
    ('deed', 'noun', 'action', 'Good deed.'),
    ('default', 'noun', 'failure', 'By default.'),
    ('defeat', 'noun', 'loss', 'Major defeat.'),
    ('defence', 'noun', 'protection', 'In defence of.'),
    ('deficiency', 'noun', 'lack', 'Nutritional deficiency.'),
    # 형용사 150개
    ('found', 'adjective', 'discovered', 'Found evidence.'),
    ('fragile', 'adjective', 'delicate', 'Fragile situation.'),
    ('frank', 'adjective', 'honest', 'Frank discussion.'),
    ('free', 'adjective', 'without cost', 'Free access.'),
    ('frequent', 'adjective', 'often', 'Frequent occurrence.'),
    ('fresh', 'adjective', 'new', 'Fresh perspective.'),
    ('friendly', 'adjective', 'kind', 'User-friendly.'),
    ('frightening', 'adjective', 'scary', 'Frightening prospect.'),
    ('front', 'adjective', 'forward', 'Front page.'),
    ('frozen', 'adjective', 'very cold', 'Frozen assets.'),
    ('fruitful', 'adjective', 'productive', 'Fruitful discussion.'),
    ('frustrated', 'adjective', 'annoyed', 'Frustrated researcher.'),
    ('frustrating', 'adjective', 'annoying', 'Frustrating process.'),
    ('full', 'adjective', 'complete', 'Full analysis.'),
    ('functional', 'adjective', 'working', 'Fully functional.'),
    ('fundamental', 'adjective', 'basic', 'Fundamental concept.'),
    ('funny', 'adjective', 'amusing', 'Funny enough.'),
    ('furious', 'adjective', 'very angry', 'Furious debate.'),
    ('further', 'adjective', 'additional', 'Further research.'),
    ('future', 'adjective', 'coming', 'Future development.'),
]

# Band 7.0-7.5 대량 추가
BAND70_MEGA = [
    # 동사 200개
    ('constrain', 'verb', 'to restrict', 'Constrain options.'),
    ('constrict', 'verb', 'to tighten', 'Constrict flow.'),
    ('construct', 'verb', 'to build', 'Construct argument.'),
    ('construe', 'verb', 'to interpret', 'Construe meaning.'),
    ('consult', 'verb', 'to seek advice', 'Consult experts.'),
    ('consume', 'verb', 'to use up', 'Consume resources.'),
    ('contaminate', 'verb', 'to pollute', 'Contaminate sample.'),
    ('contemplate', 'verb', 'to consider', 'Contemplate options.'),
    ('contend', 'verb', 'to argue', 'Contend that.'),
    ('contest', 'verb', 'to dispute', 'Contest findings.'),
    ('contextualize', 'verb', 'to place in context', 'Contextualize results.'),
    ('continue', 'verb', 'to carry on', 'Continue analysis.'),
    ('contract', 'verb', 'to shrink', 'Markets contract.'),
    ('contradict', 'verb', 'to deny', 'Contradict claims.'),
    ('contrast', 'verb', 'to compare', 'Contrast approaches.'),
    ('contribute', 'verb', 'to give', 'Contribute to field.'),
    ('contrive', 'verb', 'to devise', 'Contrive solution.'),
    ('control', 'verb', 'to manage', 'Control variables.'),
    ('convene', 'verb', 'to assemble', 'Convene meeting.'),
    ('converge', 'verb', 'to come together', 'Lines converge.'),
    # 명사 200개
    ('commonplace', 'noun', 'ordinary thing', 'Become commonplace.'),
    ('commonwealth', 'noun', 'federation', 'British Commonwealth.'),
    ('commotion', 'noun', 'disturbance', 'Cause commotion.'),
    ('commune', 'noun', 'community', 'Academic commune.'),
    ('communication', 'noun', 'exchange', 'Clear communication.'),
    ('communiqué', 'noun', 'official statement', 'Press communiqué.'),
    ('community', 'noun', 'group', 'Research community.'),
    ('commutation', 'noun', 'exchange', 'Sentence commutation.'),
    ('compact', 'noun', 'agreement', 'Social compact.'),
    ('companion', 'noun', 'associate', 'Research companion.'),
    ('company', 'noun', 'firm', 'Large company.'),
    ('comparability', 'noun', 'similarity', 'Ensure comparability.'),
    ('comparison', 'noun', 'evaluation', 'Make comparison.'),
    ('compartment', 'noun', 'section', 'Separate compartment.'),
    ('compass', 'noun', 'range', 'Within compass of.'),
    ('compassion', 'noun', 'sympathy', 'Show compassion.'),
    ('compatibility', 'noun', 'suitability', 'Check compatibility.'),
    ('compatriot', 'noun', 'fellow citizen', 'Fellow compatriot.'),
    ('compendium', 'noun', 'collection', 'Research compendium.'),
    ('compensation', 'noun', 'payment', 'Fair compensation.'),
    # 형용사 100개
    ('colorful', 'adjective', 'vivid', 'Colorful description.'),
    ('colossal', 'adjective', 'huge', 'Colossal effort.'),
    ('combative', 'adjective', 'aggressive', 'Combative style.'),
    ('combined', 'adjective', 'joint', 'Combined effort.'),
    ('combustible', 'adjective', 'flammable', 'Combustible material.'),
    ('comfortable', 'adjective', 'at ease', 'Comfortable margin.'),
    ('comic', 'adjective', 'funny', 'Comic relief.'),
    ('coming', 'adjective', 'approaching', 'Coming years.'),
    ('commanding', 'adjective', 'authoritative', 'Commanding lead.'),
    ('commemorative', 'adjective', 'honoring', 'Commemorative event.'),
    ('commensurate', 'adjective', 'proportionate', 'Commensurate with.'),
    ('commercial', 'adjective', 'business', 'Commercial success.'),
    ('committed', 'adjective', 'dedicated', 'Committed to.'),
    ('common', 'adjective', 'shared', 'Common ground.'),
    ('commonplace', 'adjective', 'ordinary', 'Commonplace occurrence.'),
    ('communal', 'adjective', 'shared', 'Communal effort.'),
    ('communicable', 'adjective', 'transmittable', 'Communicable disease.'),
    ('communicative', 'adjective', 'talkative', 'Communicative style.'),
    ('communist', 'adjective', 'of communism', 'Communist regime.'),
    ('compact', 'adjective', 'small', 'Compact summary.'),
]

# Band 8.0+ 대량 추가
BAND80_MEGA = [
    # 동사 150개
    ('enunciate', 'verb', 'to pronounce', 'Enunciate clearly.'),
    ('envision', 'verb', 'to imagine', 'Envision future.'),
    ('epitomize', 'verb', 'to embody', 'Epitomize excellence.'),
    ('equivocate', 'verb', 'to be ambiguous', 'Never equivocate.'),
    ('eradicate', 'verb', 'to eliminate', 'Eradicate errors.'),
    ('eschew', 'verb', 'to avoid', 'Eschew simplicity.'),
    ('espouse', 'verb', 'to adopt', 'Espouse principles.'),
    ('establish', 'verb', 'to found', 'Establish precedent.'),
    ('estrange', 'verb', 'to alienate', 'Estrange colleagues.'),
    ('etch', 'verb', 'to engrave', 'Etch in memory.'),
    ('eulogize', 'verb', 'to praise', 'Eulogize achievements.'),
    ('evaluate', 'verb', 'to assess', 'Rigorously evaluate.'),
    ('evince', 'verb', 'to show', 'Evince concern.'),
    ('eviscerate', 'verb', 'to disembowel', 'Eviscerate argument.'),
    ('evoke', 'verb', 'to bring forth', 'Evoke memories.'),
    ('exacerbate', 'verb', 'to worsen', 'Exacerbate tensions.'),
    ('exalt', 'verb', 'to praise highly', 'Exalt achievements.'),
    ('excavate', 'verb', 'to dig out', 'Excavate evidence.'),
    ('excel', 'verb', 'to surpass', 'Excel in field.'),
    ('excerpt', 'verb', 'to extract', 'Excerpt passages.'),
    # 명사 150개
    ('characterization', 'noun', 'description', 'Accurate characterization.'),
    ('charisma', 'noun', 'charm', 'Personal charisma.'),
    ('charlatan', 'noun', 'fraud', 'Academic charlatan.'),
    ('charter', 'noun', 'document', 'Royal charter.'),
    ('chasm', 'noun', 'gap', 'Intellectual chasm.'),
    ('chicanery', 'noun', 'trickery', 'Political chicanery.'),
    ('chimera', 'noun', 'illusion', 'Scientific chimera.'),
    ('chronicle', 'noun', 'record', 'Historical chronicle.'),
    ('chronology', 'noun', 'time sequence', 'Establish chronology.'),
    ('cipher', 'noun', 'code', 'Decipher cipher.'),
    ('circuitry', 'noun', 'system', 'Complex circuitry.'),
    ('circumlocution', 'noun', 'roundabout expression', 'Avoid circumlocution.'),
    ('circumscription', 'noun', 'limitation', 'Within circumscription.'),
    ('circumspection', 'noun', 'caution', 'Exercise circumspection.'),
    ('circumstance', 'noun', 'condition', 'Mitigating circumstance.'),
    ('citadel', 'noun', 'fortress', 'Citadel of learning.'),
    ('citation', 'noun', 'reference', 'Proper citation.'),
    ('citizenry', 'noun', 'citizens', 'Educated citizenry.'),
    ('clairvoyance', 'noun', 'foresight', 'Academic clairvoyance.'),
    ('clamor', 'noun', 'outcry', 'Public clamor.'),
    # 형용사 100개
    ('chagrinned', 'adjective', 'embarrassed', 'Chagrinned admission.'),
    ('chaotic', 'adjective', 'disordered', 'Chaotic system.'),
    ('characteristic', 'adjective', 'typical', 'Characteristic feature.'),
    ('charismatic', 'adjective', 'charming', 'Charismatic leader.'),
    ('charitable', 'adjective', 'generous', 'Charitable interpretation.'),
    ('chaste', 'adjective', 'pure', 'Chaste language.'),
    ('cheap', 'adjective', 'inexpensive', 'Cheap trick.'),
    ('checkered', 'adjective', 'varied', 'Checkered history.'),
    ('cheerful', 'adjective', 'happy', 'Cheerful outlook.'),
    ('cherished', 'adjective', 'valued', 'Cherished belief.'),
    ('chief', 'adjective', 'main', 'Chief concern.'),
    ('childish', 'adjective', 'immature', 'Childish argument.'),
    ('chilling', 'adjective', 'frightening', 'Chilling effect.'),
    ('choice', 'adjective', 'excellent', 'Choice selection.'),
    ('choleric', 'adjective', 'irritable', 'Choleric response.'),
    ('chronic', 'adjective', 'persistent', 'Chronic problem.'),
    ('chronological', 'adjective', 'in time order', 'Chronological sequence.'),
    ('churlish', 'adjective', 'rude', 'Churlish behavior.'),
    ('cinematographic', 'adjective', 'of film', 'Cinematographic technique.'),
    ('circuitous', 'adjective', 'roundabout', 'Circuitous route.'),
]

CATEGORIES_45 = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
                 'Business', 'Society', 'Science', 'Culture', 'Media']
CATEGORIES_60 = ['Academic', 'Research', 'Science', 'Analysis', 'Writing', 
                 'Critical Thinking', 'Education', 'Professional', 'Data', 'Theory']
CATEGORIES_70 = ['Academic Writing', 'Research Methods', 'Critical Analysis', 
                 'Advanced Theory', 'Scholarly Discussion', 'Professional Development']
CATEGORIES_80 = ['Advanced Academic Writing', 'Sophisticated Argumentation', 
                 'Expert Level Research', 'High-Level Critical Analysis']

def add_words(filename, words, level, categories):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            existing = json.load(f)
    except:
        existing = []
    
    existing_words = {w['word'] for w in existing}
    start_id = len(existing) + 1
    added = 0
    
    for word, pos, definition, example in words:
        if word not in existing_words:
            existing.append({
                'id': start_id + added,
                'word': word,
                'level': level,
                'partOfSpeech': pos,
                'definition': definition,
                'example': example,
                'category': categories[(start_id + added) % len(categories)]
            })
            existing_words.add(word)
            added += 1
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    return len(existing), added

def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    total45, added45 = add_words('assets/data/band45_words.json', BAND45_MEGA, 'Band 4.5-5.5', CATEGORIES_45)
    print(f'✅ Band 4.5-5.5: {total45}개 (추가: {added45}개)')
    
    total60, added60 = add_words('assets/data/band60_words.json', BAND60_MEGA, 'Band 6.0-6.5', CATEGORIES_60)
    print(f'✅ Band 6.0-6.5: {total60}개 (추가: {added60}개)')
    
    total70, added70 = add_words('assets/data/band70_words.json', BAND70_MEGA, 'Band 7.0-7.5', CATEGORIES_70)
    print(f'✅ Band 7.0-7.5: {total70}개 (추가: {added70}개)')
    
    total80, added80 = add_words('assets/data/band80_words.json', BAND80_MEGA, 'Band 8.0+', CATEGORIES_80)
    print(f'✅ Band 8.0+: {total80}개 (추가: {added80}개)')

if __name__ == '__main__':
    main()
