#!/usr/bin/env python3
"""IELTS AWL (Academic Word List) 기반 대량 생성"""
import json
import os

# Academic Word List 기반 단어
AWL_WORDS_45 = [
    # Sublist 1 - Most frequent academic words
    ('analysis', 'noun', 'detailed examination', 'Conduct detailed analysis.'),
    ('approach', 'noun', 'method', 'New approach to problem.'),
    ('area', 'noun', 'field', 'Research area expands.'),
    ('assessment', 'noun', 'evaluation', 'Risk assessment needed.'),
    ('assume', 'verb', 'to suppose', 'Assume the hypothesis.'),
    ('authority', 'noun', 'power', 'Legal authority grants.'),
    ('available', 'adjective', 'accessible', 'Data available online.'),
    ('benefit', 'noun', 'advantage', 'Long-term benefits.'),
    ('concept', 'noun', 'idea', 'Core concept emerges.'),
    ('consistent', 'adjective', 'unchanging', 'Consistent results.'),
    ('constitutional', 'adjective', 'of constitution', 'Constitutional rights.'),
    ('context', 'noun', 'circumstances', 'Historical context.'),
    ('contract', 'noun', 'agreement', 'Legal contract signed.'),
    ('create', 'verb', 'to make', 'Create new methods.'),
    ('data', 'noun', 'information', 'Collect data carefully.'),
    ('definition', 'noun', 'meaning', 'Clear definition needed.'),
    ('derived', 'adjective', 'obtained from', 'Derived conclusions.'),
    ('distribution', 'noun', 'spread', 'Normal distribution.'),
    ('economic', 'adjective', 'of economy', 'Economic factors.'),
    ('environment', 'noun', 'surroundings', 'Natural environment.'),
    ('established', 'adjective', 'accepted', 'Established practice.'),
    ('estimate', 'verb', 'to calculate', 'Estimate value.'),
    ('evident', 'adjective', 'obvious', 'Evidence evident.'),
    ('export', 'noun', 'goods sold abroad', 'Export volume.'),
    ('factor', 'noun', 'element', 'Key factor identified.'),
    ('financial', 'adjective', 'monetary', 'Financial support.'),
    ('formula', 'noun', 'rule', 'Mathematical formula.'),
    ('function', 'noun', 'purpose', 'Main function clear.'),
    ('identified', 'adjective', 'recognized', 'Identified patterns.'),
    ('income', 'noun', 'earnings', 'Annual income rises.'),
    ('indicate', 'verb', 'to show', 'Results indicate trend.'),
    ('individual', 'noun', 'person', 'Each individual differs.'),
    ('interpretation', 'noun', 'explanation', 'Different interpretation.'),
    ('involved', 'adjective', 'participating', 'Factors involved.'),
    ('issue', 'noun', 'matter', 'Address the issue.'),
    ('labor', 'noun', 'work', 'Labor market changes.'),
    ('legal', 'adjective', 'lawful', 'Legal requirements.'),
    ('legislation', 'noun', 'laws', 'New legislation passed.'),
    ('major', 'adjective', 'significant', 'Major findings.'),
    ('method', 'noun', 'approach', 'Research method.'),
    ('occur', 'verb', 'to happen', 'Changes occur.'),
    ('percent', 'noun', 'per hundred', 'Fifty percent increase.'),
    ('period', 'noun', 'time span', 'Extended period.'),
    ('policy', 'noun', 'plan', 'Government policy.'),
    ('principle', 'noun', 'rule', 'Basic principle.'),
    ('procedure', 'noun', 'process', 'Standard procedure.'),
    ('process', 'noun', 'series of actions', 'Decision process.'),
    ('required', 'adjective', 'needed', 'Required documents.'),
    ('research', 'noun', 'study', 'Further research needed.'),
    ('response', 'noun', 'answer', 'Positive response.'),
    # Sublist 2
    ('achieve', 'verb', 'to accomplish', 'Achieve goals successfully.'),
    ('acquisition', 'noun', 'obtaining', 'Knowledge acquisition.'),
    ('administration', 'noun', 'management', 'Public administration.'),
    ('affect', 'verb', 'to influence', 'Climate affects crops.'),
    ('appropriate', 'adjective', 'suitable', 'Appropriate measures.'),
    ('aspects', 'noun', 'features', 'Various aspects.'),
    ('assistance', 'noun', 'help', 'Financial assistance.'),
    ('categories', 'noun', 'groups', 'Different categories.'),
    ('chapter', 'noun', 'section', 'Chapter outline.'),
    ('commission', 'noun', 'committee', 'Research commission.'),
    ('community', 'noun', 'group', 'Scientific community.'),
    ('complex', 'adjective', 'complicated', 'Complex problem.'),
    ('computer', 'noun', 'electronic device', 'Computer analysis.'),
    ('conclusion', 'noun', 'end result', 'Draw conclusions.'),
    ('conduct', 'verb', 'to carry out', 'Conduct research.'),
    ('consequences', 'noun', 'results', 'Face consequences.'),
    ('construction', 'noun', 'building', 'Theory construction.'),
    ('consumer', 'noun', 'buyer', 'Consumer behavior.'),
    ('credit', 'noun', 'recognition', 'Give credit.'),
    ('cultural', 'adjective', 'of culture', 'Cultural factors.'),
    ('design', 'noun', 'plan', 'Research design.'),
    ('distinction', 'noun', 'difference', 'Clear distinction.'),
    ('elements', 'noun', 'parts', 'Key elements.'),
    ('equation', 'noun', 'mathematical statement', 'Solve equation.'),
    ('evaluation', 'noun', 'assessment', 'Comprehensive evaluation.'),
    ('features', 'noun', 'characteristics', 'Main features.'),
    ('final', 'adjective', 'last', 'Final analysis.'),
    ('focus', 'noun', 'center of attention', 'Main focus.'),
    ('impact', 'noun', 'effect', 'Significant impact.'),
    ('injury', 'noun', 'harm', 'Physical injury.'),
    ('institute', 'noun', 'organization', 'Research institute.'),
    ('investment', 'noun', 'money put in', 'Capital investment.'),
    ('items', 'noun', 'things', 'Survey items.'),
    ('journal', 'noun', 'periodical', 'Academic journal.'),
    ('maintenance', 'noun', 'upkeep', 'System maintenance.'),
    ('normal', 'adjective', 'usual', 'Normal distribution.'),
    ('obtained', 'adjective', 'acquired', 'Obtained results.'),
    ('participation', 'noun', 'involvement', 'Active participation.'),
    ('perceived', 'adjective', 'noticed', 'Perceived benefits.'),
    ('positive', 'adjective', 'good', 'Positive outcome.'),
    ('potential', 'noun', 'possibility', 'Full potential.'),
    ('previous', 'adjective', 'earlier', 'Previous research.'),
    ('primary', 'adjective', 'main', 'Primary source.'),
    ('purchase', 'noun', 'buying', 'Major purchase.'),
    ('range', 'noun', 'extent', 'Wide range.'),
    ('region', 'noun', 'area', 'Geographic region.'),
    ('regulations', 'noun', 'rules', 'Government regulations.'),
    ('relevant', 'adjective', 'pertinent', 'Relevant data.'),
    ('resident', 'noun', 'inhabitant', 'Local resident.'),
    ('resources', 'noun', 'supplies', 'Natural resources.'),
]

AWL_WORDS_60 = [
    # Sublist 3
    ('alternative', 'noun', 'other option', 'Consider alternatives.'),
    ('circumstances', 'noun', 'conditions', 'Under circumstances.'),
    ('comments', 'noun', 'remarks', 'Brief comments.'),
    ('compensation', 'noun', 'payment', 'Fair compensation.'),
    ('components', 'noun', 'parts', 'Key components.'),
    ('consent', 'noun', 'agreement', 'Informed consent.'),
    ('considerable', 'adjective', 'significant', 'Considerable impact.'),
    ('constant', 'adjective', 'unchanging', 'Constant rate.'),
    ('constraints', 'noun', 'limitations', 'Budget constraints.'),
    ('contribution', 'noun', 'input', 'Major contribution.'),
    ('convention', 'noun', 'tradition', 'Academic convention.'),
    ('coordination', 'noun', 'organization', 'Better coordination.'),
    ('core', 'noun', 'center', 'Core concept.'),
    ('corporate', 'adjective', 'of business', 'Corporate responsibility.'),
    ('corresponding', 'adjective', 'matching', 'Corresponding values.'),
    ('criteria', 'noun', 'standards', 'Selection criteria.'),
    ('deduction', 'noun', 'conclusion', 'Logical deduction.'),
    ('demonstrate', 'verb', 'to show', 'Demonstrate effect.'),
    ('document', 'noun', 'record', 'Official document.'),
    ('dominant', 'adjective', 'main', 'Dominant factor.'),
    ('emphasis', 'noun', 'stress', 'Place emphasis on.'),
    ('ensure', 'verb', 'to guarantee', 'Ensure quality.'),
    ('exclude', 'verb', 'to leave out', 'Exclude outliers.'),
    ('framework', 'noun', 'structure', 'Theoretical framework.'),
    ('funds', 'noun', 'money', 'Research funds.'),
    ('illustrated', 'adjective', 'shown', 'Illustrated clearly.'),
    ('immigration', 'noun', 'migration', 'Immigration policy.'),
    ('imply', 'verb', 'to suggest', 'Results imply.'),
    ('initial', 'adjective', 'first', 'Initial findings.'),
    ('instance', 'noun', 'example', 'For instance.'),
    ('interaction', 'noun', 'communication', 'Social interaction.'),
    ('justification', 'noun', 'reason', 'Provide justification.'),
    ('layer', 'noun', 'level', 'Add layer.'),
    ('link', 'noun', 'connection', 'Establish link.'),
    ('location', 'noun', 'place', 'Research location.'),
    ('maximum', 'adjective', 'greatest', 'Maximum effect.'),
    ('minorities', 'noun', 'small groups', 'Ethnic minorities.'),
    ('negative', 'adjective', 'bad', 'Negative impact.'),
    ('outcomes', 'noun', 'results', 'Expected outcomes.'),
    ('partnership', 'noun', 'alliance', 'Research partnership.'),
    ('philosophy', 'noun', 'beliefs', 'Research philosophy.'),
    ('physical', 'adjective', 'bodily', 'Physical health.'),
    ('proportion', 'noun', 'ratio', 'Large proportion.'),
    ('published', 'adjective', 'printed', 'Published research.'),
    ('reaction', 'noun', 'response', 'Initial reaction.'),
    ('registered', 'adjective', 'recorded', 'Registered participants.'),
    ('reliance', 'noun', 'dependence', 'Heavy reliance.'),
    ('removed', 'adjective', 'taken away', 'Removed from sample.'),
    ('scheme', 'noun', 'plan', 'Classification scheme.'),
    ('sequence', 'noun', 'order', 'In sequence.'),
    # Sublist 4
    ('access', 'noun', 'entry', 'Internet access.'),
    ('adequate', 'adjective', 'sufficient', 'Adequate evidence.'),
    ('annual', 'adjective', 'yearly', 'Annual report.'),
    ('apparent', 'adjective', 'obvious', 'Apparent contradiction.'),
    ('approximated', 'adjective', 'estimated', 'Approximated value.'),
    ('attitudes', 'noun', 'opinions', 'Changing attitudes.'),
    ('attributed', 'adjective', 'credited', 'Attributed to.'),
    ('civil', 'adjective', 'civic', 'Civil society.'),
    ('code', 'noun', 'system', 'Ethical code.'),
    ('commitment', 'noun', 'dedication', 'Strong commitment.'),
    ('communication', 'noun', 'exchange', 'Clear communication.'),
    ('concentration', 'noun', 'focus', 'High concentration.'),
    ('conference', 'noun', 'meeting', 'Academic conference.'),
    ('contrast', 'noun', 'difference', 'Stark contrast.'),
    ('cycle', 'noun', 'series', 'Life cycle.'),
    ('debate', 'noun', 'discussion', 'Public debate.'),
    ('despite', 'preposition', 'in spite of', 'Despite challenges.'),
    ('dimensions', 'noun', 'aspects', 'Multiple dimensions.'),
    ('domestic', 'adjective', 'national', 'Domestic policy.'),
    ('emerged', 'adjective', 'appeared', 'Emerged trends.'),
    ('error', 'noun', 'mistake', 'Margin of error.'),
    ('ethnic', 'adjective', 'racial', 'Ethnic diversity.'),
    ('goals', 'noun', 'objectives', 'Achieve goals.'),
    ('granted', 'adjective', 'given', 'Taken for granted.'),
    ('hence', 'adverb', 'therefore', 'Hence, we conclude.'),
    ('hypothesis', 'noun', 'theory', 'Test hypothesis.'),
    ('implementation', 'noun', 'execution', 'Policy implementation.'),
    ('implications', 'noun', 'consequences', 'Important implications.'),
    ('imposed', 'adjective', 'enforced', 'Imposed restrictions.'),
    ('integration', 'noun', 'combination', 'System integration.'),
]

AWL_WORDS_70 = [
    # Sublist 5
    ('academic', 'adjective', 'scholarly', 'Academic research.'),
    ('adjustment', 'noun', 'modification', 'Minor adjustment.'),
    ('alter', 'verb', 'to change', 'Alter approach.'),
    ('amendment', 'noun', 'change', 'Policy amendment.'),
    ('awareness', 'noun', 'knowledge', 'Raise awareness.'),
    ('capacity', 'noun', 'ability', 'Full capacity.'),
    ('challenge', 'noun', 'difficulty', 'Major challenge.'),
    ('clause', 'noun', 'provision', 'Contract clause.'),
    ('compounds', 'noun', 'combinations', 'Chemical compounds.'),
    ('conflict', 'noun', 'disagreement', 'Resolve conflict.'),
    ('consultation', 'noun', 'discussion', 'Expert consultation.'),
    ('contact', 'noun', 'communication', 'Make contact.'),
    ('decline', 'noun', 'decrease', 'Steady decline.'),
    ('discretion', 'noun', 'freedom to decide', 'Exercise discretion.'),
    ('draft', 'noun', 'preliminary version', 'First draft.'),
    ('enable', 'verb', 'to make possible', 'Enable progress.'),
    ('energy', 'noun', 'power', 'Renewable energy.'),
    ('enforcement', 'noun', 'implementation', 'Law enforcement.'),
    ('entities', 'noun', 'things', 'Legal entities.'),
    ('equivalent', 'adjective', 'equal', 'Equivalent results.'),
    ('evolution', 'noun', 'development', 'Theory of evolution.'),
    ('expansion', 'noun', 'growth', 'Rapid expansion.'),
    ('exposure', 'noun', 'contact', 'Media exposure.'),
    ('external', 'adjective', 'outside', 'External factors.'),
    ('facilitate', 'verb', 'to make easier', 'Facilitate learning.'),
    ('fundamental', 'adjective', 'basic', 'Fundamental concept.'),
    ('generated', 'adjective', 'produced', 'Generated results.'),
    ('generation', 'noun', 'age group', 'Younger generation.'),
    ('image', 'noun', 'picture', 'Public image.'),
    ('liberal', 'adjective', 'open-minded', 'Liberal approach.'),
    ('licence', 'noun', 'permission', 'Research licence.'),
    ('logic', 'noun', 'reasoning', 'Sound logic.'),
    ('margin', 'noun', 'edge', 'Narrow margin.'),
    ('medical', 'adjective', 'of medicine', 'Medical research.'),
    ('mental', 'adjective', 'of mind', 'Mental health.'),
    ('modified', 'adjective', 'changed', 'Modified approach.'),
    ('monitoring', 'noun', 'observation', 'Continuous monitoring.'),
    ('network', 'noun', 'system', 'Social network.'),
    ('notion', 'noun', 'idea', 'Basic notion.'),
    ('objective', 'noun', 'goal', 'Main objective.'),
    ('oriented', 'adjective', 'directed', 'Goal-oriented.'),
    ('perspective', 'noun', 'viewpoint', 'New perspective.'),
    ('precise', 'adjective', 'exact', 'Precise measurement.'),
    ('prime', 'adjective', 'main', 'Prime example.'),
    ('psychology', 'noun', 'study of mind', 'Social psychology.'),
    ('pursue', 'verb', 'to follow', 'Pursue goals.'),
    ('ratio', 'noun', 'proportion', 'High ratio.'),
    ('rejected', 'adjective', 'refused', 'Rejected hypothesis.'),
    ('revenue', 'noun', 'income', 'Annual revenue.'),
    ('stability', 'noun', 'steadiness', 'Economic stability.'),
]

AWL_WORDS_80 = [
    # Sublist 6-10 (Advanced)
    ('abstract', 'adjective', 'theoretical', 'Abstract concept.'),
    ('accommodate', 'verb', 'to provide for', 'Accommodate needs.'),
    ('acknowledge', 'verb', 'to recognize', 'Acknowledge limitations.'),
    ('aggregate', 'noun', 'total', 'In aggregate.'),
    ('allocate', 'verb', 'to assign', 'Allocate resources.'),
    ('analogous', 'adjective', 'similar', 'Analogous situation.'),
    ('anticipate', 'verb', 'to expect', 'Anticipate outcomes.'),
    ('arbitrary', 'adjective', 'random', 'Arbitrary decision.'),
    ('automate', 'verb', 'to make automatic', 'Automate process.'),
    ('bias', 'noun', 'prejudice', 'Selection bias.'),
    ('chart', 'noun', 'diagram', 'Flow chart.'),
    ('clarify', 'verb', 'to explain', 'Clarify meaning.'),
    ('commodity', 'noun', 'product', 'Basic commodity.'),
    ('compile', 'verb', 'to gather', 'Compile data.'),
    ('complement', 'verb', 'to complete', 'Complement findings.'),
    ('conceive', 'verb', 'to imagine', 'Conceive idea.'),
    ('concurrent', 'adjective', 'simultaneous', 'Concurrent events.'),
    ('confine', 'verb', 'to limit', 'Confine scope.'),
    ('contradict', 'verb', 'to deny', 'Contradict claims.'),
    ('conversely', 'adverb', 'on the other hand', 'Conversely, we find.'),
    ('deviate', 'verb', 'to differ', 'Deviate from norm.'),
    ('diminish', 'verb', 'to reduce', 'Diminish returns.'),
    ('displace', 'verb', 'to move', 'Displace workers.'),
    ('distort', 'verb', 'to misrepresent', 'Distort facts.'),
    ('empirical', 'adjective', 'based on observation', 'Empirical evidence.'),
    ('encounter', 'verb', 'to meet', 'Encounter obstacles.'),
    ('explicit', 'adjective', 'clear', 'Explicit statement.'),
    ('finite', 'adjective', 'limited', 'Finite resources.'),
    ('fluctuate', 'verb', 'to vary', 'Prices fluctuate.'),
    ('forthcoming', 'adjective', 'upcoming', 'Forthcoming publication.'),
    ('globe', 'noun', 'world', 'Around the globe.'),
    ('hierarchy', 'noun', 'ranking system', 'Social hierarchy.'),
    ('identical', 'adjective', 'same', 'Identical results.'),
    ('ideology', 'noun', 'belief system', 'Political ideology.'),
    ('incentive', 'noun', 'motivation', 'Financial incentive.'),
    ('incidence', 'noun', 'occurrence', 'High incidence.'),
    ('inclination', 'noun', 'tendency', 'Natural inclination.'),
    ('incorporate', 'verb', 'to include', 'Incorporate findings.'),
    ('induce', 'verb', 'to cause', 'Induce change.'),
    ('inhibit', 'verb', 'to prevent', 'Inhibit growth.'),
    ('inherent', 'adjective', 'built-in', 'Inherent bias.'),
    ('innovate', 'verb', 'to introduce new', 'Innovate constantly.'),
    ('integral', 'adjective', 'essential', 'Integral part.'),
    ('intermediate', 'adjective', 'middle', 'Intermediate level.'),
    ('intervene', 'verb', 'to come between', 'Intervene early.'),
    ('invoke', 'verb', 'to call upon', 'Invoke principles.'),
    ('mediate', 'verb', 'to intervene', 'Mediate conflict.'),
    ('migrate', 'verb', 'to move', 'Populations migrate.'),
    ('minimise', 'verb', 'to reduce', 'Minimise risk.'),
    ('mutual', 'adjective', 'shared', 'Mutual benefit.'),
]

CATEGORIES_45 = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
                 'Business', 'Society', 'Science', 'Culture', 'Media']
CATEGORIES_60 = ['Academic', 'Research', 'Science', 'Analysis', 'Writing', 
                 'Critical Thinking', 'Education', 'Professional', 'Data', 'Theory']
CATEGORIES_70 = ['Academic Writing', 'Research Methods', 'Critical Analysis', 
                 'Advanced Theory', 'Scholarly Discussion', 'Professional Development']
CATEGORIES_80 = ['Advanced Academic Writing', 'Sophisticated Argumentation', 
                 'Expert Level Research', 'High-Level Critical Analysis']

def add_words(filename, words, level, categories):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            existing = json.load(f)
    except:
        existing = []
    
    existing_words = {w['word'] for w in existing}
    start_id = len(existing) + 1
    added = 0
    
    for word, pos, definition, example in words:
        if word not in existing_words:
            existing.append({
                'id': start_id + added,
                'word': word,
                'level': level,
                'partOfSpeech': pos,
                'definition': definition,
                'example': example,
                'category': categories[(start_id + added) % len(categories)]
            })
            existing_words.add(word)
            added += 1
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    return len(existing), added

def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    total45, added45 = add_words('assets/data/band45_words.json', AWL_WORDS_45, 'Band 4.5-5.5', CATEGORIES_45)
    print(f'✅ Band 4.5-5.5: {total45}개 (추가: {added45}개)')
    
    total60, added60 = add_words('assets/data/band60_words.json', AWL_WORDS_60, 'Band 6.0-6.5', CATEGORIES_60)
    print(f'✅ Band 6.0-6.5: {total60}개 (추가: {added60}개)')
    
    total70, added70 = add_words('assets/data/band70_words.json', AWL_WORDS_70, 'Band 7.0-7.5', CATEGORIES_70)
    print(f'✅ Band 7.0-7.5: {total70}개 (추가: {added70}개)')
    
    total80, added80 = add_words('assets/data/band80_words.json', AWL_WORDS_80, 'Band 8.0+', CATEGORIES_80)
    print(f'✅ Band 8.0+: {total80}개 (추가: {added80}개)')

if __name__ == '__main__':
    main()
