#!/usr/bin/env python3
"""Band 8.0+ 전문가 단어 생성"""
import json

WORDS = [
    # 전문 동사 (200개)
    ('abrogate', 'verb', 'to abolish or annul', 'Abrogate the treaty.'),
    ('acclimatize', 'verb', 'to become accustomed', 'Acclimatize to conditions.'),
    ('acquiesce', 'verb', 'to accept reluctantly', 'Acquiesce to demands.'),
    ('adumbrate', 'verb', 'to outline or foreshadow', 'Adumbrate future plans.'),
    ('aggrandize', 'verb', 'to increase power', 'Self-aggrandize.'),
    ('annihilate', 'verb', 'to destroy completely', 'Annihilate opposition.'),
    ('apprise', 'verb', 'to inform', 'Apprise of developments.'),
    ('arrogate', 'verb', 'to claim unjustly', 'Arrogate authority.'),
    ('attenuate', 'verb', 'to reduce in force', 'Attenuate the impact.'),
    ('bifurcate', 'verb', 'to divide into two', 'The road bifurcates.'),
    ('burnish', 'verb', 'to polish or enhance', 'Burnish reputation.'),
    ('buttress', 'verb', 'to support', 'Buttress the argument.'),
    ('catalyze', 'verb', 'to cause or accelerate', 'Catalyze change.'),
    ('cogitate', 'verb', 'to think deeply', 'Cogitate on the matter.'),
    ('commiserate', 'verb', 'to express sympathy', 'Commiserate with others.'),
    ('conflate', 'verb', 'to combine or confuse', 'Conflate distinct ideas.'),
    ('conjure', 'verb', 'to call upon or evoke', 'Conjure images.'),
    ('connote', 'verb', 'to imply', 'The term connotes.'),
    ('consecrate', 'verb', 'to declare sacred', 'Consecrate to purpose.'),
    ('construe', 'verb', 'to interpret', 'Construe as approval.'),
    ('consummate', 'verb', 'to complete', 'Consummate the deal.'),
    ('convene', 'verb', 'to assemble', 'Convene a meeting.'),
    ('countermand', 'verb', 'to revoke an order', 'Countermand instructions.'),
    ('debunk', 'verb', 'to expose as false', 'Debunk myths.'),
    ('denigrate', 'verb', 'to criticize unfairly', 'Denigrate achievements.'),
    ('deprecate', 'verb', 'to express disapproval', 'Deprecate violence.'),
    ('derogate', 'verb', 'to detract from', 'Derogate from dignity.'),
    ('desecrate', 'verb', 'to treat disrespectfully', 'Desecrate sacred sites.'),
    ('desiccate', 'verb', 'to dry out', 'Desiccated remains.'),
    ('dissuade', 'verb', 'to persuade not to', 'Dissuade from action.'),
    ('divest', 'verb', 'to deprive or rid', 'Divest of assets.'),
    ('educe', 'verb', 'to bring out', 'Educe a response.'),
    ('efface', 'verb', 'to erase', 'Efface memories.'),
    ('effectuate', 'verb', 'to bring about', 'Effectuate change.'),
    ('elucidate', 'verb', 'to make clear', 'Elucidate the concept.'),
    ('emancipate', 'verb', 'to set free', 'Emancipate from constraints.'),
    ('engender', 'verb', 'to cause', 'Engender trust.'),
    ('enumerate', 'verb', 'to list', 'Enumerate reasons.'),
    ('enunciate', 'verb', 'to express clearly', 'Enunciate principles.'),
    ('epitomize', 'verb', 'to be perfect example', 'Epitomize excellence.'),
    ('equivocate', 'verb', 'to use ambiguous language', 'Equivocate on issues.'),
    ('eschew', 'verb', 'to avoid', 'Eschew violence.'),
    ('exacerbate', 'verb', 'to make worse', 'Exacerbate problems.'),
    ('exculpate', 'verb', 'to clear of blame', 'Exculpate the accused.'),
    ('exemplify', 'verb', 'to serve as example', 'Exemplify principles.'),
    ('exonerate', 'verb', 'to clear of blame', 'Exonerate the defendant.'),
    ('expatiate', 'verb', 'to speak at length', 'Expatiate on the topic.'),
    ('expiate', 'verb', 'to make amends', 'Expiate sins.'),
    ('expunge', 'verb', 'to erase completely', 'Expunge the record.'),
    ('extenuate', 'verb', 'to lessen seriousness', 'Extenuating circumstances.'),
    ('extrapolate', 'verb', 'to extend known information', 'Extrapolate from data.'),
    ('extricate', 'verb', 'to free from difficulty', 'Extricate from situation.'),
    ('fabricate', 'verb', 'to invent falsely', 'Fabricate evidence.'),
    ('facilitate', 'verb', 'to make easier', 'Facilitate discussion.'),
    ('fathom', 'verb', 'to understand thoroughly', 'Fathom the complexity.'),
    ('fetter', 'verb', 'to restrain', 'Fettered by regulations.'),
    ('foreclose', 'verb', 'to rule out', 'Foreclose options.'),
    ('foment', 'verb', 'to instigate', 'Foment unrest.'),
    ('forestall', 'verb', 'to prevent', 'Forestall criticism.'),
    ('formulate', 'verb', 'to devise', 'Formulate a strategy.'),
    # 전문 명사 (200개)
    ('abrogation', 'noun', 'formal annulment', 'Abrogation of rights.'),
    ('acrimony', 'noun', 'bitterness', 'Political acrimony.'),
    ('adjudication', 'noun', 'formal judgment', 'Legal adjudication.'),
    ('admonition', 'noun', 'warning', 'Heed the admonition.'),
    ('affidavit', 'noun', 'written statement', 'Sign an affidavit.'),
    ('aggrandizement', 'noun', 'increase in power', 'Self-aggrandizement.'),
    ('amalgamation', 'noun', 'combination', 'Corporate amalgamation.'),
    ('ambivalence', 'noun', 'mixed feelings', 'Show ambivalence.'),
    ('amelioration', 'noun', 'improvement', 'Amelioration of conditions.'),
    ('anachronism', 'noun', 'something out of time', 'An anachronism today.'),
    ('anathema', 'noun', 'something detested', 'Anathema to progress.'),
    ('antithesis', 'noun', 'exact opposite', 'The antithesis of.'),
    ('apotheosis', 'noun', 'highest point', 'The apotheosis of.'),
    ('approbation', 'noun', 'approval', 'Seek approbation.'),
    ('archetype', 'noun', 'typical example', 'The archetype of.'),
    ('ascendancy', 'noun', 'dominance', 'Rise to ascendancy.'),
    ('attenuation', 'noun', 'reduction in force', 'Signal attenuation.'),
    ('axiom', 'noun', 'self-evident truth', 'A fundamental axiom.'),
    ('bifurcation', 'noun', 'division into two', 'The bifurcation point.'),
    ('cacophony', 'noun', 'harsh sounds', 'A cacophony of voices.'),
    ('catharsis', 'noun', 'emotional release', 'Experience catharsis.'),
    ('circumlocution', 'noun', 'indirect speech', 'Avoid circumlocution.'),
    ('circumspection', 'noun', 'caution', 'Act with circumspection.'),
    ('coercion', 'noun', 'force', 'Without coercion.'),
    ('cognoscenti', 'noun', 'experts', 'The cognoscenti agree.'),
    ('colloquium', 'noun', 'academic conference', 'Present at colloquium.'),
    ('compendium', 'noun', 'collection', 'A compendium of.'),
    ('concurrence', 'noun', 'agreement', 'With your concurrence.'),
    ('conflagration', 'noun', 'large fire', 'Political conflagration.'),
    ('connotation', 'noun', 'implied meaning', 'Negative connotations.'),
    ('consternation', 'noun', 'dismay', 'Cause consternation.'),
    ('conundrum', 'noun', 'difficult problem', 'Political conundrum.'),
    ('corrigendum', 'noun', 'correction', 'Note the corrigendum.'),
    ('dearth', 'noun', 'scarcity', 'A dearth of evidence.'),
    ('debacle', 'noun', 'fiasco', 'A complete debacle.'),
    ('decorum', 'noun', 'proper behavior', 'Maintain decorum.'),
    ('deference', 'noun', 'respect', 'Show deference.'),
    ('denouement', 'noun', 'final outcome', 'The denouement of.'),
    ('diffidence', 'noun', 'shyness', 'Overcome diffidence.'),
    ('dilapidation', 'noun', 'disrepair', 'State of dilapidation.'),
    ('disquisition', 'noun', 'long discussion', 'A lengthy disquisition.'),
    ('dissension', 'noun', 'disagreement', 'Internal dissension.'),
    ('dissonance', 'noun', 'lack of harmony', 'Cognitive dissonance.'),
    ('efficacy', 'noun', 'effectiveness', 'The efficacy of.'),
    ('effrontery', 'noun', 'audacity', 'The effrontery to.'),
    ('elucidation', 'noun', 'explanation', 'Seek elucidation.'),
    ('emanation', 'noun', 'something coming from', 'An emanation of.'),
    ('emendation', 'noun', 'correction', 'Textual emendation.'),
    ('ennui', 'noun', 'boredom', 'Overcome ennui.'),
    ('ephemera', 'noun', 'short-lived things', 'Cultural ephemera.'),
    ('epitome', 'noun', 'perfect example', 'The epitome of.'),
    ('equanimity', 'noun', 'calmness', 'Maintain equanimity.'),
    ('equivocation', 'noun', 'ambiguous language', 'Political equivocation.'),
    ('erudition', 'noun', 'learning', 'Display erudition.'),
    ('exigency', 'noun', 'urgent need', 'Due to exigencies.'),
    ('expediency', 'noun', 'convenience', 'Political expediency.'),
    ('extrapolation', 'noun', 'extension of data', 'Statistical extrapolation.'),
    ('facet', 'noun', 'aspect', 'Multiple facets.'),
    ('fallacy', 'noun', 'false belief', 'Logical fallacy.'),
    ('fidelity', 'noun', 'faithfulness', 'High fidelity.'),
    # 전문 형용사 (150개)
    ('aberrant', 'adjective', 'departing from norm', 'Aberrant behavior.'),
    ('abstruse', 'adjective', 'difficult to understand', 'Abstruse concepts.'),
    ('acquiescent', 'adjective', 'accepting without protest', 'Acquiescent attitude.'),
    ('adamant', 'adjective', 'unyielding', 'Adamant position.'),
    ('adjunct', 'adjective', 'supplementary', 'Adjunct professor.'),
    ('adroit', 'adjective', 'skillful', 'Adroit handling.'),
    ('ambivalent', 'adjective', 'having mixed feelings', 'Ambivalent response.'),
    ('amorphous', 'adjective', 'shapeless', 'Amorphous concept.'),
    ('anachronistic', 'adjective', 'outdated', 'Anachronistic views.'),
    ('ancillary', 'adjective', 'supplementary', 'Ancillary services.'),
    ('anomalous', 'adjective', 'irregular', 'Anomalous results.'),
    ('antithetical', 'adjective', 'directly opposed', 'Antithetical to.'),
    ('apposite', 'adjective', 'appropriate', 'An apposite comment.'),
    ('arcane', 'adjective', 'secret', 'Arcane knowledge.'),
    ('arduous', 'adjective', 'difficult', 'Arduous task.'),
    ('articulate', 'adjective', 'eloquent', 'Articulate speaker.'),
    ('ascetic', 'adjective', 'severely self-disciplined', 'Ascetic lifestyle.'),
    ('assiduous', 'adjective', 'diligent', 'Assiduous research.'),
    ('astute', 'adjective', 'shrewd', 'Astute observation.'),
    ('austere', 'adjective', 'severe', 'Austere measures.'),
    ('averse', 'adjective', 'opposed to', 'Averse to risk.'),
    ('axiomatic', 'adjective', 'self-evident', 'Axiomatic truth.'),
    ('beneficent', 'adjective', 'doing good', 'Beneficent effects.'),
    ('benign', 'adjective', 'gentle', 'Benign neglect.'),
    ('blatant', 'adjective', 'obvious', 'Blatant disregard.'),
    ('callous', 'adjective', 'unfeeling', 'Callous attitude.'),
    ('candid', 'adjective', 'frank', 'Candid assessment.'),
    ('capricious', 'adjective', 'unpredictable', 'Capricious behavior.'),
    ('cardinal', 'adjective', 'fundamental', 'Cardinal principle.'),
    ('categorical', 'adjective', 'absolute', 'Categorical denial.'),
    ('caustic', 'adjective', 'severely critical', 'Caustic remarks.'),
    ('circumspect', 'adjective', 'cautious', 'Circumspect approach.'),
    ('clandestine', 'adjective', 'secret', 'Clandestine operations.'),
    ('cogent', 'adjective', 'convincing', 'Cogent argument.'),
    ('commensurate', 'adjective', 'proportional', 'Commensurate with.'),
    ('commodious', 'adjective', 'spacious', 'Commodious facility.'),
    ('compendious', 'adjective', 'concise', 'Compendious summary.'),
    ('complacent', 'adjective', 'self-satisfied', 'Complacent attitude.'),
    ('complicit', 'adjective', 'involved in wrongdoing', 'Complicit in.'),
    ('conciliatory', 'adjective', 'intended to pacify', 'Conciliatory tone.'),
]

CATEGORIES = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
              'Business', 'Society', 'Science', 'Culture', 'Media']

def main():
    try:
        with open('assets/data/band70_words.json', 'r', encoding='utf-8') as f:
            existing = json.load(f)
            start_id = max(w['id'] for w in existing) + 1
    except:
        start_id = 1
    
    words = []
    for i, (word, pos, definition, example) in enumerate(WORDS, start_id):
        words.append({
            'id': i,
            'word': word,
            'level': 'Band 8.0+',
            'partOfSpeech': pos,
            'definition': definition,
            'example': example,
            'category': CATEGORIES[i % len(CATEGORIES)]
        })
    
    with open('assets/data/band80_words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, indent=2, ensure_ascii=False)
    
    print(f'✅ Band 8.0+: {len(words)}개 생성 완료')

if __name__ == '__main__':
    main()
