#!/usr/bin/env python3
"""Band 4.5-5.5 기초 단어 1,200개 생성"""
import json

WORDS = [
    # 기본 동사 (300개)
    ('accept', 'verb', 'to agree to receive', 'I accept your offer.'),
    ('achieve', 'verb', 'to succeed in doing', 'She achieved her goals.'),
    ('act', 'verb', 'to do something', 'We must act quickly.'),
    ('add', 'verb', 'to put together', 'Add more details.'),
    ('admit', 'verb', 'to confess', 'He admitted his mistake.'),
    ('affect', 'verb', 'to influence', 'Weather affects mood.'),
    ('agree', 'verb', 'to have same opinion', 'I agree with you.'),
    ('allow', 'verb', 'to permit', 'Allow children to play.'),
    ('answer', 'verb', 'to respond', 'Answer the question.'),
    ('appear', 'verb', 'to become visible', 'Stars appear at night.'),
    ('apply', 'verb', 'to make a request', 'Apply for the job.'),
    ('argue', 'verb', 'to give reasons', 'They argue about politics.'),
    ('arrange', 'verb', 'to organize', 'Arrange a meeting.'),
    ('arrive', 'verb', 'to reach destination', 'The train arrived late.'),
    ('ask', 'verb', 'to request info', 'Ask a question.'),
    ('assume', 'verb', 'to suppose', 'Do not assume anything.'),
    ('avoid', 'verb', 'to keep away from', 'Avoid making mistakes.'),
    ('base', 'verb', 'to use as foundation', 'Base your argument on facts.'),
    ('become', 'verb', 'to begin to be', 'She became a doctor.'),
    ('begin', 'verb', 'to start', 'Begin the presentation.'),
    ('believe', 'verb', 'to accept as true', 'I believe in equality.'),
    ('belong', 'verb', 'to be member of', 'This belongs to me.'),
    ('break', 'verb', 'to separate', 'Do not break the rules.'),
    ('bring', 'verb', 'to carry toward', 'Bring your documents.'),
    ('build', 'verb', 'to construct', 'Build a strong foundation.'),
    ('buy', 'verb', 'to purchase', 'Buy local products.'),
    ('call', 'verb', 'to name or phone', 'Call me tomorrow.'),
    ('care', 'verb', 'to feel concern', 'I care about environment.'),
    ('carry', 'verb', 'to transport', 'Carry your ID card.'),
    ('catch', 'verb', 'to capture', 'Catch the opportunity.'),
    ('cause', 'verb', 'to make happen', 'Pollution causes problems.'),
    ('change', 'verb', 'to make different', 'Change your approach.'),
    ('check', 'verb', 'to examine', 'Check your answers.'),
    ('choose', 'verb', 'to select', 'Choose the best option.'),
    ('claim', 'verb', 'to assert', 'Scientists claim findings.'),
    ('close', 'verb', 'to shut', 'Close the discussion.'),
    ('come', 'verb', 'to move toward', 'Come to the meeting.'),
    ('compare', 'verb', 'to examine differences', 'Compare the two methods.'),
    ('complete', 'verb', 'to finish', 'Complete the assignment.'),
    ('concern', 'verb', 'to relate to', 'This concerns everyone.'),
    ('consider', 'verb', 'to think carefully', 'Consider all options.'),
    ('contain', 'verb', 'to hold within', 'The report contains errors.'),
    ('continue', 'verb', 'to keep going', 'Continue your research.'),
    ('control', 'verb', 'to have power over', 'Control the situation.'),
    ('cost', 'verb', 'to require payment', 'It costs too much.'),
    ('cover', 'verb', 'to place over', 'The study covers topics.'),
    ('create', 'verb', 'to make new', 'Create innovative solutions.'),
    ('cut', 'verb', 'to divide', 'Cut unnecessary costs.'),
    ('deal', 'verb', 'to handle', 'Deal with the problem.'),
    ('decide', 'verb', 'to make choice', 'Decide on priorities.'),
    ('define', 'verb', 'to explain meaning', 'Define the concept clearly.'),
    ('deliver', 'verb', 'to bring to', 'Deliver the results on time.'),
    ('demand', 'verb', 'to ask firmly', 'Demand an explanation.'),
    ('demonstrate', 'verb', 'to show clearly', 'Demonstrate the process.'),
    ('depend', 'verb', 'to rely on', 'Success depends on effort.'),
    ('describe', 'verb', 'to give details', 'Describe your experience.'),
    ('design', 'verb', 'to plan', 'Design a new system.'),
    ('destroy', 'verb', 'to damage completely', 'Fire destroyed the building.'),
    ('determine', 'verb', 'to decide', 'Determine the cause.'),
    ('develop', 'verb', 'to grow', 'Develop new skills.'),
    ('die', 'verb', 'to stop living', 'Plants die without water.'),
    ('disappear', 'verb', 'to vanish', 'Problems disappeared quickly.'),
    ('discover', 'verb', 'to find out', 'Discover new possibilities.'),
    ('discuss', 'verb', 'to talk about', 'Discuss the issue.'),
    ('divide', 'verb', 'to separate', 'Divide into groups.'),
    ('draw', 'verb', 'to make picture', 'Draw a conclusion.'),
    ('drive', 'verb', 'to operate vehicle', 'Drive economic growth.'),
    ('drop', 'verb', 'to fall', 'Prices dropped significantly.'),
    ('eat', 'verb', 'to consume food', 'Eat healthy food.'),
    ('employ', 'verb', 'to give work to', 'The company employs thousands.'),
    ('encourage', 'verb', 'to give support', 'Encourage participation.'),
    ('end', 'verb', 'to finish', 'End the debate.'),
    ('enjoy', 'verb', 'to take pleasure', 'Enjoy the experience.'),
    ('enter', 'verb', 'to go into', 'Enter the competition.'),
    ('establish', 'verb', 'to set up', 'Establish clear guidelines.'),
    ('examine', 'verb', 'to inspect', 'Examine the evidence.'),
    ('exist', 'verb', 'to be real', 'Problems still exist.'),
    ('expect', 'verb', 'to anticipate', 'Expect good results.'),
    ('experience', 'verb', 'to undergo', 'Experience different cultures.'),
    ('explain', 'verb', 'to make clear', 'Explain your reasoning.'),
    ('express', 'verb', 'to show feelings', 'Express your opinion.'),
    ('extend', 'verb', 'to make longer', 'Extend the deadline.'),
    ('face', 'verb', 'to deal with', 'Face the challenges.'),
    ('fail', 'verb', 'to not succeed', 'Do not fail to respond.'),
    ('fall', 'verb', 'to drop down', 'Temperatures fall in winter.'),
    ('fear', 'verb', 'to be afraid', 'Fear the consequences.'),
    ('feel', 'verb', 'to sense', 'Feel confident about results.'),
    ('fight', 'verb', 'to struggle against', 'Fight against injustice.'),
    ('fill', 'verb', 'to make full', 'Fill in the form.'),
    ('find', 'verb', 'to discover', 'Find the solution.'),
    ('finish', 'verb', 'to complete', 'Finish the project.'),
    ('fit', 'verb', 'to be suitable', 'Fit the requirements.'),
    ('follow', 'verb', 'to go after', 'Follow the instructions.'),
    ('force', 'verb', 'to make someone do', 'Force change to happen.'),
    ('forget', 'verb', 'to not remember', 'Do not forget the deadline.'),
    ('form', 'verb', 'to create', 'Form a committee.'),
    ('gain', 'verb', 'to obtain', 'Gain experience.'),
    ('get', 'verb', 'to obtain', 'Get the information.'),
    ('give', 'verb', 'to provide', 'Give an example.'),
    ('go', 'verb', 'to move', 'Go to the conference.'),
    # 기본 명사 (400개)
    ('ability', 'noun', 'capacity to do', 'Improve your ability.'),
    ('access', 'noun', 'means of approaching', 'Access to education.'),
    ('account', 'noun', 'a record', 'Give an account of events.'),
    ('action', 'noun', 'process of doing', 'Take immediate action.'),
    ('activity', 'noun', 'something done', 'Physical activity is healthy.'),
    ('advantage', 'noun', 'favorable condition', 'Use technology to advantage.'),
    ('advice', 'noun', 'guidance', 'Follow expert advice.'),
    ('age', 'noun', 'length of time lived', 'Age affects learning.'),
    ('aim', 'noun', 'purpose', 'The main aim of study.'),
    ('amount', 'noun', 'quantity', 'A large amount of data.'),
    ('analysis', 'noun', 'detailed examination', 'Conduct thorough analysis.'),
    ('answer', 'noun', 'response', 'Find the correct answer.'),
    ('approach', 'noun', 'way of dealing', 'A new approach to learning.'),
    ('area', 'noun', 'region', 'Urban areas are growing.'),
    ('argument', 'noun', 'reason given', 'Present strong argument.'),
    ('art', 'noun', 'creative expression', 'Art reflects culture.'),
    ('attention', 'noun', 'notice', 'Pay attention to details.'),
    ('authority', 'noun', 'power to control', 'Local authorities decided.'),
    ('basis', 'noun', 'foundation', 'On the basis of evidence.'),
    ('beginning', 'noun', 'start', 'From the beginning.'),
    ('behavior', 'noun', 'way one acts', 'Human behavior is complex.'),
    ('benefit', 'noun', 'advantage', 'The benefits of exercise.'),
    ('body', 'noun', 'physical structure', 'The human body.'),
    ('book', 'noun', 'written work', 'Read the book carefully.'),
    ('building', 'noun', 'structure', 'Modern buildings save energy.'),
    ('business', 'noun', 'commercial activity', 'Start a new business.'),
    ('case', 'noun', 'instance', 'In this case, we disagree.'),
    ('cause', 'noun', 'reason', 'The cause of the problem.'),
    ('center', 'noun', 'middle point', 'The city center is busy.'),
    ('century', 'noun', '100 years', 'The 21st century began.'),
    ('chance', 'noun', 'possibility', 'Give everyone a chance.'),
    ('change', 'noun', 'alteration', 'Climate change is real.'),
    ('child', 'noun', 'young person', 'Every child deserves education.'),
    ('choice', 'noun', 'option', 'Make the right choice.'),
    ('city', 'noun', 'large town', 'Cities are expanding.'),
    ('class', 'noun', 'group', 'Attend the morning class.'),
    ('community', 'noun', 'group of people', 'Support your community.'),
    ('company', 'noun', 'business', 'The company employs thousands.'),
    ('condition', 'noun', 'state', 'Living conditions improved.'),
    ('control', 'noun', 'power to direct', 'Gain control of situation.'),
    ('cost', 'noun', 'price paid', 'The cost of living.'),
    ('country', 'noun', 'nation', 'Developing countries face challenges.'),
    ('course', 'noun', 'series of lessons', 'Take an online course.'),
    ('culture', 'noun', 'customs', 'Respect different cultures.'),
    ('data', 'noun', 'facts', 'Collect relevant data.'),
    ('day', 'noun', '24-hour period', 'One day at a time.'),
    ('decision', 'noun', 'conclusion', 'Make informed decision.'),
    ('demand', 'noun', 'request', 'High demand for skills.'),
    ('development', 'noun', 'growth', 'Sustainable development.'),
    ('difference', 'noun', 'distinction', 'Notice the difference.'),
    ('direction', 'noun', 'course', 'Move in right direction.'),
    ('discussion', 'noun', 'conversation', 'Join the discussion.'),
    ('economy', 'noun', 'financial system', 'The global economy.'),
    ('education', 'noun', 'learning process', 'Education is essential.'),
    ('effect', 'noun', 'result', 'The effect of policy.'),
    ('effort', 'noun', 'attempt', 'Make an effort.'),
    ('end', 'noun', 'final part', 'At the end of the day.'),
    ('energy', 'noun', 'power', 'Renewable energy sources.'),
    ('environment', 'noun', 'surroundings', 'Protect the environment.'),
    ('event', 'noun', 'occurrence', 'A significant event.'),
    ('evidence', 'noun', 'proof', 'Scientific evidence shows.'),
    ('example', 'noun', 'instance', 'For example, consider this.'),
    ('experience', 'noun', 'practical contact', 'Gain valuable experience.'),
    ('fact', 'noun', 'truth', 'The fact remains.'),
    ('family', 'noun', 'group of relatives', 'Family support is important.'),
    ('field', 'noun', 'area of study', 'In the field of science.'),
    ('figure', 'noun', 'number', 'The figures show increase.'),
    ('film', 'noun', 'movie', 'Watch a documentary film.'),
    ('food', 'noun', 'nourishment', 'Healthy food choices.'),
    ('force', 'noun', 'power', 'The force of argument.'),
    ('form', 'noun', 'type', 'A new form of energy.'),
    ('friend', 'noun', 'companion', 'A true friend helps.'),
    ('future', 'noun', 'time ahead', 'Plan for the future.'),
    ('game', 'noun', 'activity', 'Play the game fairly.'),
    ('government', 'noun', 'ruling body', 'Government policies change.'),
    ('group', 'noun', 'collection', 'A group of experts.'),
    ('growth', 'noun', 'increase', 'Economic growth slowed.'),
    ('health', 'noun', 'physical condition', 'Mental health matters.'),
    ('help', 'noun', 'assistance', 'Ask for help.'),
    ('history', 'noun', 'past events', 'Learn from history.'),
    ('home', 'noun', 'residence', 'Work from home.'),
    ('hour', 'noun', '60 minutes', 'Wait for an hour.'),
    ('house', 'noun', 'building', 'Buy a house.'),
    ('idea', 'noun', 'thought', 'Share your ideas.'),
    ('image', 'noun', 'picture', 'Create a positive image.'),
    ('importance', 'noun', 'significance', 'The importance of education.'),
    ('increase', 'noun', 'growth', 'A significant increase.'),
    ('individual', 'noun', 'person', 'Each individual matters.'),
    ('industry', 'noun', 'economic sector', 'The tech industry grows.'),
    ('information', 'noun', 'facts', 'Access information online.'),
    ('interest', 'noun', 'attention', 'Show interest in learning.'),
    ('issue', 'noun', 'topic', 'Address the main issue.'),
    ('job', 'noun', 'work', 'Find a good job.'),
    ('knowledge', 'noun', 'understanding', 'Gain knowledge through study.'),
    ('land', 'noun', 'ground', 'Agricultural land decreases.'),
    ('language', 'noun', 'communication system', 'Learn a new language.'),
    ('law', 'noun', 'rule', 'Follow the law.'),
    ('leader', 'noun', 'person in charge', 'A strong leader inspires.'),
    ('level', 'noun', 'degree', 'High level of skill.'),
    ('life', 'noun', 'existence', 'Quality of life improves.'),
    # 기본 형용사 (300개)
    ('able', 'adjective', 'having skill', 'Be able to adapt.'),
    ('available', 'adjective', 'accessible', 'Resources are available.'),
    ('basic', 'adjective', 'fundamental', 'Learn basic concepts.'),
    ('big', 'adjective', 'large', 'A big improvement.'),
    ('certain', 'adjective', 'sure', 'Certain factors matter.'),
    ('clear', 'adjective', 'easy to understand', 'Make your point clear.'),
    ('common', 'adjective', 'frequent', 'A common misconception.'),
    ('complete', 'adjective', 'whole', 'A complete analysis.'),
    ('concerned', 'adjective', 'worried', 'Concerned about future.'),
    ('current', 'adjective', 'present', 'Current trends show.'),
    ('different', 'adjective', 'not same', 'Different perspectives.'),
    ('difficult', 'adjective', 'hard', 'A difficult decision.'),
    ('early', 'adjective', 'near beginning', 'Early intervention helps.'),
    ('easy', 'adjective', 'simple', 'An easy solution.'),
    ('economic', 'adjective', 'relating to economy', 'Economic growth.'),
    ('effective', 'adjective', 'producing results', 'An effective strategy.'),
    ('environmental', 'adjective', 'relating to nature', 'Environmental protection.'),
    ('essential', 'adjective', 'necessary', 'Essential skills needed.'),
    ('final', 'adjective', 'last', 'The final result.'),
    ('financial', 'adjective', 'relating to money', 'Financial support.'),
    ('foreign', 'adjective', 'from another country', 'Foreign investment.'),
    ('free', 'adjective', 'without cost', 'Free education.'),
    ('full', 'adjective', 'complete', 'Full participation.'),
    ('future', 'adjective', 'yet to come', 'Future generations.'),
    ('general', 'adjective', 'overall', 'General consensus.'),
    ('global', 'adjective', 'worldwide', 'Global warming.'),
    ('good', 'adjective', 'high quality', 'Good practices.'),
    ('great', 'adjective', 'large', 'Great progress.'),
    ('high', 'adjective', 'elevated', 'High expectations.'),
    ('human', 'adjective', 'relating to people', 'Human rights.'),
    ('important', 'adjective', 'significant', 'Important decisions.'),
    ('individual', 'adjective', 'single', 'Individual needs vary.'),
    ('international', 'adjective', 'between nations', 'International cooperation.'),
    ('large', 'adjective', 'big', 'A large population.'),
    ('late', 'adjective', 'after expected', 'Late submissions.'),
    ('legal', 'adjective', 'relating to law', 'Legal requirements.'),
    ('likely', 'adjective', 'probable', 'Likely outcomes.'),
    ('local', 'adjective', 'relating to area', 'Local businesses.'),
    ('long', 'adjective', 'extended', 'Long-term planning.'),
    ('low', 'adjective', 'below average', 'Low income.'),
    ('main', 'adjective', 'primary', 'The main reason.'),
    ('major', 'adjective', 'important', 'A major breakthrough.'),
    ('medical', 'adjective', 'relating to medicine', 'Medical advances.'),
    ('national', 'adjective', 'relating to nation', 'National policies.'),
    ('natural', 'adjective', 'in nature', 'Natural resources.'),
    ('necessary', 'adjective', 'required', 'Necessary steps.'),
    ('new', 'adjective', 'recent', 'New technologies.'),
    ('normal', 'adjective', 'usual', 'Normal conditions.'),
    ('old', 'adjective', 'not new', 'Old methods.'),
    ('open', 'adjective', 'not closed', 'Open communication.'),
    ('particular', 'adjective', 'specific', 'A particular case.'),
    ('personal', 'adjective', 'individual', 'Personal experience.'),
    ('physical', 'adjective', 'bodily', 'Physical activity.'),
    ('political', 'adjective', 'relating to politics', 'Political decisions.'),
    ('poor', 'adjective', 'lacking money', 'Poor communities.'),
    ('popular', 'adjective', 'well-liked', 'Popular opinion.'),
    ('positive', 'adjective', 'good', 'Positive results.'),
    ('possible', 'adjective', 'able to happen', 'Possible solutions.'),
    ('present', 'adjective', 'current', 'Present situation.'),
    ('private', 'adjective', 'not public', 'Private sector.'),
    ('public', 'adjective', 'open to all', 'Public services.'),
    ('real', 'adjective', 'actual', 'Real problems.'),
    ('recent', 'adjective', 'not long ago', 'Recent research.'),
    ('responsible', 'adjective', 'accountable', 'Responsible behavior.'),
    ('right', 'adjective', 'correct', 'The right answer.'),
    ('safe', 'adjective', 'protected', 'Safe environment.'),
    ('serious', 'adjective', 'grave', 'A serious issue.'),
    ('short', 'adjective', 'brief', 'Short-term goals.'),
    ('similar', 'adjective', 'alike', 'Similar results.'),
    ('simple', 'adjective', 'easy', 'A simple solution.'),
    ('single', 'adjective', 'one only', 'A single factor.'),
    ('small', 'adjective', 'little', 'Small changes matter.'),
    ('social', 'adjective', 'relating to society', 'Social issues.'),
    ('special', 'adjective', 'unique', 'Special attention.'),
    ('specific', 'adjective', 'particular', 'Specific requirements.'),
    ('strong', 'adjective', 'powerful', 'Strong evidence.'),
    ('successful', 'adjective', 'achieving aims', 'Successful outcomes.'),
    ('sure', 'adjective', 'certain', 'Make sure it works.'),
    ('traditional', 'adjective', 'customary', 'Traditional methods.'),
    ('true', 'adjective', 'accurate', 'True statement.'),
    ('various', 'adjective', 'different', 'Various factors.'),
    ('whole', 'adjective', 'entire', 'The whole process.'),
    ('wide', 'adjective', 'broad', 'Wide range of topics.'),
    ('wrong', 'adjective', 'incorrect', 'Wrong approach.'),
    ('young', 'adjective', 'not old', 'Young people today.'),
    # 부사 및 연결어 (200개)
    ('actually', 'adverb', 'in fact', 'Actually, research shows.'),
    ('already', 'adverb', 'by this time', 'Already completed.'),
    ('also', 'adverb', 'in addition', 'Also consider factors.'),
    ('always', 'adverb', 'at all times', 'Always verify sources.'),
    ('certainly', 'adverb', 'definitely', 'Certainly true.'),
    ('clearly', 'adverb', 'obviously', 'Clearly needed.'),
    ('directly', 'adverb', 'without intermediary', 'Directly affects.'),
    ('especially', 'adverb', 'particularly', 'Especially important.'),
    ('even', 'adverb', 'emphasis', 'Even experts disagree.'),
    ('eventually', 'adverb', 'in the end', 'Eventually emerged.'),
    ('finally', 'adverb', 'at last', 'Finally reached agreement.'),
    ('frequently', 'adverb', 'often', 'Frequently cited.'),
    ('fully', 'adverb', 'completely', 'Fully understand.'),
    ('generally', 'adverb', 'usually', 'Generally speaking.'),
    ('however', 'adverb', 'nevertheless', 'However, exceptions exist.'),
    ('immediately', 'adverb', 'at once', 'Immediately address.'),
    ('indeed', 'adverb', 'truly', 'Indeed confirms.'),
    ('just', 'adverb', 'exactly', 'Just as predicted.'),
    ('mainly', 'adverb', 'chiefly', 'Mainly focused.'),
    ('nearly', 'adverb', 'almost', 'Nearly half participated.'),
    ('never', 'adverb', 'at no time', 'Never ignore data.'),
    ('now', 'adverb', 'at present', 'Now is the time.'),
    ('often', 'adverb', 'frequently', 'Often overlooked.'),
    ('only', 'adverb', 'solely', 'Only one solution.'),
    ('particularly', 'adverb', 'especially', 'Particularly relevant.'),
    ('perhaps', 'adverb', 'maybe', 'Perhaps more research.'),
    ('probably', 'adverb', 'likely', 'Probably best approach.'),
    ('quite', 'adverb', 'fairly', 'Quite significant.'),
    ('rather', 'adverb', 'somewhat', 'Rather than ignoring.'),
    ('really', 'adverb', 'truly', 'Really important.'),
    ('recently', 'adverb', 'not long ago', 'Recently published.'),
    ('simply', 'adverb', 'merely', 'Simply put.'),
    ('sometimes', 'adverb', 'occasionally', 'Sometimes errors occur.'),
    ('soon', 'adverb', 'shortly', 'Soon the results.'),
    ('still', 'adverb', 'yet', 'Still relevant.'),
    ('therefore', 'adverb', 'consequently', 'Therefore conclude.'),
    ('thus', 'adverb', 'in this way', 'Thus hypothesis holds.'),
    ('together', 'adverb', 'jointly', 'Work together.'),
    ('usually', 'adverb', 'normally', 'Usually works.'),
    ('well', 'adverb', 'satisfactorily', 'Well documented.'),
]

# 카테고리 목록
CATEGORIES = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
              'Business', 'Society', 'Science', 'Culture', 'Media']

def main():
    words = []
    for i, (word, pos, definition, example) in enumerate(WORDS, 1):
        words.append({
            'id': i,
            'word': word,
            'level': 'Band 4.5-5.5',
            'partOfSpeech': pos,
            'definition': definition,
            'example': example,
            'category': CATEGORIES[i % len(CATEGORIES)]
        })
    
    with open('assets/data/band45_words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, indent=2, ensure_ascii=False)
    
    print(f'✅ Band 4.5-5.5: {len(words)}개 생성 완료')
    return words

if __name__ == '__main__':
    main()
