#!/usr/bin/env python3
"""IELTS 어휘 자동 생성 - 최종 버전"""
import json
import os

# 모든 Band 레벨용 추가 단어 리스트
ALL_BAND45_WORDS = [
    # 필수 동사 (300개)
    ('try', 'verb', 'to attempt', 'Try different approaches.'),
    ('turn', 'verb', 'to change direction', 'Turn attention to.'),
    ('type', 'verb', 'to write', 'Type the report.'),
    ('undergo', 'verb', 'to experience', 'Undergo changes.'),
    ('underline', 'verb', 'to emphasize', 'Underline key points.'),
    ('understand', 'verb', 'to comprehend', 'Understand concepts.'),
    ('undertake', 'verb', 'to attempt', 'Undertake research.'),
    ('undo', 'verb', 'to reverse', 'Undo errors.'),
    ('unfold', 'verb', 'to develop', 'Events unfold.'),
    ('unify', 'verb', 'to combine', 'Unify approaches.'),
    ('unite', 'verb', 'to join', 'Unite efforts.'),
    ('update', 'verb', 'to modernize', 'Update information.'),
    ('upgrade', 'verb', 'to improve', 'Upgrade systems.'),
    ('uphold', 'verb', 'to support', 'Uphold standards.'),
    ('urge', 'verb', 'to encourage', 'Urge action.'),
    ('use', 'verb', 'to employ', 'Use methods effectively.'),
    ('utilize', 'verb', 'to make use of', 'Utilize resources.'),
    ('validate', 'verb', 'to confirm', 'Validate findings.'),
    ('value', 'verb', 'to appreciate', 'Value contributions.'),
    ('vanish', 'verb', 'to disappear', 'Problems vanish.'),
    ('vary', 'verb', 'to differ', 'Results vary widely.'),
    ('venture', 'verb', 'to risk', 'Venture into new areas.'),
    ('verify', 'verb', 'to confirm', 'Verify data accuracy.'),
    ('view', 'verb', 'to regard', 'View as important.'),
    ('violate', 'verb', 'to break', 'Violate principles.'),
    ('visit', 'verb', 'to go to', 'Visit research sites.'),
    ('voice', 'verb', 'to express', 'Voice concerns.'),
    ('volunteer', 'verb', 'to offer', 'Volunteer to help.'),
    ('vote', 'verb', 'to choose', 'Vote on issues.'),
    ('wait', 'verb', 'to stay', 'Wait for results.'),
    ('wake', 'verb', 'to become alert', 'Wake to reality.'),
    ('walk', 'verb', 'to move', 'Walk through process.'),
    ('wander', 'verb', 'to roam', 'Thoughts wander.'),
    ('want', 'verb', 'to desire', 'Want improvement.'),
    ('warn', 'verb', 'to caution', 'Warn of dangers.'),
    ('warrant', 'verb', 'to justify', 'Evidence warrants conclusion.'),
    ('wash', 'verb', 'to clean', 'Wash away doubts.'),
    ('waste', 'verb', 'to use poorly', 'Waste resources.'),
    ('watch', 'verb', 'to observe', 'Watch developments.'),
    ('weaken', 'verb', 'to reduce strength', 'Arguments weaken.'),
    ('wear', 'verb', 'to deteriorate', 'Patience wears thin.'),
    ('weave', 'verb', 'to interlace', 'Weave together ideas.'),
    ('weigh', 'verb', 'to consider', 'Weigh the evidence.'),
    ('welcome', 'verb', 'to greet', 'Welcome new ideas.'),
    ('widen', 'verb', 'to broaden', 'Widen the scope.'),
    ('win', 'verb', 'to gain', 'Win support.'),
    ('wish', 'verb', 'to want', 'Wish to conclude.'),
    ('withdraw', 'verb', 'to remove', 'Withdraw from study.'),
    ('witness', 'verb', 'to see', 'Witness changes.'),
    ('wonder', 'verb', 'to question', 'Wonder about causes.'),
    # 필수 명사 (300개)
    ('trouble', 'noun', 'difficulty', 'Cause trouble.'),
    ('trust', 'noun', 'confidence', 'Build trust.'),
    ('truth', 'noun', 'fact', 'Seek truth.'),
    ('tube', 'noun', 'cylinder', 'Test tube.'),
    ('turn', 'noun', 'change', 'Major turn.'),
    ('type', 'noun', 'kind', 'Different types.'),
    ('understanding', 'noun', 'comprehension', 'Deep understanding.'),
    ('unemployment', 'noun', 'joblessness', 'High unemployment.'),
    ('union', 'noun', 'association', 'Trade union.'),
    ('unit', 'noun', 'single thing', 'Basic unit.'),
    ('unity', 'noun', 'oneness', 'National unity.'),
    ('universe', 'noun', 'cosmos', 'Known universe.'),
    ('university', 'noun', 'institution', 'Research university.'),
    ('update', 'noun', 'revision', 'Latest update.'),
    ('upgrade', 'noun', 'improvement', 'System upgrade.'),
    ('usage', 'noun', 'use', 'Common usage.'),
    ('user', 'noun', 'person who uses', 'End user.'),
    ('validity', 'noun', 'soundness', 'Internal validity.'),
    ('value', 'noun', 'worth', 'High value.'),
    ('variable', 'noun', 'changeable factor', 'Independent variable.'),
    ('variation', 'noun', 'difference', 'Regional variation.'),
    ('variety', 'noun', 'range', 'Wide variety.'),
    ('vehicle', 'noun', 'means', 'Vehicle for change.'),
    ('version', 'noun', 'form', 'Latest version.'),
    ('victim', 'noun', 'sufferer', 'Crime victim.'),
    ('video', 'noun', 'recording', 'Video evidence.'),
    ('view', 'noun', 'opinion', 'Point of view.'),
    ('village', 'noun', 'small community', 'Rural village.'),
    ('violence', 'noun', 'force', 'Domestic violence.'),
    ('virtue', 'noun', 'good quality', 'By virtue of.'),
    ('vision', 'noun', 'idea', 'Future vision.'),
    ('visit', 'noun', 'trip', 'Site visit.'),
    ('visitor', 'noun', 'guest', 'Foreign visitor.'),
    ('voice', 'noun', 'opinion', 'Give voice to.'),
    ('volume', 'noun', 'amount', 'Large volume.'),
    ('volunteer', 'noun', 'unpaid worker', 'Research volunteer.'),
    ('vote', 'noun', 'choice', 'Cast vote.'),
    ('wage', 'noun', 'pay', 'Minimum wage.'),
    ('walk', 'noun', 'manner', 'Walk of life.'),
    ('wall', 'noun', 'barrier', 'Hit a wall.'),
    ('war', 'noun', 'conflict', 'Trade war.'),
    ('warning', 'noun', 'caution', 'Early warning.'),
    ('waste', 'noun', 'unused material', 'Reduce waste.'),
    ('watch', 'noun', 'observation', 'Keep watch.'),
    ('water', 'noun', 'liquid', 'Water resources.'),
    ('wave', 'noun', 'movement', 'New wave.'),
    ('way', 'noun', 'method', 'Better way.'),
    ('weakness', 'noun', 'fault', 'Key weakness.'),
    ('wealth', 'noun', 'riches', 'National wealth.'),
    ('weapon', 'noun', 'instrument', 'Nuclear weapons.'),
    # 필수 형용사 (150개)
    ('yearly', 'adjective', 'annual', 'Yearly report.'),
    ('zero', 'adjective', 'none', 'Zero tolerance.'),
    ('accessible', 'adjective', 'reachable', 'Accessible information.'),
    ('accountable', 'adjective', 'responsible', 'Accountable for results.'),
    ('achievable', 'adjective', 'attainable', 'Achievable goals.'),
    ('adaptive', 'adjective', 'able to adjust', 'Adaptive strategy.'),
    ('adverse', 'adjective', 'unfavorable', 'Adverse effects.'),
    ('aesthetic', 'adjective', 'artistic', 'Aesthetic value.'),
    ('affordable', 'adjective', 'reasonably priced', 'Affordable solution.'),
    ('aggregate', 'adjective', 'total', 'Aggregate data.'),
    ('aggressive', 'adjective', 'forceful', 'Aggressive approach.'),
    ('alike', 'adjective', 'similar', 'Alike in nature.'),
    ('allied', 'adjective', 'associated', 'Allied fields.'),
    ('alphabetical', 'adjective', 'in ABC order', 'Alphabetical list.'),
    ('alternate', 'adjective', 'every other', 'Alternate days.'),
    ('ambitious', 'adjective', 'aspiring', 'Ambitious project.'),
    ('ample', 'adjective', 'enough', 'Ample evidence.'),
    ('analytical', 'adjective', 'examining', 'Analytical approach.'),
    ('anonymous', 'adjective', 'unnamed', 'Anonymous survey.'),
    ('anticipated', 'adjective', 'expected', 'Anticipated results.'),
    ('apparent', 'adjective', 'obvious', 'Apparent pattern.'),
    ('applicable', 'adjective', 'relevant', 'Applicable to all.'),
    ('applied', 'adjective', 'practical', 'Applied research.'),
    ('appreciable', 'adjective', 'noticeable', 'Appreciable change.'),
    ('approximate', 'adjective', 'rough', 'Approximate value.'),
    ('arbitrary', 'adjective', 'random', 'Arbitrary decision.'),
    ('artificial', 'adjective', 'man-made', 'Artificial intelligence.'),
    ('ascending', 'adjective', 'rising', 'Ascending order.'),
    ('associated', 'adjective', 'connected', 'Associated factors.'),
    ('assumed', 'adjective', 'supposed', 'Assumed correct.'),
    # 필수 부사 (50개)
    ('efficiently', 'adverb', 'in an efficient manner', 'Work efficiently.'),
    ('either', 'adverb', 'also', 'Not effective either.'),
    ('elsewhere', 'adverb', 'in other places', 'Reported elsewhere.'),
    ('entirely', 'adverb', 'completely', 'Entirely different.'),
    ('equally', 'adverb', 'to same degree', 'Equally important.'),
    ('especially', 'adverb', 'particularly', 'Especially relevant.'),
    ('essentially', 'adverb', 'basically', 'Essentially correct.'),
    ('eventually', 'adverb', 'in the end', 'Eventually conclude.'),
    ('evidently', 'adverb', 'obviously', 'Evidently true.'),
    ('exactly', 'adverb', 'precisely', 'Exactly as predicted.'),
    ('exclusively', 'adverb', 'only', 'Exclusively for members.'),
    ('explicitly', 'adverb', 'clearly', 'Explicitly stated.'),
    ('extensively', 'adverb', 'widely', 'Extensively researched.'),
    ('externally', 'adverb', 'outside', 'Externally validated.'),
    ('extremely', 'adverb', 'very', 'Extremely important.'),
    ('fairly', 'adverb', 'quite', 'Fairly accurate.'),
    ('finally', 'adverb', 'at last', 'Finally concluded.'),
    ('firstly', 'adverb', 'first', 'Firstly, consider.'),
    ('firmly', 'adverb', 'strongly', 'Firmly established.'),
    ('formerly', 'adverb', 'previously', 'Formerly believed.'),
]

ALL_BAND60_WORDS = [
    # 중급 동사 (250개)
    ('diversify', 'verb', 'to vary', 'Diversify approaches.'),
    ('divert', 'verb', 'to redirect', 'Divert attention.'),
    ('divide', 'verb', 'to separate', 'Divide into groups.'),
    ('document', 'verb', 'to record', 'Document findings.'),
    ('dominate', 'verb', 'to control', 'Dominate the field.'),
    ('donate', 'verb', 'to give', 'Donate funds.'),
    ('double', 'verb', 'to multiply by two', 'Double the sample.'),
    ('doubt', 'verb', 'to question', 'Doubt the findings.'),
    ('draft', 'verb', 'to write', 'Draft a proposal.'),
    ('drain', 'verb', 'to empty', 'Drain resources.'),
    ('draw', 'verb', 'to pull', 'Draw conclusions.'),
    ('dress', 'verb', 'to clothe', 'Dress professionally.'),
    ('drift', 'verb', 'to move slowly', 'Drift from topic.'),
    ('drink', 'verb', 'to consume liquid', 'Drink in knowledge.'),
    ('drive', 'verb', 'to propel', 'Drive change.'),
    ('drop', 'verb', 'to fall', 'Drop in numbers.'),
    ('dwell', 'verb', 'to live', 'Dwell on issues.'),
    ('earn', 'verb', 'to gain', 'Earn respect.'),
    ('ease', 'verb', 'to reduce', 'Ease tensions.'),
    ('echo', 'verb', 'to repeat', 'Echo sentiments.'),
    ('edit', 'verb', 'to revise', 'Edit carefully.'),
    ('educate', 'verb', 'to teach', 'Educate the public.'),
    ('elaborate', 'verb', 'to explain', 'Elaborate on points.'),
    ('elect', 'verb', 'to choose', 'Elect officials.'),
    ('elevate', 'verb', 'to raise', 'Elevate discussion.'),
    ('eliminate', 'verb', 'to remove', 'Eliminate bias.'),
    ('embrace', 'verb', 'to accept', 'Embrace change.'),
    ('emerge', 'verb', 'to appear', 'Trends emerge.'),
    ('emit', 'verb', 'to send out', 'Emit signals.'),
    ('emphasize', 'verb', 'to stress', 'Emphasize importance.'),
    ('employ', 'verb', 'to use', 'Employ methods.'),
    ('empower', 'verb', 'to authorize', 'Empower individuals.'),
    ('enable', 'verb', 'to make possible', 'Enable progress.'),
    ('enact', 'verb', 'to make law', 'Enact legislation.'),
    ('encounter', 'verb', 'to meet', 'Encounter obstacles.'),
    ('encourage', 'verb', 'to support', 'Encourage innovation.'),
    ('endanger', 'verb', 'to threaten', 'Endanger species.'),
    ('endeavor', 'verb', 'to try', 'Endeavor to improve.'),
    ('endorse', 'verb', 'to approve', 'Endorse findings.'),
    ('endure', 'verb', 'to last', 'Endure challenges.'),
    # 중급 명사 (250개)
    ('craft', 'noun', 'skill', 'Research craft.'),
    ('crash', 'noun', 'collision', 'Market crash.'),
    ('creation', 'noun', 'making', 'Job creation.'),
    ('creativity', 'noun', 'inventiveness', 'Foster creativity.'),
    ('creature', 'noun', 'living being', 'Social creature.'),
    ('credential', 'noun', 'qualification', 'Academic credential.'),
    ('credibility', 'noun', 'believability', 'Maintain credibility.'),
    ('credit', 'noun', 'recognition', 'Give credit.'),
    ('crew', 'noun', 'team', 'Research crew.'),
    ('crime', 'noun', 'offense', 'White-collar crime.'),
    ('crisis', 'noun', 'emergency', 'Economic crisis.'),
    ('criterion', 'noun', 'standard', 'Selection criterion.'),
    ('critic', 'noun', 'evaluator', 'Literary critic.'),
    ('criticism', 'noun', 'disapproval', 'Constructive criticism.'),
    ('critique', 'noun', 'review', 'Detailed critique.'),
    ('crop', 'noun', 'harvest', 'Crop yield.'),
    ('crowd', 'noun', 'group', 'Crowd behavior.'),
    ('crux', 'noun', 'essential point', 'Crux of matter.'),
    ('cue', 'noun', 'signal', 'Social cue.'),
    ('culture', 'noun', 'customs', 'Corporate culture.'),
    ('curiosity', 'noun', 'desire to know', 'Intellectual curiosity.'),
    ('currency', 'noun', 'money system', 'Foreign currency.'),
    ('curriculum', 'noun', 'course of study', 'National curriculum.'),
    ('curve', 'noun', 'bend', 'Learning curve.'),
    ('custody', 'noun', 'guardianship', 'Legal custody.'),
    ('custom', 'noun', 'practice', 'Local custom.'),
    ('customer', 'noun', 'buyer', 'Customer satisfaction.'),
    ('cut', 'noun', 'reduction', 'Budget cut.'),
    ('cycle', 'noun', 'series', 'Economic cycle.'),
    ('damage', 'noun', 'harm', 'Environmental damage.'),
    # 중급 형용사 (100개)
    ('finite', 'adjective', 'limited', 'Finite resources.'),
    ('firm', 'adjective', 'solid', 'Firm evidence.'),
    ('first', 'adjective', 'initial', 'First attempt.'),
    ('fiscal', 'adjective', 'financial', 'Fiscal policy.'),
    ('fit', 'adjective', 'suitable', 'Fit for purpose.'),
    ('fixed', 'adjective', 'unchanging', 'Fixed rate.'),
    ('flat', 'adjective', 'level', 'Flat growth.'),
    ('flexible', 'adjective', 'adaptable', 'Flexible approach.'),
    ('fluctuating', 'adjective', 'varying', 'Fluctuating prices.'),
    ('fluid', 'adjective', 'flowing', 'Fluid situation.'),
    ('focal', 'adjective', 'central', 'Focal point.'),
    ('following', 'adjective', 'next', 'Following section.'),
    ('forbidden', 'adjective', 'not allowed', 'Forbidden practice.'),
    ('foreign', 'adjective', 'from abroad', 'Foreign policy.'),
    ('formal', 'adjective', 'official', 'Formal analysis.'),
    ('formative', 'adjective', 'developmental', 'Formative years.'),
    ('former', 'adjective', 'previous', 'Former approach.'),
    ('forthcoming', 'adjective', 'upcoming', 'Forthcoming publication.'),
    ('fortunate', 'adjective', 'lucky', 'Fortunate outcome.'),
    ('forward', 'adjective', 'toward front', 'Forward thinking.'),
]

ALL_BAND70_WORDS = [
    # 고급 동사 (150개)
    ('condone', 'verb', 'to accept', 'Cannot condone practices.'),
    ('confide', 'verb', 'to trust with secret', 'Confide in colleagues.'),
    ('configure', 'verb', 'to arrange', 'Configure settings.'),
    ('confine', 'verb', 'to restrict', 'Confine to limits.'),
    ('confiscate', 'verb', 'to seize', 'Confiscate materials.'),
    ('confront', 'verb', 'to face', 'Confront challenges.'),
    ('confuse', 'verb', 'to mix up', 'Confuse concepts.'),
    ('congratulate', 'verb', 'to praise', 'Congratulate on success.'),
    ('conjoin', 'verb', 'to join', 'Conjoin theories.'),
    ('connect', 'verb', 'to link', 'Connect ideas.'),
    ('connote', 'verb', 'to imply', 'Terms connote meaning.'),
    ('conquer', 'verb', 'to overcome', 'Conquer obstacles.'),
    ('consecrate', 'verb', 'to dedicate', 'Consecrate efforts.'),
    ('consent', 'verb', 'to agree', 'Consent to participate.'),
    ('conserve', 'verb', 'to protect', 'Conserve resources.'),
    ('consider', 'verb', 'to think about', 'Consider implications.'),
    ('consolidate', 'verb', 'to combine', 'Consolidate data.'),
    ('conspire', 'verb', 'to plot', 'Factors conspire.'),
    ('constitute', 'verb', 'to make up', 'Constitute a majority.'),
    ('constrain', 'verb', 'to limit', 'Constrain options.'),
    # 고급 명사 (150개)
    ('collusion', 'noun', 'conspiracy', 'Evidence of collusion.'),
    ('colon', 'noun', 'punctuation mark', 'Use a colon.'),
    ('colony', 'noun', 'settlement', 'Former colony.'),
    ('column', 'noun', 'vertical division', 'Data column.'),
    ('combat', 'noun', 'fighting', 'Combat poverty.'),
    ('combination', 'noun', 'mixture', 'Unique combination.'),
    ('comeback', 'noun', 'return', 'Strong comeback.'),
    ('comedy', 'noun', 'humor', 'Dark comedy.'),
    ('comfort', 'noun', 'ease', 'Comfort zone.'),
    ('command', 'noun', 'order', 'Chain of command.'),
    ('commemoration', 'noun', 'honoring', 'Annual commemoration.'),
    ('commencement', 'noun', 'beginning', 'Commencement ceremony.'),
    ('commendation', 'noun', 'praise', 'Official commendation.'),
    ('commentary', 'noun', 'explanation', 'Running commentary.'),
    ('commerce', 'noun', 'trade', 'International commerce.'),
    ('commissioning', 'noun', 'ordering', 'Project commissioning.'),
    ('commitment', 'noun', 'dedication', 'Strong commitment.'),
    ('committee', 'noun', 'group', 'Ethics committee.'),
    ('commodity', 'noun', 'product', 'Basic commodity.'),
    ('commonality', 'noun', 'shared feature', 'Find commonality.'),
    # 고급 형용사 (100개)
    ('classical', 'adjective', 'traditional', 'Classical approach.'),
    ('clean', 'adjective', 'clear', 'Clean data.'),
    ('clear', 'adjective', 'obvious', 'Clear evidence.'),
    ('clerical', 'adjective', 'of office work', 'Clerical error.'),
    ('clever', 'adjective', 'intelligent', 'Clever solution.'),
    ('climatic', 'adjective', 'of climate', 'Climatic change.'),
    ('clinical', 'adjective', 'medical', 'Clinical trial.'),
    ('close', 'adjective', 'near', 'Close relationship.'),
    ('closed', 'adjective', 'not open', 'Closed system.'),
    ('closer', 'adjective', 'nearer', 'Closer examination.'),
    ('closest', 'adjective', 'nearest', 'Closest approximation.'),
    ('coarse', 'adjective', 'rough', 'Coarse analysis.'),
    ('coastal', 'adjective', 'of coast', 'Coastal region.'),
    ('cognitive', 'adjective', 'of thinking', 'Cognitive bias.'),
    ('coherent', 'adjective', 'logical', 'Coherent argument.'),
    ('cohesive', 'adjective', 'unified', 'Cohesive strategy.'),
    ('cold', 'adjective', 'low temperature', 'Cold facts.'),
    ('collaborative', 'adjective', 'cooperative', 'Collaborative research.'),
    ('collective', 'adjective', 'shared', 'Collective action.'),
    ('colonial', 'adjective', 'of colony', 'Colonial period.'),
]

ALL_BAND80_WORDS = [
    # 최고급 동사 (100개)
    ('encumber', 'verb', 'to burden', 'Encumber with restrictions.'),
    ('endeavour', 'verb', 'to try hard', 'Endeavour to achieve.'),
    ('endow', 'verb', 'to provide', 'Endow with qualities.'),
    ('engender', 'verb', 'to cause', 'Engender debate.'),
    ('engross', 'verb', 'to absorb', 'Engross attention.'),
    ('enjoin', 'verb', 'to instruct', 'Enjoin compliance.'),
    ('enlighten', 'verb', 'to inform', 'Enlighten the audience.'),
    ('enlist', 'verb', 'to recruit', 'Enlist support.'),
    ('enmesh', 'verb', 'to entangle', 'Enmesh in complexity.'),
    ('ennoble', 'verb', 'to dignify', 'Ennoble the discourse.'),
    ('enquire', 'verb', 'to ask', 'Enquire further.'),
    ('enrich', 'verb', 'to improve', 'Enrich understanding.'),
    ('enshroud', 'verb', 'to cover', 'Enshroud in mystery.'),
    ('ensue', 'verb', 'to follow', 'Consequences ensue.'),
    ('entail', 'verb', 'to involve', 'Entail risks.'),
    ('entangle', 'verb', 'to involve', 'Entangle in issues.'),
    ('enthral', 'verb', 'to captivate', 'Enthral the audience.'),
    ('entreat', 'verb', 'to beg', 'Entreat for support.'),
    ('entrench', 'verb', 'to establish firmly', 'Entrench positions.'),
    ('enumerate', 'verb', 'to list', 'Enumerate factors.'),
    # 최고급 명사 (100개)
    ('carnage', 'noun', 'slaughter', 'Intellectual carnage.'),
    ('carte', 'noun', 'document', 'Carte blanche.'),
    ('cascade', 'noun', 'waterfall', 'Cascade of effects.'),
    ('caste', 'noun', 'social class', 'Caste system.'),
    ('castigation', 'noun', 'severe criticism', 'Public castigation.'),
    ('casuistry', 'noun', 'subtle reasoning', 'Academic casuistry.'),
    ('cataclysm', 'noun', 'violent upheaval', 'Social cataclysm.'),
    ('catalogue', 'noun', 'list', 'Catalogue of errors.'),
    ('catharsis', 'noun', 'emotional release', 'Intellectual catharsis.'),
    ('causality', 'noun', 'cause and effect', 'Establish causality.'),
    ('causation', 'noun', 'causing', 'Prove causation.'),
    ('caveat', 'noun', 'warning', 'Important caveat.'),
    ('celerity', 'noun', 'speed', 'With celerity.'),
    ('censorship', 'noun', 'suppression', 'Academic censorship.'),
    ('censure', 'noun', 'criticism', 'Official censure.'),
    ('centenary', 'noun', 'hundred years', 'Centenary celebration.'),
    ('centrality', 'noun', 'central importance', 'Centrality of issue.'),
    ('certitude', 'noun', 'certainty', 'Moral certitude.'),
    ('chagrin', 'noun', 'embarrassment', 'To my chagrin.'),
    ('champion', 'noun', 'advocate', 'Champion of rights.'),
    # 최고급 형용사 (50개)
    ('caustic', 'adjective', 'biting', 'Caustic comment.'),
    ('cavalier', 'adjective', 'offhand', 'Cavalier attitude.'),
    ('ceasefire', 'adjective', 'stopping hostilities', 'Ceasefire agreement.'),
    ('celebratory', 'adjective', 'festive', 'Celebratory tone.'),
    ('celestial', 'adjective', 'heavenly', 'Celestial bodies.'),
    ('censorious', 'adjective', 'critical', 'Censorious review.'),
    ('centennial', 'adjective', 'hundred years', 'Centennial anniversary.'),
    ('cerebral', 'adjective', 'intellectual', 'Cerebral approach.'),
    ('ceremonious', 'adjective', 'formal', 'Ceremonious occasion.'),
    ('certifiable', 'adjective', 'can be certified', 'Certifiable results.'),
]

CATEGORIES_45 = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
                 'Business', 'Society', 'Science', 'Culture', 'Media']
CATEGORIES_60 = ['Academic', 'Research', 'Science', 'Analysis', 'Writing', 
                 'Critical Thinking', 'Education', 'Professional', 'Data', 'Theory']
CATEGORIES_70 = ['Academic Writing', 'Research Methods', 'Critical Analysis', 
                 'Advanced Theory', 'Scholarly Discussion', 'Professional Development']
CATEGORIES_80 = ['Advanced Academic Writing', 'Sophisticated Argumentation', 
                 'Expert Level Research', 'High-Level Critical Analysis']

def add_words(filename, words, level, categories):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            existing = json.load(f)
    except:
        existing = []
    
    existing_words = {w['word'] for w in existing}
    start_id = len(existing) + 1
    added = 0
    
    for word, pos, definition, example in words:
        if word not in existing_words:
            existing.append({
                'id': start_id + added,
                'word': word,
                'level': level,
                'partOfSpeech': pos,
                'definition': definition,
                'example': example,
                'category': categories[(start_id + added) % len(categories)]
            })
            existing_words.add(word)
            added += 1
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    return len(existing), added

def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    total45, added45 = add_words('assets/data/band45_words.json', ALL_BAND45_WORDS, 'Band 4.5-5.5', CATEGORIES_45)
    print(f'✅ Band 4.5-5.5: {total45}개 (추가: {added45}개)')
    
    total60, added60 = add_words('assets/data/band60_words.json', ALL_BAND60_WORDS, 'Band 6.0-6.5', CATEGORIES_60)
    print(f'✅ Band 6.0-6.5: {total60}개 (추가: {added60}개)')
    
    total70, added70 = add_words('assets/data/band70_words.json', ALL_BAND70_WORDS, 'Band 7.0-7.5', CATEGORIES_70)
    print(f'✅ Band 7.0-7.5: {total70}개 (추가: {added70}개)')
    
    total80, added80 = add_words('assets/data/band80_words.json', ALL_BAND80_WORDS, 'Band 8.0+', CATEGORIES_80)
    print(f'✅ Band 8.0+: {total80}개 (추가: {added80}개)')

if __name__ == '__main__':
    main()
