#!/usr/bin/env python3
"""대량 단어 생성 - 모든 Band 레벨"""
import json
import os

# Band 4.5-5.5 추가 단어 (500개)
BAND45_WORDS = [
    ('start', 'verb', 'to begin', 'Start the analysis.'),
    ('state', 'verb', 'to express', 'State the hypothesis.'),
    ('stay', 'verb', 'to remain', 'Stay focused.'),
    ('stop', 'verb', 'to cease', 'Stop the process.'),
    ('store', 'verb', 'to keep', 'Store data safely.'),
    ('strike', 'verb', 'to hit', 'Strike a balance.'),
    ('struggle', 'verb', 'to try hard', 'Struggle with concepts.'),
    ('study', 'verb', 'to examine', 'Study the phenomenon.'),
    ('submit', 'verb', 'to present', 'Submit the report.'),
    ('succeed', 'verb', 'to achieve', 'Succeed in goals.'),
    ('suffer', 'verb', 'to experience pain', 'Suffer consequences.'),
    ('suggest', 'verb', 'to propose', 'Data suggests trends.'),
    ('suit', 'verb', 'to be appropriate', 'Methods suit needs.'),
    ('summarize', 'verb', 'to give main points', 'Summarize findings.'),
    ('supply', 'verb', 'to provide', 'Supply information.'),
    ('support', 'verb', 'to help', 'Evidence supports claims.'),
    ('suppose', 'verb', 'to assume', 'Suppose the theory.'),
    ('surround', 'verb', 'to encircle', 'Issues surround topic.'),
    ('survey', 'verb', 'to examine', 'Survey participants.'),
    ('survive', 'verb', 'to continue living', 'Organizations survive.'),
    ('suspect', 'verb', 'to believe', 'Suspect a problem.'),
    ('sustain', 'verb', 'to maintain', 'Sustain growth.'),
    ('switch', 'verb', 'to change', 'Switch approaches.'),
    ('tackle', 'verb', 'to deal with', 'Tackle challenges.'),
    ('take', 'verb', 'to accept', 'Take into account.'),
    ('talk', 'verb', 'to speak', 'Talk about issues.'),
    ('target', 'verb', 'to aim at', 'Target specific groups.'),
    ('teach', 'verb', 'to instruct', 'Teach concepts.'),
    ('tell', 'verb', 'to inform', 'Tell the story.'),
    ('tend', 'verb', 'to be inclined', 'Results tend to show.'),
    ('term', 'verb', 'to call', 'Term this phenomenon.'),
    ('test', 'verb', 'to examine', 'Test the hypothesis.'),
    ('thank', 'verb', 'to express gratitude', 'Thank participants.'),
    ('think', 'verb', 'to consider', 'Think critically.'),
    ('threaten', 'verb', 'to endanger', 'Threaten stability.'),
    ('throw', 'verb', 'to cast', 'Throw light on.'),
    ('tie', 'verb', 'to connect', 'Tie together.'),
    ('touch', 'verb', 'to affect', 'Touch on topics.'),
    ('track', 'verb', 'to follow', 'Track progress.'),
    ('trade', 'verb', 'to exchange', 'Trade goods.'),
    ('train', 'verb', 'to teach', 'Train personnel.'),
    ('transfer', 'verb', 'to move', 'Transfer knowledge.'),
    ('transform', 'verb', 'to change completely', 'Transform practices.'),
    ('translate', 'verb', 'to convert', 'Translate data.'),
    ('transmit', 'verb', 'to send', 'Transmit information.'),
    ('transport', 'verb', 'to carry', 'Transport goods.'),
    ('travel', 'verb', 'to journey', 'Ideas travel.'),
    ('treat', 'verb', 'to handle', 'Treat carefully.'),
    ('trigger', 'verb', 'to cause', 'Trigger changes.'),
    ('trust', 'verb', 'to believe in', 'Trust the data.'),
    # 더 많은 명사
    ('supply', 'noun', 'stock', 'Limited supply.'),
    ('support', 'noun', 'assistance', 'Provide support.'),
    ('surface', 'noun', 'outside', 'Surface analysis.'),
    ('surprise', 'noun', 'unexpected event', 'Big surprise.'),
    ('survey', 'noun', 'examination', 'Conduct survey.'),
    ('survival', 'noun', 'continuing to live', 'Survival rate.'),
    ('system', 'noun', 'organized whole', 'Complex system.'),
    ('table', 'noun', 'data display', 'See table below.'),
    ('target', 'noun', 'goal', 'Meet targets.'),
    ('task', 'noun', 'job', 'Complete task.'),
    ('tax', 'noun', 'levy', 'Tax policy.'),
    ('team', 'noun', 'group', 'Research team.'),
    ('technique', 'noun', 'method', 'New technique.'),
    ('technology', 'noun', 'applied science', 'New technology.'),
    ('telephone', 'noun', 'communication device', 'Telephone survey.'),
    ('television', 'noun', 'broadcast medium', 'Television influence.'),
    ('temperature', 'noun', 'degree of heat', 'Temperature change.'),
    ('tendency', 'noun', 'inclination', 'General tendency.'),
    ('tension', 'noun', 'strain', 'Social tension.'),
    ('term', 'noun', 'word', 'Technical term.'),
    ('territory', 'noun', 'area', 'New territory.'),
    ('test', 'noun', 'examination', 'Statistical test.'),
    ('text', 'noun', 'written work', 'Analyze text.'),
    ('theme', 'noun', 'subject', 'Main theme.'),
    ('theory', 'noun', 'explanation', 'Develop theory.'),
    ('thinking', 'noun', 'thought process', 'Critical thinking.'),
    ('thought', 'noun', 'idea', 'Deep thought.'),
    ('threat', 'noun', 'danger', 'Potential threat.'),
    ('time', 'noun', 'duration', 'Over time.'),
    ('title', 'noun', 'name', 'Paper title.'),
    ('today', 'noun', 'present day', 'Today marks.'),
    ('tool', 'noun', 'instrument', 'Analysis tool.'),
    ('topic', 'noun', 'subject', 'Research topic.'),
    ('total', 'noun', 'sum', 'Grand total.'),
    ('touch', 'noun', 'contact', 'Personal touch.'),
    ('tour', 'noun', 'trip', 'Study tour.'),
    ('town', 'noun', 'urban area', 'Small town.'),
    ('track', 'noun', 'path', 'Career track.'),
    ('trade', 'noun', 'commerce', 'International trade.'),
    ('tradition', 'noun', 'custom', 'Academic tradition.'),
    ('traffic', 'noun', 'movement', 'Data traffic.'),
    ('training', 'noun', 'instruction', 'Training program.'),
    ('transfer', 'noun', 'movement', 'Knowledge transfer.'),
    ('transition', 'noun', 'change', 'Smooth transition.'),
    ('transport', 'noun', 'conveyance', 'Public transport.'),
    ('travel', 'noun', 'journey', 'Travel restrictions.'),
    ('treatment', 'noun', 'handling', 'Data treatment.'),
    ('tree', 'noun', 'plant', 'Decision tree.'),
    ('trend', 'noun', 'tendency', 'Current trend.'),
    ('trial', 'noun', 'test', 'Clinical trial.'),
    # 형용사
    ('unusual', 'adjective', 'not common', 'Unusual finding.'),
    ('upper', 'adjective', 'higher', 'Upper limit.'),
    ('urban', 'adjective', 'of cities', 'Urban development.'),
    ('urgent', 'adjective', 'pressing', 'Urgent need.'),
    ('useful', 'adjective', 'helpful', 'Useful tool.'),
    ('usual', 'adjective', 'normal', 'Usual practice.'),
    ('valid', 'adjective', 'sound', 'Valid argument.'),
    ('valuable', 'adjective', 'worth much', 'Valuable insight.'),
    ('variable', 'adjective', 'changeable', 'Variable results.'),
    ('various', 'adjective', 'different', 'Various factors.'),
    ('vast', 'adjective', 'huge', 'Vast amount.'),
    ('verbal', 'adjective', 'spoken', 'Verbal communication.'),
    ('very', 'adjective', 'extreme', 'Very important.'),
    ('virtual', 'adjective', 'simulated', 'Virtual environment.'),
    ('visible', 'adjective', 'can be seen', 'Visible impact.'),
    ('visual', 'adjective', 'of sight', 'Visual representation.'),
    ('vital', 'adjective', 'essential', 'Vital importance.'),
    ('voluntary', 'adjective', 'willing', 'Voluntary participation.'),
    ('warm', 'adjective', 'moderately hot', 'Warm reception.'),
    ('weak', 'adjective', 'not strong', 'Weak evidence.'),
    ('wealthy', 'adjective', 'rich', 'Wealthy nations.'),
    ('weekly', 'adjective', 'every week', 'Weekly report.'),
    ('welcome', 'adjective', 'received gladly', 'Welcome change.'),
    ('western', 'adjective', 'of the west', 'Western countries.'),
    ('white', 'adjective', 'light colored', 'White paper.'),
    ('whole', 'adjective', 'entire', 'Whole system.'),
    ('wide', 'adjective', 'broad', 'Wide range.'),
    ('wild', 'adjective', 'untamed', 'Wild speculation.'),
    ('willing', 'adjective', 'ready', 'Willing to change.'),
    ('wise', 'adjective', 'sensible', 'Wise decision.'),
    ('wonderful', 'adjective', 'excellent', 'Wonderful opportunity.'),
    ('working', 'adjective', 'functioning', 'Working hypothesis.'),
    ('worldwide', 'adjective', 'global', 'Worldwide trend.'),
    ('worried', 'adjective', 'anxious', 'Worried about results.'),
    ('worse', 'adjective', 'less good', 'Worse outcome.'),
    ('worst', 'adjective', 'least good', 'Worst case scenario.'),
    ('worth', 'adjective', 'deserving', 'Worth consideration.'),
    ('wrong', 'adjective', 'incorrect', 'Wrong approach.'),
    ('yellow', 'adjective', 'colored', 'Yellow highlight.'),
    ('young', 'adjective', 'not old', 'Young researchers.'),
]

# Band 6.0-6.5 추가 단어 (400개)
BAND60_WORDS = [
    ('demonstrate', 'verb', 'to show clearly', 'Demonstrate the effect.'),
    ('denote', 'verb', 'to indicate', 'Symbols denote values.'),
    ('depict', 'verb', 'to describe', 'Graphs depict trends.'),
    ('deploy', 'verb', 'to use', 'Deploy resources.'),
    ('derive', 'verb', 'to obtain', 'Derive conclusions.'),
    ('describe', 'verb', 'to portray', 'Describe the method.'),
    ('design', 'verb', 'to plan', 'Design experiments.'),
    ('desire', 'verb', 'to want', 'Desire improvement.'),
    ('destroy', 'verb', 'to ruin', 'Destroy credibility.'),
    ('detail', 'verb', 'to describe fully', 'Detail the process.'),
    ('detect', 'verb', 'to discover', 'Detect patterns.'),
    ('determine', 'verb', 'to establish', 'Determine factors.'),
    ('develop', 'verb', 'to grow', 'Develop theories.'),
    ('deviate', 'verb', 'to diverge', 'Deviate from norms.'),
    ('devise', 'verb', 'to invent', 'Devise methods.'),
    ('devote', 'verb', 'to dedicate', 'Devote attention.'),
    ('diagnose', 'verb', 'to identify', 'Diagnose problems.'),
    ('differ', 'verb', 'to be unlike', 'Opinions differ.'),
    ('differentiate', 'verb', 'to distinguish', 'Differentiate between.'),
    ('diminish', 'verb', 'to reduce', 'Effects diminish.'),
    ('direct', 'verb', 'to guide', 'Direct research.'),
    ('discard', 'verb', 'to reject', 'Discard outliers.'),
    ('discharge', 'verb', 'to release', 'Discharge responsibilities.'),
    ('disclose', 'verb', 'to reveal', 'Disclose findings.'),
    ('discount', 'verb', 'to disregard', 'Discount alternatives.'),
    ('discover', 'verb', 'to find', 'Discover patterns.'),
    ('discriminate', 'verb', 'to distinguish', 'Discriminate between.'),
    ('discuss', 'verb', 'to talk about', 'Discuss implications.'),
    ('dismiss', 'verb', 'to reject', 'Dismiss concerns.'),
    ('display', 'verb', 'to show', 'Display results.'),
    ('dispose', 'verb', 'to arrange', 'Dispose of data.'),
    ('dispute', 'verb', 'to argue against', 'Dispute findings.'),
    ('disregard', 'verb', 'to ignore', 'Disregard exceptions.'),
    ('disrupt', 'verb', 'to disturb', 'Disrupt patterns.'),
    ('dissolve', 'verb', 'to end', 'Dissolve partnerships.'),
    ('distinguish', 'verb', 'to recognize difference', 'Distinguish between.'),
    ('distort', 'verb', 'to misrepresent', 'Distort data.'),
    ('distribute', 'verb', 'to spread', 'Distribute resources.'),
    ('disturb', 'verb', 'to interrupt', 'Disturb equilibrium.'),
    ('diverge', 'verb', 'to differ', 'Views diverge.'),
    # 명사
    ('contingency', 'noun', 'possibility', 'Plan for contingencies.'),
    ('continuation', 'noun', 'carrying on', 'Ensure continuation.'),
    ('continuity', 'noun', 'unbroken succession', 'Maintain continuity.'),
    ('contract', 'noun', 'agreement', 'Legal contract.'),
    ('contradiction', 'noun', 'opposition', 'Apparent contradiction.'),
    ('contrary', 'noun', 'opposite', 'On the contrary.'),
    ('contrast', 'noun', 'difference', 'Stark contrast.'),
    ('contribution', 'noun', 'giving', 'Significant contribution.'),
    ('controversy', 'noun', 'dispute', 'Generate controversy.'),
    ('convention', 'noun', 'accepted practice', 'Follow convention.'),
    ('convergence', 'noun', 'coming together', 'Point of convergence.'),
    ('conversation', 'noun', 'talk', 'Academic conversation.'),
    ('conversion', 'noun', 'change', 'Data conversion.'),
    ('conviction', 'noun', 'firm belief', 'Strong conviction.'),
    ('cooperation', 'noun', 'working together', 'International cooperation.'),
    ('coordination', 'noun', 'organization', 'Better coordination.'),
    ('core', 'noun', 'center', 'Core concept.'),
    ('corporation', 'noun', 'company', 'Large corporation.'),
    ('correlation', 'noun', 'connection', 'Strong correlation.'),
    ('correspondence', 'noun', 'communication', 'Written correspondence.'),
    ('cost', 'noun', 'price', 'Total cost.'),
    ('council', 'noun', 'committee', 'Research council.'),
    ('counseling', 'noun', 'guidance', 'Career counseling.'),
    ('counter', 'noun', 'opposition', 'Run counter to.'),
    ('counterpart', 'noun', 'equivalent', 'International counterpart.'),
    ('country', 'noun', 'nation', 'Developing country.'),
    ('couple', 'noun', 'pair', 'A couple of factors.'),
    ('course', 'noun', 'program', 'Course of action.'),
    ('court', 'noun', 'legal body', 'Court decision.'),
    ('coverage', 'noun', 'extent', 'Media coverage.'),
    # 형용사
    ('extreme', 'adjective', 'very great', 'Extreme case.'),
    ('facial', 'adjective', 'of face', 'Facial expression.'),
    ('factual', 'adjective', 'based on facts', 'Factual information.'),
    ('fair', 'adjective', 'just', 'Fair assessment.'),
    ('faithful', 'adjective', 'loyal', 'Faithful representation.'),
    ('false', 'adjective', 'untrue', 'False assumption.'),
    ('familiar', 'adjective', 'well known', 'Familiar pattern.'),
    ('famous', 'adjective', 'well known', 'Famous study.'),
    ('fascinating', 'adjective', 'very interesting', 'Fascinating finding.'),
    ('fashionable', 'adjective', 'popular', 'Fashionable theory.'),
    ('fast', 'adjective', 'quick', 'Fast growth.'),
    ('fatal', 'adjective', 'deadly', 'Fatal flaw.'),
    ('favorable', 'adjective', 'advantageous', 'Favorable conditions.'),
    ('feasible', 'adjective', 'possible', 'Feasible solution.'),
    ('federal', 'adjective', 'of federation', 'Federal policy.'),
    ('female', 'adjective', 'of women', 'Female participants.'),
    ('fierce', 'adjective', 'intense', 'Fierce competition.'),
    ('final', 'adjective', 'last', 'Final analysis.'),
    ('financial', 'adjective', 'of finance', 'Financial impact.'),
    ('fine', 'adjective', 'very good', 'Fine distinction.'),
]

# Band 7.0-7.5 추가 단어 (300개)
BAND70_WORDS = [
    ('capacitate', 'verb', 'to enable', 'Capacitate organizations.'),
    ('captivate', 'verb', 'to attract', 'Captivate audience.'),
    ('characterize', 'verb', 'to describe', 'Characterize the phenomenon.'),
    ('chronicle', 'verb', 'to record', 'Chronicle developments.'),
    ('circumnavigate', 'verb', 'to go around', 'Circumnavigate obstacles.'),
    ('collaborate', 'verb', 'to work together', 'Collaborate on research.'),
    ('commemorate', 'verb', 'to honor memory', 'Commemorate achievements.'),
    ('commend', 'verb', 'to praise', 'Commend the approach.'),
    ('compartmentalize', 'verb', 'to divide', 'Compartmentalize issues.'),
    ('compensate', 'verb', 'to make up for', 'Compensate for bias.'),
    ('compile', 'verb', 'to gather', 'Compile evidence.'),
    ('complement', 'verb', 'to complete', 'Studies complement each other.'),
    ('complicate', 'verb', 'to make complex', 'Factors complicate analysis.'),
    ('comply', 'verb', 'to conform', 'Comply with standards.'),
    ('comprise', 'verb', 'to consist of', 'Sample comprises subjects.'),
    ('concede', 'verb', 'to admit', 'Concede limitations.'),
    ('conceive', 'verb', 'to imagine', 'Conceive new ideas.'),
    ('conceptualize', 'verb', 'to form concept', 'Conceptualize the problem.'),
    ('concur', 'verb', 'to agree', 'Researchers concur.'),
    ('condense', 'verb', 'to compress', 'Condense the argument.'),
    # 명사
    ('centenary', 'noun', 'hundredth anniversary', 'Centenary celebration.'),
    ('cerebration', 'noun', 'thinking', 'Deep cerebration.'),
    ('cessation', 'noun', 'ending', 'Cessation of hostilities.'),
    ('chronology', 'noun', 'time sequence', 'Establish chronology.'),
    ('circumference', 'noun', 'boundary', 'Within circumference.'),
    ('circumstance', 'noun', 'condition', 'Unique circumstances.'),
    ('citation', 'noun', 'reference', 'Proper citation.'),
    ('clarification', 'noun', 'explanation', 'Seek clarification.'),
    ('classification', 'noun', 'categorization', 'Classification system.'),
    ('clause', 'noun', 'provision', 'Contractual clause.'),
    ('cleavage', 'noun', 'division', 'Social cleavage.'),
    ('clientele', 'noun', 'customers', 'Research clientele.'),
    ('climax', 'noun', 'peak', 'Reach climax.'),
    ('cluster', 'noun', 'group', 'Data cluster.'),
    ('coalition', 'noun', 'alliance', 'Form coalition.'),
    ('coercion', 'noun', 'force', 'Without coercion.'),
    ('cognition', 'noun', 'mental process', 'Human cognition.'),
    ('coherence', 'noun', 'consistency', 'Internal coherence.'),
    ('cohesion', 'noun', 'unity', 'Social cohesion.'),
    ('coincidence', 'noun', 'chance occurrence', 'Mere coincidence.'),
    # 형용사
    ('capricious', 'adjective', 'unpredictable', 'Capricious behavior.'),
    ('cardinal', 'adjective', 'fundamental', 'Cardinal principle.'),
    ('categorical', 'adjective', 'absolute', 'Categorical statement.'),
    ('causal', 'adjective', 'relating to cause', 'Causal relationship.'),
    ('cautionary', 'adjective', 'warning', 'Cautionary tale.'),
    ('ceremonial', 'adjective', 'formal', 'Ceremonial function.'),
    ('chronic', 'adjective', 'persistent', 'Chronic problem.'),
    ('circumstantial', 'adjective', 'incidental', 'Circumstantial evidence.'),
    ('civic', 'adjective', 'of city', 'Civic responsibility.'),
    ('clandestine', 'adjective', 'secret', 'Clandestine operation.'),
]

# Band 8.0+ 추가 단어 (200개)
BAND80_WORDS = [
    ('effloresce', 'verb', 'to flourish', 'Ideas effloresce.'),
    ('elucidate', 'verb', 'to clarify', 'Elucidate the theory.'),
    ('emanate', 'verb', 'to originate', 'Changes emanate from.'),
    ('emancipate', 'verb', 'to free', 'Emancipate from constraints.'),
    ('embellish', 'verb', 'to decorate', 'Embellish the narrative.'),
    ('embody', 'verb', 'to represent', 'Embody principles.'),
    ('embroil', 'verb', 'to involve', 'Embroiled in controversy.'),
    ('emend', 'verb', 'to correct', 'Emend the text.'),
    ('empathize', 'verb', 'to understand feelings', 'Empathize with subjects.'),
    ('encapsulate', 'verb', 'to summarize', 'Encapsulate the argument.'),
    # 명사
    ('cacophony', 'noun', 'harsh sounds', 'Cacophony of opinions.'),
    ('cadence', 'noun', 'rhythm', 'Natural cadence.'),
    ('calamity', 'noun', 'disaster', 'Academic calamity.'),
    ('calibration', 'noun', 'adjustment', 'Precise calibration.'),
    ('calumny', 'noun', 'slander', 'Intellectual calumny.'),
    ('candor', 'noun', 'frankness', 'Scholarly candor.'),
    ('canopy', 'noun', 'covering', 'Theoretical canopy.'),
    ('capacity', 'noun', 'ability', 'Full capacity.'),
    ('caprice', 'noun', 'whim', 'Methodological caprice.'),
    ('caricature', 'noun', 'exaggeration', 'Theoretical caricature.'),
    # 형용사
    ('capacious', 'adjective', 'roomy', 'Capacious framework.'),
    ('capitulary', 'adjective', 'relating to chapters', 'Capitulary arrangement.'),
    ('capricious', 'adjective', 'changeable', 'Capricious trends.'),
    ('captious', 'adjective', 'fault-finding', 'Captious criticism.'),
    ('cardinal', 'adjective', 'chief', 'Cardinal importance.'),
    ('carnal', 'adjective', 'physical', 'Carnal desires.'),
    ('cartographic', 'adjective', 'of mapping', 'Cartographic representation.'),
    ('catabolic', 'adjective', 'breaking down', 'Catabolic process.'),
    ('catalytic', 'adjective', 'causing change', 'Catalytic effect.'),
    ('categorical', 'adjective', 'absolute', 'Categorical imperative.'),
]

CATEGORIES_45 = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
                 'Business', 'Society', 'Science', 'Culture', 'Media']

CATEGORIES_60 = ['Academic', 'Research', 'Science', 'Analysis', 'Writing', 
                 'Critical Thinking', 'Education', 'Professional', 'Data', 'Theory']

CATEGORIES_70 = ['Academic Writing', 'Research Methods', 'Critical Analysis', 
                 'Advanced Theory', 'Scholarly Discussion', 'Professional Development',
                 'Data Interpretation', 'Literature Review', 'Argumentation', 'Synthesis']

CATEGORIES_80 = ['Advanced Academic Writing', 'Sophisticated Argumentation', 
                 'Expert Level Research', 'High-Level Critical Analysis',
                 'Scholarly Excellence', 'Professional Mastery',
                 'Distinguished Discourse', 'Elite Academia']

def add_words(filename, words, level, categories):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            existing = json.load(f)
    except:
        existing = []
    
    existing_words = {w['word'] for w in existing}
    start_id = len(existing) + 1
    added = 0
    
    for i, (word, pos, definition, example) in enumerate(words):
        if word not in existing_words:
            existing.append({
                'id': start_id + added,
                'word': word,
                'level': level,
                'partOfSpeech': pos,
                'definition': definition,
                'example': example,
                'category': categories[(start_id + added) % len(categories)]
            })
            existing_words.add(word)
            added += 1
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    return len(existing), added

def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    total45, added45 = add_words('assets/data/band45_words.json', BAND45_WORDS, 'Band 4.5-5.5', CATEGORIES_45)
    print(f'✅ Band 4.5-5.5: {total45}개 (추가: {added45}개)')
    
    total60, added60 = add_words('assets/data/band60_words.json', BAND60_WORDS, 'Band 6.0-6.5', CATEGORIES_60)
    print(f'✅ Band 6.0-6.5: {total60}개 (추가: {added60}개)')
    
    total70, added70 = add_words('assets/data/band70_words.json', BAND70_WORDS, 'Band 7.0-7.5', CATEGORIES_70)
    print(f'✅ Band 7.0-7.5: {total70}개 (추가: {added70}개)')
    
    total80, added80 = add_words('assets/data/band80_words.json', BAND80_WORDS, 'Band 8.0+', CATEGORIES_80)
    print(f'✅ Band 8.0+: {total80}개 (추가: {added80}개)')

if __name__ == '__main__':
    main()
