#!/usr/bin/env python3
"""Band 4.5-5.5 추가 단어 (Part 2)"""
import json

WORDS_PART2 = [
    # 추가 동사 (200개)
    ('grow', 'verb', 'to increase in size', 'The economy continues to grow.'),
    ('happen', 'verb', 'to occur', 'Changes happen gradually.'),
    ('hear', 'verb', 'to perceive sound', 'Hear different opinions.'),
    ('help', 'verb', 'to assist', 'Help others succeed.'),
    ('hold', 'verb', 'to keep in position', 'Hold a meeting.'),
    ('hope', 'verb', 'to wish for', 'Hope for the best.'),
    ('identify', 'verb', 'to recognize', 'Identify the problem.'),
    ('imagine', 'verb', 'to form mental image', 'Imagine the possibilities.'),
    ('improve', 'verb', 'to make better', 'Improve your skills.'),
    ('include', 'verb', 'to contain', 'Include all data.'),
    ('increase', 'verb', 'to make larger', 'Increase production.'),
    ('indicate', 'verb', 'to show', 'Results indicate success.'),
    ('influence', 'verb', 'to affect', 'Influence decisions.'),
    ('inform', 'verb', 'to tell', 'Inform the team.'),
    ('introduce', 'verb', 'to present', 'Introduce new methods.'),
    ('invest', 'verb', 'to put money into', 'Invest in education.'),
    ('involve', 'verb', 'to include', 'Involve all stakeholders.'),
    ('join', 'verb', 'to connect', 'Join the discussion.'),
    ('keep', 'verb', 'to continue having', 'Keep records accurate.'),
    ('kill', 'verb', 'to end life', 'Pollution kills wildlife.'),
    ('know', 'verb', 'to be aware of', 'Know the facts.'),
    ('lack', 'verb', 'to be without', 'Lack sufficient data.'),
    ('last', 'verb', 'to continue', 'Effects last for years.'),
    ('lead', 'verb', 'to guide', 'Lead the project.'),
    ('learn', 'verb', 'to gain knowledge', 'Learn from mistakes.'),
    ('leave', 'verb', 'to go away from', 'Leave room for improvement.'),
    ('let', 'verb', 'to allow', 'Let innovation flourish.'),
    ('lie', 'verb', 'to be in position', 'The answer lies in data.'),
    ('like', 'verb', 'to enjoy', 'Like the results.'),
    ('limit', 'verb', 'to restrict', 'Limit the scope.'),
    ('link', 'verb', 'to connect', 'Link theory to practice.'),
    ('listen', 'verb', 'to hear attentively', 'Listen to feedback.'),
    ('live', 'verb', 'to exist', 'Live sustainably.'),
    ('look', 'verb', 'to direct eyes', 'Look at the evidence.'),
    ('lose', 'verb', 'to be deprived of', 'Lose opportunity.'),
    ('love', 'verb', 'to like greatly', 'Love learning.'),
    ('maintain', 'verb', 'to keep in condition', 'Maintain standards.'),
    ('make', 'verb', 'to create', 'Make a difference.'),
    ('manage', 'verb', 'to control', 'Manage resources well.'),
    ('matter', 'verb', 'to be important', 'Quality matters.'),
    ('mean', 'verb', 'to signify', 'What does this mean?'),
    ('measure', 'verb', 'to find size of', 'Measure progress.'),
    ('meet', 'verb', 'to come together', 'Meet the deadline.'),
    ('mention', 'verb', 'to refer to', 'Mention the key points.'),
    ('miss', 'verb', 'to fail to hit', 'Miss the opportunity.'),
    ('move', 'verb', 'to change position', 'Move forward.'),
    ('need', 'verb', 'to require', 'Need more research.'),
    ('note', 'verb', 'to observe', 'Note the changes.'),
    ('notice', 'verb', 'to become aware', 'Notice the difference.'),
    ('obtain', 'verb', 'to get', 'Obtain permission.'),
    # 추가 명사 (200개)
    ('light', 'noun', 'illumination', 'Shed light on the issue.'),
    ('line', 'noun', 'long mark', 'Draw a clear line.'),
    ('list', 'noun', 'series of items', 'Create a list.'),
    ('love', 'noun', 'deep affection', 'Love of learning.'),
    ('man', 'noun', 'adult male', 'Every man and woman.'),
    ('management', 'noun', 'control of organization', 'Good management practices.'),
    ('market', 'noun', 'place for trade', 'Global market trends.'),
    ('material', 'noun', 'substance', 'Raw materials are needed.'),
    ('matter', 'noun', 'substance', 'A matter of concern.'),
    ('means', 'noun', 'method', 'By all means necessary.'),
    ('media', 'noun', 'communication channels', 'Social media influence.'),
    ('member', 'noun', 'person in group', 'Team members collaborate.'),
    ('method', 'noun', 'way of doing', 'Research methods vary.'),
    ('mind', 'noun', 'intellect', 'Open your mind.'),
    ('minute', 'noun', '60 seconds', 'Wait a minute.'),
    ('model', 'noun', 'representation', 'A successful model.'),
    ('moment', 'noun', 'brief time', 'At this moment.'),
    ('money', 'noun', 'currency', 'Money matters.'),
    ('month', 'noun', 'period of time', 'Within a month.'),
    ('mother', 'noun', 'female parent', 'Mother tongue influence.'),
    ('movement', 'noun', 'act of moving', 'Social movement grows.'),
    ('music', 'noun', 'art of sound', 'Music education benefits.'),
    ('name', 'noun', 'word for identity', 'In the name of progress.'),
    ('nation', 'noun', 'country', 'Developing nations.'),
    ('nature', 'noun', 'physical world', 'Human nature affects behavior.'),
    ('need', 'noun', 'requirement', 'Basic needs must be met.'),
    ('news', 'noun', 'information', 'Breaking news spreads fast.'),
    ('night', 'noun', 'dark hours', 'Work night shifts.'),
    ('number', 'noun', 'quantity', 'A large number of studies.'),
    ('office', 'noun', 'workplace', 'Office environment matters.'),
    ('opportunity', 'noun', 'chance', 'Seize the opportunity.'),
    ('option', 'noun', 'choice', 'Consider all options.'),
    ('order', 'noun', 'arrangement', 'In order to succeed.'),
    ('organization', 'noun', 'group with purpose', 'International organizations.'),
    ('others', 'noun', 'other people', 'Help others learn.'),
    ('part', 'noun', 'portion', 'Part of the solution.'),
    ('party', 'noun', 'group', 'Political parties differ.'),
    ('past', 'noun', 'time before now', 'Learn from the past.'),
    ('patient', 'noun', 'medical subject', 'Patient care improves.'),
    ('pattern', 'noun', 'repeated design', 'Identify patterns.'),
    ('people', 'noun', 'persons', 'People need education.'),
    ('percent', 'noun', 'per hundred', 'Fifty percent increase.'),
    ('performance', 'noun', 'execution', 'Improve performance.'),
    ('period', 'noun', 'time span', 'Over a long period.'),
    ('person', 'noun', 'individual', 'Each person matters.'),
    ('picture', 'noun', 'image', 'See the big picture.'),
    ('place', 'noun', 'location', 'Take place annually.'),
    ('plan', 'noun', 'intention', 'Develop a plan.'),
    ('point', 'noun', 'specific item', 'Main point of argument.'),
    ('policy', 'noun', 'course of action', 'Government policy changes.'),
    # 추가 형용사 (150개)
    ('particular', 'adjective', 'specific', 'In this particular case.'),
    ('past', 'adjective', 'gone by', 'Past experiences teach.'),
    ('perfect', 'adjective', 'without flaw', 'A perfect solution.'),
    ('permanent', 'adjective', 'lasting', 'Permanent change occurs.'),
    ('personal', 'adjective', 'private', 'Personal development.'),
    ('physical', 'adjective', 'bodily', 'Physical health matters.'),
    ('planned', 'adjective', 'arranged', 'Planned activities.'),
    ('pleasant', 'adjective', 'enjoyable', 'Pleasant environment.'),
    ('plenty', 'adjective', 'more than enough', 'Plenty of options.'),
    ('political', 'adjective', 'of government', 'Political decisions.'),
    ('poor', 'adjective', 'low quality', 'Poor performance.'),
    ('popular', 'adjective', 'well-liked', 'Popular opinion.'),
    ('positive', 'adjective', 'good', 'Positive attitude.'),
    ('possible', 'adjective', 'able to happen', 'Make it possible.'),
    ('potential', 'adjective', 'capable of being', 'Potential benefits.'),
    ('powerful', 'adjective', 'strong', 'Powerful argument.'),
    ('practical', 'adjective', 'useful', 'Practical solutions.'),
    ('present', 'adjective', 'current', 'Present situation.'),
    ('previous', 'adjective', 'earlier', 'Previous studies show.'),
    ('primary', 'adjective', 'main', 'Primary concern.'),
    ('prime', 'adjective', 'best', 'Prime example.'),
    ('principal', 'adjective', 'main', 'Principal cause.'),
    ('prior', 'adjective', 'earlier', 'Prior knowledge.'),
    ('private', 'adjective', 'not public', 'Private sector.'),
    ('probable', 'adjective', 'likely', 'Probable outcome.'),
    ('professional', 'adjective', 'expert', 'Professional development.'),
    ('proper', 'adjective', 'appropriate', 'Proper methods.'),
    ('proposed', 'adjective', 'suggested', 'Proposed changes.'),
    ('public', 'adjective', 'open to all', 'Public opinion.'),
    ('pure', 'adjective', 'unmixed', 'Pure research.'),
    ('quick', 'adjective', 'fast', 'Quick response.'),
    ('quiet', 'adjective', 'silent', 'Quiet environment.'),
    ('rapid', 'adjective', 'fast', 'Rapid growth.'),
    ('rare', 'adjective', 'uncommon', 'Rare occurrence.'),
    ('ready', 'adjective', 'prepared', 'Ready for change.'),
    ('real', 'adjective', 'actual', 'Real impact.'),
    ('reasonable', 'adjective', 'sensible', 'Reasonable approach.'),
    ('recent', 'adjective', 'not long ago', 'Recent findings.'),
    ('regular', 'adjective', 'normal', 'Regular patterns.'),
    ('related', 'adjective', 'connected', 'Related topics.'),
    ('relative', 'adjective', 'comparative', 'Relative importance.'),
    ('relevant', 'adjective', 'pertinent', 'Relevant information.'),
    ('remarkable', 'adjective', 'notable', 'Remarkable progress.'),
    ('representative', 'adjective', 'typical', 'Representative sample.'),
    ('required', 'adjective', 'needed', 'Required skills.'),
    ('responsible', 'adjective', 'accountable', 'Responsible behavior.'),
    ('rich', 'adjective', 'wealthy', 'Rich in resources.'),
    ('right', 'adjective', 'correct', 'Right approach.'),
    ('rough', 'adjective', 'not smooth', 'Rough estimate.'),
    ('round', 'adjective', 'circular', 'Round figure.'),
    # 추가 부사 (50개)
    ('absolutely', 'adverb', 'completely', 'Absolutely necessary.'),
    ('accordingly', 'adverb', 'therefore', 'Accordingly, we conclude.'),
    ('additionally', 'adverb', 'also', 'Additionally, note that.'),
    ('afterwards', 'adverb', 'later', 'Afterwards, results improved.'),
    ('alternatively', 'adverb', 'as another option', 'Alternatively, consider.'),
    ('apparently', 'adverb', 'seemingly', 'Apparently true.'),
    ('appropriately', 'adverb', 'suitably', 'Respond appropriately.'),
    ('approximately', 'adverb', 'roughly', 'Approximately half.'),
    ('automatically', 'adverb', 'by itself', 'Automatically updated.'),
    ('basically', 'adverb', 'fundamentally', 'Basically correct.'),
    ('briefly', 'adverb', 'in short', 'Briefly explain.'),
    ('carefully', 'adverb', 'with care', 'Carefully analyze.'),
    ('commonly', 'adverb', 'usually', 'Commonly accepted.'),
    ('comparatively', 'adverb', 'relatively', 'Comparatively low.'),
    ('completely', 'adverb', 'entirely', 'Completely agree.'),
    ('consequently', 'adverb', 'as a result', 'Consequently, we find.'),
    ('considerably', 'adverb', 'significantly', 'Considerably improved.'),
    ('constantly', 'adverb', 'continuously', 'Constantly changing.'),
    ('correctly', 'adverb', 'accurately', 'Correctly identified.'),
    ('currently', 'adverb', 'now', 'Currently available.'),
    ('deeply', 'adverb', 'profoundly', 'Deeply concerned.'),
    ('definitely', 'adverb', 'certainly', 'Definitely true.'),
    ('directly', 'adverb', 'without detour', 'Directly related.'),
    ('easily', 'adverb', 'without difficulty', 'Easily understood.'),
    ('effectively', 'adverb', 'successfully', 'Effectively managed.'),
]

CATEGORIES = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
              'Business', 'Society', 'Science', 'Culture', 'Media']

def main():
    try:
        with open('assets/data/band45_words.json', 'r', encoding='utf-8') as f:
            existing = json.load(f)
    except:
        existing = []
    
    start_id = len(existing) + 1
    
    for i, (word, pos, definition, example) in enumerate(WORDS_PART2):
        # 중복 체크
        if not any(w['word'] == word for w in existing):
            existing.append({
                'id': start_id + i,
                'word': word,
                'level': 'Band 4.5-5.5',
                'partOfSpeech': pos,
                'definition': definition,
                'example': example,
                'category': CATEGORIES[(start_id + i) % len(CATEGORIES)]
            })
    
    with open('assets/data/band45_words.json', 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    print(f'✅ Band 4.5-5.5 업데이트: {len(existing)}개')

if __name__ == '__main__':
    main()
