#!/usr/bin/env python3
"""Band 7.0-7.5 고급 단어 생성"""
import json

WORDS = [
    # 고급 동사 (250개)
    ('abolish', 'verb', 'to formally put an end to', 'Abolish outdated policies.'),
    ('abstain', 'verb', 'to refrain from', 'Abstain from voting.'),
    ('accentuate', 'verb', 'to emphasize', 'Accentuate the positive.'),
    ('adjudicate', 'verb', 'to make formal judgment', 'Adjudicate disputes.'),
    ('aggregate', 'verb', 'to combine', 'Aggregate the findings.'),
    ('alleviate', 'verb', 'to make less severe', 'Alleviate poverty.'),
    ('amalgamate', 'verb', 'to combine', 'Amalgamate departments.'),
    ('ameliorate', 'verb', 'to improve', 'Ameliorate conditions.'),
    ('annotate', 'verb', 'to add notes', 'Annotate the text.'),
    ('apportion', 'verb', 'to divide', 'Apportion blame fairly.'),
    ('arbitrate', 'verb', 'to settle dispute', 'Arbitrate between parties.'),
    ('articulate', 'verb', 'to express clearly', 'Articulate your ideas.'),
    ('ascertain', 'verb', 'to find out for certain', 'Ascertain the facts.'),
    ('assimilate', 'verb', 'to absorb', 'Assimilate information.'),
    ('augment', 'verb', 'to increase', 'Augment your income.'),
    ('authenticate', 'verb', 'to verify', 'Authenticate the document.'),
    ('benchmark', 'verb', 'to evaluate by comparison', 'Benchmark performance.'),
    ('calibrate', 'verb', 'to adjust precisely', 'Calibrate instruments.'),
    ('capitalize', 'verb', 'to take advantage of', 'Capitalize on opportunities.'),
    ('circumscribe', 'verb', 'to restrict', 'Circumscribe authority.'),
    ('coalesce', 'verb', 'to come together', 'Ideas coalesced.'),
    ('codify', 'verb', 'to arrange systematically', 'Codify the rules.'),
    ('collaborate', 'verb', 'to work jointly', 'Collaborate internationally.'),
    ('collate', 'verb', 'to collect and combine', 'Collate the data.'),
    ('commend', 'verb', 'to praise', 'Commend the effort.'),
    ('compartmentalize', 'verb', 'to divide into sections', 'Compartmentalize tasks.'),
    ('concatenate', 'verb', 'to link together', 'Concatenate strings.'),
    ('conceptualize', 'verb', 'to form a concept', 'Conceptualize the problem.'),
    ('concur', 'verb', 'to agree', 'Experts concur.'),
    ('condense', 'verb', 'to make concentrated', 'Condense the report.'),
    ('confiscate', 'verb', 'to seize', 'Confiscate illegal goods.'),
    ('consolidate', 'verb', 'to combine', 'Consolidate gains.'),
    ('constrain', 'verb', 'to restrict', 'Constrain budget.'),
    ('contextualize', 'verb', 'to place in context', 'Contextualize findings.'),
    ('contradict', 'verb', 'to deny truth', 'Evidence contradicts.'),
    ('contravene', 'verb', 'to violate', 'Contravene regulations.'),
    ('converge', 'verb', 'to come together', 'Opinions converge.'),
    ('correlate', 'verb', 'to have mutual relationship', 'Variables correlate.'),
    ('corroborate', 'verb', 'to confirm', 'Corroborate findings.'),
    ('culminate', 'verb', 'to reach climax', 'Efforts culminated.'),
    ('curtail', 'verb', 'to reduce', 'Curtail spending.'),
    ('decentralize', 'verb', 'to distribute authority', 'Decentralize power.'),
    ('deduce', 'verb', 'to conclude by reasoning', 'Deduce from evidence.'),
    ('delineate', 'verb', 'to describe precisely', 'Delineate boundaries.'),
    ('demarcate', 'verb', 'to set boundaries', 'Demarcate territories.'),
    ('depict', 'verb', 'to represent', 'Depict accurately.'),
    ('derive', 'verb', 'to obtain from', 'Derive conclusions.'),
    ('designate', 'verb', 'to officially assign', 'Designate a leader.'),
    ('deteriorate', 'verb', 'to become worse', 'Conditions deteriorate.'),
    ('deviate', 'verb', 'to depart from', 'Deviate from the norm.'),
    ('differentiate', 'verb', 'to distinguish', 'Differentiate between.'),
    ('diminish', 'verb', 'to make less', 'Diminish the impact.'),
    ('discern', 'verb', 'to perceive', 'Discern patterns.'),
    ('disclose', 'verb', 'to reveal', 'Disclose information.'),
    ('discriminate', 'verb', 'to distinguish', 'Discriminate between.'),
    ('disperse', 'verb', 'to scatter', 'Disperse resources.'),
    ('displace', 'verb', 'to move from place', 'Displace workers.'),
    ('dispose', 'verb', 'to get rid of', 'Dispose of waste.'),
    ('disseminate', 'verb', 'to spread widely', 'Disseminate knowledge.'),
    ('dissolve', 'verb', 'to bring to end', 'Dissolve the partnership.'),
    ('distort', 'verb', 'to twist', 'Distort the truth.'),
    ('diversify', 'verb', 'to make varied', 'Diversify investments.'),
    ('divert', 'verb', 'to redirect', 'Divert resources.'),
    ('dominate', 'verb', 'to control', 'Dominate the market.'),
    ('draft', 'verb', 'to prepare preliminary', 'Draft the proposal.'),
    ('duplicate', 'verb', 'to copy', 'Duplicate the results.'),
    ('dwell', 'verb', 'to focus on', 'Dwell on the details.'),
    ('elaborate', 'verb', 'to explain in detail', 'Elaborate on the point.'),
    ('elicit', 'verb', 'to draw out', 'Elicit a response.'),
    ('eliminate', 'verb', 'to remove', 'Eliminate errors.'),
    ('embed', 'verb', 'to fix firmly', 'Embed in culture.'),
    ('embody', 'verb', 'to represent', 'Embody principles.'),
    ('emerge', 'verb', 'to come into view', 'Patterns emerge.'),
    ('emphasize', 'verb', 'to stress', 'Emphasize importance.'),
    ('emulate', 'verb', 'to match or surpass', 'Emulate success.'),
    ('enable', 'verb', 'to make possible', 'Enable participation.'),
    ('encompass', 'verb', 'to include', 'Encompass all aspects.'),
    ('encounter', 'verb', 'to meet', 'Encounter difficulties.'),
    ('endorse', 'verb', 'to approve', 'Endorse the proposal.'),
    ('enforce', 'verb', 'to compel compliance', 'Enforce regulations.'),
    # 고급 명사 (250개)
    ('aberration', 'noun', 'deviation from normal', 'A statistical aberration.'),
    ('abstraction', 'noun', 'theoretical concept', 'Levels of abstraction.'),
    ('acumen', 'noun', 'keen insight', 'Business acumen.'),
    ('adversity', 'noun', 'misfortune', 'Overcome adversity.'),
    ('affiliation', 'noun', 'connection', 'Political affiliation.'),
    ('allegation', 'noun', 'claim without proof', 'Serious allegations.'),
    ('ambiguity', 'noun', 'uncertainty', 'Remove ambiguity.'),
    ('analogue', 'noun', 'something comparable', 'Find an analogue.'),
    ('anomaly', 'noun', 'irregularity', 'A statistical anomaly.'),
    ('antecedent', 'noun', 'thing that comes before', 'Historical antecedents.'),
    ('apparatus', 'noun', 'complex equipment', 'The state apparatus.'),
    ('appraisal', 'noun', 'assessment', 'Performance appraisal.'),
    ('aptitude', 'noun', 'natural ability', 'Test aptitude.'),
    ('articulation', 'noun', 'expression', 'Clear articulation.'),
    ('assertion', 'noun', 'confident statement', 'Bold assertions.'),
    ('assimilation', 'noun', 'absorption', 'Cultural assimilation.'),
    ('asymmetry', 'noun', 'lack of equality', 'Information asymmetry.'),
    ('attrition', 'noun', 'gradual reduction', 'Staff attrition.'),
    ('autonomy', 'noun', 'self-governance', 'Regional autonomy.'),
    ('benchmark', 'noun', 'standard', 'Industry benchmarks.'),
    ('beneficiary', 'noun', 'person who benefits', 'The main beneficiary.'),
    ('bureaucracy', 'noun', 'administrative system', 'Government bureaucracy.'),
    ('calibration', 'noun', 'precise adjustment', 'Instrument calibration.'),
    ('caveat', 'noun', 'warning', 'Add a caveat.'),
    ('cessation', 'noun', 'stopping', 'Cessation of hostilities.'),
    ('cohesion', 'noun', 'unity', 'Social cohesion.'),
    ('collusion', 'noun', 'secret cooperation', 'Price collusion.'),
    ('compilation', 'noun', 'collection', 'A compilation of data.'),
    ('concession', 'noun', 'something granted', 'Make concessions.'),
    ('confluence', 'noun', 'coming together', 'A confluence of factors.'),
    ('congruence', 'noun', 'agreement', 'Goal congruence.'),
    ('conjecture', 'noun', 'opinion without proof', 'Pure conjecture.'),
    ('consolidation', 'noun', 'combination', 'Market consolidation.'),
    ('consortium', 'noun', 'group of organizations', 'Research consortium.'),
    ('contingency', 'noun', 'future event', 'Plan for contingencies.'),
    ('continuity', 'noun', 'unbroken existence', 'Business continuity.'),
    ('contraction', 'noun', 'decrease', 'Economic contraction.'),
    ('convergence', 'noun', 'coming together', 'Technological convergence.'),
    ('counterpart', 'noun', 'equivalent', 'Foreign counterparts.'),
    ('credibility', 'noun', 'trustworthiness', 'Maintain credibility.'),
    ('deficiency', 'noun', 'lack', 'Nutritional deficiency.'),
    ('degradation', 'noun', 'decline', 'Environmental degradation.'),
    ('delegation', 'noun', 'group of representatives', 'Send a delegation.'),
    ('demography', 'noun', 'study of population', 'Demographic shifts.'),
    ('deviation', 'noun', 'departure from norm', 'Standard deviation.'),
    ('dichotomy', 'noun', 'division into two', 'A false dichotomy.'),
    ('differential', 'noun', 'difference', 'Price differential.'),
    ('diffusion', 'noun', 'spreading', 'Technology diffusion.'),
    ('dilemma', 'noun', 'difficult choice', 'Face a dilemma.'),
    ('dimension', 'noun', 'aspect', 'Multiple dimensions.'),
    ('discrepancy', 'noun', 'inconsistency', 'Address the discrepancy.'),
    ('discretion', 'noun', 'judgment', 'Use discretion.'),
    ('disparity', 'noun', 'inequality', 'Income disparity.'),
    ('disposition', 'noun', 'tendency', 'Natural disposition.'),
    ('disruption', 'noun', 'disturbance', 'Market disruption.'),
    ('distinction', 'noun', 'difference', 'Make a distinction.'),
    ('distortion', 'noun', 'misrepresentation', 'Market distortion.'),
    ('diversity', 'noun', 'variety', 'Cultural diversity.'),
    ('doctrine', 'noun', 'principle', 'Political doctrine.'),
    ('domain', 'noun', 'area of knowledge', 'In the domain of.'),
    # 고급 형용사 (200개)
    ('abrupt', 'adjective', 'sudden', 'An abrupt change.'),
    ('adverse', 'adjective', 'negative', 'Adverse effects.'),
    ('arbitrary', 'adjective', 'random', 'Arbitrary decisions.'),
    ('asymmetric', 'adjective', 'unequal', 'Asymmetric relationship.'),
    ('authentic', 'adjective', 'genuine', 'Authentic sources.'),
    ('autonomous', 'adjective', 'independent', 'Autonomous region.'),
    ('burgeoning', 'adjective', 'growing rapidly', 'Burgeoning industry.'),
    ('causal', 'adjective', 'relating to cause', 'Causal relationship.'),
    ('chronic', 'adjective', 'long-lasting', 'Chronic problems.'),
    ('cognitive', 'adjective', 'relating to cognition', 'Cognitive development.'),
    ('cohesive', 'adjective', 'unified', 'Cohesive strategy.'),
    ('compelling', 'adjective', 'convincing', 'Compelling evidence.'),
    ('complementary', 'adjective', 'completing', 'Complementary skills.'),
    ('concomitant', 'adjective', 'accompanying', 'Concomitant factors.'),
    ('conducive', 'adjective', 'favorable', 'Conducive to learning.'),
    ('congruent', 'adjective', 'in agreement', 'Congruent with goals.'),
    ('consecutive', 'adjective', 'following each other', 'Consecutive years.'),
    ('conspicuous', 'adjective', 'obvious', 'Conspicuous absence.'),
    ('constituent', 'adjective', 'forming part of', 'Constituent elements.'),
    ('contingent', 'adjective', 'dependent', 'Contingent on approval.'),
    ('controversial', 'adjective', 'causing debate', 'Controversial topic.'),
    ('convergent', 'adjective', 'coming together', 'Convergent views.'),
    ('cumulative', 'adjective', 'increasing', 'Cumulative effect.'),
    ('decisive', 'adjective', 'conclusive', 'A decisive factor.'),
    ('definitive', 'adjective', 'conclusive', 'Definitive answer.'),
    ('deliberate', 'adjective', 'intentional', 'Deliberate action.'),
    ('detrimental', 'adjective', 'harmful', 'Detrimental effects.'),
    ('differential', 'adjective', 'distinctive', 'Differential treatment.'),
    ('discrete', 'adjective', 'separate', 'Discrete categories.'),
    ('disproportionate', 'adjective', 'unequal', 'Disproportionate impact.'),
    ('disruptive', 'adjective', 'causing disturbance', 'Disruptive technology.'),
    ('distinct', 'adjective', 'clearly different', 'Distinct patterns.'),
    ('divergent', 'adjective', 'differing', 'Divergent opinions.'),
    ('dormant', 'adjective', 'inactive', 'Dormant potential.'),
    ('drastic', 'adjective', 'extreme', 'Drastic measures.'),
    ('dynamic', 'adjective', 'changing', 'Dynamic environment.'),
    ('elusive', 'adjective', 'hard to find', 'Elusive goals.'),
    ('empirical', 'adjective', 'based on observation', 'Empirical evidence.'),
    ('endemic', 'adjective', 'native to area', 'Endemic species.'),
    ('equitable', 'adjective', 'fair', 'Equitable distribution.'),
]

CATEGORIES = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
              'Business', 'Society', 'Science', 'Culture', 'Media']

def main():
    try:
        with open('assets/data/band60_words.json', 'r', encoding='utf-8') as f:
            existing = json.load(f)
            start_id = max(w['id'] for w in existing) + 1
    except:
        start_id = 1
    
    words = []
    for i, (word, pos, definition, example) in enumerate(WORDS, start_id):
        words.append({
            'id': i,
            'word': word,
            'level': 'Band 7.0-7.5',
            'partOfSpeech': pos,
            'definition': definition,
            'example': example,
            'category': CATEGORIES[i % len(CATEGORIES)]
        })
    
    with open('assets/data/band70_words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, indent=2, ensure_ascii=False)
    
    print(f'✅ Band 7.0-7.5: {len(words)}개 생성 완료')

if __name__ == '__main__':
    main()
