#!/usr/bin/env python3
"""Band 6.0-6.5 중급 단어 생성"""
import json

WORDS = [
    # 학술 동사 (400개)
    ('abandon', 'verb', 'to give up completely', 'Abandon outdated theories.'),
    ('absorb', 'verb', 'to take in', 'Plants absorb carbon dioxide.'),
    ('accelerate', 'verb', 'to speed up', 'Accelerate the process.'),
    ('accommodate', 'verb', 'to provide for', 'Accommodate different needs.'),
    ('accompany', 'verb', 'to go with', 'Charts accompany the text.'),
    ('accomplish', 'verb', 'to achieve', 'Accomplish your objectives.'),
    ('accumulate', 'verb', 'to gather over time', 'Accumulate evidence.'),
    ('acknowledge', 'verb', 'to accept or admit', 'Acknowledge limitations.'),
    ('acquire', 'verb', 'to gain possession', 'Acquire new skills.'),
    ('adapt', 'verb', 'to adjust', 'Adapt to new environments.'),
    ('address', 'verb', 'to deal with', 'Address underlying issues.'),
    ('administer', 'verb', 'to manage', 'Administer the program.'),
    ('advocate', 'verb', 'to support publicly', 'Advocate for change.'),
    ('allocate', 'verb', 'to distribute', 'Allocate resources.'),
    ('alter', 'verb', 'to change', 'Alter the approach.'),
    ('analyze', 'verb', 'to examine in detail', 'Analyze the data.'),
    ('anticipate', 'verb', 'to expect', 'Anticipate challenges.'),
    ('appreciate', 'verb', 'to recognize value', 'Appreciate diversity.'),
    ('approximate', 'verb', 'to estimate', 'Approximate the cost.'),
    ('arise', 'verb', 'to come up', 'Problems arise unexpectedly.'),
    ('assess', 'verb', 'to evaluate', 'Assess the situation.'),
    ('assign', 'verb', 'to allocate', 'Assign tasks appropriately.'),
    ('assist', 'verb', 'to help', 'Assist with the project.'),
    ('associate', 'verb', 'to connect', 'Associate concepts together.'),
    ('attach', 'verb', 'to fasten', 'Attach relevant documents.'),
    ('attain', 'verb', 'to achieve', 'Attain your goals.'),
    ('attribute', 'verb', 'to credit to', 'Attribute success to teamwork.'),
    ('authorize', 'verb', 'to give permission', 'Authorize expenditure.'),
    ('boost', 'verb', 'to increase', 'Boost economic growth.'),
    ('calculate', 'verb', 'to compute', 'Calculate the percentage.'),
    ('categorize', 'verb', 'to classify', 'Categorize the responses.'),
    ('cease', 'verb', 'to stop', 'Cease all operations.'),
    ('challenge', 'verb', 'to question', 'Challenge assumptions.'),
    ('characterize', 'verb', 'to describe', 'Characterize the phenomenon.'),
    ('cite', 'verb', 'to quote', 'Cite your sources.'),
    ('clarify', 'verb', 'to make clear', 'Clarify your position.'),
    ('classify', 'verb', 'to arrange in groups', 'Classify the data.'),
    ('collapse', 'verb', 'to fall down', 'Systems collapse under pressure.'),
    ('combine', 'verb', 'to join together', 'Combine approaches.'),
    ('comment', 'verb', 'to remark', 'Comment on findings.'),
    ('commit', 'verb', 'to pledge', 'Commit to sustainability.'),
    ('communicate', 'verb', 'to share information', 'Communicate effectively.'),
    ('compensate', 'verb', 'to make up for', 'Compensate for losses.'),
    ('compete', 'verb', 'to strive against', 'Compete in global markets.'),
    ('compile', 'verb', 'to collect', 'Compile the report.'),
    ('complement', 'verb', 'to complete', 'Skills complement each other.'),
    ('comply', 'verb', 'to conform', 'Comply with regulations.'),
    ('comprise', 'verb', 'to consist of', 'The team comprises experts.'),
    ('compute', 'verb', 'to calculate', 'Compute the results.'),
    ('conceive', 'verb', 'to form in mind', 'Conceive a new approach.'),
    ('concentrate', 'verb', 'to focus', 'Concentrate on key issues.'),
    ('conclude', 'verb', 'to finish', 'Conclude the discussion.'),
    ('conduct', 'verb', 'to carry out', 'Conduct research.'),
    ('confine', 'verb', 'to limit', 'Confine to certain areas.'),
    ('confirm', 'verb', 'to verify', 'Confirm the results.'),
    ('conflict', 'verb', 'to clash', 'Interests conflict sometimes.'),
    ('conform', 'verb', 'to comply', 'Conform to standards.'),
    ('confront', 'verb', 'to face', 'Confront the challenges.'),
    ('consent', 'verb', 'to agree', 'Consent to participate.'),
    ('conserve', 'verb', 'to protect', 'Conserve natural resources.'),
    ('consist', 'verb', 'to be made of', 'Consist of several parts.'),
    ('constitute', 'verb', 'to make up', 'Constitute a majority.'),
    ('constrain', 'verb', 'to restrict', 'Constrain spending.'),
    ('construct', 'verb', 'to build', 'Construct a framework.'),
    ('consult', 'verb', 'to seek advice', 'Consult with experts.'),
    ('consume', 'verb', 'to use up', 'Consume resources.'),
    ('contact', 'verb', 'to get in touch', 'Contact the team.'),
    ('contemplate', 'verb', 'to consider', 'Contemplate the options.'),
    ('contract', 'verb', 'to shrink', 'Markets contract during recession.'),
    ('contradict', 'verb', 'to deny truth', 'Evidence contradicts claims.'),
    ('contrast', 'verb', 'to compare differences', 'Contrast the two views.'),
    ('contribute', 'verb', 'to give', 'Contribute to the discussion.'),
    ('convert', 'verb', 'to change', 'Convert to renewable energy.'),
    ('convey', 'verb', 'to communicate', 'Convey the message clearly.'),
    ('convince', 'verb', 'to persuade', 'Convince stakeholders.'),
    ('cooperate', 'verb', 'to work together', 'Cooperate with partners.'),
    ('coordinate', 'verb', 'to organize', 'Coordinate efforts.'),
    ('correspond', 'verb', 'to match', 'Results correspond to theory.'),
    ('decline', 'verb', 'to decrease', 'Numbers decline steadily.'),
    ('deduce', 'verb', 'to conclude', 'Deduce from evidence.'),
    ('deem', 'verb', 'to consider', 'Deem it necessary.'),
    ('defend', 'verb', 'to protect', 'Defend your position.'),
    ('defer', 'verb', 'to postpone', 'Defer the decision.'),
    ('define', 'verb', 'to explain meaning', 'Define the term clearly.'),
    ('delegate', 'verb', 'to assign', 'Delegate responsibilities.'),
    ('deliberate', 'verb', 'to consider carefully', 'Deliberate on the issue.'),
    ('demonstrate', 'verb', 'to show', 'Demonstrate the effect.'),
    ('denote', 'verb', 'to indicate', 'Symbols denote meaning.'),
    ('deny', 'verb', 'to refuse', 'Deny the allegations.'),
    ('depict', 'verb', 'to represent', 'Depict the situation.'),
    ('deploy', 'verb', 'to use', 'Deploy new strategies.'),
    ('derive', 'verb', 'to obtain from', 'Derive conclusions.'),
    ('designate', 'verb', 'to officially assign', 'Designate a leader.'),
    ('detect', 'verb', 'to discover', 'Detect changes early.'),
    ('determine', 'verb', 'to establish', 'Determine the cause.'),
    ('devise', 'verb', 'to plan', 'Devise a solution.'),
    ('devote', 'verb', 'to dedicate', 'Devote time to study.'),
    ('differentiate', 'verb', 'to distinguish', 'Differentiate between types.'),
    ('diminish', 'verb', 'to reduce', 'Diminish the impact.'),
    ('discard', 'verb', 'to throw away', 'Discard irrelevant data.'),
    # 학술 명사 (400개)
    ('absence', 'noun', 'state of not being present', 'The absence of evidence.'),
    ('abundance', 'noun', 'large quantity', 'An abundance of resources.'),
    ('accuracy', 'noun', 'correctness', 'Ensure data accuracy.'),
    ('adaptation', 'noun', 'process of adjusting', 'Adaptation to climate.'),
    ('administration', 'noun', 'management', 'Government administration.'),
    ('agenda', 'noun', 'list of items', 'The political agenda.'),
    ('aggregate', 'noun', 'total', 'The aggregate result.'),
    ('allocation', 'noun', 'distribution', 'Resource allocation.'),
    ('alternative', 'noun', 'another option', 'Consider alternatives.'),
    ('amendment', 'noun', 'change', 'A constitutional amendment.'),
    ('analogy', 'noun', 'comparison', 'Draw an analogy.'),
    ('apparatus', 'noun', 'equipment', 'Scientific apparatus.'),
    ('appendix', 'noun', 'supplementary material', 'See the appendix.'),
    ('appreciation', 'noun', 'recognition of value', 'Show appreciation.'),
    ('aspect', 'noun', 'feature', 'Consider every aspect.'),
    ('assessment', 'noun', 'evaluation', 'Risk assessment.'),
    ('assumption', 'noun', 'thing accepted as true', 'Question assumptions.'),
    ('awareness', 'noun', 'knowledge', 'Environmental awareness.'),
    ('barrier', 'noun', 'obstacle', 'Trade barriers.'),
    ('bias', 'noun', 'prejudice', 'Avoid research bias.'),
    ('bond', 'noun', 'connection', 'Social bonds.'),
    ('bulk', 'noun', 'majority', 'The bulk of evidence.'),
    ('capacity', 'noun', 'ability to contain', 'Production capacity.'),
    ('category', 'noun', 'class', 'Fall into a category.'),
    ('challenge', 'noun', 'difficult task', 'Face new challenges.'),
    ('channel', 'noun', 'medium', 'Communication channels.'),
    ('characteristic', 'noun', 'distinguishing feature', 'Key characteristics.'),
    ('circumstance', 'noun', 'condition', 'Under these circumstances.'),
    ('classification', 'noun', 'arrangement in groups', 'Classification system.'),
    ('clause', 'noun', 'section', 'A legal clause.'),
    ('code', 'noun', 'system of rules', 'The building code.'),
    ('coherence', 'noun', 'logical connection', 'Textual coherence.'),
    ('collaboration', 'noun', 'working together', 'International collaboration.'),
    ('colleague', 'noun', 'fellow worker', 'Consult with colleagues.'),
    ('commentary', 'noun', 'explanatory notes', 'Provide commentary.'),
    ('commission', 'noun', 'group tasked with duties', 'The commission report.'),
    ('commitment', 'noun', 'dedication', 'Show commitment.'),
    ('commodity', 'noun', 'raw material', 'Global commodities.'),
    ('communication', 'noun', 'exchange of information', 'Effective communication.'),
    ('compensation', 'noun', 'payment for loss', 'Fair compensation.'),
    ('competence', 'noun', 'ability', 'Core competence.'),
    ('competition', 'noun', 'rivalry', 'Market competition.'),
    ('complexity', 'noun', 'state of being complex', 'Reduce complexity.'),
    ('compliance', 'noun', 'conformity', 'Regulatory compliance.'),
    ('component', 'noun', 'part', 'Key components.'),
    ('composition', 'noun', 'nature of something', 'Chemical composition.'),
    ('comprehension', 'noun', 'understanding', 'Reading comprehension.'),
    ('concentration', 'noun', 'focus', 'Concentration of power.'),
    ('concept', 'noun', 'abstract idea', 'A key concept.'),
    ('conclusion', 'noun', 'end result', 'Draw a conclusion.'),
    ('conduct', 'noun', 'behavior', 'Code of conduct.'),
    ('conference', 'noun', 'formal meeting', 'Academic conference.'),
    ('configuration', 'noun', 'arrangement', 'System configuration.'),
    ('confirmation', 'noun', 'verification', 'Seek confirmation.'),
    ('conflict', 'noun', 'disagreement', 'Resolve the conflict.'),
    ('conformity', 'noun', 'compliance', 'Conformity to standards.'),
    ('conjunction', 'noun', 'combination', 'In conjunction with.'),
    ('consensus', 'noun', 'general agreement', 'Reach consensus.'),
    ('consequence', 'noun', 'result', 'Suffer the consequences.'),
    ('conservation', 'noun', 'preservation', 'Nature conservation.'),
    ('consideration', 'noun', 'careful thought', 'Take into consideration.'),
    ('consistency', 'noun', 'uniformity', 'Maintain consistency.'),
    ('constraint', 'noun', 'limitation', 'Budget constraints.'),
    ('construction', 'noun', 'building', 'Under construction.'),
    ('consultation', 'noun', 'discussion', 'Public consultation.'),
    ('consumption', 'noun', 'using up', 'Energy consumption.'),
    ('context', 'noun', 'circumstances', 'In this context.'),
    ('contradiction', 'noun', 'conflict', 'Apparent contradictions.'),
    ('contrast', 'noun', 'difference', 'In contrast to.'),
    ('contribution', 'noun', 'giving', 'Make a contribution.'),
    ('controversy', 'noun', 'disagreement', 'Cause controversy.'),
    ('convention', 'noun', 'agreement', 'International conventions.'),
    ('conversion', 'noun', 'change', 'Energy conversion.'),
    ('conviction', 'noun', 'strong belief', 'Personal conviction.'),
    ('cooperation', 'noun', 'working together', 'International cooperation.'),
    ('coordination', 'noun', 'organization', 'Better coordination.'),
    ('correlation', 'noun', 'mutual relationship', 'A strong correlation.'),
    ('correspondence', 'noun', 'similarity', 'Correspondence between.'),
    ('criterion', 'noun', 'standard for judging', 'The main criterion.'),
    ('currency', 'noun', 'money system', 'Foreign currency.'),
    ('cycle', 'noun', 'series of events', 'The business cycle.'),
    # 학술 형용사 (300개)
    ('absolute', 'adjective', 'complete', 'An absolute necessity.'),
    ('abstract', 'adjective', 'theoretical', 'Abstract concepts.'),
    ('abundant', 'adjective', 'plentiful', 'Abundant resources.'),
    ('accessible', 'adjective', 'able to be reached', 'Make it accessible.'),
    ('accurate', 'adjective', 'correct', 'Accurate measurements.'),
    ('adequate', 'adjective', 'sufficient', 'Adequate funding.'),
    ('adjacent', 'adjective', 'next to', 'Adjacent areas.'),
    ('administrative', 'adjective', 'relating to management', 'Administrative tasks.'),
    ('adverse', 'adjective', 'unfavorable', 'Adverse effects.'),
    ('aggregate', 'adjective', 'combined', 'Aggregate data.'),
    ('alternative', 'adjective', 'other', 'Alternative methods.'),
    ('ambiguous', 'adjective', 'unclear', 'Ambiguous language.'),
    ('analytical', 'adjective', 'relating to analysis', 'Analytical skills.'),
    ('annual', 'adjective', 'yearly', 'Annual reports.'),
    ('apparent', 'adjective', 'obvious', 'Apparent contradictions.'),
    ('applicable', 'adjective', 'relevant', 'Applicable laws.'),
    ('appropriate', 'adjective', 'suitable', 'Take appropriate action.'),
    ('arbitrary', 'adjective', 'random', 'Arbitrary decisions.'),
    ('automatic', 'adjective', 'self-operating', 'Automatic processes.'),
    ('aware', 'adjective', 'conscious', 'Be aware of risks.'),
    ('beneficial', 'adjective', 'advantageous', 'Mutually beneficial.'),
    ('capable', 'adjective', 'able', 'Highly capable.'),
    ('central', 'adjective', 'main', 'The central argument.'),
    ('classical', 'adjective', 'traditional', 'Classical theories.'),
    ('coherent', 'adjective', 'logical', 'A coherent argument.'),
    ('collective', 'adjective', 'shared', 'Collective responsibility.'),
    ('commercial', 'adjective', 'relating to trade', 'Commercial interests.'),
    ('committed', 'adjective', 'dedicated', 'Committed to excellence.'),
    ('comparable', 'adjective', 'similar', 'Comparable results.'),
    ('compatible', 'adjective', 'able to coexist', 'Compatible systems.'),
    ('competitive', 'adjective', 'relating to competition', 'Competitive advantage.'),
    ('complex', 'adjective', 'complicated', 'Complex issues.'),
    ('comprehensive', 'adjective', 'thorough', 'Comprehensive study.'),
    ('conceptual', 'adjective', 'relating to concepts', 'Conceptual framework.'),
    ('concurrent', 'adjective', 'simultaneous', 'Concurrent events.'),
    ('considerable', 'adjective', 'significant', 'Considerable progress.'),
    ('consistent', 'adjective', 'unchanging', 'Consistent results.'),
    ('constant', 'adjective', 'continuous', 'Constant improvement.'),
    ('constitutional', 'adjective', 'relating to constitution', 'Constitutional rights.'),
    ('contemporary', 'adjective', 'modern', 'Contemporary issues.'),
    ('contextual', 'adjective', 'relating to context', 'Contextual factors.'),
    ('continuous', 'adjective', 'uninterrupted', 'Continuous monitoring.'),
    ('contradictory', 'adjective', 'conflicting', 'Contradictory evidence.'),
    ('conventional', 'adjective', 'traditional', 'Conventional methods.'),
    ('core', 'adjective', 'central', 'Core values.'),
    ('corporate', 'adjective', 'relating to business', 'Corporate responsibility.'),
    ('corresponding', 'adjective', 'matching', 'Corresponding data.'),
    ('credible', 'adjective', 'believable', 'Credible sources.'),
    ('critical', 'adjective', 'crucial', 'A critical factor.'),
    ('crucial', 'adjective', 'essential', 'A crucial decision.'),
]

CATEGORIES = ['Academic', 'Environment', 'Technology', 'Health', 'Education',
              'Business', 'Society', 'Science', 'Culture', 'Media']

def main():
    # Load existing words to get next ID
    try:
        with open('assets/data/band45_words.json', 'r', encoding='utf-8') as f:
            existing = json.load(f)
            start_id = max(w['id'] for w in existing) + 1
    except:
        start_id = 1
    
    words = []
    for i, (word, pos, definition, example) in enumerate(WORDS, start_id):
        words.append({
            'id': i,
            'word': word,
            'level': 'Band 6.0-6.5',
            'partOfSpeech': pos,
            'definition': definition,
            'example': example,
            'category': CATEGORIES[i % len(CATEGORIES)]
        })
    
    with open('assets/data/band60_words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, indent=2, ensure_ascii=False)
    
    print(f'✅ Band 6.0-6.5: {len(words)}개 생성 완료')
    return words

if __name__ == '__main__':
    main()
