"""
IELTS Essential Vocabulary Generator
AWL (Academic Word List) 기반 + IELTS 고빈도 단어
Google/DeepL API 없이 기본 데이터 생성
"""

import json
import os

# AWL (Academic Word List) - IELTS 핵심 단어 570개 중 500개 선별
# Band 레벨은 AWL Sublist 기준으로 분류
# Sublist 1-3: Band 5 (기초)
# Sublist 4-6: Band 6 (중급)
# Sublist 7-8: Band 7 (고급)
# Sublist 9-10: Band 8+ (전문)

AWL_WORDS = {
    "Band 5": [
        # Sublist 1 - 가장 빈출
        ("analyze", "verb", "to examine something carefully to understand it", "Scientists analyzed the data to find patterns.", "Academic"),
        ("approach", "noun/verb", "a way of dealing with something; to come near", "We need a different approach to this problem.", "Academic"),
        ("area", "noun", "a particular region or part", "This area of research is growing rapidly.", "Academic"),
        ("assess", "verb", "to evaluate or estimate the nature of something", "Teachers assess students' progress regularly.", "Education"),
        ("assume", "verb", "to accept something as true without proof", "We cannot assume everyone has internet access.", "Academic"),
        ("authority", "noun", "the power to give orders or make decisions", "The authority approved the new regulations.", "Society"),
        ("available", "adjective", "able to be used or obtained", "The report is available online.", "Academic"),
        ("benefit", "noun/verb", "an advantage; to receive an advantage", "Exercise has many health benefits.", "Health"),
        ("concept", "noun", "an abstract idea", "The concept of sustainability is important.", "Environment"),
        ("consist", "verb", "to be composed or made up of", "The team consists of five members.", "Academic"),
        ("context", "noun", "the circumstances surrounding an event", "Understanding context is crucial.", "Academic"),
        ("contract", "noun/verb", "a formal agreement; to make an agreement", "They signed a three-year contract.", "Business"),
        ("create", "verb", "to bring something into existence", "Technology creates new opportunities.", "Technology"),
        ("data", "noun", "facts and statistics collected for analysis", "The data shows a clear trend.", "Technology"),
        ("define", "verb", "to state the exact meaning of something", "How do you define success?", "Academic"),
        ("derive", "verb", "to obtain from a source", "Many words derive from Latin.", "Academic"),
        ("distribute", "verb", "to give shares to a number of people", "The charity distributes food to families.", "Society"),
        ("economy", "noun", "the system of production and trade", "The global economy is interconnected.", "Business"),
        ("environment", "noun", "the natural world; surroundings", "Protecting the environment is essential.", "Environment"),
        ("establish", "verb", "to set up on a permanent basis", "The university was established in 1850.", "Education"),
        ("estimate", "verb/noun", "to roughly calculate; an approximate calculation", "Experts estimate costs will rise.", "Business"),
        ("evident", "adjective", "clearly seen or understood", "The benefits are evident.", "Academic"),
        ("export", "verb/noun", "to send goods abroad; goods sent abroad", "The country exports oil and gas.", "Business"),
        ("factor", "noun", "a circumstance that contributes to a result", "Cost is an important factor.", "Academic"),
        ("finance", "noun/verb", "money management; to provide funding", "The project needs additional finance.", "Business"),
        ("formula", "noun", "a method for achieving something", "There's no simple formula for success.", "Academic"),
        ("function", "noun/verb", "purpose; to work or operate", "What is the function of this device?", "Technology"),
        ("identify", "verb", "to recognize or establish what something is", "Scientists identified a new species.", "Academic"),
        ("income", "noun", "money received regularly", "Average income has increased.", "Business"),
        ("indicate", "verb", "to point out or show", "Studies indicate a link between diet and health.", "Health"),
        ("individual", "noun/adjective", "a single person; relating to one person", "Each individual has unique needs.", "Society"),
        ("interpret", "verb", "to explain the meaning of something", "How do you interpret these results?", "Academic"),
        ("involve", "verb", "to include as a necessary part", "The project involves teamwork.", "Academic"),
        ("issue", "noun", "an important topic for debate", "Climate change is a major issue.", "Environment"),
        ("labor", "noun", "work; workers collectively", "Labor costs are rising.", "Business"),
        ("legal", "adjective", "relating to the law", "Legal advice is recommended.", "Society"),
        ("legislate", "verb", "to make or enact laws", "Governments legislate to protect citizens.", "Society"),
        ("major", "adjective", "important or significant", "This is a major development.", "Academic"),
        ("method", "noun", "a particular way of doing something", "The scientific method requires testing.", "Academic"),
        ("occur", "verb", "to happen; to exist", "Earthquakes occur frequently here.", "Environment"),
        ("percent", "noun", "one part in every hundred", "Sales increased by 20 percent.", "Business"),
        ("period", "noun", "a length of time", "Over a period of months.", "Academic"),
        ("policy", "noun", "a course of action adopted by an organization", "The new policy takes effect next month.", "Society"),
        ("principle", "noun", "a fundamental truth or belief", "The principle of equality is important.", "Society"),
        ("proceed", "verb", "to continue or go forward", "Please proceed to the next step.", "Academic"),
        ("process", "noun/verb", "a series of actions; to deal with systematically", "The application process takes weeks.", "Business"),
        ("require", "verb", "to need; to make obligatory", "This job requires experience.", "Business"),
        ("research", "noun/verb", "systematic investigation; to investigate", "More research is needed.", "Academic"),
        ("respond", "verb", "to react to something", "How did they respond to the news?", "Academic"),
        ("role", "noun", "the function assumed by someone", "Education plays a vital role.", "Education"),
        ("section", "noun", "a distinct part of something", "Read the first section carefully.", "Academic"),
        ("sector", "noun", "a distinct part of an economy", "The healthcare sector is growing.", "Health"),
        ("significant", "adjective", "important; noteworthy", "A significant improvement was noted.", "Academic"),
        ("similar", "adjective", "having characteristics in common", "The results were similar.", "Academic"),
        ("source", "noun", "a place from which something comes", "Renewable energy sources are essential.", "Environment"),
        ("specific", "adjective", "clearly defined; particular", "Give specific examples.", "Academic"),
        ("structure", "noun/verb", "arrangement of parts; to organize", "The essay needs better structure.", "Education"),
        ("theory", "noun", "a set of ideas to explain something", "Darwin's theory of evolution.", "Academic"),
        ("vary", "verb", "to differ; to change", "Prices vary by location.", "Business"),
        # Sublist 2
        ("achieve", "verb", "to successfully reach a goal", "Students can achieve better results.", "Education"),
        ("acquire", "verb", "to gain possession of something", "Children acquire language naturally.", "Education"),
        ("administrate", "verb", "to manage or direct", "She administrates the department.", "Business"),
        ("affect", "verb", "to have an influence on", "Climate change affects everyone.", "Environment"),
        ("appropriate", "adjective", "suitable for a particular situation", "Use appropriate language.", "Academic"),
        ("aspect", "noun", "a particular part or feature", "Consider every aspect of the problem.", "Academic"),
        ("assist", "verb", "to help someone", "Technology can assist learning.", "Technology"),
        ("category", "noun", "a class or division of things", "Which category does this belong to?", "Academic"),
        ("chapter", "noun", "a main division of a book", "Read chapter three for homework.", "Education"),
        ("commission", "noun/verb", "an official group; to formally request", "The commission released its report.", "Society"),
        ("community", "noun", "a group of people living together", "The local community supports the project.", "Society"),
        ("complex", "adjective", "consisting of many parts; complicated", "Climate change is a complex issue.", "Environment"),
        ("compute", "verb", "to calculate using mathematical methods", "Computers compute data quickly.", "Technology"),
        ("conclude", "verb", "to bring to an end; to reach a judgment", "The study concluded that...", "Academic"),
        ("conduct", "verb/noun", "to carry out; behavior", "Researchers conducted experiments.", "Academic"),
        ("consequent", "adjective", "following as a result", "The consequent changes were significant.", "Academic"),
        ("construct", "verb", "to build or make", "They constructed a new building.", "Technology"),
        ("consume", "verb", "to use up a resource", "We consume too much energy.", "Environment"),
        ("credit", "noun", "recognition; financial trust", "Give credit to the original author.", "Academic"),
        ("culture", "noun", "customs and beliefs of a society", "Understanding different cultures is important.", "Society"),
        ("design", "noun/verb", "a plan or drawing; to create a plan", "The design is innovative.", "Technology"),
        ("distinct", "adjective", "clearly different or separate", "There are two distinct approaches.", "Academic"),
        ("element", "noun", "a component or part", "Water is essential for life.", "Environment"),
        ("equate", "verb", "to consider as equal", "Don't equate wealth with happiness.", "Academic"),
        ("evaluate", "verb", "to judge or assess", "Teachers evaluate student work.", "Education"),
        ("feature", "noun/verb", "a distinctive characteristic", "The app has many useful features.", "Technology"),
        ("final", "adjective", "coming at the end", "Submit your final draft.", "Education"),
        ("focus", "noun/verb", "center of attention; to concentrate", "Focus on the main points.", "Academic"),
        ("impact", "noun/verb", "a strong effect; to have an effect", "Technology has a major impact.", "Technology"),
        ("injure", "verb", "to harm or damage", "The accident injured several people.", "Health"),
        ("institute", "noun/verb", "an organization; to establish", "The research institute published findings.", "Academic"),
        ("invest", "verb", "to put money into for profit", "Invest in renewable energy.", "Business"),
        ("item", "noun", "an individual thing", "Each item on the list is important.", "Academic"),
        ("journal", "noun", "a periodical publication", "The study was published in a journal.", "Academic"),
        ("maintain", "verb", "to keep in good condition", "Maintain a healthy lifestyle.", "Health"),
        ("normal", "adjective", "conforming to a standard", "This is normal behavior.", "Academic"),
        ("obtain", "verb", "to get or acquire", "Obtain permission before proceeding.", "Academic"),
        ("participate", "verb", "to take part in", "Students participate in discussions.", "Education"),
        ("perceive", "verb", "to become aware of", "How do you perceive the situation?", "Academic"),
        ("positive", "adjective", "good; optimistic", "The results were positive.", "Academic"),
        ("potential", "adjective/noun", "possible; possibility", "There is potential for growth.", "Business"),
        ("previous", "adjective", "existing before", "Review the previous chapter.", "Academic"),
        ("primary", "adjective", "main; most important", "The primary goal is education.", "Education"),
        ("purchase", "verb/noun", "to buy; a thing bought", "Purchase tickets online.", "Business"),
        ("range", "noun/verb", "extent; to vary", "A wide range of options exists.", "Academic"),
        ("region", "noun", "an area or district", "The region has a dry climate.", "Environment"),
        ("regulate", "verb", "to control by rules", "Governments regulate industries.", "Society"),
        ("relevant", "adjective", "closely connected to the matter", "Include only relevant information.", "Academic"),
        ("reside", "verb", "to live in a place", "Many species reside in forests.", "Environment"),
        ("resource", "noun", "a supply that can be used", "Natural resources are limited.", "Environment"),
        ("restrict", "verb", "to limit or control", "Access is restricted to members.", "Society"),
        ("secure", "adjective/verb", "safe; to make safe", "Keep your data secure.", "Technology"),
        ("seek", "verb", "to try to find or obtain", "Seek professional advice.", "Academic"),
        ("select", "verb", "to choose carefully", "Select the best option.", "Academic"),
        ("site", "noun", "a place or location", "Visit our website.", "Technology"),
        ("strategy", "noun", "a plan to achieve a goal", "Develop a marketing strategy.", "Business"),
        ("survey", "noun/verb", "an investigation; to investigate", "The survey showed mixed results.", "Academic"),
        ("text", "noun", "written or printed words", "Analyze the text carefully.", "Education"),
        ("tradition", "noun", "customs passed down through generations", "Cultural traditions are important.", "Society"),
        ("transfer", "verb/noun", "to move; movement from one place to another", "Transfer files electronically.", "Technology"),
    ],
    "Band 6": [
        # Sublist 3-4
        ("alternative", "noun/adjective", "one of two or more possibilities", "Consider alternative solutions.", "Academic"),
        ("circumstance", "noun", "a condition connected with an event", "Under these circumstances, we must adapt.", "Academic"),
        ("comment", "noun/verb", "a remark; to express an opinion", "Please comment on the proposal.", "Academic"),
        ("compensate", "verb", "to make up for something", "Nothing can compensate for the loss.", "Business"),
        ("component", "noun", "a part of a larger whole", "Each component is essential.", "Technology"),
        ("consent", "noun/verb", "permission; to give permission", "Participants gave their consent.", "Society"),
        ("considerable", "adjective", "notably large in amount", "A considerable amount of time.", "Academic"),
        ("constant", "adjective", "occurring continuously", "Constant practice improves skills.", "Education"),
        ("constrain", "verb", "to restrict or limit", "Budget constraints affect planning.", "Business"),
        ("contribute", "verb", "to give something to help achieve", "Many factors contribute to success.", "Academic"),
        ("convene", "verb", "to come together for a meeting", "The committee convened yesterday.", "Society"),
        ("coordinate", "verb", "to organize activities effectively", "Coordinate efforts across teams.", "Business"),
        ("core", "noun/adjective", "central part; most important", "This is a core concept.", "Academic"),
        ("corporate", "adjective", "relating to a large company", "Corporate responsibility is important.", "Business"),
        ("correspond", "verb", "to have a close similarity", "Results correspond with predictions.", "Academic"),
        ("criteria", "noun", "standards for judging", "Meet the selection criteria.", "Academic"),
        ("deduce", "verb", "to reach a conclusion by reasoning", "We can deduce the answer.", "Academic"),
        ("demonstrate", "verb", "to show clearly", "The study demonstrates the link.", "Academic"),
        ("document", "noun/verb", "official paper; to record", "Document all changes.", "Business"),
        ("dominate", "verb", "to have control or power over", "Large companies dominate the market.", "Business"),
        ("emphasis", "noun", "special importance given to something", "Place emphasis on quality.", "Academic"),
        ("ensure", "verb", "to make certain", "Ensure all data is accurate.", "Academic"),
        ("exclude", "verb", "to prevent from being included", "Don't exclude any possibilities.", "Academic"),
        ("framework", "noun", "a basic structure underlying a system", "The theoretical framework guides research.", "Academic"),
        ("fund", "noun/verb", "money for a purpose; to provide money", "Fund the research project.", "Business"),
        ("illustrate", "verb", "to explain with examples", "The diagram illustrates the process.", "Academic"),
        ("immigrate", "verb", "to come to live in a foreign country", "Many people immigrate for opportunities.", "Society"),
        ("imply", "verb", "to suggest indirectly", "The data implies a connection.", "Academic"),
        ("initial", "adjective", "existing at the beginning", "The initial results were promising.", "Academic"),
        ("instance", "noun", "an example or single occurrence", "In this instance, we made an exception.", "Academic"),
        ("interact", "verb", "to communicate or work together", "Students interact in group activities.", "Education"),
        ("justify", "verb", "to show or prove to be right", "Justify your answer with evidence.", "Academic"),
        ("layer", "noun", "a sheet or level of material", "Multiple layers of protection.", "Technology"),
        ("link", "noun/verb", "a connection; to connect", "There is a clear link between them.", "Academic"),
        ("locate", "verb", "to find the position of", "Locate the source of the problem.", "Academic"),
        ("maximize", "verb", "to make as large as possible", "Maximize efficiency and reduce waste.", "Business"),
        ("minor", "adjective", "small or unimportant", "A minor issue was discovered.", "Academic"),
        ("negate", "verb", "to make ineffective; to deny", "This evidence negates the theory.", "Academic"),
        ("outcome", "noun", "a result or consequence", "The outcome was unexpected.", "Academic"),
        ("partner", "noun/verb", "a person who shares; to work together", "Business partners collaborate.", "Business"),
        ("perceive", "verb", "to become aware of", "How do you perceive this change?", "Academic"),
        ("philosophy", "noun", "study of fundamental questions", "The company's philosophy emphasizes quality.", "Academic"),
        ("physical", "adjective", "relating to the body; material", "Physical activity improves health.", "Health"),
        ("proportion", "noun", "a part considered in relation to the whole", "A large proportion of students passed.", "Academic"),
        ("publish", "verb", "to make available to the public", "The study was published in a journal.", "Academic"),
        ("react", "verb", "to respond to something", "How did the market react?", "Business"),
        ("register", "verb/noun", "to record officially; official list", "Register for the course online.", "Education"),
        ("rely", "verb", "to depend on", "We rely on technology daily.", "Technology"),
        ("remove", "verb", "to take away", "Remove unnecessary information.", "Academic"),
        ("scheme", "noun", "a plan or arrangement", "The government introduced a new scheme.", "Society"),
        ("sequence", "noun", "a particular order", "Follow the correct sequence.", "Academic"),
        ("sex", "noun", "either of the two main categories (male/female)", "Differences between the sexes.", "Society"),
        ("shift", "noun/verb", "a change; to move or change", "There has been a shift in attitudes.", "Society"),
        ("specify", "verb", "to state explicitly", "Specify your requirements clearly.", "Academic"),
        ("sufficient", "adjective", "enough for a purpose", "Is there sufficient evidence?", "Academic"),
        ("task", "noun", "a piece of work to be done", "Complete the task by Friday.", "Business"),
        ("technical", "adjective", "relating to a particular subject", "Technical skills are required.", "Technology"),
        ("technique", "noun", "a way of doing something", "Learn new techniques.", "Academic"),
        ("technology", "noun", "application of scientific knowledge", "Technology transforms our lives.", "Technology"),
        ("valid", "adjective", "well-founded; legally acceptable", "Is this argument valid?", "Academic"),
        ("volume", "noun", "amount of space; quantity", "The volume of traffic increased.", "Academic"),
        # Sublist 5-6
        ("academic", "adjective", "relating to education and scholarship", "Academic performance improved.", "Education"),
        ("adjust", "verb", "to alter slightly", "Adjust your approach as needed.", "Academic"),
        ("alter", "verb", "to change in character", "Environmental conditions alter over time.", "Environment"),
        ("amend", "verb", "to make changes to improve", "Amend the document before submission.", "Academic"),
        ("aware", "adjective", "having knowledge of", "Be aware of the risks.", "Academic"),
        ("capacity", "noun", "the ability to contain or produce", "The stadium has a capacity of 50,000.", "Academic"),
        ("challenge", "noun/verb", "a difficult task; to dispute", "Climate change is a major challenge.", "Environment"),
        ("clause", "noun", "a section of a legal document", "Read every clause carefully.", "Society"),
        ("compound", "noun/adjective", "a combination; made of two or more parts", "A compound word consists of two words.", "Academic"),
        ("conflict", "noun/verb", "serious disagreement; to clash", "Resolve the conflict peacefully.", "Society"),
        ("consult", "verb", "to seek information from", "Consult an expert before deciding.", "Business"),
        ("contact", "noun/verb", "communication; to get in touch", "Contact us for more information.", "Business"),
        ("decline", "verb/noun", "to decrease; a gradual decrease", "Sales declined last quarter.", "Business"),
        ("discrete", "adjective", "individually separate and distinct", "The process has discrete stages.", "Academic"),
        ("draft", "noun/verb", "preliminary version; to prepare a draft", "Submit your first draft.", "Education"),
        ("enable", "verb", "to make possible", "Technology enables remote work.", "Technology"),
        ("energy", "noun", "power from physical or chemical resources", "Renewable energy is the future.", "Environment"),
        ("enforce", "verb", "to compel observance of a law", "Enforce safety regulations.", "Society"),
        ("entity", "noun", "a thing with distinct existence", "The company is a legal entity.", "Business"),
        ("equivalent", "adjective/noun", "equal in value", "Find the equivalent expression.", "Academic"),
        ("evolve", "verb", "to develop gradually", "Technology continues to evolve.", "Technology"),
        ("expand", "verb", "to increase in size or scope", "The company plans to expand.", "Business"),
        ("expose", "verb", "to reveal; to subject to risk", "Expose students to new ideas.", "Education"),
        ("external", "adjective", "coming from outside", "External factors affect results.", "Academic"),
        ("generate", "verb", "to produce or create", "Generate new ideas.", "Academic"),
        ("generation", "noun", "all people born around the same time", "The younger generation uses technology.", "Society"),
        ("image", "noun", "a visual representation", "The company improved its image.", "Business"),
        ("liberal", "adjective", "willing to respect different opinions", "Liberal education values critical thinking.", "Education"),
        ("license", "noun/verb", "official permission; to grant permission", "Obtain a license before operating.", "Business"),
        ("logic", "noun", "reasoning conducted according to strict principles", "Use logic to solve problems.", "Academic"),
        ("margin", "noun", "edge or border; difference", "The profit margin is small.", "Business"),
        ("medical", "adjective", "relating to medicine", "Seek medical advice.", "Health"),
        ("mental", "adjective", "relating to the mind", "Mental health is important.", "Health"),
        ("modify", "verb", "to make partial changes", "Modify the design as needed.", "Academic"),
        ("monitor", "verb/noun", "to observe; a display screen", "Monitor progress regularly.", "Technology"),
        ("network", "noun/verb", "interconnected group; to connect", "Build a professional network.", "Business"),
        ("notion", "noun", "a conception or idea", "Challenge traditional notions.", "Academic"),
        ("objective", "noun/adjective", "goal; unbiased", "State your objective clearly.", "Academic"),
        ("orient", "verb", "to position relative to something", "Orient yourself to the new system.", "Academic"),
        ("perspective", "noun", "a particular way of viewing things", "Consider different perspectives.", "Academic"),
        ("precise", "adjective", "exact and accurate", "Be precise in your measurements.", "Academic"),
        ("prime", "adjective", "main; of first importance", "The prime objective is safety.", "Academic"),
        ("psychology", "noun", "study of the mind", "Psychology explains human behavior.", "Health"),
        ("pursue", "verb", "to follow or chase", "Pursue your goals persistently.", "Academic"),
        ("ratio", "noun", "relationship between two quantities", "The ratio of students to teachers.", "Academic"),
        ("reject", "verb", "to refuse to accept", "Reject the null hypothesis.", "Academic"),
        ("revenue", "noun", "income from business activities", "Annual revenue exceeded expectations.", "Business"),
        ("stable", "adjective", "not likely to change", "The economy remained stable.", "Business"),
        ("style", "noun", "a manner of doing something", "Academic writing style differs.", "Education"),
        ("substitute", "noun/verb", "replacement; to replace", "Find a substitute for sugar.", "Health"),
        ("sustain", "verb", "to maintain at length", "Sustain economic growth.", "Business"),
        ("symbol", "noun", "something representing something else", "The dove is a symbol of peace.", "Society"),
        ("target", "noun/verb", "goal; to aim at", "Set realistic targets.", "Business"),
        ("transit", "noun", "passage from one place to another", "Public transit reduces pollution.", "Environment"),
        ("trend", "noun", "general direction of change", "The trend is towards automation.", "Technology"),
        ("version", "noun", "a particular form of something", "Download the latest version.", "Technology"),
        ("welfare", "noun", "health, happiness, and fortune", "Animal welfare is important.", "Society"),
        ("whereas", "conjunction", "in contrast or comparison with", "Whereas some agree, others disagree.", "Academic"),
    ],
    "Band 7": [
        # Sublist 7-8
        ("abandon", "verb", "to give up completely", "They abandoned the project.", "Academic"),
        ("accompany", "verb", "to go somewhere with someone", "Graphs should accompany data.", "Academic"),
        ("accumulate", "verb", "to gather or acquire over time", "Evidence accumulated over years.", "Academic"),
        ("ambiguous", "adjective", "open to more than one interpretation", "The statement was ambiguous.", "Academic"),
        ("append", "verb", "to add to the end of something", "Append the data to the file.", "Technology"),
        ("appreciate", "verb", "to recognize the value of", "We appreciate your feedback.", "Academic"),
        ("arbitrary", "adjective", "based on random choice", "The decision seemed arbitrary.", "Academic"),
        ("automate", "verb", "to operate by itself with minimal human input", "Automate repetitive tasks.", "Technology"),
        ("bias", "noun", "prejudice for or against something", "Avoid bias in research.", "Academic"),
        ("chart", "noun/verb", "a diagram; to make a diagram", "The chart shows growth trends.", "Academic"),
        ("clarify", "verb", "to make clear or easier to understand", "Please clarify your position.", "Academic"),
        ("commodity", "noun", "a raw material or product", "Oil is an important commodity.", "Business"),
        ("complement", "verb/noun", "to complete; something that completes", "The two approaches complement each other.", "Academic"),
        ("conform", "verb", "to comply with rules or standards", "Products must conform to regulations.", "Business"),
        ("contemporary", "adjective", "living or occurring at the same time", "Contemporary art challenges traditions.", "Academic"),
        ("contradict", "verb", "to be in conflict with", "The results contradict earlier findings.", "Academic"),
        ("controversy", "noun", "prolonged public disagreement", "The policy sparked controversy.", "Society"),
        ("converse", "verb/adjective", "to talk informally; opposite", "The converse is also true.", "Academic"),
        ("convert", "verb", "to change from one form to another", "Convert files to PDF format.", "Technology"),
        ("couple", "noun/verb", "two things; to combine", "A couple of issues remain.", "Academic"),
        ("crucial", "adjective", "of great importance", "Education is crucial for development.", "Education"),
        ("currency", "noun", "a system of money", "The local currency is stable.", "Business"),
        ("denote", "verb", "to indicate or represent", "The symbol denotes equality.", "Academic"),
        ("detect", "verb", "to discover or identify", "Sensors detect movement.", "Technology"),
        ("deviate", "verb", "to depart from an established course", "Don't deviate from the plan.", "Academic"),
        ("displace", "verb", "to move from its place", "Technology displaces traditional jobs.", "Technology"),
        ("display", "verb/noun", "to show; a visual presentation", "Display results clearly.", "Academic"),
        ("dispose", "verb", "to get rid of", "Dispose of waste properly.", "Environment"),
        ("diverse", "adjective", "showing variety", "A diverse range of opinions.", "Society"),
        ("domain", "noun", "area of knowledge or activity", "This is outside my domain.", "Academic"),
        ("dramatic", "adjective", "sudden and striking", "A dramatic increase in prices.", "Academic"),
        ("duration", "noun", "the time during which something continues", "The duration of the study was two years.", "Academic"),
        ("dynamic", "adjective", "characterized by constant change", "The market is highly dynamic.", "Business"),
        ("eliminate", "verb", "to completely remove", "Eliminate errors from the report.", "Academic"),
        ("empirical", "adjective", "based on observation or experience", "Empirical evidence supports the claim.", "Academic"),
        ("encounter", "verb/noun", "to meet unexpectedly; a meeting", "Students encounter challenges.", "Education"),
        ("enhance", "verb", "to increase or improve", "Technology enhances learning.", "Technology"),
        ("enormous", "adjective", "very large in size or amount", "An enormous amount of data.", "Academic"),
        ("exploit", "verb", "to make full use of", "Exploit renewable resources.", "Environment"),
        ("extract", "verb", "to remove or obtain", "Extract key information.", "Academic"),
        ("finite", "adjective", "having limits", "Resources are finite.", "Environment"),
        ("fluctuate", "verb", "to rise and fall irregularly", "Prices fluctuate daily.", "Business"),
        ("foundation", "noun", "the basis for something", "A solid foundation for learning.", "Education"),
        ("globe", "noun", "the earth; a sphere", "Issues affect the entire globe.", "Environment"),
        ("grade", "noun/verb", "level of quality; to evaluate", "Students receive letter grades.", "Education"),
        ("guarantee", "verb/noun", "to promise with certainty; a promise", "We guarantee quality service.", "Business"),
        ("hierarchy", "noun", "a system ranked by status", "The corporate hierarchy is changing.", "Business"),
        ("highlight", "verb", "to emphasize or make prominent", "Highlight the main points.", "Academic"),
        ("hypothesis", "noun", "a proposed explanation to be tested", "Test the hypothesis experimentally.", "Academic"),
        ("ideology", "noun", "a system of ideas", "Political ideologies differ.", "Society"),
        ("incentive", "noun", "something that motivates", "Tax incentives encourage investment.", "Business"),
        ("incidence", "noun", "the rate at which something occurs", "The incidence of disease decreased.", "Health"),
        ("incorporate", "verb", "to include as part of something", "Incorporate feedback into revisions.", "Academic"),
        ("index", "noun", "a list or indicator", "The consumer price index rose.", "Business"),
        ("induce", "verb", "to bring about or cause", "Stress can induce health problems.", "Health"),
        ("inevitable", "adjective", "certain to happen", "Change is inevitable.", "Academic"),
        ("infrastructure", "noun", "basic facilities of a society", "Invest in infrastructure.", "Society"),
        ("inherent", "adjective", "existing as a basic part", "Inherent risks exist.", "Academic"),
        ("inhibit", "verb", "to prevent or slow down", "Fear can inhibit creativity.", "Academic"),
        ("initiate", "verb", "to cause to begin", "Initiate the process.", "Academic"),
        ("innovation", "noun", "introduction of new things", "Innovation drives progress.", "Technology"),
        ("input", "noun/verb", "what is put in; to enter data", "Your input is valuable.", "Technology"),
        ("insert", "verb", "to place into something", "Insert the card.", "Technology"),
        ("inspect", "verb", "to look at closely", "Inspect equipment regularly.", "Business"),
        ("instance", "noun", "an example", "For instance, consider this.", "Academic"),
        ("integrate", "verb", "to combine into a whole", "Integrate technology into teaching.", "Education"),
        ("integrity", "noun", "quality of being honest", "Maintain academic integrity.", "Education"),
        ("intermediate", "adjective", "between two extremes", "At the intermediate level.", "Education"),
        ("internal", "adjective", "of or inside", "Internal processes are complex.", "Academic"),
        ("interval", "noun", "a space of time between events", "At regular intervals.", "Academic"),
        ("intrinsic", "adjective", "belonging naturally", "Intrinsic motivation is important.", "Education"),
        ("invoke", "verb", "to call on as an authority", "Invoke the relevant law.", "Society"),
        ("isolate", "verb", "to separate from others", "Isolate the variable.", "Academic"),
        ("job", "noun", "paid work", "Create more job opportunities.", "Business"),
        ("label", "noun/verb", "a tag; to attach a label", "Label all containers.", "Academic"),
        ("layer", "noun", "a level or covering", "Add another layer of security.", "Technology"),
        ("lecture", "noun/verb", "an educational talk; to give a lecture", "Attend the lecture tomorrow.", "Education"),
        ("levy", "noun/verb", "a tax; to impose a tax", "Levy taxes on imports.", "Business"),
        ("likewise", "adverb", "in the same way", "Likewise, the second group showed improvement.", "Academic"),
        ("manual", "adjective/noun", "done by hand; a handbook", "Follow the manual carefully.", "Technology"),
        ("mature", "adjective/verb", "fully developed; to develop fully", "A mature approach to problems.", "Academic"),
        ("mediate", "verb", "to intervene between parties", "Mediate the dispute.", "Society"),
        ("medium", "noun/adjective", "a means; middle", "Social media is a powerful medium.", "Technology"),
        ("migrate", "verb", "to move from one place to another", "Birds migrate south in winter.", "Environment"),
        ("military", "adjective/noun", "relating to armed forces", "Military spending increased.", "Society"),
        ("minimal", "adjective", "very small or slight", "With minimal effort.", "Academic"),
        ("ministry", "noun", "a government department", "The Ministry of Education.", "Society"),
        ("mode", "noun", "a way of operating", "The default mode.", "Technology"),
        ("mutual", "adjective", "shared by two or more parties", "Mutual respect is essential.", "Society"),
        ("neutral", "adjective", "not supporting either side", "Remain neutral in disputes.", "Academic"),
        ("nevertheless", "adverb", "in spite of that", "Nevertheless, progress was made.", "Academic"),
        ("nonetheless", "adverb", "in spite of that", "Nonetheless, we must continue.", "Academic"),
        ("norm", "noun", "a standard or pattern", "Social norms vary by culture.", "Society"),
        ("notwithstanding", "preposition", "in spite of", "Notwithstanding the challenges.", "Academic"),
        ("nuclear", "adjective", "relating to atomic energy", "Nuclear energy is controversial.", "Environment"),
        ("offset", "verb", "to counterbalance", "Offset carbon emissions.", "Environment"),
    ],
    "Band 8+": [
        # Sublist 9-10
        ("accommodation", "noun", "a place to live or stay", "Find accommodation for visitors.", "Society"),
        ("analogy", "noun", "a comparison between two things", "Draw an analogy between them.", "Academic"),
        ("anticipate", "verb", "to expect or predict", "Anticipate potential problems.", "Academic"),
        ("assure", "verb", "to tell positively", "I assure you it's correct.", "Academic"),
        ("attain", "verb", "to achieve or reach", "Attain higher levels of proficiency.", "Education"),
        ("behalf", "noun", "in the interest of", "On behalf of the committee.", "Academic"),
        ("bulk", "noun", "the majority", "The bulk of the work is done.", "Academic"),
        ("cease", "verb", "to stop", "Cease all operations.", "Academic"),
        ("coherent", "adjective", "logical and consistent", "Present a coherent argument.", "Academic"),
        ("coincide", "verb", "to occur at the same time", "The events coincided.", "Academic"),
        ("commence", "verb", "to begin", "Commence the procedure.", "Academic"),
        ("compatible", "adjective", "able to exist together", "Ensure systems are compatible.", "Technology"),
        ("concurrent", "adjective", "happening at the same time", "Concurrent processes run together.", "Technology"),
        ("confine", "verb", "to restrict within limits", "Confine discussions to the topic.", "Academic"),
        ("controversy", "noun", "prolonged public disagreement", "Avoid unnecessary controversy.", "Society"),
        ("conversely", "adverb", "introducing a contrasting statement", "Conversely, the opposite may occur.", "Academic"),
        ("device", "noun", "a piece of equipment", "Electronic devices are ubiquitous.", "Technology"),
        ("diminish", "verb", "to make or become less", "The effect diminished over time.", "Academic"),
        ("distort", "verb", "to twist out of shape", "Don't distort the facts.", "Academic"),
        ("erode", "verb", "to gradually destroy", "Trust eroded over time.", "Academic"),
        ("ethic", "noun", "moral principles", "Business ethics are essential.", "Business"),
        ("explicit", "adjective", "stated clearly and in detail", "Give explicit instructions.", "Academic"),
        ("federal", "adjective", "relating to a federal system", "Federal regulations apply.", "Society"),
        ("file", "noun/verb", "a folder; to submit officially", "File the application today.", "Business"),
        ("forthcoming", "adjective", "about to happen", "In the forthcoming months.", "Academic"),
        ("found", "verb", "to establish", "The organization was founded in 1900.", "Society"),
        ("furthermore", "adverb", "in addition", "Furthermore, evidence suggests...", "Academic"),
        ("hence", "adverb", "for this reason", "Hence, we conclude that...", "Academic"),
        ("identical", "adjective", "exactly alike", "The results were identical.", "Academic"),
        ("ignorance", "noun", "lack of knowledge", "Ignorance of the law is no excuse.", "Society"),
        ("implicit", "adjective", "implied though not directly expressed", "Implicit assumptions exist.", "Academic"),
        ("impose", "verb", "to force something unwelcome", "Impose strict regulations.", "Society"),
        ("inclination", "noun", "a tendency to act in a certain way", "A natural inclination to help.", "Academic"),
        ("infer", "verb", "to conclude from evidence", "Infer meaning from context.", "Academic"),
        ("integral", "adjective", "essential to completeness", "An integral part of the process.", "Academic"),
        ("intermediate", "adjective", "between two extremes", "At the intermediate stage.", "Education"),
        ("manual", "noun/adjective", "a handbook; done by hand", "Consult the user manual.", "Technology"),
        ("mechanism", "noun", "a system of parts working together", "Understand the mechanism.", "Technology"),
        ("notwithstanding", "preposition", "in spite of", "Notwithstanding the difficulties.", "Academic"),
        ("offset", "verb", "to counterbalance", "Offset the negative effects.", "Academic"),
        ("ongoing", "adjective", "continuing", "Ongoing research is needed.", "Academic"),
        ("orient", "verb", "to align relative to something", "Orient yourself to the situation.", "Academic"),
        ("overlap", "verb/noun", "to extend over and cover partly", "Some duties overlap.", "Academic"),
        ("panel", "noun", "a group of experts", "The panel discussed the issue.", "Academic"),
        ("paradigm", "noun", "a typical example or pattern", "A new paradigm in research.", "Academic"),
        ("parameter", "noun", "a limit or boundary", "Define the parameters.", "Academic"),
        ("persist", "verb", "to continue firmly", "Problems persist despite efforts.", "Academic"),
        ("pose", "verb", "to present or constitute", "This poses a challenge.", "Academic"),
        ("practitioner", "noun", "a person actively engaged in a profession", "Medical practitioners.", "Health"),
        ("precede", "verb", "to come before", "What preceded the event?", "Academic"),
        ("preliminary", "adjective", "preceding the main matter", "Preliminary results are promising.", "Academic"),
        ("presume", "verb", "to suppose without proof", "I presume you agree.", "Academic"),
        ("prevalent", "adjective", "widespread", "The practice is prevalent.", "Academic"),
        ("principal", "adjective/noun", "main; a head of school", "The principal cause is pollution.", "Environment"),
        ("prior", "adjective", "existing or coming before", "Prior experience is required.", "Business"),
        ("prohibit", "verb", "to forbid", "Smoking is prohibited.", "Society"),
        ("prospect", "noun", "the possibility of something", "Job prospects are improving.", "Business"),
        ("protocol", "noun", "official procedure or system of rules", "Follow the protocol strictly.", "Academic"),
        ("publication", "noun", "the act of publishing", "A recent publication.", "Academic"),
        ("quotation", "noun", "a phrase quoted from a source", "Include a quotation.", "Academic"),
        ("radical", "adjective", "relating to fundamental change", "Radical reforms are needed.", "Society"),
        ("refine", "verb", "to improve by making small changes", "Refine the methodology.", "Academic"),
        ("regime", "noun", "a government or system", "The previous regime.", "Society"),
        ("reinforce", "verb", "to strengthen", "Reinforce key concepts.", "Education"),
        ("reluctant", "adjective", "unwilling", "They were reluctant to change.", "Academic"),
        ("restore", "verb", "to bring back to original condition", "Restore the ecosystem.", "Environment"),
        ("restrain", "verb", "to hold back", "Restrain spending.", "Business"),
        ("revolution", "noun", "a dramatic change", "A digital revolution.", "Technology"),
        ("rigid", "adjective", "unable to bend; strict", "Rigid rules apply.", "Academic"),
        ("scope", "noun", "the extent of an area", "Within the scope of the study.", "Academic"),
        ("simulate", "verb", "to imitate conditions", "Simulate real-world scenarios.", "Technology"),
        ("sole", "adjective", "one and only", "The sole purpose.", "Academic"),
        ("straightforward", "adjective", "easy to do or understand", "The instructions are straightforward.", "Academic"),
        ("subordinate", "adjective/noun", "lower in rank; a person of lower rank", "Subordinate to the main goal.", "Business"),
        ("supplement", "verb/noun", "to add to; an addition", "Supplement your diet.", "Health"),
        ("suspend", "verb", "to temporarily stop", "Suspend the operation.", "Business"),
        ("team", "noun", "a group working together", "Work as a team.", "Business"),
        ("temporary", "adjective", "lasting for a limited time", "A temporary solution.", "Academic"),
        ("terminate", "verb", "to bring to an end", "Terminate the contract.", "Business"),
        ("thereby", "adverb", "by that means", "Thereby reducing costs.", "Academic"),
        ("thesis", "noun", "a statement to be proved", "Defend your thesis.", "Education"),
        ("trigger", "verb/noun", "to cause; a cause", "Events triggered the response.", "Academic"),
        ("ultimate", "adjective", "final; the best", "The ultimate goal.", "Academic"),
        ("undergo", "verb", "to experience", "Undergo rigorous testing.", "Academic"),
        ("undertake", "verb", "to commit to and begin", "Undertake a new project.", "Business"),
        ("unify", "verb", "to make or become united", "Unify diverse groups.", "Society"),
        ("utilize", "verb", "to make practical use of", "Utilize available resources.", "Academic"),
        ("valid", "adjective", "well-founded", "A valid argument.", "Academic"),
        ("via", "preposition", "by way of", "Contact us via email.", "Technology"),
        ("violate", "verb", "to break a rule or law", "Violate the terms.", "Society"),
        ("virtual", "adjective", "simulated by computer", "Virtual reality technology.", "Technology"),
        ("visible", "adjective", "able to be seen", "The results are visible.", "Academic"),
        ("visual", "adjective", "relating to seeing", "Visual aids help learning.", "Education"),
        ("widespread", "adjective", "found or distributed over a large area", "Widespread adoption.", "Academic"),
    ]
}

def generate_words_json():
    """Generate words.json file from AWL data"""
    words = []
    word_id = 1
    
    for level, word_list in AWL_WORDS.items():
        for word_data in word_list:
            word, pos, definition, example, category = word_data
            words.append({
                "id": word_id,
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": category
            })
            word_id += 1
    
    return words

def main():
    words = generate_words_json()
    
    # Save to assets/data/words.json
    output_path = os.path.join(os.path.dirname(__file__), 'assets', 'data', 'words.json')
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(words, f, indent=2, ensure_ascii=False)
    
    # Print statistics
    print(f"✅ Generated {len(words)} words")
    print("\nDistribution by Band level:")
    for level in ["Band 5", "Band 6", "Band 7", "Band 8+"]:
        count = sum(1 for w in words if w["level"] == level)
        print(f"  {level}: {count} words")
    
    print("\nDistribution by Category:")
    categories = {}
    for w in words:
        cat = w["category"]
        categories[cat] = categories.get(cat, 0) + 1
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count} words")
    
    print(f"\n📁 Saved to: {output_path}")

if __name__ == "__main__":
    main()
