#!/usr/bin/env python3
"""
IELTS 단어 5000개 달성을 위한 최종 대량 추가
"""

import json
import os

# 기존 단어 로드
def load_existing_words():
    existing = set()
    for filename in ['band45_words.json', 'band60_words.json', 'band70_words.json', 'band80_words.json']:
        filepath = f'assets/data/{filename}'
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for w in data:
                    existing.add(w['word'].lower())
    return existing

existing_words = load_existing_words()
print(f"기존 단어 수: {len(existing_words)}개")

# =====================================================================
# 대량 단어 목록 - 모든 밴드
# =====================================================================

# Band 6.0-6.5 추가 (800개 이상 필요)
BAND60_EXTRA = [
    # D
    ("decade", "noun", "a period of ten years", "Over the past decade."),
    ("decent", "adjective", "of an acceptable standard", "A decent salary."),
    ("declaration", "noun", "a formal statement", "A declaration of intent."),
    ("decline", "verb", "become smaller or weaker", "Sales have declined."),
    ("dedicate", "verb", "devote time and effort to", "Dedicate yourself to study."),
    ("deduce", "verb", "arrive at by reasoning", "Deduce the conclusion."),
    ("deem", "verb", "regard or consider", "Deemed necessary."),
    ("defect", "noun", "a shortcoming or fault", "A manufacturing defect."),
    ("defendant", "noun", "a person accused in court", "The defendant pleaded guilty."),
    ("defer", "verb", "put off to a later time", "Defer the decision."),
    ("deficiency", "noun", "a lack or shortage", "A vitamin deficiency."),
    ("deficit", "noun", "the amount by which something falls short", "A budget deficit."),
    ("degradation", "noun", "the condition of being degraded", "Environmental degradation."),
    ("delegate", "verb", "entrust to another", "Delegate responsibilities."),
    ("deliberate", "verb", "engage in long consideration", "The jury deliberated."),
    ("delineate", "verb", "describe or portray precisely", "Delineate the boundaries."),
    ("demographic", "adjective", "relating to population statistics", "Demographic changes."),
    ("demolish", "verb", "pull or knock down", "Demolish the building."),
    ("denote", "verb", "be a sign of", "The color denotes danger."),
    ("density", "noun", "the quantity per unit volume", "Population density."),
    ("deny", "verb", "refuse to admit the truth", "Deny the allegations."),
    ("depict", "verb", "show or represent by a drawing", "The painting depicts a scene."),
    ("deplete", "verb", "reduce the fullness of", "Deplete natural resources."),
    ("deploy", "verb", "bring into effective action", "Deploy the strategy."),
    ("depression", "noun", "a period of low economic activity", "The Great Depression."),
    ("deprive", "verb", "deny the possession or use of", "Deprived of rights."),
    ("deputy", "noun", "a person appointed to act for another", "The deputy manager."),
    ("derive", "verb", "obtain something from a source", "Derive benefits from."),
    ("designate", "verb", "appoint to a position", "Designate a leader."),
    ("despite", "preposition", "without being affected by", "Despite the challenges."),
    ("detach", "verb", "disengage or separate", "Detach from the group."),
    ("detail", "noun", "an individual feature or fact", "Pay attention to detail."),
    ("detect", "verb", "discover the presence of", "Detect a problem."),
    ("deteriorate", "verb", "become progressively worse", "Conditions deteriorated."),
    ("determine", "verb", "cause to occur in a particular way", "Factors that determine success."),
    ("devastate", "verb", "destroy or ruin", "The storm devastated the area."),
    ("device", "noun", "a thing made for a particular purpose", "A measuring device."),
    ("devote", "verb", "give all or most of one's time to", "Devote time to study."),
    ("diagram", "noun", "a simplified drawing showing appearances", "A flow diagram."),
    ("dictate", "verb", "state or order authoritatively", "Market forces dictate prices."),
    ("differentiate", "verb", "recognize as different", "Differentiate between the two."),
    ("diffuse", "verb", "spread over a wide area", "The idea diffused quickly."),
    ("digest", "verb", "break down food", "Digest information."),
    ("dilemma", "noun", "a situation requiring a difficult choice", "Face a dilemma."),
    ("dilute", "verb", "make thinner or weaker", "Dilute the solution."),
    ("dimension", "noun", "an aspect or feature", "The human dimension."),
    ("diminish", "verb", "make or become less", "Interest may diminish."),
    ("diploma", "noun", "a certificate awarded for passing an exam", "Receive a diploma."),
    ("diplomatic", "adjective", "relating to diplomacy", "Diplomatic relations."),
    ("directory", "noun", "a book listing individuals", "A business directory."),
    # E
    ("elaborate", "adjective", "involving many carefully arranged parts", "An elaborate plan."),
    ("elapse", "verb", "pass or slip by", "Time elapsed quickly."),
    ("elderly", "adjective", "old or aging", "Care for the elderly."),
    ("elevate", "verb", "raise to a higher position", "Elevate the discussion."),
    ("eligible", "adjective", "having the right to do or obtain something", "Eligible for benefits."),
    ("eliminate", "verb", "completely remove or get rid of", "Eliminate waste."),
    ("elite", "noun", "a select group that is superior", "The social elite."),
    ("eloquent", "adjective", "fluent or persuasive in speaking", "An eloquent speaker."),
    ("embed", "verb", "fix firmly in a surrounding mass", "Embed the video."),
    ("embrace", "verb", "accept or support willingly", "Embrace new technology."),
    ("emerge", "verb", "move out of or away from something", "New leaders emerged."),
    ("emission", "noun", "the production and discharge of something", "Carbon emissions."),
    ("emotion", "noun", "a strong feeling", "Express emotions."),
    ("emphasis", "noun", "special importance given to something", "Place emphasis on quality."),
    ("empire", "noun", "an extensive group of states ruled over", "The Roman Empire."),
    ("employ", "verb", "give work to someone", "Employ skilled workers."),
    ("empower", "verb", "give power or authority to", "Empower employees."),
    ("enable", "verb", "give someone the authority to do something", "Enable access."),
    ("enact", "verb", "make a bill into law", "Enact legislation."),
    ("encounter", "verb", "unexpectedly experience or be faced with", "Encounter difficulties."),
    ("endorse", "verb", "declare public approval of", "Endorse a candidate."),
    ("endure", "verb", "suffer patiently", "Endure hardship."),
    ("enforce", "verb", "compel observance of a law", "Enforce regulations."),
    ("engage", "verb", "occupy or attract someone's interest", "Engage the audience."),
    ("enhance", "verb", "intensify or improve quality", "Enhance performance."),
    ("enormous", "adjective", "very large in size", "An enormous challenge."),
    ("enquiry", "noun", "an act of asking for information", "Make enquiries."),
    ("ensure", "verb", "make certain that something happens", "Ensure safety."),
    ("enterprise", "noun", "a project or undertaking", "A business enterprise."),
    ("enthusiastic", "adjective", "having intense enjoyment", "An enthusiastic response."),
    ("entity", "noun", "a thing with distinct existence", "A legal entity."),
    ("entrepreneur", "noun", "a person who sets up a business", "A successful entrepreneur."),
    ("entry", "noun", "an act of going into a place", "Entry requirements."),
    ("environment", "noun", "the surroundings", "Protect the environment."),
    ("episode", "noun", "an event or period as part of a sequence", "A historical episode."),
    ("equal", "adjective", "being the same in quantity or value", "Equal opportunities."),
    ("equip", "verb", "supply with necessary items", "Equip the team."),
    ("equivalent", "adjective", "equal in value or function", "The equivalent amount."),
    ("era", "noun", "a long and distinct period of history", "A new era."),
    ("erode", "verb", "gradually wear away", "Coastal erosion."),
    ("error", "noun", "a mistake", "Correct the error."),
    ("escape", "verb", "break free from confinement", "Escape from danger."),
    ("essential", "adjective", "absolutely necessary", "Essential supplies."),
    ("estate", "noun", "an extensive area of land", "A large estate."),
    ("esteem", "noun", "respect and admiration", "Hold in high esteem."),
    ("ethical", "adjective", "relating to moral principles", "Ethical standards."),
    ("ethnic", "adjective", "relating to a population subgroup", "Ethnic diversity."),
    ("evaluate", "verb", "form an idea of the value of", "Evaluate performance."),
    ("eventually", "adverb", "in the end", "Eventually succeeded."),
    # F-G
    ("fabric", "noun", "cloth or textile material", "The social fabric."),
    ("facilitate", "verb", "make an action or process easier", "Facilitate communication."),
    ("facility", "noun", "a place provided for a purpose", "Sports facilities."),
    ("faction", "noun", "a small dissenting group", "Political factions."),
    ("faculty", "noun", "an inherent mental or physical power", "The faculty of speech."),
    ("fade", "verb", "gradually grow faint", "Memories fade."),
    ("failure", "noun", "lack of success", "Fear of failure."),
    ("fair", "adjective", "treating people equally", "A fair decision."),
    ("faith", "noun", "complete trust or confidence", "Have faith."),
    ("fame", "noun", "the state of being known widely", "Achieve fame."),
    ("famine", "noun", "extreme scarcity of food", "A devastating famine."),
    ("fantasy", "noun", "imagination especially when extravagant", "A world of fantasy."),
    ("fare", "noun", "the money a passenger pays", "Bus fare."),
    ("fascinate", "verb", "draw irresistibly the attention of", "The subject fascinates me."),
    ("fashion", "noun", "a popular trend", "Fashion trends."),
    ("fatal", "adjective", "causing death", "A fatal accident."),
    ("fate", "noun", "the development of events beyond control", "Accept one's fate."),
    ("fatigue", "noun", "extreme tiredness", "Suffer from fatigue."),
    ("fault", "noun", "responsibility for an accident or misfortune", "Not my fault."),
    ("favor", "noun", "an act of kindness beyond what is due", "Do a favor."),
    ("feasibility", "noun", "the state of being possible", "Study the feasibility."),
    ("feat", "noun", "an achievement requiring great skill", "An amazing feat."),
    ("federal", "adjective", "relating to a central government", "Federal law."),
    ("fee", "noun", "a payment made for professional advice", "Legal fees."),
    ("feedback", "noun", "information about reactions to a product", "Provide feedback."),
    ("fellow", "noun", "a man or boy", "A fellow student."),
    ("feminist", "noun", "a person who supports feminism", "A feminist activist."),
    ("fertile", "adjective", "producing abundant vegetation or crops", "Fertile soil."),
    ("festival", "noun", "a day or period of celebration", "A music festival."),
    ("fiber", "noun", "a thread or filament forming tissue", "Dietary fiber."),
    ("fiction", "noun", "literature describing imaginary events", "Science fiction."),
    ("fierce", "adjective", "having a violent or ferocious nature", "Fierce competition."),
    ("filter", "verb", "pass through a device to remove unwanted material", "Filter the water."),
    ("finance", "verb", "provide funding for", "Finance the project."),
    ("fine", "noun", "a sum of money paid as a penalty", "Pay a fine."),
    ("finite", "adjective", "limited in size or extent", "Finite resources."),
    ("firm", "noun", "a business concern", "A law firm."),
    ("fiscal", "adjective", "relating to government revenue", "Fiscal policy."),
    ("fit", "adjective", "in good health", "Stay fit."),
    ("flaw", "noun", "a mark or fault that spoils something", "A design flaw."),
    ("flee", "verb", "run away from danger", "Flee the country."),
    ("flexibility", "noun", "the quality of bending easily", "Work flexibility."),
    ("flourish", "verb", "grow or develop in a healthy way", "Business flourished."),
    ("fluctuate", "verb", "rise and fall irregularly", "Prices fluctuate."),
    ("fluid", "noun", "a substance that flows freely", "Body fluids."),
    ("folder", "noun", "a folding cover for loose papers", "Create a folder."),
    ("forecast", "noun", "a prediction about the future", "Weather forecast."),
    ("forefront", "noun", "the leading position", "At the forefront."),
    ("foreign", "adjective", "of or from another country", "Foreign policy."),
    ("format", "noun", "the way in which something is arranged", "File format."),
    ("formula", "noun", "a mathematical relationship", "A winning formula."),
    ("formulate", "verb", "create or devise methodically", "Formulate a plan."),
    ("forth", "adverb", "out and away from a starting point", "Put forth ideas."),
    ("fortune", "noun", "chance as a force affecting human affairs", "Good fortune."),
    ("forum", "noun", "a meeting or medium for open discussion", "A public forum."),
    ("fossil", "noun", "the remains of prehistoric organisms", "Fossil fuels."),
    ("foster", "verb", "encourage or promote development", "Foster creativity."),
    ("foundation", "noun", "an underlying basis", "The foundation of success."),
    ("fraction", "noun", "a numerical quantity less than one", "A small fraction."),
    ("fragment", "noun", "a small part broken off", "Fragments of evidence."),
    ("framework", "noun", "a basic structure underlying a system", "A legal framework."),
    ("franchise", "noun", "an authorization to sell a company's goods", "A franchise business."),
    ("fraud", "noun", "wrongful deception intended to result in gain", "Insurance fraud."),
    ("free", "adjective", "not under the control of another", "A free society."),
    ("frequency", "noun", "the rate at which something occurs", "High frequency."),
    ("friction", "noun", "the resistance between two surfaces", "Reduce friction."),
    ("frontier", "noun", "a line separating two countries", "Push back the frontiers."),
    ("fulfill", "verb", "carry out or bring to completion", "Fulfill a promise."),
    ("function", "verb", "work or operate in a proper way", "The system functions well."),
    ("fundamental", "adjective", "forming a necessary base", "Fundamental principles."),
    ("funding", "noun", "money provided for a purpose", "Government funding."),
    ("furthermore", "adverb", "in addition; besides", "Furthermore, we found."),
    ("fusion", "noun", "the process of joining together", "Nuclear fusion."),
    # G
    ("gain", "verb", "obtain or secure something", "Gain experience."),
    ("gallery", "noun", "a room for the display of art", "An art gallery."),
    ("gap", "noun", "a break or hole in an object", "Bridge the gap."),
    ("garment", "noun", "an item of clothing", "Designer garments."),
    ("gender", "noun", "the state of being male or female", "Gender equality."),
    ("gene", "noun", "a unit of heredity", "Gene therapy."),
    ("generate", "verb", "cause to arise or come about", "Generate revenue."),
    ("generation", "noun", "all the people born around the same time", "The younger generation."),
    ("generic", "adjective", "characteristic of a class or group", "A generic term."),
    ("generous", "adjective", "showing a readiness to give more", "A generous donation."),
    ("genetic", "adjective", "relating to genes", "Genetic research."),
    ("genius", "noun", "exceptional intellectual or creative power", "A musical genius."),
    ("genre", "noun", "a category of artistic composition", "A new genre."),
    ("genuine", "adjective", "truly what something is said to be", "Genuine concern."),
    ("gesture", "noun", "a movement of part of the body", "A kind gesture."),
    ("giant", "adjective", "of very great size", "A giant corporation."),
    ("glance", "verb", "take a brief look", "Glance at the report."),
    ("glimpse", "noun", "a momentary or partial view", "Catch a glimpse."),
    ("global", "adjective", "relating to the whole world", "Global warming."),
    ("globe", "noun", "the earth", "Around the globe."),
    ("glory", "noun", "high renown or honor won by achievement", "Past glory."),
    ("goal", "noun", "the object of a person's ambition", "Achieve your goals."),
    ("govern", "verb", "conduct the policy and affairs of a state", "Govern effectively."),
    ("governor", "noun", "an official appointed to govern a town", "The state governor."),
    ("grace", "noun", "simple elegance of movement", "Move with grace."),
    ("gradual", "adjective", "taking place by degrees", "A gradual improvement."),
    ("grain", "noun", "wheat or any other cultivated cereal", "Grain production."),
    ("grammar", "noun", "the rules of a language", "English grammar."),
    ("grand", "adjective", "magnificent and imposing", "A grand design."),
    ("grant", "verb", "agree to give or allow", "Grant permission."),
    ("graphic", "adjective", "relating to visual art", "Graphic design."),
    ("grasp", "verb", "seize and hold firmly", "Grasp the concept."),
    ("grave", "adjective", "giving cause for alarm", "A grave situation."),
    ("gravity", "noun", "the force that attracts a body toward earth", "The law of gravity."),
    ("grid", "noun", "a network of lines", "A power grid."),
    ("grief", "noun", "deep sorrow especially caused by death", "Overcome by grief."),
    ("gross", "adjective", "unattractively large", "Gross domestic product."),
    ("ground", "noun", "the solid surface of the earth", "Common ground."),
    ("group", "noun", "a number of people gathered together", "A study group."),
    ("growth", "noun", "the process of increasing in size", "Economic growth."),
    ("guarantee", "verb", "promise with certainty", "Guarantee quality."),
    ("guardian", "noun", "a defender or protector", "A legal guardian."),
    ("guidance", "noun", "advice or information", "Provide guidance."),
    ("guideline", "noun", "a general rule", "Follow the guidelines."),
    ("guilt", "noun", "the fact of having committed an offense", "Feelings of guilt."),
    # H
    ("habitat", "noun", "the natural home of an organism", "Natural habitat."),
    ("halt", "verb", "bring or come to an abrupt stop", "Halt production."),
    ("handle", "verb", "manage a situation or problem", "Handle the crisis."),
    ("handful", "noun", "a small number", "A handful of people."),
    ("handicap", "noun", "a circumstance that makes progress difficult", "Overcome a handicap."),
    ("harbour", "noun", "a place on the coast where ships shelter", "A natural harbour."),
    ("hardship", "noun", "severe suffering or privation", "Endure hardship."),
    ("hardware", "noun", "tools and machines", "Computer hardware."),
    ("harm", "noun", "physical injury", "Do no harm."),
    ("harmony", "noun", "agreement or concord", "Live in harmony."),
    ("harsh", "adjective", "unpleasantly rough or jarring", "Harsh criticism."),
    ("harvest", "noun", "the process of gathering crops", "A good harvest."),
    ("hasty", "adjective", "done with excessive speed", "A hasty decision."),
    ("hazard", "noun", "a danger or risk", "Health hazards."),
    ("heal", "verb", "cause to become sound again", "Time heals."),
    ("heap", "noun", "an untidy collection of things", "A heap of evidence."),
    ("height", "noun", "the measurement from base to top", "At its height."),
    ("heritage", "noun", "valued objects inherited from the past", "Cultural heritage."),
    ("hero", "noun", "a person admired for courage", "A national hero."),
    ("hesitate", "verb", "pause before saying or doing something", "Don't hesitate to ask."),
    ("hierarchy", "noun", "a ranking system", "Corporate hierarchy."),
    ("highlight", "verb", "pick out and emphasize", "Highlight key points."),
    ("hint", "noun", "a slight or indirect indication", "Take a hint."),
    ("historian", "noun", "an expert in history", "A noted historian."),
    ("historic", "adjective", "famous or important in history", "A historic moment."),
    ("history", "noun", "the study of past events", "Learn from history."),
    ("hobby", "noun", "an activity done for pleasure", "My favorite hobby."),
    ("hollow", "adjective", "having a hole or empty space inside", "Hollow promises."),
    ("holy", "adjective", "dedicated to God", "A holy place."),
    ("honest", "adjective", "free of deceit", "An honest answer."),
    ("honor", "noun", "high respect", "An honor to meet you."),
    ("hook", "noun", "a curved piece of metal", "A marketing hook."),
    ("horizon", "noun", "the line at which earth and sky appear to meet", "Broaden your horizons."),
    ("horizontal", "adjective", "parallel to the ground", "A horizontal line."),
    ("hormone", "noun", "a regulatory substance produced in an organism", "Growth hormones."),
    ("horror", "noun", "an intense feeling of fear", "Horror films."),
    ("host", "verb", "act as host at an event", "Host a conference."),
    ("hostile", "adjective", "unfriendly; antagonistic", "A hostile environment."),
    ("household", "noun", "a house and its occupants", "Average household."),
    ("housing", "noun", "houses and apartments collectively", "Affordable housing."),
    ("huge", "adjective", "extremely large", "A huge success."),
    ("humanity", "noun", "human beings collectively", "Crimes against humanity."),
    ("humble", "adjective", "having a modest view of importance", "A humble beginning."),
    ("humid", "adjective", "marked by a high level of moisture", "Hot and humid."),
    ("humiliate", "verb", "make someone feel ashamed", "Humiliate an opponent."),
    ("humour", "noun", "the quality of being amusing", "A sense of humour."),
    ("hunger", "noun", "a feeling of discomfort from lack of food", "World hunger."),
    ("hypothesis", "noun", "a proposed explanation", "Test the hypothesis."),
    # I
    ("icon", "noun", "a person or thing regarded as representative", "A cultural icon."),
    ("ideal", "adjective", "satisfying one's conception of perfection", "Ideal conditions."),
    ("identical", "adjective", "exactly alike", "Identical twins."),
    ("identification", "noun", "the action of identifying", "Require identification."),
    ("identify", "verb", "establish the identity of", "Identify the problem."),
    ("identity", "noun", "the fact of being who or what a person is", "Cultural identity."),
    ("ideology", "noun", "a system of ideas and ideals", "Political ideology."),
    ("ignorance", "noun", "lack of knowledge or information", "Ignorance of the law."),
    ("ignore", "verb", "refuse to take notice of", "Ignore the criticism."),
    ("illegal", "adjective", "contrary to or forbidden by law", "Illegal activities."),
    ("illusion", "noun", "a false idea or belief", "An optical illusion."),
    ("illustrate", "verb", "explain or make clear by examples", "Illustrate the point."),
    ("illustration", "noun", "a picture illustrating a book", "A book of illustrations."),
    ("image", "noun", "a representation of someone", "Corporate image."),
    ("imagination", "noun", "the faculty of forming mental images", "Use your imagination."),
    ("imitate", "verb", "take or follow as a model", "Imitate successful people."),
    ("immediate", "adjective", "occurring at once", "Immediate action."),
    ("immense", "adjective", "extremely large or great", "Immense pressure."),
    ("immigrant", "noun", "a person who comes to live in a foreign country", "Immigrant workers."),
    ("immune", "adjective", "resistant to a particular infection", "Immune system."),
]

# Band 7.0-7.5 추가
BAND70_EXTRA = [
    ("criterion", "noun", "a principle or standard for judging", "Selection criteria."),
    ("critique", "noun", "a detailed analysis and assessment", "A literary critique."),
    ("crucial", "adjective", "of great importance", "A crucial decision."),
    ("culminate", "verb", "reach a climax or point of highest development", "Culminate in success."),
    ("cumulative", "adjective", "increasing by successive additions", "Cumulative effect."),
    ("currency", "noun", "a system of money in general use", "Foreign currency."),
    ("curriculum", "noun", "the subjects comprising a course of study", "The school curriculum."),
    ("curtail", "verb", "reduce in extent or quantity", "Curtail spending."),
    ("customary", "adjective", "according to custom; usual", "Customary practices."),
    ("cyclic", "adjective", "occurring in cycles", "Cyclic patterns."),
    ("dearth", "noun", "a scarcity or lack of something", "A dearth of evidence."),
    ("debatable", "adjective", "open to discussion or argument", "A debatable point."),
    ("decentralize", "verb", "transfer power from central to local authority", "Decentralize operations."),
    ("deceptive", "adjective", "giving an appearance or impression different from true", "Deceptive practices."),
    ("decisive", "adjective", "settling an issue; producing a definite result", "A decisive victory."),
    ("declaration", "noun", "a formal or explicit statement or announcement", "A declaration of independence."),
    ("deduction", "noun", "the action of deducting or subtracting", "Tax deductions."),
    ("deficient", "adjective", "not having enough of a specified quality", "Nutritionally deficient."),
    ("definitive", "adjective", "done or reached decisively and with authority", "A definitive answer."),
    ("degradation", "noun", "the condition of being degraded", "Environmental degradation."),
    ("deliberate", "adjective", "done consciously and intentionally", "A deliberate act."),
    ("demarcate", "verb", "set the boundaries or limits of", "Demarcate the territory."),
    ("demographic", "noun", "a particular sector of a population", "Target demographics."),
    ("denominator", "noun", "the number below the line in a fraction", "A common denominator."),
    ("depict", "verb", "show or represent by a drawing, painting, or other art form", "Depict the scene."),
    ("deployment", "noun", "the movement of troops or equipment to a place", "Troop deployment."),
    ("depreciate", "verb", "diminish in value over a period of time", "Assets depreciate."),
    ("derivative", "adjective", "imitative of the work of another person", "A derivative work."),
    ("designate", "verb", "appoint to a specified position", "Designate a leader."),
    ("desirable", "adjective", "worth having or wanting", "A desirable outcome."),
    ("detach", "verb", "disengage from a group or place", "Detach from emotions."),
    ("deteriorate", "verb", "become progressively worse", "Health deteriorates."),
    ("detrimental", "adjective", "tending to cause harm", "Detrimental effects."),
    ("deviate", "verb", "depart from an established course", "Deviate from the norm."),
    ("devise", "verb", "plan or invent by careful thought", "Devise a strategy."),
    ("devoid", "adjective", "entirely lacking or free from", "Devoid of emotion."),
    ("dictate", "verb", "lay down authoritatively; prescribe", "Market forces dictate prices."),
    ("diffuse", "adjective", "spread out over a large area; not concentrated", "A diffuse pattern."),
    ("dilemma", "noun", "a situation in which a difficult choice has to be made", "An ethical dilemma."),
    ("diminish", "verb", "make or become less", "Interest diminishes."),
    ("discard", "verb", "get rid of as no longer useful or desirable", "Discard old ideas."),
    ("discern", "verb", "perceive or recognize something", "Discern the truth."),
    ("disciplinary", "adjective", "concerning or enforcing discipline", "Disciplinary action."),
    ("disclose", "verb", "make secret or new information known", "Disclose the findings."),
    ("discrepancy", "noun", "a lack of compatibility between two facts", "A discrepancy in the accounts."),
    ("discrete", "adjective", "individually separate and distinct", "Discrete categories."),
    ("discrimination", "noun", "the unjust treatment of different categories of people", "Racial discrimination."),
    ("dismantle", "verb", "take to pieces", "Dismantle the system."),
    ("dispatch", "verb", "send off to a destination or for a purpose", "Dispatch the goods."),
    ("dispense", "verb", "distribute or provide a service to a number of people", "Dispense advice."),
    ("disperse", "verb", "distribute or spread over a wide area", "The crowd dispersed."),
    ("displace", "verb", "take over the place, position, or role of someone", "Technology displaces workers."),
    ("disposal", "noun", "the action or process of throwing away", "Waste disposal."),
    ("dispose", "verb", "get rid of by throwing away or giving away", "Dispose of waste properly."),
    ("disproportionate", "adjective", "too large or too small in comparison", "Disproportionate response."),
    ("dispute", "noun", "a disagreement or argument", "A legal dispute."),
    ("disrupt", "verb", "interrupt by causing a disturbance", "Disrupt the market."),
    ("disseminate", "verb", "spread information widely", "Disseminate knowledge."),
    ("dissolve", "verb", "become or cause to become incorporated into a liquid", "Dissolve the partnership."),
    ("distil", "verb", "extract the essential meaning", "Distil the information."),
    ("distinction", "noun", "a difference or contrast between similar things", "A clear distinction."),
    ("distinctive", "adjective", "characteristic of one person or thing", "A distinctive style."),
    ("distinguish", "verb", "recognize or treat as different", "Distinguish between the two."),
    ("distort", "verb", "give a misleading account of", "Distort the facts."),
    ("distribute", "verb", "give shares of something", "Distribute resources."),
    ("diverge", "verb", "separate from another route or direction", "Opinions diverge."),
    ("diverse", "adjective", "showing a great deal of variety", "A diverse population."),
    ("divert", "verb", "cause to change course or turn from one direction to another", "Divert attention."),
    ("dividend", "noun", "a sum of money paid regularly to shareholders", "Pay dividends."),
    ("doctrine", "noun", "a belief or set of beliefs held by a group", "Economic doctrine."),
    ("document", "verb", "record in written, photographic, or other form", "Document the process."),
    ("domain", "noun", "an area of territory owned or controlled", "The public domain."),
    ("domestic", "adjective", "relating to the running of a home or family", "Domestic affairs."),
    ("dominant", "adjective", "most important, powerful, or influential", "The dominant culture."),
    ("dominate", "verb", "have a commanding influence on", "Dominate the market."),
    ("donor", "noun", "a person who donates something", "Blood donors."),
    ("draft", "noun", "a preliminary version of a piece of writing", "The first draft."),
    ("drain", "verb", "cause the water or other liquid in something to run out", "Drain resources."),
    ("dramatic", "adjective", "sudden and striking", "A dramatic increase."),
    ("drastically", "adverb", "in a way that has a strong or far-reaching effect", "Drastically reduced."),
    ("drawback", "noun", "a feature that renders something less acceptable", "A major drawback."),
    ("dual", "adjective", "consisting of two parts, elements, or aspects", "A dual purpose."),
    ("duration", "noun", "the time during which something continues", "The duration of the project."),
    ("dynamic", "adjective", "characterized by constant change", "A dynamic environment."),
]

# Band 8.0+ 추가
BAND80_EXTRA = [
    ("pacify", "verb", "bring peace to a country or group", "Pacify the region."),
    ("palatable", "adjective", "pleasant to taste", "A palatable solution."),
    ("palpable", "adjective", "so intense as to be almost touched", "Palpable tension."),
    ("panacea", "noun", "a solution for all difficulties", "There is no panacea."),
    ("panache", "noun", "flamboyant confidence of style", "Perform with panache."),
    ("pandemic", "noun", "a disease prevalent over a whole country", "A global pandemic."),
    ("paradigmatic", "adjective", "serving as a typical example", "A paradigmatic case."),
    ("paradoxical", "adjective", "seemingly contradictory but true", "A paradoxical situation."),
    ("paramount", "adjective", "more important than anything else", "Of paramount importance."),
    ("paraphrase", "verb", "express the meaning using different words", "Paraphrase the text."),
    ("parochial", "adjective", "having a limited outlook", "A parochial attitude."),
    ("parsimonious", "adjective", "unwilling to spend money", "A parsimonious approach."),
    ("partisan", "adjective", "prejudiced in favor of a particular cause", "Partisan politics."),
    ("patent", "adjective", "easily recognizable; obvious", "A patent falsehood."),
    ("pathetic", "adjective", "arousing pity", "A pathetic attempt."),
    ("patronize", "verb", "treat in a way that is apparently kind but betrays superiority", "Don't patronize me."),
    ("pecuniary", "adjective", "relating to or consisting of money", "Pecuniary interests."),
    ("pedantic", "adjective", "excessively concerned with minor details", "A pedantic scholar."),
    ("pedestrian", "adjective", "lacking inspiration or excitement", "A pedestrian approach."),
    ("pejorative", "adjective", "expressing contempt or disapproval", "A pejorative term."),
    ("penchant", "noun", "a strong liking for something", "A penchant for drama."),
    ("penetrate", "verb", "succeed in forcing a way into or through", "Penetrate the market."),
    ("perennial", "adjective", "lasting for an indefinitely long time", "A perennial problem."),
    ("perfunctory", "adjective", "carried out with a minimum of effort", "A perfunctory inspection."),
    ("peripheral", "adjective", "relating to the edge or periphery", "Peripheral issues."),
    ("permeate", "verb", "spread throughout", "The smell permeated the room."),
    ("permutation", "noun", "a way in which a set can be ordered", "Various permutations."),
    ("perpetual", "adjective", "never ending or changing", "Perpetual motion."),
    ("perplex", "verb", "make someone feel completely baffled", "The question perplexed her."),
    ("persevere", "verb", "continue in a course of action despite difficulty", "Persevere through challenges."),
    ("personify", "verb", "attribute a personal nature to something", "Personify evil."),
    ("pertain", "verb", "be appropriate, related, or applicable", "Pertain to the case."),
    ("pertinent", "adjective", "relevant or applicable", "A pertinent question."),
    ("perturb", "verb", "make someone anxious or unsettled", "The news perturbed him."),
    ("peruse", "verb", "read thoroughly or carefully", "Peruse the documents."),
    ("pervasive", "adjective", "spreading widely throughout an area", "A pervasive influence."),
    ("pessimistic", "adjective", "tending to see the worst aspect of things", "A pessimistic outlook."),
    ("phenomenon", "noun", "a fact or situation observed to exist", "A natural phenomenon."),
    ("philanthropic", "adjective", "seeking to promote the welfare of others", "Philanthropic activities."),
    ("philosophical", "adjective", "relating to the study of philosophy", "A philosophical question."),
    ("pinnacle", "noun", "the most successful point", "The pinnacle of success."),
    ("pioneer", "noun", "a person who is among the first to explore", "A pioneer in the field."),
    ("pivotal", "adjective", "of crucial importance", "A pivotal moment."),
    ("placate", "verb", "make someone less angry or hostile", "Placate the critics."),
    ("placid", "adjective", "not easily upset or excited", "A placid temperament."),
    ("plagiarize", "verb", "take someone's work and pass it off as one's own", "Never plagiarize."),
    ("plausible", "adjective", "seeming reasonable or probable", "A plausible explanation."),
    ("plight", "noun", "a dangerous, difficult, or unfortunate situation", "The plight of refugees."),
    ("plunge", "verb", "jump or dive quickly", "Prices plunged."),
    ("polarize", "verb", "divide or cause to divide into sharply contrasting groups", "Polarize opinion."),
    ("polemical", "adjective", "involving strongly critical or controversial discussion", "A polemical essay."),
    ("pompous", "adjective", "affectedly grand or self-important", "A pompous official."),
    ("ponder", "verb", "think about something carefully", "Ponder the question."),
    ("portray", "verb", "depict in a work of art or literature", "Portray the character."),
    ("posterity", "noun", "all future generations of people", "Preserve for posterity."),
    ("postulate", "verb", "suggest or assume as a fact", "Postulate a theory."),
    ("potent", "adjective", "having great power, influence, or effect", "A potent argument."),
    ("pragmatic", "adjective", "dealing with things sensibly and realistically", "A pragmatic approach."),
    ("precarious", "adjective", "not securely held or in position", "A precarious situation."),
    ("precedent", "noun", "an earlier event serving as an example", "Set a precedent."),
    ("precipitate", "verb", "cause an event to happen suddenly", "Precipitate a crisis."),
    ("precise", "adjective", "marked by exactness", "Precise measurements."),
    ("preclude", "verb", "prevent from happening", "Preclude any possibility."),
    ("preconceive", "verb", "form an idea beforehand", "Preconceived notions."),
    ("predecessor", "noun", "a person who held a position before another", "My predecessor."),
    ("predicament", "noun", "a difficult, unpleasant, or embarrassing situation", "A terrible predicament."),
    ("predicate", "verb", "found or base something on", "Predicate on assumptions."),
    ("predilection", "noun", "a preference or special liking", "A predilection for sweets."),
    ("predominantly", "adverb", "mainly; for the most part", "Predominantly urban."),
    ("preeminent", "adjective", "surpassing all others; very distinguished", "A preeminent scholar."),
    ("preempt", "verb", "take action to prevent an anticipated event", "Preempt criticism."),
    ("prejudice", "noun", "preconceived opinion not based on reason", "Racial prejudice."),
    ("preliminary", "adjective", "denoting something that precedes a main action", "Preliminary results."),
    ("premise", "noun", "a previous statement from which another is inferred", "Based on the premise."),
    ("preoccupy", "verb", "dominate the mind of to the exclusion of other thoughts", "Preoccupied with work."),
    ("prerequisite", "noun", "a thing required as a prior condition", "A prerequisite for success."),
    ("prescribe", "verb", "advise and authorize the use of a medicine", "Prescribe treatment."),
    ("prevalent", "adjective", "widespread in a particular area at a particular time", "Prevalent attitudes."),
    ("prima facie", "adverb", "based on the first impression", "Prima facie evidence."),
    ("primarily", "adverb", "for the most part; mainly", "Primarily concerned with."),
    ("pristine", "adjective", "in its original condition; unspoiled", "Pristine wilderness."),
    ("proactive", "adjective", "creating or controlling a situation", "A proactive approach."),
    ("probe", "verb", "physically explore or examine", "Probe the issue."),
    ("procure", "verb", "obtain something with care or effort", "Procure funding."),
    ("proficient", "adjective", "competent or skilled", "Proficient in languages."),
    ("profound", "adjective", "very great or intense", "Profound implications."),
    ("proliferate", "verb", "increase rapidly in numbers", "Weapons proliferate."),
    ("prolific", "adjective", "producing much fruit or foliage or many offspring", "A prolific writer."),
    ("prolong", "verb", "extend the duration of", "Prolong the discussion."),
    ("prominent", "adjective", "important; famous", "A prominent figure."),
    ("promote", "verb", "further the progress of", "Promote equality."),
    ("prompt", "verb", "cause or bring about an action", "Prompt a response."),
    ("prone", "adjective", "likely to suffer from or do something", "Prone to errors."),
    ("propagate", "verb", "spread and promote an idea widely", "Propagate beliefs."),
    ("propel", "verb", "drive or push forward", "Propel the economy."),
    ("proportionate", "adjective", "corresponding in size or amount", "A proportionate response."),
    ("proposition", "noun", "a statement expressing a judgment", "An interesting proposition."),
    ("proprietary", "adjective", "relating to an owner or ownership", "Proprietary information."),
    ("prosecute", "verb", "institute legal proceedings against", "Prosecute the offenders."),
    ("prospective", "adjective", "expected or expecting to be", "Prospective employees."),
    ("prosperity", "noun", "the state of being prosperous", "Economic prosperity."),
    ("protagonist", "noun", "the leading character in a drama", "The story's protagonist."),
    ("protocol", "noun", "the official procedure or system of rules", "Follow protocol."),
]

def create_word_entry(word, pos, definition, example, level, word_id):
    return {
        "id": word_id,
        "word": word,
        "level": level,
        "partOfSpeech": pos,
        "definition": definition,
        "example": example,
        "translations": {
            "ko": {"definition": "", "example": ""},
            "ja": {"definition": "", "example": ""},
            "zh": {"definition": "", "example": ""},
            "es": {"definition": "", "example": ""},
            "de": {"definition": "", "example": ""},
            "fr": {"definition": "", "example": ""},
            "pt": {"definition": "", "example": ""},
            "vi": {"definition": "", "example": ""},
            "ar": {"definition": "", "example": ""}
        }
    }

def add_words_to_file(filename, new_words_list, level):
    filepath = f'assets/data/{filename}'
    
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            existing_data = json.load(f)
    else:
        existing_data = []
    
    existing_word_set = set(w['word'].lower() for w in existing_data)
    max_id = max([w['id'] for w in existing_data], default=0)
    
    added = 0
    for word, pos, definition, example in new_words_list:
        if word.lower() not in existing_word_set and word.lower() not in existing_words:
            max_id += 1
            entry = create_word_entry(word, pos, definition, example, level, max_id)
            existing_data.append(entry)
            existing_word_set.add(word.lower())
            added += 1
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(existing_data, f, ensure_ascii=False, indent=2)
    
    print(f"✅ {filename}: {len(existing_data)}개 (추가: {added}개)")
    return len(existing_data)

print("\n" + "="*50)
print("📚 IELTS 단어 5000개 목표 최종 추가")
print("="*50 + "\n")

total_band60 = add_words_to_file('band60_words.json', BAND60_EXTRA, 'Band 6.0-6.5')
total_band70 = add_words_to_file('band70_words.json', BAND70_EXTRA, 'Band 7.0-7.5')
total_band80 = add_words_to_file('band80_words.json', BAND80_EXTRA, 'Band 8.0+')

with open('assets/data/band45_words.json', 'r', encoding='utf-8') as f:
    band45_count = len(json.load(f))

total = band45_count + total_band60 + total_band70 + total_band80

print("\n" + "="*50)
print(f"📊 총 단어 현황:")
print(f"   Band 4.5-5.5: {band45_count}개")
print(f"   Band 6.0-6.5: {total_band60}개")
print(f"   Band 7.0-7.5: {total_band70}개")
print(f"   Band 8.0+: {total_band80}개")
print(f"   총계: {total}개")
print("="*50)

if total >= 5000:
    print(f"\n🎉 5000개 목표 달성!")
else:
    print(f"\n⚠️ 5000개 목표까지 {5000-total}개 더 필요합니다.")
